### ISSUE TITLE
zowe cli script not seeing my profile. 

### ISSUE THREAD

**Issue by frankgiordano** [zowe/zowe-cli#1000]
I can run zowe cli commands without a problem at the OS prompt but my script below does not seem to find profile. 

npm run build && node lib

> use-zowe-cli-package@1.0.0 build C:\Users\IdeaProjects\ZoweCCSSanityChecksPOC
> tsc --pretty

ImperativeError: Failed to get a profile.
    at C:\Users\IdeaProjects\ZoweCCSSanityChecksPOC\lib\index.js:24:15
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\IdeaProjects\ZoweCCSSanityChecksPOC\lib\index.js:6:65) {
  mDetails: { msg: 'Failed to get a profile.' },
  mMessage: 'Failed to get a profile.'
}

Code:

import { IProfile, Session, Logger, LoggingConfigurer, ImperativeError,
    CredentialManagerFactory } from "@zowe/imperative";
import { ZosmfSession } from "@zowe/zosmf-for-zowe-sdk";
import { getDefaultProfile } from "@zowe/core-for-zowe-sdk";
import { DownloadJobs, IDownloadAllSpoolContentParms } from "@zowe/zos-jobs-for-zowe-sdk";

(async () => {
//Initialize the Imperative Credential Manager Factory and Logger
Logger.initLogger(LoggingConfigurer.configureLogger('lib', {name: 'test'}));
// Uncommment the below line if the Secure Credential Store is in use
// await CredentialManagerFactory.initialize({service: "Zowe-Plugin"});

// Get the default z/OSMF profile and create a z/OSMF session with it
let defaultZosmfProfile: IProfile;
try {
   defaultZosmfProfile = await getDefaultProfile("zosmf", true);
} catch (err) {
   throw new ImperativeError({msg: "Failed to get a profile."});
}

// Job Options
const jobParms: IDownloadAllSpoolContentParms = {
   jobname: "JOBNAME",
   jobid: "JOBID",
   outDir: undefined,
   extension: ".txt",
   omitJobidDirectory: false
}
const session: Session = ZosmfSession.createBasicZosmfSession(defaultZosmfProfile);
let response: any;
response = await DownloadJobs.downloadAllSpoolContentCommon(session, jobParms);
console.log(response);
process.exit(0);
})().catch((err) => {
console.error(err);
process.exit(1);
});

{
  "name": "use-zowe-cli-package",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build": "tsc --pretty",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@zowe/cli": "^6.31.0",
    "@zowe/core-for-zowe-sdk": "6.26.0",
    "@zowe/imperative": "4.11.0",
    "@zowe/zos-jobs-for-zowe-sdk": "6.26.0"
  },
  "devDependencies": {
    "@types/node": "^12.7.11",
    "typescript": "^4.2.4"
  }
}

{
  "compilerOptions": {
      "declaration": false,
      "module": "commonjs",
      "moduleResolution": "node",
      "lib": [
          "esnext"
      ],
      "target": "es2015",
      "strict": true,
      "outDir": "./lib",
      "preserveConstEnums": true,
      "removeComments": true,
      "inlineSourceMap": true,
      "typeRoots": [
          "./node_modules/@types"
      ]
  },
  "include": [
      "src/**/*"
  ],
  "exclude": [
      "config/**",
      "node_modules",
      "**/*-spec.ts"
  ]
}

**Comment by MikeBauerCA** [comment]
+ @awharn could you please review?

**Comment by awharn** [comment]
I may need some additional information before I can come to any conclusions. I need the output of a handful of commands:

- `npm --version`
- `node --version`
- `zowe --version`
- `zowe plugins list`
- `zowe profiles list zosmf`

Also, error is shown if you replace
```
try {
defaultZosmfProfile = await getDefaultProfile("zosmf", true);
} catch (err) {
throw new ImperativeError({msg: "Failed to get a profile."});
}
```
with just
```
defaultZosmfProfile = await getDefaultProfile("zosmf", true);
```

**Comment by frankgiordano** [comment]
C:\Users\IdeaProjects\ZoweCCSSanityChecksPOC>npm -v
6.14.11

C:\Users\IdeaProjects\ZoweCCSSanityChecksPOC>npm --version
6.14.11

C:\Users\IdeaProjects\ZoweCCSSanityChecksPOC>node --version
v14.16.0

C:\Users\\IdeaProjects\ZoweCCSSanityChecksPOC>zowe --version
6.27.1

C:\Users\IdeaProjects\ZoweCCSSanityChecksPOC>zowe plugins list

Installed plugins:

 -- pluginName: @zowe/secure-credential-store-for-zowe-cli
 -- package: @zowe/secure-credential-store-for-zowe-cli
 -- version: 4.1.3
 -- registry: https://registry.npmjs.org/

C:\Users\fg892105\IdeaProjects\ZoweCCSSanityChecksPOC>zowe profiles list zosmf
CA31 (default)
CA31cli
ccsAutoCA31

Is it because I have multiple only one profile works..

**Comment by frankgiordano** [comment]
with just defaultZosmfProfile = await getDefaultProfile("zosmf", true);

C:\Users\fg892105\IdeaProjects\ZoweCCSSanityChecksPOC>npm run build && node lib

> use-zowe-cli-package@1.0.0 build C:\Users\fg892105\IdeaProjects\ZoweCCSSanityChecksPOC
> tsc --pretty

RestClientError: This operation requires authentication.

z/OSMF REST API Error:
Rest API failure with HTTP(S) status 401

Host:      usilca32.lvn.broadcom.net
Port:      1443
Base Path:
Resource:  /zosmf/restjobs/jobs?owner=*&prefix=ENF
Request:   GET
Headers:   [{"X-CSRF-ZOSMF-HEADER":true}]
Payload:   GET

    at ZosmfRestClient.populateError (C:\Users\fg892105\IdeaProjects\ZoweCCSSanityChecksPOC\node_modules\@zowe\imperative\lib\rest\src\client\AbstractRestClient.js:507:16)
    at ZosmfRestClient.onEnd (C:\Users\fg892105\IdeaProjects\ZoweCCSSanityChecksPOC\node_modules\@zowe\imperative\lib\rest\src\client\AbstractRestClient.js:427:31)
    at IncomingMessage.<anonymous> (C:\Users\fg892105\IdeaProjects\ZoweCCSSanityChecksPOC\node_modules\@zowe\imperative\lib\rest\src\client\AbstractRestClient.js:362:18)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  mDetails: {
    msg: 'This operation requires authentication.\n' +
      '\n' +
      'z/OSMF REST API Error:\n' +
      'Rest API failure with HTTP(S) status 401\n' +
      '\n' +
      'Host:      usilca32.lvn.broadcom.net\n' +
      'Port:      1443\n' +
      'Base Path: \n' +
      'Resource:  /zosmf/restjobs/jobs?owner=*&prefix=ENF\n' +
      'Request:   GET\n' +
      'Headers:   [{"X-CSRF-ZOSMF-HEADER":true}]\n' +
      'Payload:   GET\n',
    causeErrors: '',
    source: 'http',
    errorCode: 401,
    port: 1443,
    host: 'usilca32.lvn.broadcom.net',
    basePath: '',
    httpStatus: 401,
    errno: undefined,
    syscall: undefined,
    payload: undefined,
    headers: [ [Object] ],
    resource: '/zosmf/restjobs/jobs?owner=*&prefix=ENF',
    request: 'GET',
    additionalDetails: 'Username or password are not valid or expired.\n\n'
  },
  mMessage: 'This operation requires authentication.\n' +
    '\n' +
    'z/OSMF REST API Error:\n' +
    'Rest API failure with HTTP(S) status 401\n' +
    '\n' +
    'Host:      usilca32.lvn.broadcom.net\n' +
    'Port:      1443\n' +
    'Base Path: \n' +
    'Resource:  /zosmf/restjobs/jobs?owner=*&prefix=ENF\n' +
    'Request:   GET\n' +
    'Headers:   [{"X-CSRF-ZOSMF-HEADER":true}]\n' +
    'Payload:   GET\n'
}

**Comment by frankgiordano** [comment]
I removed profiles and left one:

C:\Users\IdeaProjects\ZoweCCSSanityChecksPOC>zowe profiles list zosmf
CA31cli

with just defaultZosmfProfile = await getDefaultProfile("zosmf", true);

get errors:

C:\Users\fg892105\IdeaProjects\ZoweCCSSanityChecksPOC>npm run build && node lib

> use-zowe-cli-package@1.0.0 build C:\Users\IdeaProjects\ZoweCCSSanityChecksPOC
> tsc --pretty

ImperativeError: Failed to load default profiles of types "zosmf" and "base"
    at Object.<anonymous> (C:\Users\IdeaProjects\ZoweCCSSanityChecksPOC\node_modules\@zowe\core-for-zowe-sdk\lib\utils\ProfileUtils.js:100:19)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\fg892105\IdeaProjects\ZoweCCSSanityChecksPOC\node_modules\@zowe\core-for-zowe-sdk\lib\utils\ProfileUtils.js:16:65) {
  mDetails: {
    msg: 'Failed to load default profiles of types "zosmf" and "base"'
  },
  mMessage: 'Failed to load default profiles of types "zosmf" and "base"'
}

C:\Users\IdeaProjects\ZoweCCSSanityChecksPOC>npm run build && node lib

> use-zowe-cli-package@1.0.0 build C:\Users\IdeaProjects\ZoweCCSSanityChecksPOC
> tsc --pretty

ImperativeError: Failed to load default profiles of types "zosmf" and "base"
    at Object.<anonymous> (C:\Users\IdeaProjects\ZoweCCSSanityChecksPOC\node_modules\@zowe\core-for-zowe-sdk\lib\utils\ProfileUtils.js:100:19)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\IdeaProjects\ZoweCCSSanityChecksPOC\node_modules\@zowe\core-for-zowe-sdk\lib\utils\ProfileUtils.js:16:65) {
  mDetails: {
    msg: 'Failed to load default profiles of types "zosmf" and "base"'
  },
  mMessage: 'Failed to load default profiles of types "zosmf" and "base"'
}

**Comment by frankgiordano** [comment]
I set my working profile as the default and it still does not work:

C:\Users\IdeaProjects\ZoweCCSSanityChecksPOC>npm run build && node lib

> use-zowe-cli-package@1.0.0 build C:\Users\fg892105\IdeaProjects\ZoweCCSSanityChecksPOC
> tsc --pretty

ImperativeError: Failed to get a profile.
    at C:\Users\IdeaProjects\ZoweCCSSanityChecksPOC\lib\index.js:24:15
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\IdeaProjects\ZoweCCSSanityChecksPOC\lib\index.js:6:65) {
  mDetails: { msg: 'Failed to get a profile.' },
  mMessage: 'Failed to get a profile.'
}

C:\Users\IdeaProjects\ZoweCCSSanityChecksPOC>zowe profiles list zosmf
CA31cli (default)

**Comment by frankgiordano** [comment]
my workaround to get this to work is to comment out
// await CredentialManagerFactory.initialize({service: "Zowe-Plugin"});

and to add 

        defaultZosmfProfile.user = "xxxx"
        defaultZosmfProfile.password = "xxxx"

under

defaultZosmfProfile = await getDefaultProfile("zosmf", true);

**Comment by awharn** [comment]
Interesting. Multiple profiles should not be a problem, as the code is only grabbing the profile that the `zowe profiles list zosmf` command lists as `(default)`. It also shouldn't be a problem that you're using the Secure Credential Store plugin, given that you had `await CredentialManagerFactory.initialize({service: "Zowe-Plugin"});` uncommented.

If you run `set` in the command prompt, does the variable ZOWE_CLI_HOME appear?
Also, if you add `console.log(defaultZosmfProfile.user)` to the line before `defaultZosmfProfile.user = "xxxx"`, does it print undefined, or a string similar to "managed by @zowe/secure-credential-store-for-zowe-cli"?

**Comment by awharn** [comment]
After investigating further, I have a suggestion. Could you try running `npm install keytar` in your project, uncomment the `await CredentialManagerFactory.initialize({service: "Zowe-Plugin"});` line, and try again? It seems likely that the keytar package is missing, and needs to be added to access the secured credentials.

**Comment by frankgiordano** [comment]
getting error

C:\Users\IdeaProjects\ZoweCCSSanityChecksPOC>npm install keytar

> keytar@7.6.0 install C:\Users\IdeaProjects\ZoweCCSSanityChecksPOC\node_modules\keytar
> prebuild-install || npm run build

prebuild-install WARN install unable to get local issuer certificate

> keytar@7.6.0 build C:\Users\IdeaProjects\ZoweCCSSanityChecksPOC\node_modules\keytar
> node-gyp rebuild


C:\Users\IdeaProjects\ZoweCCSSanityChecksPOC\node_modules\keytar>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: unable to get local issuer certificate
gyp ERR! stack     at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
gyp ERR! stack     at TLSSocket.emit (events.js:315:20)
gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:932:8)
gyp ERR! stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\IdeaProjects\ZoweCCSSanityChecksPOC\node_modules\keytar
gyp ERR! node -v v14.16.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keytar@7.6.0 build: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the keytar@7.6.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\AppData\Roaming\npm-cache\_logs\2021-04-20T20_53_14_540Z-debug.log
npm WARN use-zowe-cli-package@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keytar@7.6.0 install: `prebuild-install || npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the keytar@7.6.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\AppData\Roaming\npm-cache\_logs\2021-04-20T20_53_14_730Z-debug.log

**Comment by frankgiordano** [comment]
executing set at the prompt does not show ZOWE_CLI_HOME

**Comment by frankgiordano** [comment]
I was able to perform npm install keytar successfully.. and now auth store works well. We can close this issue.
