### ISSUE TITLE
Validate Zowe CLI to work with Node 16

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/zowe-cli#1004]
Test Zowe CLI on Node 16 - becomes LTS in October

**Comment by t1m0thyj** [comment]
Tasks:
* Update GitHub Actions workflows
  * [x] Imperative
  * [x] Zowe CLI
* Use npm@7 for Zowe CLI
  * [x] Migrate to workspaces in monorepo
  * [x] Support workspaces in shared Jenkins library
* Make SCS compatible with Node 16
  * [x] Update Keytar
  * Test installing in Node 16 environment
    * [x] Windows
    * [x] Linux
    * [x] macOS
* [x] Install CLI bundle + plugins

**Comment by MikeBauerCA** [comment]
Thanks @t1m0thyj
