### ISSUE TITLE
zowe cli install issue in jenkins pipeline

### ISSUE THREAD

**Issue by Simnbf** [zowe/zowe-cli#1013]
We're getting the below issue when attempting to install zowe-cli from the npm repository on a linux jenkins slave. The npm command we're using is below. It seems to install OK but then falls over during post-install scripts.

12:25:14  + npm install -g @zowe/cli@zowe-v1-lts

12:26:43  Since you re-installed Zowe CLI, we are re-validating any plugins.
12:26:43  /home/syspcbjenkins/store/dx-rhel7-apaas-ganges-sl-101/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Latest/node-v8.9.4-linux-x64/lib/node_modules/@zowe/cli/node_modules/@zowe/imperative/lib/cmd/src/help/WebHelpGenerator.js:101
12:26:43          this.singlePageHtml = rootHelpContent.replace(/<h4>Groups.+?<\/ul>/s, "");
12:26:43                                                        ^
12:26:43  
12:26:43  SyntaxError: Invalid regular expression flags
12:26:43      at createScript (vm.js:80:10)
12:26:43      at Object.runInThisContext (vm.js:139:10)
12:26:43      at Module._compile (module.js:607:28)
12:26:43      at Object.Module._extensions..js (module.js:654:10)
12:26:43      at Module.load (module.js:556:32)
12:26:43      at tryModuleLoad (module.js:499:12)
12:26:43      at Function.Module._load (module.js:491:3)
12:26:43      at Module.require (module.js:587:17)
12:26:43      at require (internal/module.js:11:18)
12:26:43      at Object.<anonymous> (/home/syspcbjenkins/store/dx-rhel7-apaas-ganges-sl-101/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Latest/node-v8.9.4-linux-x64/lib/node_modules/@zowe/cli/node_modules/@zowe/imperative/lib/cmd/index.js:55:14)
12:26:57  npm ERR! code ELIFECYCLE
12:26:57  npm ERR! errno 1
12:26:57  npm ERR! @zowe/cli@6.31.0 postinstall: `node ./scripts/validatePlugins`
12:26:57  npm ERR! Exit status 1
12:26:57  npm ERR! 
12:26:57  npm ERR! Failed at the @zowe/cli@6.31.0 postinstall script.
12:26:57  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
12:26:57  
12:26:57  npm ERR! A complete log of this run can be found in:
12:26:57  npm ERR!     /home/syspcbjenkins/.npm/_logs/2021-05-05T11_26_56_478Z-debug.log

**Comment by t1m0thyj** [comment]
Hello, it appears from the log message that you're using Node.js v8.9.4. Zowe CLI only supports current LTS Node.js versions.

For an up-to-date list of supported LTS versions, see [Nodejs.org](https://nodejs.org/en/about/releases/) or [EndOfLife.date](https://endoflife.date/nodejs). Currently only Node.js 12.x and 14.x are supported (10.x is probably also compatible, but it reached End of Life last week).

You may be able to install a newer version of Node.js in your Jenkins pipeline using [NodeSource distributions](https://github.com/nodesource/distributions#installation-instructions).

**Comment by Simnbf** [comment]
Thanks Timothy, the zowe-cli documentation (below) says it supports Node.js v8.0 and above, I'll see about using a more up to date version of node within Jenkins.

https://docs.zowe.org/v1-1-x/user-guide/systemrequirements.html#zowe-application-framework-requirements

**Comment by t1m0thyj** [comment]
@Simnbf That link points to an old version of the Zowe docs (v1-1-x). The latest version can be found here and contains up-to-date info about Node.js versions:
https://docs.zowe.org/stable/user-guide/systemrequirements.html#zowe-cli-requirements

How did you find the "v1-1-x" version of Zowe docs? Just wondering if there's a link we need to update somewhere that points to old doc 🙂

**Comment by Simnbf** [comment]
Ah I see! I just googled 'zowe cli install', clicked first link and then went to system requirements. 

![image](https://user-images.githubusercontent.com/13423139/117338807-eda0d500-ae96-11eb-98a2-9c220e4256ba.png)

![image](https://user-images.githubusercontent.com/13423139/117338791-e7125d80-ae96-11eb-9293-994ed9acd722.png)

**Comment by MikeBauerCA** [comment]
Adding some folks from the doc squad - @MichaelABroadcom @nannanli

**Comment by MikeBauerCA** [comment]
Tagging @MichaelABroadcom @nannanli in case they need to open an issue against the docs-site but closing for this repo.
