### ISSUE TITLE
Installed cli V7 in order to test the daemon. Now unable to remove Secure Credentials store

### ISSUE THREAD

**Issue by davidkjackson54** [zowe/zowe-cli#1015]
I installed cli V7 in order to test the performance of the Daemon.
I also had the SCS plugin in installed previously. 
After the update to CLI 7, I then tried to remove the SCS by:
C:\Users\djackson>zowe plugins uninstall @zowe/secure-credential-store-for-zowe-cli
[         .........] | idealTree: timing idealTree Completed in 11ms        

it hangs and I appear to now be left with an indeterminate state of the SCS.
How do I now blow away the SCS completely? 

I can reinstall the scs plugin with no problem but the subsequent attempt to uninstall iot again hangs.

I am running npm V7.11

**Comment by t1m0thyj** [comment]
@davidkjackson54 There is a known issue with the SCS plug-in where uninstalling on Windows hangs: https://github.com/zowe/zowe-cli-scs-plugin/issues/20

If you `Ctrl+C` to abort the uninstall command and reissue it a second time, it should uninstall successfully.
