### ISSUE TITLE
Install Zowe CLI outside of the npm modules folder (management of multiple node.js/npm versions)

### ISSUE THREAD

**Issue by FALLAI-Denis** [zowe/zowe-cli#1019]
We use the `nvm` software, node.js version manager, to be able to quickly switch from one version of `node.js` to another.
This is a need of our organization.

With `nvm`, each version of `node.js/npm` is installed in a different folder, with a subfolder containing the npm modules.
`@zowe/cli` is an npm module, and therefore when activating a `node.js/npm` version for the first time, the `@zowe/cli` npm module must be reinstalled.
The installation of `@zowe/cli` detects previous installation of zowe plugins which are installed outside of the npm modules subfolder. The zowe plugins therefore do not need to be reinstalled, but there may be dependency problems with the npm version used to install them, cf. [zowe/zowe-cli-db2-plugin issue #80](https://github.com/zowe/zowe-cli-db2-plugin/issues/80).

We need a mechanism to not completely reinstall `@zowe/cli` when switching the version of `node.js/npm`:
* either install it completely outside the npm modules subfolder of the `node.js/npm` version, and in this case reference the location of the `zowe` command in the PATH of the host system,
* either install only the `zowe` command in the npm modules sub-folder, but install all the other `@zowe/cli` components outside this sub-folder, a priori in the same folder as the zowe cli plugins ; when installing `@zowe/cli`, detect the previous installation, and just drop the `zowe` command in the npm subfolder.

**Comment by FALLAI-Denis** [comment]
Question: does the installation of Zowe CLI have to be done at the global level? Is it possible to install Zowe CLI outside of the node.js / npm installation folder? (implied that the folder containing the zowe command is in the path of the execution environment).

**Comment by t1m0thyj** [comment]
@FALLAI-Denis Although NPM CLI packages are typically installed globally, they don't have to be 🙂 You can install Zowe CLI in your project and execute the zowe binary with [npx](https://docs.npmjs.com/cli/v7/commands/npx).

If you install multiple instances of Zowe CLI across multiple projects, they will all share the same .zowe folder in your user home directory, but you can also change this behavior with the ZOWE_CLI_HOME environment variable.

**Comment by FALLAI-Denis** [comment]
Thanks @t1m0thyj 

I don't know how node.js works (40 years of mainframe ...), and my question may be silly: why would running Zowe via npx be required?

When the "zowe" command is called, it is in fact a "zowe.cmd" call (in Windows environment) that is executed.

My idea was therefore to install Zowe CLI in a dedicated folder (npm install without the -g option), and to update the PATH so that this folder is used when calling the "zowe" command.

But when I see the contents of "zowe.cmd" I wonder about installing it outside of the "node.js" folder because it favors the search for node.exe in the same location as "zowe.cmd" .

zowe.cmd:
```
@ECHO off
SETLOCAL
CALL :find_dp0

IF EXIST "%dp0%\node.exe" (
  SET "_prog=%dp0%\node.exe"
) ELSE (
  SET "_prog=node"
  SET PATHEXT=%PATHEXT:;.JS;=;%
)

"%_prog%"  "%dp0%\node_modules\@zowe\cli\lib\main.js" %*
ENDLOCAL
EXIT /b %errorlevel%
:find_dp0
SET dp0=%~dp0
EXIT /b
```

**Comment by t1m0thyj** [comment]
@FALLAI-Denis You are right, if you add the "<projectDir>/node_modules/.bin" folder to your PATH then you don't need to use `npx`. As long as the dedicated folder is at the top of your PATH above the global node_modules location, it should have priority. If you're running in an environment where you can't or don't want to update PATH, then `npx` may still be useful.

**Comment by FALLAI-Denis** [comment]
Thanks @t1m0thyj 

If the order of declarations in the PATH has an impact, to avoid having to manage the order of declarations in the PATH, could the zowe cli launch script be adapted to dynamically declare the path to the zowe cli installation "/node_modules/.bin"  folder?

For example for a Windows installation with zowe.cmd:

```
@ECHO off
SETLOCAL
CALL :find_dp0

IF EXIST "%dp0%\node.exe" (
  SET "_prog=%dp0%\node.exe"
) ELSE (
  SET "_prog=node"
  SET PATHEXT=%PATHEXT:;.JS;=;%
  PATH=%dp0%\node_modules\@zowe\cli\node_modules\.bin;%PATH%     <-- something like this
)

"%_prog%"  "%dp0%\node_modules\@zowe\cli\lib\main.js" %*
ENDLOCAL
EXIT /b %errorlevel%
:find_dp0
SET dp0=%~dp0
EXIT /b
```

**Comment by t1m0thyj** [comment]
@FALLAI-Denis I'm afraid not, the `zowe.cmd` script is automatically generated by NPM, so we don't have control over it.

When a package is installed, NPM will create `.cmd`/`.ps1`/`.sh` scripts for any binaries declared in package.json:
https://github.com/zowe/zowe-cli/blob/d1da9779288ba66c9f463c095d63679cff01e7d4/packages/cli/package.json#L15-L18

At this time, the recommended solution is to manage the order of declarations in the PATH.

**Comment by FALLAI-Denis** [comment]
PS:

With a standard installation of node.js & npm, in `C:\Program Files\nodejs` for a Windows environment, the global modules (npm -g install) are installed in `C:\Users\<username>\AppData\Roaming\npm`. 
The path `C:\Users\<username>\AppData\Roaming\npm` is added to the `PATH`.
Global modules are therefore installed outside of the node.js & npm installation folder.
This also applies to Zowe CLI "core".

What is described above therefore only concerns node.js & npm installations made using nvm (node version manager). 

I don't know why the installation of a global module by npm doesn't follow the same rules depending on how node.js & npm itself is installed.

**Comment by t1m0thyj** [comment]
Closing as the original question appears to have been resolved by installing Zowe CLI in a custom directory that is added to the PATH environment variable.

As has been pointed out, the default behavior of npm on Windows is to install global packages in `C:\Users\<username>\AppData\Roaming\npm`. It is possible to customize this location (see [here](https://stackoverflow.com/questions/19874582/change-default-global-installation-directory-for-node-js-modules-in-windows)), but generally not recommended to set it to `C:\Program Files\nodejs`, unless it is desirable for admin rights to be required to install packages globally.
