### ISSUE TITLE
Misleading SSH documentation claims you can use APIML tokens 

### ISSUE THREAD

**Issue by JirkaAichler** [zowe/zowe-cli#1032]
The documentation for SSH commands contains these parameters:

```
Base Connection Options

Default value: true

--token-type | --tt (string)

The type of token to get and use for the API. Omit this option to use the default token type, which is provided by 'zowe auth login'.

--token-value | --tv (string)

The value of the token to pass to the API.
```

This leads to an expectation that the SSH command supports APIML SSO. Although these parameters are accepted, the functionality is not there.

```
λ zowe --version
6.32.0
```

**Comment by gejohnston** [comment]
Altered the help text to clarify that the token-type and token-value options are not valid for SSH commands.
This change will be available in the next publication of the @latest and @zowe-v1-lts versions of zowe-cli.
