### ISSUE TITLE
Zowe requires password when using MFA for SSH command

### ISSUE THREAD

**Issue by JirkaAichler** [zowe/zowe-cli#1033]
I am asked for a password when calling the SSH command with MFA (APIML token). I would expect to be asked for an SSH key.

Base profile:

```
host:               sys1.com
port:               1443
rejectUnauthorized: true
tokenType:          apimlAuthenticationToken
tokenValue:         1234
user:               user1
```

SSH profile:
```
  name:     sys1 (default)
  contents:
    host: sys1.com
    port: 22
```

Command:
```
λ zowe zos-uss issue ssh "echo test"
Enter password : ******

$ test
```

Version:
```
λ zowe --version
6.32.0
```

**Comment by MarkAckert** [comment]
SSH commands support both password and private key based authentication, so we shouldn't switch the prompt from password to private key. Would prompting users to first choose one of the two authentication options be sufficient?

**Comment by JirkaAichler** [comment]
I suppose I originally had trouble to setup Zowe CLI with MFA. Now this behavior does not look wrong,

I think the user experience would be better if there would be a message like: "It is not possible to use an APIML authentication token for SSH. Please update your SSH profile with credentials or SSH key."

**Comment by JTonda** [comment]
Documentation has been updated in the command line help describing this situation.  Closing out the issue.

https://github.com/zowe/zowe-cli/blob/master/packages/cli/src/zosuss/issue/ssh/Ssh.definition.ts#L17-L19
