### ISSUE TITLE
Zowe requires password when using SSH key for SSH command 

### ISSUE THREAD

**Issue by JirkaAichler** [zowe/zowe-cli#1034]
I am asked for a password when calling the SSH command with an SSH key. Then it is possible to do the action with the incorrect password.

Base profile:

```
host:               sys1.com
port:               1443
rejectUnauthorized: true
```

SSH profile:
```
  name:     sys1 (default)
  contents:
    host:       sys1.com
    port:       22
    user:       user1
    privateKey: c:\Users\user1\.ssh\id_rsa
```

Command:
```
λ zowe zos-uss issue ssh "echo test"
Enter password : invalid_password

$ test
```

Version:
```
λ zowe --version
6.32.0
```

**Comment by zFernand0** [comment]
If I remember correctly, we said that a possible temporary solution could be to document the unexpected behavior in a troubleshooting section on zowe/docs.
Long term, we wouldn't want to be asking for a password whenever there is an SSH key already in the `~/.ssh/authorized_keys` file

**Comment by JirkaAichler** [comment]
I would personally prefer the long-term solution. Do not ask for a password when `privateKey` parameter is specified. Is it that difficult to implement?

**Comment by gejohnston** [comment]
The CLI team is fully scheduled to meet objectives from previous commitments. If you feel that the business impact is significant enough to warrant a higher priority, your best course of action is to raise those business concerns with Zowe Product Management who can re-prioritize commitments.

**Comment by jace-roell** [comment]
Tested with v7.27.0 and vNext, issue has been resolved.
