### ISSUE TITLE
Add --edit flag to zowe config init

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/zowe-cli#1035]
An "--edit" flag that opens the config file in the user's default text editor would be nice (similar to "git config -e").

**Comment by zFernand0** [comment]
Should there also be a `zowe config edit` command?

**Comment by MikeBauerCA** [comment]
I like this idea - less to understand. `zowe config edit` could also accept the `--global` and `--user` flags to determine which config file to open.

**Comment by t1m0thyj** [comment]
Both `zowe config edit` and `zowe config init --edit` (and also `zowe config auto-init --edit`) have been implemented.
