### ISSUE TITLE
Add `dir-from-uss` option to `zowe files download`

### ISSUE THREAD

**Issue by boris-bc** [zowe/zowe-cli#1038]
Make possible to download the contents of a USS directory.

**Comment by JTonda** [comment]
Open to discussion but currently leaning towards zowe files download uss-dir | ud as the command name

**Comment by awharn** [comment]
Outstanding Questions:
1) How do we follow symbolic links? Follow them, ignore them, empty folders/files?
2) What happens if there is a circular symbolic link?
3) What should the default depth be?
4) Can `find` warn us about an infinite loop? Or is that out of scope because that would require ssh.
