### ISSUE TITLE
Command "zowe profiles create" prints the password that should be secret

### ISSUE THREAD

**Issue by plavjanik** [zowe/zowe-cli#1050]
I am using Zowe CLI in a CI pipeline.

As a part of the pipeline, I call following command:
```
zowe profiles create zosmf-profile zowe \
                      --host $ZOS_HOST --port $ZOS_ZOSMF_PORT \
                      --user "$USERID" --pass "$PASSWORD"
```                      

In the log of the job is the following output:

```
Profile created successfully! Path:
/var/lib/jenkins_agent/workspace/Verify Zowe Prereqs/profiles/zosmf/zowe.yaml

host:               myhost
port:               443
user:               MYUSER
password:           MYPASSWORD
rejectUnauthorized: true
protocol:           https
```

I am not happy that my password is printed and all other users can see it.

**Comment by zFernand0** [comment]
After discussing with the team, we considered that using environment variables might be the best approach for moving any sensitive information away from the CLI profiles, commands, and logs.

We think that hiding content from the yaml file without the SCS plugin could be considered a breaking change since users in an unsecure environment could be using it as confirmation.

Another option could be to wrap zowe commands in the CI Pipeline masking mechanism (e.g. `withCrendentials` in Jenkins).

**Comment by plavjanik** [comment]
You are right about `withCrendentials` in Jenkins. When this is used, Jenkins will mask the password.

There are other cases when it will not be masked:
- `password` parameter in Jenkins and then using the environment variable in Jenkinsfile
     ```
     parameters {
       password(name: 'PASSWORD', description: 'z/OS password',)
    }
    ```
- using Zowe CLI via WebEx or Zoom - when I create a profile, I enter a password without displaying it but the Zowe CLI will print the password 
- other CI solutions do not mask the password as Jenkins. Anyway, masking is just a patch for bad behavior. Ideally, no good tool should print sensitive information without explicit request.

Hiding the password can be seen as a breaking change. Showing the password is a security issue. What is more important? Keeping insecure behavior or making Zowe CLI more secure?

In my case, I have used `sed` to mask the password from the log. But I am concerned about other users who will not do it and will leak their credentials into logs:

```
set +x
zowe profiles create zosmf-profile zowe \
                      --host $ZOS_HOST --port $ZOS_ZOSMF_PORT \
                      --user "$USERID" --pass "$PASSWORD" \
                      | sed 's/$PASSWORD/***/g'
```

**Comment by zFernand0** [comment]
How about using `ZOWE_OPT_USER=<userid>` and `ZOWE_OPT_PASSWORD=<password>`?
They should get picked up by the CLI automatically without having to specify them anywhere in your profiles or commands 😋 
And you should be able to submit commands without creating profiles, for instance `zowe jobs lis jobs --host <host> --port 1234`
Note: Credentials will still be shown in plain text when doing `zowe profiles create` if the SCS plugin has not been installed.

In regards to...
> using Zowe CLI via WebEx or Zoom - when I create a profile, I enter a password without displaying it but the Zowe CLI will print the password

I believe that `prompt*` should help with this. Any property that you type `prompt*` as the value, will be considered as secure (for interactive purposes only) and you will get prompted to enter a value for that property which will be obscured when typing it.

**Comment by MikeBauerCA** [comment]
It is best practice to use the secure credential store plug-in when using the CLI interactively. This plug-in is part of the core bundle on Zowe.org. In the `@next` release, the SCS will become part of the core CLI.

In CI environments, we typically use their credential stores and supply the info via `ZOWE_OPT_USER` and `ZOWE_OPT_PASSWORD`. You could use the SCS in pipeline runs but sometimes pipeline runs are done in containers that do not have access to the OS and the SCS requires such access to securely store creds. 

This will not be a high-priority issue in the `@next` release as profile creation commands are deprecated in favor of the new config.

**Comment by zFernand0** [comment]
This seems to be an enhancement request on the `zowe profiles create`  which is deprecated.
The V2 equivalent (`zowe config set ...`) does not expose any passwords in plain text.
Closing.
If you think this should be addressed on V1, please reopen the issue.
