### ISSUE TITLE
env var to disable CLI colors

### ISSUE THREAD

**Issue by tucker01** [zowe/zowe-cli#1057]
There are certain situations where terminal colors won't work. We should allow disabling colors via env var so that the output isn't cluttered by color escape codes. 

See #938 for an example of colors not working.

**Comment by dkelosky** [comment]
This looks to be possible today.  In `cmd.exe` try:
1. `set FORCE_COLOR=0`
2. `start zowe --daemon`

**Comment by tucker01** [comment]
That works for both `zowex` and `zowe`.
