### ISSUE TITLE
zowe in daemon mode not working in service

### ISSUE THREAD

**Issue by YvesMichon** [zowe/zowe-cli#1068]
Hello.
We want to use ZOWEX on Redhat8 machine. By sending commands "zowe --daemon &" in one session, we open another session to use ZOWEX, it works. 
But when we start "zowe --daemon &" in a service, ZOWEX is not responding and we found this message in /var/log/messages : 

**Erreur : Jul 22 09:52:45 ibldfzt5027m zowedaemon[6668]: Internal Imperative Error: Root command help error occurred: Cannot 
autolaunch D-Bus without X11 $DISPLAY**

Here is the service declaration :

ZOWE.service
[Unit]
Description=Daemon Zowe
After=network.target
[Service]
WorkingDirectory=
User=******
Group=*******
ExecStart=zowe --daemon &
Restart=on-failure
RestartSec=500ms
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=zowedaemon
[Install]
WantedBy=multi-user.target

**Comment by t1m0thyj** [comment]
Daemon mode and the `@next` release of Zowe CLI require Keytar to be installed and configured for accessing secure credentials. In a headless Linux environment, the error that appears at runtime when Keytar isn't configured is `Cannot autolaunch D-Bus without X11 $DISPLAY`.

If you want to store credentials securely in the OS vault, then these instructions should help to get Keytar configured on your system: https://github.com/zowe/zowe-cli-scs-plugin#linux-headless

If you're ok with storing credentials in plain text on disk or in environment variables, then you can work around the issue by renaming Keytar to move it out of the way:
```bash
cd $(npm prefix -g)/lib/node_modules/@zowe/cli && mv node_modules/keytar node_modules/keytar-old
```

**Comment by YvesMichon** [comment]
Thanks for reply.

We have renamed the keytar module in keytar_old. We have started zowe in daemon mode but when we have used zowex, we saw `Internal Imperative Error: Root command help error occurred: Keytar not Installed` in zowe log.
We don’t need to store user and password in profile because we pass them in command line

**Comment by dkelosky** [comment]
Hi @YvesMichon - after testing with @t1m0thyj , we see that some versions of npm are incorrectly adding `keytar` to `dependencies` of `@zowe/cli`'s `package.json`.  

Can you edit `cd $(npm prefix -g)/lib/node_modules/@zowe/cli/package.json` ?  if so, please find `dependencies` and delete the line that includes `"keytar"`.  Please also leave the module named `keytar-old` as indicated above. 

Then, please restart the daemon, retest, and report back. 

Thanks,

**Comment by YvesMichon** [comment]
Hi Dan,
I've modified the package.json file. And now zowex works without keytar when we starts zowe in daemon mode in command line.
But when we starts the daemon mode in service, we still have the error message for X11.
The service is started with `systemctl start ZOWE.service`. 
Here is logs in /var/log/messages 
`Jul 30 08:02:58 ibldfzt5027m systemd[1]: Started Daemon Zowe.
Jul 30 08:02:59 ibldfzt5027m zowedaemon[524211]: [2021/07/30 08:07:98] [INFO] [Processor.js:59] server bound 4000
Jul 30 08:03:17 ibldfzt5027m zowedaemon[524211]: Internal Imperative Error: Root command help error occurred: Cannot autolaunch D-Bus without X11 $DISPLAY
`

Thanks for your help

**Comment by dkelosky** [comment]
Thanks for following up.  We'll see if we can get more time to look at this latest issue next week.

**Comment by t1m0thyj** [comment]
> I've modified the package.json file. And now zowex works without keytar when we starts zowe in daemon mode in command line.
But when we starts the daemon mode in service, we still have the error message for X11.

@YvesMichon When you start the daemon mode in service, is it running as a different user?

If you've moved Keytar out of the way, then daemon mode shouldn't behave any differently whether launched in a systemd service or on the command line. The error `Cannot autolaunch D-Bus without X11 $DISPLAY` indicates that Keytar is installed and failed to load, which is unexpected since it shouldn't have been found in your environment.

In the user environment where the systemd service is running, can you verify that these directories do not exist?
* `$(npm prefix -g)/lib/node_modules/keytar`
* `$(npm prefix -g)/lib/node_modules/@zowe/cli/node_modules/keytar`
* `~/.zowe/plugins/installed/lib/node_modules/@zowe/secure-credential-store-for-zowe-cli`

Note that the NPM prefix may be user-specific, so the actions of renaming the "keytar" directory to "keytar-old", or removing it from package.json dependencies, may need to be performed in multiple places.

Using the file below, after I performed the suggested actions, I can run the Zowe CLI daemon in CentOS 8 without any issues:
```
[Unit]
Description=Zowe CLI daemon
After=network.target

[Service]
ExecStart=/root/.nvm/versions/node/v14.17.4/bin/node zowe --daemon
WorkingDirectory=/root/.nvm/versions/node/v14.17.4/bin
StandardOutput=inherit
StandardError=inherit
Restart=always
User=root

[Install]
WantedBy=multi-user.target
```

**Comment by YvesMichon** [comment]
Thanks t1m0thyj !

You're right. It remains a keytar installation in `$(npm prefix -g)/lib/node_modules/keytar`.
After renaming it, zowex works in daemon mode.

I'm closing the issue.

**Comment by MikeBauerCA** [comment]
@YvesMichon this is the first instance we have seen interest in running "zowe --daemon &" in a service. Could you elaborate on why you want to run it in a service?

**Comment by YvesMichon** [comment]
@MikeBauerCA,

We have an NodeJs back application installed on a linux server that serve some services for a front angular other application.
In this front application, the user prepare a run test for 3270 programs. He must prepare the DB2 views for his programs by running DDL and DML and binding DB2 packages. The bind is made by sending a job with ZOWE CLI.
Next, he recover his test JCL, eventually  modify and run it. It's made by ZOWE CLI too. The application has export/import functionnalities with sequential files directly on z/OS. Sending et receiving files are made with ZOWE CLI.
All ZOWE services are in the NodeJS back application. We use Zowex to have better network performance. So we need to have Zowe running in deamon mode. The starting of Zowe is made by service as the starting of the NodesJS back application.
