### ISSUE TITLE
Switch from tslint to eslint

### ISSUE THREAD

**Issue by zFernand0** [zowe/zowe-cli#1070]
see title

**Comment by t1m0thyj** [comment]
When we migrate to ESLint, I suggest we also consider whether to adopt Prettier which is integrated with it 🙂 

If our team agrees on a code style, then we can have Prettier maintain it for us automatically, and hopefully this would make it easier to onboard new contributors so they wouldn't have to manually fix formatting-related lint errors.

**Comment by t1m0thyj** [comment]
Now that we've performed the initial migration to ESLint, here a few ideas for plugins to try out in the future 😋 
* [eslint-plugin-jsdoc](https://www.npmjs.com/package/eslint-plugin-jsdoc) - Lints JSDoc comments, currently with recommended rules enabled it finds 2679 problems in Imperative 😢 
* [eslint-plugin-license-header](https://www.npmjs.com/package/eslint-plugin-license-header) - If we want to replace our custom license checker script
* [eslint-plugin-prettier](https://www.npmjs.com/package/eslint-plugin-prettier) - If we want to adopt Prettier to enforce a specific code style
