### ISSUE TITLE
Downloading a file with "#" in member name failing

### ISSUE THREAD

**Issue by ajit-t-5144** [zowe/zowe-cli#1073]
Trying to download all members in a file . But its failing as some of the members contain "#" in the member name .

**Command**  
zowe zos-files download all-members "DatasetName" -b -d "DirectoryLocation"

**Error Message :** 

z/OSMF REST API Error:
Rest API failure with HTTP(S) status 404
category: 1
rc:       4
reason:   3
message:  DatasetName(

Error Details:
HTTP(S) error status "404" received.
Review request details (resource, base path, credentials, payload) and ensure correctness.

Protocol:  https
Host:      host
Port:      port
Base Path: basepath
Resource:  /zosmf/restfiles/ds/DatasetName(member1)
Request:   GET
Headers:   [{"X-IBM-Data-Type":"binary"},{"Accept-Encoding":"gzip"},{"X-IBM-Response-Timeout":"250"},{"X-CSRF-ZOSMF-HEADER":true}]
Payload:   undefined

From User list thread 
https://lists.openmainframeproject.org/g/zowe-user/topic/84389452?p=Created,,,20,1,0,0::recentpostdate/sticky,,,20,2,0,84389452

Thanks,Ajit

**Comment by awharn** [comment]
Thanks for reporting an issue. I just have a few questions:

1) What version of Node are you using? (node --version)
2) What version of NPM are you using? (npm --version)
3) What version of Zowe CLI are you using? (zowe --version)
4) I see that basepath is on the request. Are you using the API mediation layer?
5) What are the dataset and member names you are using? If there is data that you need to omit, please replace letters with X and numbers with 1. Please leave special characters, like the #, the same. (i.e. USER.GROUP5.TEST.JCL -> XXXX.XXXXX1.TEST.JCL)

**Comment by ajit-t-5144** [comment]
Node v 14.17.3
npm 6.14.13
zowe 6.32.1
Yes . Using a API mediation layer .

Dataset : USER.DEV.TEST.CONTROL 
members : #CONTROL1,CONTROL#2,CONTROL3,CONTROL4

Command 
zowe zos-files download all-members "USER.DEV.TEST.CONTROL " -d "DirctoryLocation"  --> Fails with above error 

zowe zos-files download all-members "USER.DEV.TEST.CONTROL " --ff false -d "DirctoryLocation" --> Download CONTROL3 and CONTROL4 .  Shows error message with below error details.
Failed to download the following members:
#CONTROL1
CONTROL#2

Note : Though i gave dummy names, the "#" are in exact positions.  this control dataset contains my Sort cards and other utility parameters .

**Comment by FALLAI-Denis** [comment]
Hi @ajit-t-5144 

What codepage (-ec parameter in z/osmf profile) are you using?

z/osmf does not correctly handle codepage for file and member lists. It always uses the IBM-1047 codepage (native USS codepage).
z/osmf uses the codepage only for transferring the content of files and members.
For example on our site which works with IBM-1147 codepage, the # characters are systematically transformed into £ characters in the lists under Zowe CLI or in Zowe Explorer.

In addition, I saw, in a another message, a status code 500 at the z/OSMF server level, which probably reflects a serious error at the server level.
Is there any information in the outputs of the z / OSMF server or in its log?

**Comment by awharn** [comment]
Can you attempt to download one of those members with the # in it individually, using the `zowe files download ds DSN(MEMBER)` command, and replace the `#` with `%23`? (i.e. `zowe files download ds USER.DEV.TEST.CONTROL(CONTROL%232`) I am beginning to wonder if this is a problem around URI encoding, and the differences between special character handling in the z/OSMF API and the API Mediation Layer's API.

**Comment by ajit-t-5144** [comment]
@FALLAI-Denis  @awharn 
Thank you Very much for looking into the issue .

neither --ec nor %23 worked . The error is still 404 . I am not sure about server logs . I will check and get back to you .

**Comment by FALLAI-Denis** [comment]
@ajit-t-5144 

Can you verify that problematic members are not in "pack" mode ?

Under TSO/ISFP, view or edit the member, and enter `profile` on the command prompt.

![image](https://user-images.githubusercontent.com/63861965/127279602-5f4c09d0-7851-4eef-874f-6ca97221f3a3.png)


Also, look for invalid characters in members : enter `find P'.'` on the command prompt.

![image](https://user-images.githubusercontent.com/63861965/127279797-e5555160-0096-4c89-8118-a8aecbff4cad.png)
