### ISSUE TITLE
Installation at "machine" level - separate the plugins folder and the profiles folder

### ISSUE THREAD

**Issue by FALLAI-Denis** [zowe/zowe-cli#1076]
Hi,

In your site context, we want to teledistribute software. Our users are not allowed to install software on workstations.
This also concerns Zowe CLI, and Zowe CLI plugins.
Teledistribution must be done independently of users, according to a "machine" context rather than an "user" context.

To date, Zowe CLI does not seem to have planned to differentiate the plugins installation folder, and the profiles declaration folder.
Everything is installed under the same root: `C:\Users\<username>\.zowe` in a Windows context.
In a "machine" installation, the plugins should be in a "machine" folder, to be common to all users, and the profiles, (also logs ?) should be in an "user" folder.

There is an environment variable `ZOWE_CLI_HOME` which allows you to choose the ".zowe" folder, but it is common for plugins,  profiles, logs, etc.

There would need to be specific variables to manage the location of items common to all users, (In principle a folder in `C:\ProgramData` in a Windows context), and to manage the location of items specific to a specific user (In principle a folder in `C:\Users\<username>` in a Windows context).

**Comment by JTonda** [comment]
Estimated size:  5

**Comment by t1m0thyj** [comment]
A new environment variable `ZOWE_CLI_PLUGINS_DIR` has been added in Zowe CLI v7.5.0 that allows you to control the plugin install location independently of `ZOWE_CLI_HOME`. It is documented here: https://docs.zowe.org/stable/user-guide/cli-configuringcli-ev/#setting-a-shared-plug-in-directory
