### ISSUE TITLE
Command Preparation Fails after deleting profiles

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/zowe-cli#108]
![image](https://user-images.githubusercontent.com/35504792/47934674-55cd6500-deae-11e8-9f28-0411c1574f90.png)

To recreate:
1. Set an environment variable for a z/OSMF profile property (E.G. ZOWE_OPT_HOST)
2. Construct a z/OSMF profile
3. Delete z/OSMF profile
4. Run a command relying on the environment variable set for the z/OSMF profile property

Workaround:
Deleting the .zowe folder resolves the issue

node --version
v10.13.0
npm --version
6.4.1
bright --version
2.0.0-next.201811011948

**Comment by ChrisBoehmCA** [comment]
I think only steps 2-4 are required to recreate this issue and that it's independent of environmental variables

**Comment by tjohnsonBCM** [comment]
Fixed in https://github.com/zowe/imperative/pull/304
