### ISSUE TITLE
`zowe config` doc needs to be updated

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/zowe-cli#1084]
The `--global` and `--user` flags on the `zowe config` commands were changed to `--global-config` and `--user-config`. [This documentation](https://github.com/zowe/zowe-cli/blob/next/docs/Early%20Access%20-%20Using%20Global%20Profile%20Configuration.md#initializing-global-configuration) needs to be updated to reflect that.

**Comment by Patil2099** [comment]
I would love to take this up.
