### ISSUE TITLE
[next] Validate @zowe/cli@next installation works on z/OS USS and zLinux

### ISSUE THREAD

**Issue by awharn** [zowe/zowe-cli#1091]
With the Secure Credential Store built directly into Imperative, and problems that exist installing Keytar on s390x, validate that the next version of Zowe CLI can be installed on the mainframe without secure credential storage.

If it cannot, find required workarounds or modifications to get it working, or consider any documentation stating that the CLI cannot be installed on a z/Linux or z/OS USS platform.

**Comment by Simnbf** [comment]
Has there been any progress on this? We're keen to test `zowe@next` on zlinux

**Comment by t1m0thyj** [comment]
@awharn Was this resolved in zowe/docs-site#2029? If so, I think we are good to close this issue.

**Comment by awharn** [comment]
@t1m0thyj I believe this has been resolved in that docs site issue. The process for installing `@zowe/cli@next` on z/Linux can be found [here](https://docs.zowe.org/stable/user-guide/cli-install-cli-next).
