### ISSUE TITLE
zowe cli compare command

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/zowe-cli#1095]
I would like to use Zowe CLI to easily compare data set members. Today, I would download the members and use another tool to perform the diff. It would be useful to provide the diff within the terminal but also have an option to display the diff in a browser similar to diff2html.

Suggested syntax:
zowe files compare members

The compare group could be expanded to compare uss files as well as combinations of local files, uss files, and data sets.

---

- [x] #1442
- [x] #1443
- [x] #1444
- [x] #1445
- [x] #1446
- [x] #1447
- [x] #1448

List copied from https://github.com/zowe/zowe-cli/issues/1095#issuecomment-1118914262

**Comment by MikeBauerCA** [comment]
This group could also be used to compare spool files from job output.

**Comment by MikeBauerCA** [comment]
Actually, that would likely be in a `zowe jobs compare` group 😄

**Comment by JTonda** [comment]
CLI diff of datasets in terminal - 5 pts
CLI diff of datasets in browser - 8 pts
CLI diff of local file and dataset in terminal/browser - 3 pts
CLI diff of USS files in terminal/browser - 5 pts
CLI diff of local file and USS file in terminal/browser - 3 pts
CLI diff of spool dds in terminal/browser - 5 pts
CLI diff of local file and spool dd in terminal/browser - 3 pts

**Comment by FALLAI-Denis** [comment]
Hi,

Zowe CLI in its latest versions, (7.4.x?), makes it possible to compare two data sets from the remote system, and the comparison (diffutil type) is done locally on the workstation.

I see that other types of comparisons are being considered.

But I don't see any use case concerning the comparison between a local file and a remote file, moreover for the same file name, to compare the local version being edited and the remote version: equivalent of the function " compare *" on the ISPF editor.
It is, however, from my point of view, the most useful type of comparison.

**Comment by zFernand0** [comment]
Based on #1502, it seems like there is more work to do around file comparison.

However, the intended enhancements outlined in this issue have been completed.
Closing.
