### ISSUE TITLE
zowe files view data-set

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/zowe-cli#1096]
I would like to have a `zowe files view data-set` and a `zowe files view uss-file` command to easily view data-sets and uss-files within the terminal. This would also help with piping content into other commands without needing to first download the content to a file.

**Comment by zFernand0** [comment]
Should this command have some sort of option to open the file/ds in the desired editor or even browser? 
Kind of like triggering the `--open-with` on Windows.
![image](https://user-images.githubusercontent.com/37381190/128350746-5d0993cf-a6f2-4731-849a-830556805b2a.png)

**Comment by MikeBauerCA** [comment]
Nice, I suppose it would just open it in the editor as a temp file? This inspires a `zowe files edit` group!

**Comment by ChrisBoehmCA** [comment]
This is a good feature for the reasons you mentioned - piping output to other commands or a simple way to get contents of a data set into memory in automation without taking up disk space locally

**Comment by MikeBauerCA** [comment]
This functionality is offered in Broadcom's extended files plug-in. Broadcom would like to contribute this idea to core Zowe CLI as part of Zowe V2 LTS. We may be able to leverage some of the code as well.

In core, the command will be zowe zos-files view data-set with an alias of ds.

Command entry in zowe files view help
data-set | ds - View content from a z/OS data set

**Command help**

zowe › zos-files › view › data-set
View content from a z/OS data set to your terminal (stdout).

Usage
zowe zos-files view data-set <dataSetName> [options]

Positional Arguments
dataSetName (string)

The name of the data set you want to print.
Options
--binary | -b (boolean)

View data set content in binary mode.

... standard profile help ...

Examples
View the contents of the data set member "ibmuser.cntl(iefbr14)":

zowe zos-files view data-set "ibmuser.cntl(iefbr14)"

View the contents of the data set member "ibmuser.test.loadlib(main)" in binary mode:

zowe zos-files view data-set "ibmuser.test.loadlib(main)" --binary

**Comment by zFernand0** [comment]
Added in v7.2.0
