### ISSUE TITLE
`zowe files edit data-set` & `zowe files edit uss-file`

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/zowe-cli#1097]
Inspired by #1096 and specifically @zFernand0's [comment](https://github.com/zowe/zowe-cli/issues/1096#issuecomment-893423267), a `zowe files edit data-set` and `zowe files edit uss-file` command could be added. The command would be able to launch the default editor where users could edit the file and upon save the data-set/file would be uploaded back to the mainframe. This will need to handle possible conflicts (e.g. while editing, someone else updated the data-set/file).

**Comment by sarthakjdev** [comment]
Hey @MikeBauerCA @zFernand0 
I would like to work on this issue.
