### ISSUE TITLE
Using `ZOWE_OPT_PASSWORD="PROMPT*"` hides the password but it then echos out after creating a profile.  

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-cli#1118]
**Problem**
For creating videos and doing demos of CLI I don't want to show my password being entered, so the feature `prompt*` is great for this, as I can specify `zowe create profile zosmf name --host host.name --port 12345 --user WINCHJ --password "PROMPT*"` which then requests for my password without echoing it back to the shell.
However ....
It then prints out all of my profile details that includes my password ! 

![image](https://user-images.githubusercontent.com/28100302/130601359-38da7fdb-6026-4d9a-ad34-2f31f17d3364.png)

**Desired Behavior**
Don't show the password back when the echo of the successful profile creation has ocurred and the `ZOWE_OPT_PASSWORD` variable is set to `PROMPT*`. 
Do likewise if `"prompt*"` is just specified at the command line when the password is being created for the profile

**Comment by t1m0thyj** [comment]
The behavior of `prompt*` is to perform one-time prompting. If you want the `prompt*` value to persist, you can set it in a persistent location like an environment variable or manually add it to a profile .yaml file. In the case of the `profiles create` command, using `prompt*` as a CLI argument doesn't make much sense unless you have the Secure Credential Store installed, as you've observed.

For your use case, would it work to create a zosmf profile without specifying any password? As long as there's not a password being stored somewhere else like an environment variable or base profile, the CLI should automatically prompt you for the missing password, like this:
```
$ zowe profiles create zosmf test --host example.com --port 443 --user XXX
Profile created successfully! Path:
C:\Users\User\.zowe\profiles\zosmf\test.yaml

host:               example.com
port:               443
user:               XXX
rejectUnauthorized: true
protocol:           https

Review the created profile and edit if necessary using the profile update command.

$ zowe jobs list jobs
Enter password : ********
...
```

**Comment by Joe-Winchester** [comment]
@t1m0thyj ,  I had tried that but I don't get a password prompt when it's left off the profile creation

![image](https://user-images.githubusercontent.com/28100302/130639009-cc47f8c4-5984-4256-a763-6f2a323f2c42.png)

**Comment by t1m0thyj** [comment]
What is your version of Zowe CLI? The prompting functionality was added in [6.16.0](https://github.com/zowe/zowe-cli/blob/master/packages/cli/CHANGELOG.md#6160).

**Comment by t1m0thyj** [comment]
Closing since the original issue has been discussed in #1050 and the second one which is outstanding can be tracked in #1119.
