### ISSUE TITLE
The `--password "prompt*"` doesn't seem to work for z/OSMF profiles

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-cli#1119]
**Problem**

To avoid the password being shown (which I am doing to create some doc videos for profile creation) I am using `--password "prompt*"` as described in https://docs.zowe.org/stable/user-guide/cli-usingcli/#using-the-prompt-feature.

The password is being prompted for without an echo (which is good) and stored in the profile which echos back (less good but covered in https://github.com/zowe/zowe-cli/issues/1118.  I've manually masked it out on the screen shot below.

The issue is that the zowe CLI command doesn't work as I get an error 
```
Syntax Error:
No value specified for option:
--password
```

I checked the `~/.zowe/profiles/zosmf/test.yaml` file for my profile and it is recorded there.

![image](https://user-images.githubusercontent.com/28100302/130602344-fb5ea903-39dc-4dc6-bdd8-f22ef601f373.png)

**Comment by adam-wolfe** [comment]
Tested with latest versions V1 and V2, no longer seeing this issue.
