### ISSUE TITLE
Include the `zowex` binary in our `next` bundle on our Zowe Downloads site

### ISSUE THREAD

**Issue by zFernand0** [zowe/zowe-cli#1120]
See title :yum:

[Zowe Downloads](https://www.zowe.org/download.html) site

_Originally posted by @MikeBauerCA in https://github.com/zowe/docs-site/pull/1785#r690701021_

**Comment by gejohnston** [comment]
Should we delay taking this action until we decide to distribute the "auto-start" version of the zowe executable? I am not sure.

**Comment by MikeBauerCA** [comment]
I think we should go ahead and include it. The "auto-start" version can be another incremental improvement.

**Comment by t1m0thyj** [comment]
Is this a duplicate of https://github.com/zowe/zowe-cli-standalone-package/issues/37? 😋
