### ISSUE TITLE
"zowe provisioning provision template" is not catching missing positional argument

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/zowe-cli#113]
`zowe provisioning provision template` is attempting to run the command with the name of the default zosmf profile when no positional argument is provided. My default profile is named zowe for the response below:
![image](https://user-images.githubusercontent.com/35504792/48221443-1dbb9b80-e360-11e8-9ae5-e50f4332d80e.png)

The expected positional argument is:
![image](https://user-images.githubusercontent.com/35504792/48221552-6a9f7200-e360-11e8-9788-7a2002f796a1.png)

node version: v8.11.3
npm version: v6.4.1
bright version: 2.0.0-next.201811011948

**Comment by AHumanFromCA** [comment]
see zowe/imperative#112

**Comment by ChrisBoehmCA** [comment]
This has been fixed
