### ISSUE TITLE
Moderate vulnerability in transitive dependency

### ISSUE THREAD

**Issue by pablocarle** [zowe/zowe-cli#1130]
`npm audit` reports a moderate vulnerability in latest version of CLI (6.33.1) on `js-yaml` component, recommended upgrade to `3.14.1`

**Comment by zFernand0** [comment]
@pablocarle 
Thanks for reporting it.

I'm afraid I haven't had the chance to spot it on `3.13.1`
https://github.com/zowe/zowe-cli/blob/41ad66100f4e788d8d57516807264f9cf5d39368/package.json#L70

Could you share a link to the advisory and/or report?
e.g. https://snyk.io/vuln/npm:js-yaml

Also, it seems that it's a devDependency of this package. We are watching other packages on zowe for the same dependency.

Note:
For further security related items, please send us an email at `zowe-security@lists.openmainframeproject.org`
We are working to get this reflected in our Security Policies.

Thanks!
