### ISSUE TITLE
zos-jobs delete job command has no sync option

### ISSUE THREAD

**Issue by DivergentEuropeans** [zowe/zowe-cli#1132]
Hello CLI team, I have a question about the zowe zos-jobs delete job command. When running something like, zowe jobs delete job JOBXXXXX --rfj  to get my JSON response object, I would get something like
{
  "success": true,
  "exitCode": 0,
  "message": "Successfully deleted job XXXXXXXX (JOBXXXXX)",
  "stdout": "Successfully deleted job XXXXXXXX (JOBXXXXX)\n",
  "stderr": "",
  "data": {
    "owner": "OWNER",
    "phase": 20,
    "subsystem": "JES2",
    "phase-name": "Job is on the hard copy queue",
    "job-correlator": "XXXXXXXXXXXXXXXXX.......:",
    "type": "JOB",
    "url": ".../zosmf/restjobs/jobs/XXXXXXXX.......%3A",
    "jobid": "JOBXXXXX",
    "class": "L",
    "files-url": ".../zosmf/restjobs/jobs/XXXXXXXX.......%3A/files",
    "jobname": "XXXXXXXX",
    "status": "OUTPUT",
    "retcode": "CC 0000"
  }
}
so we get an exit code of 0 and retCode CC 0000 but status tells us this isn't actually the status of the operation, but the status of the job. So from this we don't get whether we successfully deleted job, and this has to do with the way CLI sends an async/sync delete request. According to the z/OSMF docs, it's controlled by the X-IBM-Job-Modify-Version header which I see in some parts of the code accepts 1 or 2. But the default delete job command seems to do it async, where doing it sync I should receive the JSON job feedback document. Is there a command or arg to zowe jobs delete job that makes this sync where we get a response back about the status of the operation? I didn't see it with zowe zos-jobs --help-examples

**Comment by zFernand0** [comment]
Might be related to https://github.com/zowe/zowe-cli/issues/1092

**Comment by DivergentEuropeans** [comment]
Removing because of duplicate of #1092
