### ISSUE TITLE
ZOWE_CLI_HOME causes response time to increase

### ISSUE THREAD

**Issue by EmlynWill** [zowe/zowe-cli#1133]
I have set ZOWE_CLI_HOME so that my profile is written to a different drive to where the software is installed. This has increased my Zowe CLI command response time from about 3 seconds to 30 seconds. This is for any command even zowe --help. 
Is there any way of improving the response time?

**Comment by dkelosky** [comment]
This is not a final solution, but to help identify the problem, can you turn off the CLI logging and see if this impacts command response time?  

The env vars for this are:  `ZOWE_APP_LOG_LEVEL=FATAL` and `ZOWE_IMPERATIVE_LOG_LEVEL=FATAL`.

**Comment by EmlynWill** [comment]
Hi Daniel, There was no obvious improvement

**Comment by dkelosky** [comment]
We have a validation version of Zowe CLI and a "daemon" mode to help with command response time.  Before going that route, I'm also curious if Node.js response time is fast on your system.  Does `npm --version` return quickly?  Is the `ZOWE_CLI_HOME` the only change (e.g. if you revert this setting, does response time go back to ~3 seconds)?

**Comment by EmlynWill** [comment]
"npm --version" response is about 2 seconds
ZOWE_CLI_HOME is the only change and the response time reverts to 3 seconds when I remove it

**Comment by dkelosky** [comment]
Is `ZOWE_CLI_HOME` a network file system?  Are you running under a linux environment or a different OS?  

It might be interesting to get some IO measurements for `ZOWE_CLI_HOME` and the default location.

**Comment by dkelosky** [comment]
If linux, please run the following 2 commands at `ZOWE_CLI_HOME` and at the default home.:
* `dd if=/dev/urandom of=random_data.txt bs=1M count=1`
* `dd if=random_data.txt of=/dev/null`

Please capture the output from both commands for both locations.  These commands create and copy a `random_data.txt` file which can be deleted after.  

From here, we might also test running a simple Node.js from both locations and then likely move on to daemon mode to increase command response time.

**Comment by EmlynWill** [comment]
Yes, I set ZOWE_CLI_HOME is a network file system. I'm running on a virtual Windows desktop

**Comment by dkelosky** [comment]
Are you interested in trying "daemon" mode?  If so, please keep log level set to `FATAL` while testing: `set ZOWE_APP_LOG_LEVEL=FATAL and set ZOWE_IMPERATIVE_LOG_LEVEL=FATAL`

You'll need to:
1. install our `next` version via `npm install -g @zowe/cli@next` & verify version is `7.0.0-next.xxxxxx` via `zowe --version`
3. download `zowex.exe` from the [windows tgz file](https://github.com/zowe/zowe-cli/releases/tag/native-v0.2.1)
4. add `zowex.exe` to your PATH (e.g. `set PATH=%PATH%;C:\your\path\here\`)
5. `start zowe --daemon` (which launches a new window with a message: `[Processor.js:59] server bound 4000`)
6. in the original window, try `zowex --help` to see if response time is improved

**Comment by EmlynWill** [comment]
We can't install keytar here so there were failure messages during the @next install. I ignored the install error then I got this message wen I ran zowex --help
Internal Imperative Error: Root command help error occurred: Keytar not Installed

**Comment by dkelosky** [comment]
I think we have a workaround for this if you'd like to try.

1. run `npm prefix -g` which will return where global npm modules are installed
2. `cd` to the output location from the previous command
3. `cd node_modules/@zowe/cli/`
4. if `keytar` appears under `dependencies` instead of `optionalDependencies`, please delete that line from `package.json`
5. in the same directory as `package.json` `move node_modules/keytar node_modules/keytar-old` 

Then you can stop the daemon by closing the window and relaunching it.

**Comment by EmlynWill** [comment]
Wow. Removing keytar from the .json file worked (I didn't have a keytar directory to move)
zowex --help was super quick (1 or 2 seconds)
All my plug-ins need updating now for zowex (or do I revert back to the previous version of zowe CLI somehow?)

**Comment by EmlynWill** [comment]
One problem, zowex does not use ZOWE_CLI_HOME, it uses the default location.

**Comment by EmlynWill** [comment]
One problem, zowex does not use ZOWE_CLI_HOME, it uses the default location.

**Comment by dkelosky** [comment]
For plugins, I think it depends.  Unfortunately, we don't have a list of which plugins would continue to work without upgrading them to their respective `@next` versions.  Most plugins do have a `@next` version published.  If you upgrade a plugin (`zowe plugins install @zowe/<plugin-name-here>@next`).  We need a restart of the daemon (since there is no hot-reload support yet).

**Comment by dkelosky** [comment]
Env vars should be pushed across command prompts.  For example, if you have a command prompt, you can run:
* `set HELLO=WORLD`
* `echo HELLO` (verify `WORLD`)
* `start cmd`
* in new command prompt, `echo HELLO` (verify `WORLD`)

Can you verify that you get the same behavior?  It seems like `ZOWE_HOME_CLI` is honored in my machine, but perhaps there is something different about our environments.

**Comment by EmlynWill** [comment]
Sorry Dan, I couldn't have closed all my cmd windows when I set ZOWE_CLI_HOME. 
zowex is working now with ZOWE_CLI_HOME set to my network drive and I'm getting <1 second responses
Also, the Endevor plug in is working now with zowex, I will try updating the others

**Comment by dkelosky** [comment]
np - glad it is working.  We might have a few issues in daemon mode while we're in validation.  Please report any issues you find and thanks for trying it out.  

We've pondered storing credentials (tokens/cookies) in-memory of the daemon for folks that have issues with keytar / secure credential store.  If you have some other suggestions or opinions on alternatives to keytar, please also let us know.

**Comment by EmlynWill** [comment]
While I can't install keytar mon my virtual desktop we have installed it successfully in the Windows Appv packaging process. This package then gets rolled out to our users to install. 
When I was testing the package is when we came across the ZOWE_CLI_HOME issue, i.e. Appv does not allow our users to update the software location. And then I tried ZOWE_CLI_HOME and had the response time issue....
So we can use SCS once it's packaged, and keytar isn't an issue.
We might have to wait for you to publish Zowe CLI daemon mode before we roll it out to our users.

**Comment by dkelosky** [comment]
Got out, thanks again

**Comment by EmlynWill** [comment]
I'm assuming that the release version will not need the user to issue the "start zowe --daemon" command or need cmd.exe?

**Comment by dkelosky** [comment]
we want to make it more seamless such that the first time you use `zowe` the daemon would be launched in the background - @gejohnston began doing some of this work, but I believe it is still in progress.

**Comment by gejohnston** [comment]
Here are a couple of deamon-mode features that we have implemented in our lab. None have been released externally yet (not even in a pre-release distribution).

- You always use the zowe command (no need to use a zowex command).
- The deamon is automatically started in the background when needed. The deamon terminates when you terminate your command window.
- The end user controls whether the zowe command starts and uses the daemon by setting an environment variable.

These features may change further before the app is released.

**Comment by dkelosky** [comment]
@emlynwill, is it ok to close this issue?

**Comment by EmlynWill** [comment]
I checked with our packaging team and they think that the new process will be ok but cmd.exe will not be available to users so we'll have to see.

**Comment by dkelosky** [comment]
thanks - fyi @gejohnston to see the latest note:
> cmd.exe will not be available to users so we'll have to see.

**Comment by gejohnston** [comment]
I am not familiar with a Windows environment that does not have cmd.exe. Does this imply that there is no command prompt? In what command shell is the user typing the Zowe command? I am confused.

**Comment by EmlynWill** [comment]
I'm using powershell within VSCode
