### ISSUE TITLE
Allow easy trigger of deploy on master.

### ISSUE THREAD

**Issue by AHumanFromCA** [zowe/zowe-cli#115]
When merging code to master, a pre-release version automatically gets deployed. Sometimes this deploy can fail, leaving us unable to deploy because a bump commit was made.

We need to be able to retrigger a deploy build quickly in this scenario in both zowe-cli and imperative.

**Comment by zFernand0** [comment]
We should consider this when we finalize the Jenkins to GHA migration

**Comment by gejohnston** [comment]
Some controlling logic exists in the GitHub Actions implementation of our pipelines. If those abilities do not address this request, it is unlikely that we will commit additional work on this behavior in the foreseeable future. Thus, closing this issue.
