### ISSUE TITLE
Incorrect example on `zowe profiles create zosmf-profile` command

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/zowe-cli#1152]
![image](https://user-images.githubusercontent.com/35504792/134939277-45000e1a-bb0e-4a9a-82f2-23a7ce573dbd.png)

Recommend amending to:
Create a zosmf profile called 'zosAPIML' to connect to z/OSMF via the Zowe API Mediation Layer running at host 'zosAPIML', port '60004', and allow for self-signed certificates. To reduce duplication, you could elect to store the 'host', 'port', 'reject-unauthorized', 'user', and 'password' values for the API Mediation Layer in a base profile and only store the 'base-path' of the service in the zosmf profile. 

Also, change example command to:
`zowe profiles create zosmf-profile zosAPIML --host zosAPIML --port 60004 --user ibmuser --password myp4ss --reject-unauthorized false --base-path ibmzosmf/api/v1`

**Comment by himanshu007-creator** [comment]
hi, i would like to work on this issue

**Comment by t1m0thyj** [comment]
Instead of 60004, we should suggest 7554 since it is the default API ML gateway port (see [Zowe docs](https://docs.zowe.org/stable/troubleshoot/troubleshoot-zos/)).

**Comment by MikeBauerCA** [comment]
Thanks @t1m0thyj - good catch! Let's please make that change
