### ISSUE TITLE
`zowe jobs list jobs` option to return execution data about each job

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/zowe-cli#1158]
With [APAR PH23046](https://www.ibm.com/support/pages/apar/PH23046), it is now possible to retrieve execution data for jobs via the z/OSMF REST API. See the optional `exec-data` option in the [documentation](https://www.ibm.com/docs/en/zos/2.4.0?topic=interface-list-jobs-owner-prefix-job-id). This proposal is to add this option on the command line to return the following information for each listed job (if available):
**exec-system** - System name of the z/OS system on which the job ran (up to 8 characters)
**exec-member** - Member name of the z/OS system on which the job ran (up to 8 characters)
**exec-submitted** - Time when the job was submitted to run (the input end time)
**exec-started** - Time when job execution started
**exec-ended** - Time when job execution ended.

**Comment by MikeBauerCA** [comment]
@namanpatel1112 do you have an update on this? Also, it may be useful to allow Zowe Explorer users to customize their JES view to see such information if desired (should be customizable) on the line with the `jobname(jobid) - retcode`. +@JillieBeanSim & @zFernand0

**Comment by namanpatel1112** [comment]
> @namanpatel1112 do you have an update on this? Also, it may be useful to allow Zowe Explorer users to customize their JES view to see such information if desired (should be customizable) on the line with the `jobname(jobid) - retcode`. +@JillieBeanSim & @zFernand0

I don't have an update on this yet. I got pulled into other work, but I believe I'll have some time next week to work on this one.
