### ISSUE TITLE
Daemon mode - must enable requests from different windows to be interleaved 

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/zowe-cli#1178]
Currently headers are not passed on every request - this implies a session context.

**Comment by t1m0thyj** [comment]
Resolved in https://github.com/zowe/zowe-cli/pull/1308. The daemon communication method was switched from TCP to sockets on Unix and named pipes on Windows. The max number of concurrent connections is now limited to 1, and interleaved requests are queued to be processed sequentially.
