### ISSUE TITLE
Daemon mode - reliable data parsing

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/zowe-cli#1179]
Pass commands & arguments in structures instead of text for more reliable data parsing. Confirm proper parsing on Windows (cmd, Powershell, gitBash) Linux, & Mac.

Spaces in parameters no longer require extra escape characters in daemon mode, but other special characters on the command line may not be correctly handled in daemon mode.

**Comment by t1m0thyj** [comment]
We should also test how daemon mode handles large binary data (for example, piping a binary file larger than 1 MB).

Since stdin/stdout/stderr content is not being buffered into chunks, and in the case of stdout/stderr is being parsed as JSON, there could be some data loss or poor performance.

**Comment by t1m0thyj** [comment]
Additionally, we should probably have better error handling, for example on the `JSON.parse` of data received from the daemon client 😛

**Comment by MikeBauerCA** [comment]
Closing as resolved, if we feel additional work is needed then separate issues should be opened.
