### ISSUE TITLE
Out of memory when download big data set

### ISSUE THREAD

**Issue by lyzla01** [zowe/zowe-cli#118]
Out of memory when download large data set.
```
$ bright files dl ds 'SYS1.DUMP31' --host mvsde20 --port 449 --binary
Data set downloaded successfully.
Destination: sys1/dump31.txt

<--- Last few GCs --->

[28800:00000000002C3E60]   166557 ms: Mark-sweep 1141.1 (1152.0) -> 1141.1 (1147.5) MB, 576.6 / 0.0 ms  last resort GC in old space requested
[28800:00000000002C3E60]   167190 ms: Mark-sweep 1141.1 (1147.5) -> 1141.1 (1147.5) MB, 633.1 / 0.0 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0000002F86BA5EE1 <JSObject>
    2: replace(this=000003883F402201 <Very long string[71093534]>,0000018FACEA4961 <JSRegExp <String[19]: [\x00-\x1f\x27\x5c]>>,0000018FACEA4A99 <JSFunction escapeFn (sfi = 0000002F86BC6DC9)>)
    4: strEscape(aka strEscape) [util.js:114] [bytecode=0000013F98986C71 offset=89](this=000003EF8F202311 <undefined>,str=000003883F402201 <Very long string[71093534]>)
    6: formatPrimitive(aka formatP...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node_module_register
 2: v8::internal::FatalProcessOutOfMemory
 3: v8::internal::FatalProcessOutOfMemory
 4: v8::internal::Factory::CopyFixedArrayWithMap
 5: std::vector<v8::internal::compiler::MoveOperands * __ptr64,v8::internal::ZoneAllocator<v8::internal::compiler::MoveOperands * __ptr64> >::_Reallocate
 6: v8::internal::compiler::Operator::EffectOutputCount
 7: 00000341C03047A1
```

**Comment by AHumanFromCA** [comment]
I can't tell exactly where the problem is but I would wager a guess on the download action causing the memory exception. I think we could try to solve this by downloading the data set in smaller chunks from the zosmf API, if it supports it. If zosmf doesn't support this functionality, we'll need to get the IBM zosmf team to add it as a feature.

For now I think we can have a workaround for users to just increase their heap size by setting a node environment variable `NODE_OPTIONS=--max_old_space_size=4096`. Unfortunately if the dataset is larger than the memory you can provide, there isn't much that could be done until we get a fix.

**Comment by dkelosky** [comment]
#NoFacts

**Comment by dkelosky** [comment]
It seems the CLI attempts to buffer all data in memory before writing to disk.  Can you provide a way for the API user to write to disk or stream elsewhere without buffering?

**Comment by AHumanFromCA** [comment]
Hey @dkelosky, you know you can link code lines in the issue right? I that would be helpful to place in here to track.

**Comment by AHumanFromCA** [comment]
Is this the code you were referring to?

https://github.com/zowe/zowe-cli/blob/9df9da0c4a9de9d11aa2a97eeee2aeb3c6caceae/packages/zosfiles/src/api/methods/download/Download.ts#L83-L108

**Comment by AHumanFromCA** [comment]
So yes there are 2 problems here:

1. There is no chunking of the download. So if content becomes > heap memory it will error.
2. We take content and place it into a buffer before writing. This essentially means we are using double the memory to perform the operation.

I think both need to be addressed here for this issue to be resolved. I think by solving the first one we might also tackle the second one in the same change.

**Comment by dkelosky** [comment]
No, I didn't know you could link lines.  Yes, that's related code, you get everything at once instead of chunks.

**Comment by AHumanFromCA** [comment]
Just talked with @tucker01 in chat, it looks like the data already comes down in chunks to the RestClient but there is no way for a user of the RestClient to access those chunks. Perhaps all that needs to happen is for the RestClient to expose the chunks to the caller so they can memory manage the download.

We should open an enhancement issue in imperative to track this.

**Comment by tucker01** [comment]
It might be nice (and less of a burden on the caller) to support a stream parameter to the RestClient. The RestClient could handle it without major refactoring of commands.

**Comment by AHumanFromCA** [comment]
Perhaps it could also do a progress bar if the Content Length of the request is known to the RestClient, but that probably is a separate enhancement.
