### ISSUE TITLE
v2 LTS - Out of the box experience documentation

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/zowe-cli#1184]
Documentation is created & validated from both a fresh install/config and migration from v1 LTS perspective. Key new features are also documented (team config, daemon mode, secure by default, etc.).

- Migration from v1 LTS
- New installation (try it out - set up Zowe CLI to work with a single service)
- New installation (best practices for enterprise rollout - set up Zowe CLI to work with multiple services, leverage API Mediation Layer for single sign-on + other benefits, share configuration with others in the organization, etc.)
- Daemon mode recommended to overcome performance issues

**Comment by JamesBauman** [comment]
The installation check list is corp OOBO initiative.   you can view the latest version here:
https://github.com/zowe/docs-site/blob/v2-doc-branch/docs/user-guide/cli-install-cli-checklist.md

Suggestion: We might want to include the article as part of this initiative.
