### ISSUE TITLE
Add Intellisense to secure array in zowe.config.json

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/zowe-cli#1187]
Currently the `$version` property in zowe.schema.json is 3:
https://github.com/zowe/imperative/blob/next/packages/config/src/ConfigSchema.ts#L29-L34

This means we have already gone through 2 version changes before the release of Zowe v2.

In the future, we may wish to make another change to the schema (like the one suggested in the title) that would necessitate bumping the version to 4.

We should have a plan for how to handle this - when a CLI user has version `N - 1` schema JSONs stored on their disk, how will we upgrade them to version `N`?

**Comment by MikeBauerCA** [comment]
Scope: does not include plan for making breaking changes to schema in the future

Expectation: When typing strings in secure array, intellisense provides all profile options applicable to that profile type. If it is a typeless profile, all profile property options are displayed.

**Comment by t1m0thyj** [comment]
Updated the schema in zowe/imperative#751 and `@zowe/cli@7.0.0-next.202203231654`
