### ISSUE TITLE
Daemon Mode - Socket connection error after every command [Mac-only]

### ISSUE THREAD

**Issue by zFernand0** [zowe/zowe-cli#1192]
Version 0.2.1 (`zowex`) throws the following error after every command
_thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 57, kind: NotConnected, message: "Socket is not connected" }', src/main.rs:56:42
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace_

Version 0.3.0 (`next-zowex-is-zowe`) throws a similar error after every command
_The daemon failed to run your command due to this error:
Socket is not connected (os error 57)_

**Comment by zFernand0** [comment]
FYI, 
In the old communication protocol between the Daemon and the Client, the socket errors are the only thing going to `stderr`
https://github.com/zowe/zowe-cli/issues/1195

**Comment by t1m0thyj** [comment]
This error (`Socket is not connected (os error 57)`) is the reason why integration tests fail in our macOS CI build.
