### ISSUE TITLE
data-set-partitioned alias is pds

### ISSUE THREAD

**Issue by dkelosky** [zowe/zowe-cli#1202]
`zowe zos-files create data-set-partitioned NEW.PDS.DATASET` is synonymous with `zowe zos-files create pds NEW.PDS.DATASET`.  Should the long command name be `partitioned-data-set` instead of `data-set-partitioned` ?

**Comment by MikeBauerCA** [comment]
I'm leaning towards closing as `won't fix` unless we get a lot of 👍. My opinion is mostly based on the commands in this group all having the form `data-set-<type>`. If we made this change though we would need to keep the old names around for at least one release as this would be a breaking change. We would want to consider changing the other names in the command group as well:
![image](https://user-images.githubusercontent.com/35504792/141487906-ef6636ad-b105-4e74-81a5-73e591248b7d.png)

**Comment by dkelosky** [comment]
Understood - I'm going to lobby for 👍 for [this comment](https://github.com/zowe/zowe-cli/issues/1202#issue-1051954270) and  👎 for [this comment](https://github.com/zowe/zowe-cli/issues/1202#issuecomment-967185856) 😉 .

**Comment by MikeBauerCA** [comment]
🤣 I actually clicked your links 🤣

**Comment by FALLAI-Denis** [comment]
Missing "Extened PDS", aka "PDS-E", aka "LIBRARY" ;-)

**Comment by MarkAckert** [comment]
There have been no new comments on this issue within the last year, and no upvotes for the `--partitioned-data-set` syntax. We will keep `--data-set-partitioned` instead. Thank you
