### ISSUE TITLE
--show-attributes alias is --pa

### ISSUE THREAD

**Issue by dkelosky** [zowe/zowe-cli#1204]
`zowe files create pds --help`:
![image](https://user-images.githubusercontent.com/14940561/141478190-440bdd7c-a0bd-4fba-956d-7b5aa181c393.png)

Should the alias be `--sa` ? On `zowe files list ds --help`, a similar option is shortened to `--attributes`.

**Comment by MikeBauerCA** [comment]
We would want to leave `--pa` around for some time as removing it would be a breaking change... I did some digging and long ago, the option was named `--print-attributes`. The was even before the code was contributed to Zowe!

**Comment by dkelosky** [comment]
Perfect, interesting history, thank you 😄

**Comment by MikeBauerCA** [comment]
I typically use this option on the `list ds` command. There it is just `--attributes | -a`. I like that primary option name and alias.

**Comment by dkelosky** [comment]
we could update `Create.options.ts` to have:
```typescript

    /**
     * The indicator that we should print all allocation attributes
     * @type {ICommandOptionDefinition}
     * @deprecated
     */
    showAttributes: {
        name: "show-attributes",
        aliases: ["pa"],
        description: strings.SHOWATTRIBUTES,
        hidden: true,
        type: "boolean"
    },

    /**
     * The indicator that we should print all allocation attributes
     * @type {ICommandOptionDefinition}
     */
    attributes: {
        name: "attributes",
        aliases: ["a"],
        description: strings.SHOWATTRIBUTES,
        type: "boolean"
    },
```

And add `ZosFilesCreateExtraOptions.attributes` to the `options` array in `Pds.definition.ts`

**Comment by himanshu007-creator** [comment]
@dkelosky Hi, Please close this issue as it was solved by PR <a href="https://github.com/zowe/zowe-cli/pull/1231">1231</a>
