### ISSUE TITLE
Examples missing for commands in zowe profiles delete, list, set, and update groups

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/zowe-cli#121]
There are no examples in the help for the following commands:
`zowe profiles delete zosmf`
`zowe profiles list zosmf`
`zowe profiles set zosmf`
`zowe profiles update zosmf`

Zowe plug-in development documentation should also be updated to recommend that all commands provide examples.

**Comment by AHumanFromCA** [comment]
I would defer this to @ChrisBoehmCA or @tucker01. I don't have any knowledge on this subject besides that the change might also require an imperative change.

**Comment by zFernand0** [comment]
My questions are: 
* **Do we need an example on how to list a set of profiles?** `zowe profiles list zosmf` already shows what you are looking for (a list of profiles)
* **Do we need an example on how to delete a profile?** Doing `zowe profiles delete zosmf --help` will give you information about the only parameter you need to delete a profile (the profile name) and even how to use the command (the *usage* section)
* **Do we need an example on how to set a profile as default?** Simpler than `delete` since we don't even have a self-explaining `--force` option.

The only one I think might be valuable to add examples is `update`, and only because it has the same "complexity" as `create`.

**Comment by MikeBauerCA** [comment]
I agree that the commands are not complex, but we have examples for other simple commands like `zowe files list ds <dataSetName>`. Where would you draw the line? @jelaplan, any thoughts on this?

**Comment by MikeBauerCA** [comment]
`zowe zosmf check status` is an even simpler command that currently has an example.

**Comment by AHumanFromCA** [comment]
I'd almost argue that it's an issue that such a simple command has an example. All that example really does is takes up space on the help that provides no value to me.

For instance, in my integrated visual studio code terminal, issuing help on the command lets me only see this:

```
in your default z/OSMF profile:

      $ zowe zosmf check status

   - Report the status of the z/OSMF server that you specified
   in a supplied z/OSMF profile:

      $ zowe zosmf check status --zosmf-profile SomeZosmfProfileName

   - Report the status of the z/OSMF server that you specified
   manually via command line:

      $ zowe zosmf check status --host myhost --port 443 --user myuser --pass mypass
```

To see the rest of the help (see below) I need to scroll up, which takes my hands off the keyboard:

```
zd-check-stat --help

 COMMAND NAME
 ------------

   status

 DESCRIPTION
 -----------

   Confirm that z/OSMF is running on a system specified in your profile and gather
   information about the z/OSMF server for diagnostic purposes. The command outputs
   properties of the z/OSMF server such as version, hostname, and installed
   plug-ins.

 USAGE
 -----

   zowe zosmf check status [options]

 ZOSMF CONNECTION OPTIONS
 ------------------------

   --host  | -H (string)

      The z/OSMF server host name.

   --port  | -P (number)

      The z/OSMF server port.

      Default value: 443

   --user  | -u (string)

      Mainframe (z/OSMF) user name, which can be the same as your TSO login.

   --pass  | --pw (string)

      Mainframe (z/OSMF) password, which can be the same as your TSO password.

   --reject-unauthorized  | --ru (boolean)

      Reject self-signed certificates.

      Default value: true

   --base-path  | --bp (string)

      The base path for your API mediation layer instance. Specify this option to
      prepend the base path to all z/OSMF resources when making REST requests. Do not
      specify this option if you are not using an API mediation layer.

 PROFILE OPTIONS
 ---------------

   --zosmf-profile  | --zosmf-p (string)

      The name of a (zosmf) profile to load for this command execution.

 GLOBAL OPTIONS
 --------------

   --response-format-json  | --rfj (boolean)

      Produce JSON formatted data from a command

   --help  | -h (boolean)

      Display help text


 EXAMPLES
 --------

   - Report the status of the z/OSMF server that you specified
   in your default z/OSMF profile:

      $ zowe zosmf check status

   - Report the status of the z/OSMF server that you specified
   in a supplied z/OSMF profile:

      $ zowe zosmf check status --zosmf-profile SomeZosmfProfileName

   - Report the status of the z/OSMF server that you specified
   manually via command line:

      $ zowe zosmf check status --host myhost --port 443 --user myuser --pass mypass
```

Perhaps the main problem here is that examples are always shown even when they might not be the most helpful piece of information to the end user.

**Comment by MikeBauerCA** [comment]
The plugin developer would like to have examples for all of their commands including the profile delete, set, update, and list commands.

**Comment by tucker01** [comment]
OK, thanks. 

Following up on my previous post, does the plugin developer need the ability to customize the examples for delete, set, and list? Or is it sufficient to auto-generate them?
