### ISSUE TITLE
Support for zowe-cli install on zOS/USS to enable native scripting

### ISSUE THREAD

**Issue by nkocsis** [zowe/zowe-cli#1211]
@ibmrcruicks commented on [Tue Oct 19 2021](https://github.com/zowe/community/issues/1325)

**Is your feature request related to a problem or limitation? Please describe.**
The IBM Z Xplore learning has been established to help students, and experienced professionals to develop skills in all aspects of the Z platform. Many of the target community have limited rights/ability to install code of any kind (college/uni lab machine, corporate-managed desktops, for example) -- we lose these candidates as soon as we require installation of the zowe-cli and associated plug-in.  Currently, 10s of thousands have signed up to the community, a great start to IBM drive to educate and enable a new generation of skilled Z enthusiasts.  With a "no local code" option, we can accommodate a much greater proprtion of the community. USS environment is a fundamental part of zOS, but currently does not benefit from full zowe support.

**Describe the experience you'd like**
System level, consistent, installation of zowe-cli in conjunction with node.js for zOS UNIX -- avoiding the need for individuals to attempt their own installation of potentially different versions/releases and associated support issues.
Ideally, such an installation would have SCS support, consistent with good secure practice.

**Describe alternatives you've considered**
global install with `npm install -g` -- short-lived effectiveness on learning system which are maintained fortnightly. Node.js install volume usually read-only.
Use of zowe-cli without SCS for educational purposes 

**Additional context**
https://newsroom.ibm.com/2021-10-13-IBM-Commits-to-Skill-30-Million-People-Globally-by-2030 
zOS skills necessarily expose users to the native Unix services on every Z system - an easy on-ramp to gaining experience  with zowe in a controlled.managed environment, without dependence on other operating systems/platforms.

---

@Joe-Winchester commented on [Mon Oct 25 2021](https://github.com/zowe/community/issues/1325#issuecomment-951123517)

I've helped a few customers get Zowe CLI working on USS and these are the issues we've had to work around:
```
export _CEE_RUNOPTS="FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)"
export _BPXK_AUTOCVT="ON"
```
These ensure that the `.js` files with their `ISO-85591' encodings are read correctly and not treated as EBCDIC.
These export statements aren't necessarily going to be in everyone's .profile file,  I was thinking of adding these to core CLI as even if they happened on a laptop there would be no detriment even though they're z/OS specific

We had another customer issue where the user installing npm had a uid of 0 that meant that `npm --version` failed (which is an npm issue so not stricly a Zowe CLI one).  

---

@ibmrcruicks commented on [Mon Oct 25 2021](https://github.com/zowe/community/issues/1325#issuecomment-951245410)

thanks Joe - we can implement that as default through /etc/profile in USS

**Comment by Joe-Winchester** [comment]
@zFernand0 ,  the issue was transferred from Community Repo to CLI as it's an enhancement request for a CLI feature (i.e. supporting install and operation on USS) so it was felt it should rest in the CLI squad's backlog (although others such as myself and Ross could work on any PRs needed for the code and/or docs).
Did you close it because you feel this isn't something the CLI squad should be doing, or you closed it because you feel it should be left in the community repository to make progress ?  Cheers !

**Comment by MikeBauerCA** [comment]
@Joe-Winchester It appears he closed it after he transferred the original issue via GitHub functionality. #1213 is the same issue and remains open. This one was closed as a duplicate.

**Comment by Joe-Winchester** [comment]
> @Joe-Winchester It appears he closed it after he transferred the original issue via GitHub functionality. #1213 is the same issue and remains open. This one was closed as a duplicate.

Awesome !  Thanks for clearings things up,  I get lost in github issues sometimes and just wanted to check that there is still an open issue that we can engage on and hopefully make progress towards expanding the scope of CLI deployment.  Cheers !
