### ISSUE TITLE
ZOWE_OPT environment variables ignored in daemon mode

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/zowe-cli#1215]
**Steps to reproduce**
1. Launch Zowe daemon in the background: `zowe --daemon &`
2. Run a command with the `zowex` binary that uses environment variables. For example:
    ```
    export ZOWE_OPT_USER=XXX
    export ZOWE_OPT_PASSWORD=XXX
    zowex jobs ls jobs
    ```
    OR in one line: `ZOWE_OPT_USER=XXX ZOWE_OPT_PASSWORD=XXX zowex  jobs ls jobs`
3. You are prompted to enter user & password even though they are defined in environment variables.

**Workarounds**
The environment variables must be defined before launching the `zowe --daemon` process, but this is not ideal for secure values like user & password that should persist for no longer than necessary.

**Comment by t1m0thyj** [comment]
#1244 should improve the behavior for ZOWE_OPT environment variables in daemon mode, but some other environment variables like ZOWE_CLI_HOME and ZOWE_APP_LOG_LEVEL are only read during `Imperative.init` (when daemon server launches), so changing their value for subsequent commands run in daemon mode will have no effect.

**Comment by MikeBauerCA** [comment]
To resolve this issue, we can implement a `zowe daemon reload` command as a suitable workaround. We may need this command for other troubleshooting in the future.
