### ISSUE TITLE
zowe config init - prompt for host

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/zowe-cli#1219]
Currently, `zowe config init` prompts for user & password and subsequently stores them in the secure credential store. The created `zowe.config.json` has a base profile with property `host` listed but empty. We should prompt for `host` on `zowe config init` and store the value here. Note that `zowe config auto-init` stores the host.

**Comment by MikeBauerCA** [comment]
Include option to just leave blank to skip the question and then the host property will be listed but empty in config (just as it is today).

**Comment by t1m0thyj** [comment]
Resolved in #1334
