### ISSUE TITLE
Job spool files cannot be shown with CLI

### ISSUE THREAD

**Issue by roman-kupriyanov** [zowe/zowe-cli#1220]
## Description

Consider this example of a job JCL:
```bash
//SET1 SET PN=EXER3
//&PN JOB
```
This job, being submitted, will fall with JCL ERROR, producing the results:
![image](https://user-images.githubusercontent.com/91762867/143599735-68a18c11-c08b-4add-a710-3c46a8e98961.png)

And the list of spool files:
![image](https://user-images.githubusercontent.com/91762867/143599854-a67dcf62-648f-49b1-bd81-e2742decfb57.png)

Now to see the list of spool files for that jobID using `Zowe/CLI`, a command is issued:
```bash
❯ zowe zos-jobs ls sfbj job06330 --rft string
[{},{}]
```

And it results in returning of just the empty objects list. The number of empty objects depends on how many jobs records present in the current search request. For example, if more jobs will be run, a count of objects is increased:
```bash
❯ zowe zos-jobs ls sfbj job06330 --rft string
[{},{},{},{},{}]
```

Some investigation revealed that the unusual jobname that appears due to a syntax error, breaks a URL for z/OSMF request, turning the expected **Get Spool Files by JobID** request URL:
```bash
/zosmf/restjobs/jobs/?PN/JOB06330/files
```
Into something like this:
```bash
/zosmf/restjobs/jobs/?PN%2FJOB00239%2Ffiles
```
Which, basically, the same as **Get Job List** request if you omit an insignificant URL query part:
```bash
/zosmf/restjobs/jobs/
```

In sum, the command shows the list of jobs (assuming that all object fields are filtered out from response), instead of the expected spool files.

An attempt of escaping the question mark in URL with HTML encoding `? -> %3F` seems to lead to just an error:
```bash
GET /zosmf/restjobs/jobs/%3FPN/JOB00239/files

400 Bad Request
{
  "rc": 4,
  "reason": 7,
  "category": 6,
  "message": "No match for method GET and pathInfo='\/?PN\/JOB00239\/files'"
}
```

## Expected result

There should be a way to show the spool files for the jobs with unusual names via `Zowe/CLI`, as well as using `Zowe API`. This may be helpful for the users to investigate the problem with their JCL, otherwise the only solution is to go back to ISPF to see the spool files and to determine the reason of failure.

_As one of the suggestions:_ z/OSMF provides an alternative way of specifying a **Job correlator** value in the request URL instead of the `jobname/jobid` pair, which was proven to be working perfectly for such breaking jobnames as well. For example, a `job-correlator` value for jobID `JOB06630` is `J0006330SVSCJES2DAAC28A2.......:` and it can be used in the request URL:
```bash
GET /zosmf/restjobs/jobs/J0006330SVSCJES2DAAC28A2.......%3A/files

200 OK
[
  {
    "recfm": "UA",
    "records-url": "https:\/\/zowe:443\/zosmf\/restjobs\/jobs\/J0006330SVSCJES2DAAC28A2.......%3A\/files\/2\/records",
    "stepname": "JES2",
    "subsystem": "JES2",
    "job-correlator": "J0006330SVSCJES2DAAC28A2.......:",
    "byte-count": 316,
    "lrecl": 133,
    "jobid": "JOB06330",
    "ddname": "JESMSGLG",
    "id": 2,
    "record-count": 11,
    "class": "A",
    "jobname": "?PN",
    "procstep": null
  },
  {
    "recfm": "V",
    "records-url": "https:\/\/zowe:443\/zosmf\/restjobs\/jobs\/J0006330SVSCJES2DAAC28A2.......%3A\/files\/3\/records",
    "stepname": "JES2",
    "subsystem": "JES2",
    "job-correlator": "J0006330SVSCJES2DAAC28A2.......:",
    "byte-count": 110,
    "lrecl": 136,
    "jobid": "JOB06330",
    "ddname": "JESJCL",
    "id": 3,
    "record-count": 1,
    "class": "A",
    "jobname": "?PN",
    "procstep": null
  },
  {
    "recfm": "VA",
    "records-url": "https:\/\/zowe:443\/zosmf\/restjobs\/jobs\/J0006330SVSCJES2DAAC28A2.......%3A\/files\/4\/records",
    "stepname": "JES2",
    "subsystem": "JES2",
    "job-correlator": "J0006330SVSCJES2DAAC28A2.......:",
    "byte-count": 130,
    "lrecl": 137,
    "jobid": "JOB06330",
    "ddname": "JESYSMSG",
    "id": 4,
    "record-count": 3,
    "class": "A",
    "jobname": "?PN",
    "procstep": null
  }
]
```
But neither `Zowe/CLI` itself, nor Zowe API do not allow to use this value to request the spool lists or any other functions at the moment. A "ready to use" links are already contained in the fields like `files-url` or `records-url` from **Get Jobs List** or **Get Spool Files** responses respectively, which might be also used somehow internally to fix the problem without asking the user to operate with **Job correlator** values explicitly.

## Related issues

- https://github.com/zowe/vscode-extension-for-zowe/issues/845

**Comment by awharn** [comment]
This issue has been resolved as part of the URI encoding work completed in #1663.
