### ISSUE TITLE
bright jobs submit ds/lf --vasc

### ISSUE THREAD

**Issue by solsu01** [zowe/zowe-cli#124]
The help for bright jobs submit ds/lf --vasc says:
--view-all-spool-content  | --vasc (boolean)

      View all spool content for specified job ID

This does not let me know that the command is going to WAIT until the job finishes to show me all the output. I would recommend updating the help text to clearly state the behavior of this command.

**Comment by IgorCATech** [comment]
Acknowledged! Let me speak with the team and I'll work on the help text

**Comment by MikeBauerCA** [comment]
This has since been resolved with `Print all spool output. If you use this option you will wait for the job to complete.`
