### ISSUE TITLE
ZOWE_CLI_HOME not used in daemon mode

### ISSUE THREAD

**Issue by EmlynWill** [zowe/zowe-cli#1240]
When running zowe commands with the zowe.exe daemon running it does not use ZOWE_CLI_HOME to find the config files.
Running without the daemon uses ZOWE_CLI_HOME.

**Comment by t1m0thyj** [comment]
This may be related to https://github.com/zowe/zowe-cli/issues/1215

**Comment by EmlynWill** [comment]
Maybe, but ZOWE_CLI_HOME was already set a while back
