### ISSUE TITLE
ZOWE_CLI_HOME not used for global team config

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/zowe-cli#1245]
Reported by @EmlynWill:
> My colleague has also installed @next and does not have ZOWE_CLI_HOME set. When they issue a zowe config set command it creates the config file in their current directory not the .zowe directory as I would expect.

**Comment by EmlynWill** [comment]
I think that she did not have the zowe.exe daemon, so this is non daemon mode.

**Comment by MikeBauerCA** [comment]
@EmlynWill they would need to specify the `--global-config` (or `--gc` for short) flag on the command for it to use the global config in the `.zowe` directory.

**Comment by EmlynWill** [comment]
@MikeBauerCA I didn't expect the current working directory to be used for the user config every time the user issues a config command. So the users could have many user configs depending on the directory that they were in at the time that they ran the config command?

**Comment by EmlynWill** [comment]
@MikeBauerCA This is about the location of the config files rather than which of the user or global config files to use.
I think that the config file should always go to ZOWE_CLI_HOME by default. If a user wanted to create a config file in their current directory then that would be achieved with a zowe config set option.
I don't think that the command should fail.

**Comment by MikeBauerCA** [comment]
@EmlynWill I think project-level will remain the default. Other technologies in this space behave in a similar way in that you need to specify a flag to store something globally (in the ZOWE_CLI_HOME folder) instead of in the project (current working directory). Perhaps we could add documentation somewhere to provide more awareness.

**Comment by EmlynWill** [comment]
@MikeBauerCA How would I store my user config settings in the global folder? Or is that not possible?

**Comment by MikeBauerCA** [comment]
@EmlynWill you would just use both the `--user-config` and `--global-config` flags on the command. For example, `zowe config init --user-config --global-config` will place a template `zowe.config.user.json` in your ZOWE_CLI_HOME folder. You can also append these flags to the set command.

**Comment by EmlynWill** [comment]
@MikeBauerCA Ok I can do that but it seems a little confusing to me. 
According to the docs --global-config means "Set the property in global config." ; rather than "set the config value in the zowe home directory"

**Comment by EmlynWill** [comment]
@MikeBauerCA I think that an update to the docs would clarify it, thank you

**Comment by MikeBauerCA** [comment]
@zFernand0 I see this may be potentially closed if it does not receive some upvotes. I think it would be great to include the documentation improvement suggested above for at least these two reasons:
 - The only behavior in Zowe V1 was to store everything in the `.zowe` folder and have it apply everywhere. Now, with Zowe V2, to get a similar experience you need to include the `--global-config` option.
 - Project-based config is a new capability provided as part of team profiles. It's value is briefly highlighted in this document: https://docs.zowe.org/stable/user-guide/cli-using-team-configuration-team-leaders. However, it would be good to highlight it in the "Using team profiles" section.

**Comment by zFernand0** [comment]
Thanks Mike! 😋 
Yeah, we considered that having such documentation updates will be beneficial since people may be running into this.
I'll work with Ana on this 😺

**Comment by zFernand0** [comment]
I believe this was addressed in:
- https://github.com/zowe/docs-site/pull/3634
Thanks @anaxceron and @adam-wolfe
