### ISSUE TITLE
Download of a mainframe file with blank lines comes to PC with blank lines stripped

### ISSUE THREAD

**Issue by kpulver** [zowe/zowe-cli#125]
Supporting documentation sent to Chris Wright 11/28/18. I can resend if necessary.

**Comment by AHumanFromCA** [comment]
Basically if you have this on the mainframe:

```
Hello

World
```

It is downloaded as:

```
Hello
World
```

**Comment by dkelosky** [comment]
What is the DCB info for the data set where this problem happens?  Are there any special hex characters in the mainframe data set member?

**Comment by KevinLoesch1** [comment]
I'm unable to recreate this issue. Closing due to lack of follow up information.
