### ISSUE TITLE
Unable to update profiles with Secure Credential Manager under Redhat8

### ISSUE THREAD

**Issue by YvesMichon** [zowe/zowe-cli#1260]
hi,

Under Redhat8, I've installed Zowe CLI with Secure Credential Plugin. 
I used this page for configuring the keyring : https://github.com/zowe/zowe-cli-scs-plugin/blob/master/README.md#software-requirements

but when i use this command
`zowe scs update`
I got this message : 
`** Message: 10:49:47.675: Remote error from secret service: org.freedesktop.Secret.Error.IsLocked: Cannot create an item in a locked collection
Error:
Unable to store the secure field "user" associated with the profile "zowe-zosmf-profile" of type "zosmf".
`
I'll try to open manually the keyring by retyping this command : 
`export $(dbus-launch)`
`gnome-keyring-daemon --unlock --components=secrets`
but i always have the same message

Node Version :
`v16.13.1`

Zowe version :
`6.37.0`

**Comment by awharn** [comment]
Hello,

When you were configuring the keyring, did you follow the procedure for manually unlocking the keyring, automatically unlocking the keyring on login, or both?

**Comment by YvesMichon** [comment]
both.
I've modified the .bashrc file and I've tried to unlock manullay

**Comment by YvesMichon** [comment]
With the command `gnome-keyring-daemon --unlock --components=secrets`, I had no prompt. It juste wait something.
I enter my password, I hit Enter key and next I hit CTRL+D and the the prompt comes back.
Is that the right sequence or does I need to hit CTRL+D before the enter key ?

**Comment by awharn** [comment]
I believe you need to type in your password, and press CTRL+D before pressing enter. From past experience, the daemon treats the enter key as part of the password, as CTRL+D signifies an end of file.

**Comment by YvesMichon** [comment]
I retry the `gnome-keyring-daemon --unlock --components=secrets` command.
When it waits, i type my password and CTRL+D. But nothing happens. I type CTLR+D another time to exit and return to prompt.
But always the same error message when i type `zowe scs update`

**Comment by YvesMichon** [comment]
I've finally succeeded to use the command `zowe scs update` by using before `gnome-keyring-daemon --unlock --components=secrets <<< password`.
The Zowe commands works. But after logoff/login, the keyring is locked again.
I have updated the `/etc/pam.d/login` and `/etc/pam.d/sshd` and `~/.bashrc` files as indicated for the automatic unlock but it not works

**Comment by YvesMichon** [comment]
Solution found :

- Delete the ~/.local/share/keyrings/login.keyring and user.keystore after configuring gnome-keyring (.bashrc, sshd and login files).
- Exit the session.
- Login again.
- The login.keyring file is automatically created after login and automatically unlocked.
No need to unlock it manually
