### ISSUE TITLE
Jenkins check wrongly fails on missing changes in irrelevant changelogs

### ISSUE THREAD

**Issue by namanpatel1112** [zowe/zowe-cli#1265]
When automated tests run on a new PR in zowe-cli repo, Jenkins check wrongly fails with 'missing header' errors in changelog files in packages that haven't been modified. It seems like a bug and needs to be investigated.
Example of this occurring is in this PR: https://github.com/zowe/zowe-cli/pull/1258/

**Comment by MarkAckert** [comment]
Closing this issue, as we are migrating all of our Jenkins automation to Github actions. Thank you.
