### ISSUE TITLE
CLI Documentation Links to zowe.org 

### ISSUE THREAD

**Issue by dkelosky** [zowe/zowe-cli#1267]
The documentation link found [in this section](https://github.com/zowe/zowe-cli#documentation) of the README leads to `https://docs.zowe.org/ instead of the CLI specific documentation.  Perhaps this should direct users to here https://docs.zowe.org/stable/getting-started/cli-getting-started  ?

**Comment by JamesBauman** [comment]
This issue is resolved. the aforementioned link now refers the reader to CLI quick start.  

Closing the issue.  @MikeBauerCA, if my decision is incorrect. please let me know and i will re-open the issue.

My gut tells me it's resolved.
