### ISSUE TITLE
Daemon-disable does not kill background daemon process on Linux & Mac

### ISSUE THREAD

**Issue by gejohnston** [zowe/zowe-cli#1270]
The daemon disable command removes the zowe executable from the .zowe/bin directory, and is supposed to also kill the background daemon process: node ...../zowe (our script) --daemon

The background process is not killed on Linux and Mac. It is killed on Windows.

This is not particularly harmful, but it is incorrect.

**Comment by awharn** [comment]
I think I found the culprit(s).

On my dev machine, I have an alias pointed at the main.js built from GitHub. If the daemon is launched from there, here is my output from find-process:

```
{
      pid: 1549857,
      ppid: 1369504,
      uid: 1000,
      gid: 1000,
      name: 'node',
      bin: 'node',
      cmd: 'node /home/awharn/GitHub/zowe-cli-next/packages/cli/lib/main.js --daemon'
    }
```

This may not be relevant to this issue in particular, but it would be nice if it worked in this kind of environment. However, when installing globally from NPM, if you run the daemon, you get this output from find-process:

```
{
      pid: 1255,
      ppid: 345,
      uid: 1000,
      gid: 1000,
      name: 'node',
      bin: 'node',
      cmd: 'node /home/jenkins/.nvm/versions/node/v16.13.2/bin/zowe --daemon'
    }
```

The regex [here](https://github.com/zowe/zowe-cli/blob/8f19e12f929c58e07f6c6887054efb07e62bcd41/packages/cli/src/daemon/disable/Disable.handler.ts#L112) does not match. Granted I am using NVM, but either way, it points to the file in the NPM bin directory, not the CLI node module's lib directory.
