### ISSUE TITLE
[FEATURE REQUEST] CLI command to start a 3270 accessible on e.g. localhost

### ISSUE THREAD

**Issue by kraabrsg** [zowe/zowe-cli#1273]
Hi, like stated here too:
https://app.slack.com/client/T1BAJVCTY/CC8AALGN6/thread/CUVE37Z5F-1641995266.005400?selected_team_id=T1BAJVCTY

i wanted to use a 3270 in a webbrowser (and with that in VSCODIUM too)
i use this docker image: https://github.com/MVS-sysgen/web3270 

![grafik](https://user-images.githubusercontent.com/86772851/149516010-0bd0fa0a-69af-466a-91db-925278fff449.png)

My feature request would be a cli command to start a webserver like this, (without e.g. having to use docker)

Thank you!

**Comment by MarkAckert** [comment]
The intended functionality for the core Zowe CLI at this time is to focus on interacting with existing mainframe services and APIs. Building and integrating a local TN3270 emulator host into Zowe CLI is out of scope. We will close this here - if you think this should be a plugin in the community, you can open a new issue in the zowe/community repo.
