### ISSUE TITLE
 Unable to query datasets with `#` in the name

### ISSUE THREAD

**Issue by zFernand0** [zowe/zowe-cli#1281]
Any updates on this? Or ideas on how to fix it? I'm still having the issue, both with the VSCode extension and the Zowe CLI.
> `@zowe/cli 6.37.3`
> Zowe Explorer v1.21.0

_Originally posted by @macjabeth in https://github.com/zowe/vscode-extension-for-zowe/issues/1511#issuecomment-1018669604_

**Comment by t1m0thyj** [comment]
@zFernand0 Is this related to https://github.com/zowe/zowe-cli/issues/1073?

**Comment by zFernand0** [comment]
> Is this related to #1073?

I believe it is 😋 
Closing!
