### ISSUE TITLE
Zowe V1 to V2 Plug-in Profile Migration

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/zowe-cli#1288]
We have the following new V2 Conformance Standards:
 - If the plug-in uses a Zowe API-ML integrated API, it (the plug-in) has an option named `base-path` in the profile to be used to house the path of the associated service in the API ML.
 - If the plug-in connects to a service, it must include the following profile properties AND they MUST be these exact properties (e.g. host, NOT hostname): `host`, `port`, `user`, `password`
 - If the plug-in connects to a service, and the service supports logging in with a token, it must include the following profile properties AND they MUST be these exact properties: `tokenType`, `tokenValue`
 - If the plug-in connects to a service, and the service supports logging in with PEM certificates, it must include the following profile properties AND they MUST be these exact properties: `certFile`, `certKeyFile`
 - If the plug-in connects to a service, and the service supports logging in with PFX/P12 certificates, it must include the following profile properties AND they MUST be these exact properties: `certFile`, `certFilePassphrase`
 - If the plug-in provides an option to reject untrusted certificates, the property must be named `rejectUnauthorized`. CLI option should be `reject-unauthorized`.
 
 We are aware of plug-ins impacted by the `host`, `user`, and `tokenValue` naming standards. It has been requested for us to provide the migration as we are updating conformance requirements. Therefore, we need to make the following migrations in these profiles when our `zowe config convert-profiles` command is run:
 `hostname` -> `host`
 `username` -> `user`
 `token` -> `tokenValue`

**Comment by t1m0thyj** [comment]
@gejohnston Was this resolved in zowe/imperative#736?

**Comment by gejohnston** [comment]
After further analysis, we determined that changing token to tokenValue would not be beneficial to consumers. The current use of token was not the same as our APIML tokenValue. The resulting conversions are:

<html>
<body>


Old V1 profile property name | New V2 profile property name
-- | --
hostname | host
username | user
pass | password


</body>
</html>

I overlooked closing this issue when merging https://github.com/zowe/imperative/pull/736. Therefore I am closing this issue.
