### ISSUE TITLE
Wrong description of "zowe config init" in global profile configuration docs

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/zowe-cli#1297]
According to [the early access docs for global profile configuration](https://github.com/zowe/zowe-cli/blob/next/docs/Early%20Access%20-%20Using%20Global%20Profile%20Configuration.md#optional-initializing-user-specific-configuration):

> Issue the command `zowe config init --global-config --user-config` to generate both global (`zowe.config.json`) and user (`zowe.config.user.json`) config files.

The `zowe config init` command does not create multiple config files at once. We should document separate commands instead:
* `zowe config init --global-config` or `zowe config init --gc` to create the global zowe.config.json
* `zowe config init --global-config --user-config` or `zowe config init --gc --uc` to create the global zowe.config.user.json

Thanks to @davidkjackson54 for reporting this 🙂

**Comment by RishiKumarRay** [comment]
can i raise the PR for this?

**Comment by RishiKumarRay** [comment]
@t1m0thyj please review

**Comment by JamesBauman** [comment]
live article updated:

https://docs.zowe.org/stable/user-guide/cli-using-global-profile-configuration/
