### ISSUE TITLE
Hover over zowe V2 profile in VSCode is incorrect

### ISSUE THREAD

**Issue by davidkjackson54** [zowe/zowe-cli#1303]
This example snippet of a V2 profile viewed in VSCode.

```
 "$schema": "./zowe.schema.json",
    "profiles": {
        "d001": {
            "properties": {
                "host": "d001.myurl.com"
            },
            "secure": [
                "user",
                "password"
            ],
```

If  i hover over "properties", this is displayed.

```
z/OSMF Profile
the profile properties
```
also, if  i hover over "host" this is presented:
`The z/OSMF server host name.
`
This is incorrect  as this has nothing to do with z/OSMF

**Comment by t1m0thyj** [comment]
Fixed this schema issue in zowe/imperative#751 and `@zowe/cli@7.0.0-next.202203231654`
