### ISSUE TITLE
profiles create offers no option to "accept unauthorized"

### ISSUE THREAD

**Issue by pjfarleyiii** [zowe/zowe-cli#1321]
zowe-cli offers no option to set up a new profile with "rejectUnauthorized: false".  The option --reject-unauthorized (which is also a default) in effect sets "rejectUnauthorized: true" which causes failures on systems like the IBM zXplore system which uses self-signed certificates.

There should be another option on ```profiles create``` like ```--accept-unauthorized``` which would set "rejectUnauthorized: false" in the profile.yaml file.

**Comment by t1m0thyj** [comment]
You can specify `--reject-unauthorized false` (or `--no-ru` for short) on the `profiles create` command:
```
zowe profiles create zosmf test --host example.com --port 443 --user abc --password def --reject-unauthorized false
Profile created successfully! Path:
C:\Users\User\.zowe\profiles\zosmf\test.yaml

host:               example.com
port:               443
user:               managed by @zowe/secure-credential-store-for-zowe-cli
password:           managed by @zowe/secure-credential-store-for-zowe-cli
rejectUnauthorized: false
protocol:           https

Review the created profile and edit if necessary using the profile update command.
```

**Comment by t1m0thyj** [comment]
@pjfarleyiii Did the suggested command resolve your issue?
