### ISSUE TITLE
Document and Test future scripts/procedures for lts incremental & stable

### ISSUE THREAD

**Issue by JTonda** [zowe/zowe-cli#137]
Child of #135
Estimate 3

Acceptance Criteria:
A document was produced which can be followed to implement the fully automated version of the Versioning Scheme proposed in #77

- [x] Write outline based on the revised versioning scheme
Status: Completed
Assigned: @AHumanFromCA @zFernand0 

- [x] Prepare the first official draft of said document
Status: Completed
Assigned: @zFernand0 

- [x] Review draft
Status: Completed
Assigned: @JamesBauman 

- [x] Review per Fernando's comment below
Status: Completed
Assigned: @PeteSwauger  

- [x] Address comments/questions
Status: Completed
Assigned: @zFernand0

**Comment by zFernand0** [comment]
Feel free to review the following documents:
- [Manual process](https://github.com/zowe/zowe-cli-version-controller/blob/master/docs/ManualProcess.md)
  - This should satisfy the acceptance criteria
- [Protected branches](https://github.com/zowe/zowe-cli-version-controller/blob/master/docs/JenkinsPipeline.md#protected-branches)
  - This helps understand the branches and how tags will be migrating in the automated pipelines
  - Some details may change in the future depending on how issue #139 plays out
