### ISSUE TITLE
ZOWE CLI 2.0.0 seems to have issues with windows paths i.e backslashes or double backslashes

### ISSUE THREAD

**Issue by cybersorcerer** [zowe/zowe-cli#1392]
When i use ssh from my windows desktop to issue a command inside z/unix like this:
`ssh xv880aj@mvsb.ruv.de -i C:\<path>\<private-key-filename> ls -la`

or

`ssh xv880aj@mvsb.ruv.de -i C:\\<path>\\<private-key-filename> ls -la`

i get what i expect:

![image](https://user-images.githubusercontent.com/33680802/165894304-2fbd64e6-90c3-4969-96e9-e6062391c36e.png)

Note: The key does not have a passphrase.

when i use zowe cli 2.0.0 no matter in which format i specify the private key file name, i get prompted to enter my password:

`zowe zos-ssh issue command 'ls -la' --cwd 'my-work-dir' --user myuser --host myhost --port 22 --pk C:\<path>\<private-key-filename>` 
or
`zowe zos-ssh issue command 'ls -la' --cwd 'my-work-dir' --user myuser --host myhost --port 22 --pk C:\\<path>\\<private-key-filename>`

The same happens when i use the defined zowe ssh profile with the --ssh-p option. I tried to specify the private key filename with single and double backslashes, i even tried the Unix notation using forward slashes, nothing seems to work. The exact same command did work forever with the previous zowe cli version. 

This breaks our CI/CD workflows and should be fixed asap or tell me how i can circumvent the issue

regards

Ronny

**Comment by awharn** [comment]
Hello @cybersorcerer, we've pushed a new version of the CLI up to NPM (v7.1.2) that should fix this issue. Can you please give it a try and let us know if the problem persists?

**Comment by cybersorcerer** [comment]
Hello @awharn, i installed the updated version with `npm install -g @zowe/cli@7.1.2`. I tested zowe zos-ssh issue command with the --pk option, as well as with  --ssh-p. Both commands worked as expected. So this is fixed (IMHO) :-)

Thanks a lot for the quick solution

regards
Ronny
