### ISSUE TITLE
ssh-profile - Problem using a private key without providing a normally useless password

### ISSUE THREAD

**Issue by FALLAI-Denis** [zowe/zowe-cli#1398]
Hi,

I'm trying to implement ssh profiles, on a Windows workstation, and using a private key instead of the password.

The Windows built-in OpenSSH component is used.

```
>zowe --version
6.38.0

>ssh -V
OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2
```

The ssh private key is created and works well with OpenSSH outside of Zowe CLI.

The Zowe ssh profile is declared as follows:
```
host:       GMVS
port:       22
user:       J070188
privateKey: C:\Users\S0070188\.ssh\id_rsa
```

When I want to use this Zowe ssh profile, the password is systematically requested (but not the user):
```
>zowe ssh issue command "pwd"
Enter password : ********

$ pwd
/u/J070188
$ exit $?
```

The same test with OpenSSH does not ask for the password:
```
>ssh J070188@GMVS pwd
/u/J070188
```

If I specify a wrong path for the private key:
```
host:       GMVS
port:       22
user:       J070188
privateKey: C:\a_bad_path
```

We see that the zowe command asks for the password even before trying to access the private key:
```
>zowe ssh issue command "pwd"
Enter password : ********
Unexpected Command Error:
Please review the message and stack below.
Contact the creator of handler:
"C:\ProgramData\nvm\v12.13.0\node_modules\@zowe\cli\lib\zosuss\issue\ssh/Ssh.handler"
Message:
ENOENT: no such file or directory, open 'C:\a_bad_path'
Stack:
Error: ENOENT: no such file or directory, open 'C:\a_bad_path'
    at Object.openSync (fs.js:440:3)
    at Object.readFileSync (fs.js:342:35)
    at C:\ProgramData\nvm\v12.13.0\node_modules\@zowe\cli\node_modules\@zowe\zos-uss-for-zowe-sdk\lib\Shell.js:108:35
    at new Promise (<anonymous>)
    at Function.executeSsh (C:\ProgramData\nvm\v12.13.0\node_modules\@zowe\cli\node_modules\@zowe\zos-uss-for-zowe-sdk\lib\Shell.js:33:25)
    at Handler.<anonymous> (C:\ProgramData\nvm\v12.13.0\node_modules\@zowe\cli\lib\zosuss\issue\ssh\Ssh.handler.js:38:57)
    at Generator.next (<anonymous>)
    at C:\ProgramData\nvm\v12.13.0\node_modules\@zowe\cli\lib\zosuss\issue\ssh\Ssh.handler.js:18:71
    at new Promise (<anonymous>)
    at __awaiter (C:\ProgramData\nvm\v12.13.0\node_modules\@zowe\cli\lib\zosuss\issue\ssh\Ssh.handler.js:14:12)
```

If I save an invalid password in the profile:
```
host:       GMVS
port:       22
user:       J070188
privateKey: C:\Users\S0070188\.ssh\id_rsa
password:   managed by @zowe/secure-credential-store-for-zowe-cli
```
Note: the password is encrypted by SCS, but not the user?

It works ! While the password is invalid!
```
>zowe ssh issue command "pwd"

@@START OF COMMAND@@
$ pwd
/u/J070188
$ exit $?
```

When using a private key, one should not be required to provide a password as well, especially since it does not seem to be controlled in the presence of a private key, but mandatory so that the private key be used...

**Comment by FALLAI-Denis** [comment]
Tested : OK with 7.1.2 (but downable package on Zowe.org is version 7.0.2).

**Comment by t1m0thyj** [comment]
Thanks for testing 🙂 The downloadable package on Zowe.org is updated periodically (see the schedule [here](https://github.com/zowe/community/blob/master/Project%20Management/Schedule/Zowe%20PI%20%26%20Sprint%20Cadence.md#releases)). If you want to consume the latest fixes and enhancements, installing from NPM is the best way to do so.
