### ISSUE TITLE
Zowe CLI V2 - YAML format support for Zowe config files

### ISSUE THREAD

**Issue by FALLAI-Denis** [zowe/zowe-cli#1408]
Zowe V2 configuration files containing profiles are now managed in Json format.
It has become mandatory to directly edit these files to manage the profiles...
The YAML format, as was the case with Zowe V1, would be more appropriate because it is easier to handle.

**Comment by adam-wolfe** [comment]
We do not plan to change the configuration file format for the foreseeable future. We may consider ways for users to modify their config without directly editing the json.
