### ISSUE TITLE
Use of symbols in dataset name or files

### ISSUE THREAD

**Issue by FALLAI-Denis** [zowe/zowe-cli#1423]
Hi,

I wanted to test the use of symbols in a dataset name for action in the zos-files group, for example the &SYSUID symbol. 

The dataset name is passed as is to z/osmf, without replacing the symbol with its value. 
Z/osmf triggers an error because it also does not resolve the symbol. (On this occasion I discovered that z/osmf was using BPXWDYN which itself uses the SVC 99).

A priori the z/osmf server is not able to resolve variables, especially if they are related to the user's context. 

It would therefore be necessary for the Zowe CLI client to resolve the symbols present in the dataset names before calling z/osmf. 
Unless the user started task on behalf can take care of it, (but this then requires an evolution at the z/osmf level).

This also applies to USS files and may be other informations.

**Comment by gejohnston** [comment]
As a client-side app, it is not clear to me how the CLI can readily know the z/OS symbols before submitting the request to z/OSMF. If z/OSMF itself does not support symbol substitution, this could be a significant enhancement request. If such a feature could be implemented, it would likely require the zos-files commands to make multiple REST requests. It is not clear what impact that would have on performance.

These are just considerations that would go into the evaluation of this enhancement request.

**Comment by FALLAI-Denis** [comment]
I create an IDEA, reference ZOS-I-3326, for this issue: 

[z/OSMF - Support for symbols in query processing for MVS datasets and USS files](https://ibm-z-hardware-and-operating-systems.ideas.ibm.com/ideas/ZOS-I-3326)

**Comment by FALLAI-Denis** [comment]
Oups... that works ! But only for system symbols (visibles in SYM menu of SDSF)...

![image](https://user-images.githubusercontent.com/63861965/169565678-bc1e7836-c000-43de-b168-13ac8bc0be30.png)

```
$ zowe zos-files download data-set "&JOBNAME..TEMP.TEST" --ec 1147 -f TEST.txt
Data set downloaded successfully.
Destination: TEST.txt
```
![image](https://user-images.githubusercontent.com/63861965/169565606-4349fa4b-5ac3-4132-9143-718b3c462c18.png)

**Comment by FALLAI-Denis** [comment]
Issue relates to z/osmf.
