### ISSUE TITLE
Profile creation failed

### ISSUE THREAD

**Issue by plavjanik** [zowe/zowe-cli#1437]
**Describe the bug**

I am creating a new profile and I have entered the name `ca32 (z/OSMF)` to differentiate between FTP and z/OSMF. The extension accepted the name as valid initially but it failed to create the profile.

**To Reproduce**

1. Create new connection to z/OS for data sets
2. Use `ca32 (z/OSMF)` or similar as the name and enter other values
3. It fails to create profile with this error:

```
Profile IO Error: Error creating profile file ("C:\Users\pp669351\.zowe\profiles\zosmf\ca32 (z\OSMF).yaml"). Error Details: ENOENT: no such file or directory, open 'C:\Users\pp669351\.zowe\profiles\zosmf\ca32 (z\OSMF).yaml'
 ```

**Expected behavior**

A profile is successfully created or the name is not accepted immediately after entering so a valid name can be entered.

**Screenshots**

<img width="347" alt="image" src="https://user-images.githubusercontent.com/7644758/172384140-3ca44228-5f55-4d7f-80bc-7c6df475a423.png">

**Desktop (please complete the following information):**

- OS: Windows 10
- Zowe Explorer Version: v2.0.3
- (Optional) Zowe CLI Version: 
- (Optional) Are you using Secure Credential Store?

**Comment by zFernand0** [comment]
This is an enhancement request for V1 profiles and the Zowe V1 release is in maintenance mode.
Closing since Team configuration files do support most special characters as long as it's a valid JSON object.
For instance, this is a valid profile name on V2 `"name__!@#$%^&*()_-+=<>/?\\|{}\"__"`

**Comment by plavjanik** [comment]
It is ok not to support some characters. The typical response of software is to explain this in an error message so users know what characters can be entered. Current message does not say what is wrong and how it can be corrected.

**Comment by plavjanik** [comment]
Try to look at it from the perspective of a user. You enter a perfectly valid string - the name of the service that is used by Zowe: 
`z/OSMF` but then the CLI fails with an error that does not make much sense. As a user I would expect either Zowe to explain why my input was invalid so I can do it correctly next time or ideally to allow me to enter it and change it to something that is valid on the current file system automatically. This is an error that is not handled properly and users have to guess what how to do a workaround. And when they find it, it gives a bad impression about the product. The fix for that is easy and a similar approach should be taken in all cases when input is requested from the user. It this case the product just does not work but what if there is a case when it can lead to more severe problems?
