### ISSUE TITLE
Invalid block size is used by `zowe files create data-set-sequential`

### ISSUE THREAD

**Issue by plavjanik** [zowe/zowe-cli#1439]
When I allocate a new dataset without specifying a block size is uses a default that is not a valid size and the allocated dataset is not usable.

```
zowe files create data-set-sequential DSN --recfm VB --lrecl 32756
Data set created successfully.
```

When I use the dataset in a JCL, it fails:
```
11.05.34 JOB98529  IEC141I 013-20,IGG0191A,PLAPECHW,,ZLDATA,8F26,WRKD22,  441
```

The explanation of the code is:
```
    S013-20
        An OPEN macro instruction was issued for a sequential data set using
        queued access. BLKSIZE is not a multiple of LRECL, or LRECL is 0 with
        RECFM=FB or RECFM=FBS, or BLKSIZE is not at least four bytes greater
        than LRECL with RECFM=V.
```

It is allocated as:
<img width="191" alt="image" src="https://user-images.githubusercontent.com/7644758/172581357-81a0cc1c-a9d2-4777-9bd6-3ee875b82503.png">

I would expect to do what ISPF allocates in this case (block size is 32760 which is record length + 4 because it is VB) :
<img width="508" alt="image" src="https://user-images.githubusercontent.com/7644758/172579412-ef903487-59eb-4ce9-aa42-ad9abdc3ee04.png">

**Comment by KevinLoesch1** [comment]
Fixed in the v2.10 release.
