### ISSUE TITLE
Bump Versions (Major/Minor/Patch)

### ISSUE THREAD

**Issue by JTonda** [zowe/zowe-cli#145]
Possible implementations/Acceptance Criteria:
- Auto-bump based on PR description
- Auto-bump based on PR tags for `release-<type>`, where `<type>` is major, minor, or patch
- Document what we're keying on for this automation

Child of #135
Estimate 3

Tasks:
- [x] Research GitHub APIs on label management and status checks
      Status: Completed
      Assignee(s): @PeteSwauger, @zFernand0 

- [x] Create a [`status check`](https://developer.github.com/v3/repos/statuses/) for the label
      Status: In Progress
      Assignee(s): @PeteSwauger, @zFernand0 

  - [x] Create `release-*` labels if needed
         Status: Completed
         Assignee(s): none
    - `release-major`: Indicates a Major/Breaking version (Maybe we should send a warning email)
    - `release-minor`: Indicates a Minor/Feature version
    - `release-patch`: Indicates a Patch/Fix version
    - `no-release`: Indicates no new customer facing code is applied. (for internal purposes)

  - [x] Fail the build if no release label is specified or multiple ones are
         Status: Completee
         Assignee(s): @PeteSwauger  

- [x] Allow release label to do one of the following:
       Status: Not Started
       Assignee(s): none
  - Bypass the manual selection of the desired version to publish
  - Use the `release-*` corresponding version as the default in case of a timeout (and maybe reduce the timeout to like 1 - 5 minutes)

**Comment by zFernand0** [comment]
Fixed by https://github.com/zowe/zowe-cli-version-controller/pull/41
Pipelines will need to adjust in order to consume `v2.x`
