### ISSUE TITLE
Message Zowe Daemon in use

### ISSUE THREAD

**Issue by YvesMichon** [zowe/zowe-cli#1451]
Hi,
We used a server to centralise all Zowe commands for deploying host components. For that, there is juste one technical account which runs all zowe commands.
The Daemon is enabled for the technical account.
When we send multiple zowe commands almost silmutanely we have randomly some lines at start of JSON output but not in JSON format : 
`The Zowe daemon is in use, retrying (1 of 60)
The Zowe daemon is in use, retrying (2 of 60)
The Zowe daemon is in use, retrying (3 of 60)
The Zowe daemon is in use, retrying (4 of 60)
...`
The count can be greater 4. Next after this lines, we have the attended JSON output.
From where comes those lines ?
What causes those lines appears ?

**Comment by GhettoKiwi** [comment]
Now, I am not an expert in the use of the daemon, but I might have an idea about why you might experience this output.
First of all, pretty much all communication and output is gonna be written within the console - I assume your JSON-output is based on an execution on your server/mainframe, where the response from that execution is formatted to JSON - The program/procedure you are executing is formatting the response.

The extra lines you are experiencing "The Zowe daemon is in use ...".
As I understood it the daemon can execute one thing at a time (I might be wrong) - Depending on how long it takes to execute the command, the daemon will be "hold" by that command and freed up, whenever it has finished executing its current task - Concurrency control - The daemon is then configured to notify the user about this (Help to identify bottlenecks etc.) by writing a message in the console - Just like you write your JSON output in the console.

If you have only one "executer"(one account with only one daemon) and want to run several commands simultaneously, you are probably going to cause a bottleneck. If the commands you are trying to execute simultaneously are NOT depending on the output of eachother.
  - You should probably consider executing them one by one. 
  - You could also consider doing some string manipulation to remove the extra "The Zowe daemon is in use...." from your 
     JSON-output.
  - You could also consider looking into the possibility of configuring threads on the daemon/technical account (If it is possible)
  
 Once again - I am not an expert, I did not develop it and people are more than welcome to correct me if I am wrong :)

**Comment by YvesMichon** [comment]
I've already made string maniuplations to having a correct JSON Output in my scripts but now I don't know if it's possible to have multiple daemon for one account or if it's possible to have a circumvention for removing this posssible bottleneck.

**Comment by JTonda** [comment]
If the CI environment variable is set, do not output routine messages and move the output to stderr.

**Comment by gejohnston** [comment]
Modified the app to send daemon messages to standard error as part of the following pull request.

Display daemon messages on standard error #2150

The team chose not to implement any detection of the CI environment variable.
