### ISSUE TITLE
ZosFilesBaseHandler shows a ts error (`async` on `abstract` method)

### ISSUE THREAD

**Issue by zFernand0** [zowe/zowe-cli#1456]
Error:
![image](https://user-images.githubusercontent.com/37381190/175038315-13c87c0e-5d2a-47e2-9910-3b76e628c4d5.png)

Code:
https://github.com/zowe/zowe-cli/blob/215b74c4c9309aff9e554715a2ee79d7cb7ed2ff/packages/cli/src/zosfiles/ZosFilesBase.handler.ts#L87

Originally reported by @sarthakjdev

**Comment by sarthakjdev** [comment]
Hey 
This bug has been resolved as in the current version, so I think if nomore changes are required, we can close this issue. 
Have a look [here](https://github.com/zowe/zowe-cli/blob/e01eaf5bde1b0f44d3b80fc7dbfabd5d7e865ce9/packages/cli/src/zosfiles/ZosFilesBase.handler.ts#L87). 

Thanks!
