### ISSUE TITLE
zos-files download dataset: no CRLF for every line, only LF (0A) for some lines

### ISSUE THREAD

**Issue by markklerks** [zowe/zowe-cli#1458]
Using Zowe command: **zowe zos-files download data-set "NL09412C.BTC00.E4012.SCHEMA" -f testimport.txt**
leads to a file ("testimport.txt") where not all lines contain a CRLF (in hex: 0D0A), at least 1 line just has a LF.

Downloading it via the APIML or Zowe Explorer in VS Code, does not show this behavior.

dataset attributes:
dsname: NL09412C.BTC00.E4012.SCHEMA
blksz: 27920
catnm: SYSZ.NLBTCT00
cdate: 2021/03/31
dev: 3390
dsorg: PS
edate: ***None***
extx: 4
lrecl: 80
migr: NO
mvol: N
ovf: NO
rdate: 2022/06/24
recfm: FB
sizex: 393
spacu: TRACKS
used: 100
vol: PJC001
vols: PJC001

**Comment by t1m0thyj** [comment]
@markklerks Thank you for reporting this, I've been able to reproduce the issue on Windows where occasionally `LF` does not get replaced with `CRLF`. We are continuing to investigate this and will let you know when there is a fix available.

**Comment by VitGottwald** [comment]
Thank you @t1m0thyj! This was released to npm as part of [7.3.1](https://www.npmjs.com/package/@zowe/cli/v/7.3.1). Running `npm -g upgrade @zowe/cli` should upgrade to the latest version [7.4.0](https://www.npmjs.com/package/@zowe/cli/v/7.4.0) as of this morning.

I tested the fix and I no longer see broken CRLF.

**Comment by markklerks** [comment]
thanks @t1m0thyj , looks perfect 👍 
let's close this one

**Comment by markklerks** [comment]
👍
