### ISSUE TITLE
Feature request - Defaults X-IBM-Job-Modify-Version to 2.0

### ISSUE THREAD

**Issue by tanto259** [zowe/zowe-cli#1459]
**Problem faced**

From what I can see, #1134 set the default value of the `X-IBM-Job-Modify-Version` to 1.0, making calls asynchronous.

However, this can create complication with systems that does not have CIM enabled. Furthermore, the use of `X-IBM-Job-Modify-Version` with a value of 2.0 seems to be the default value starting from z/OS 2.4 (see #1161 and zowe/jobs#34).

**Solution requested**

Therefore, I am proposing that `X-IBM-Job-Modify-Version` be set to a default value of 2.0.

**Alternative solution**

An alternative solution will be to omit sending `X-IBM-Job-Modify-Version` altogether, unless explicitly supplied through the `--modify-version` argument, and let the system decide what to do.

**Additional details**

While the documentation page for the [cancel and purge z/OSMF REST API on z/OS 2.4](https://www.ibm.com/docs/en/zos/2.4.0?topic=interface-cancel-job-purge-its-output) seems to imply that asynchronous is the default, that does not seem to be fully accurate. _(EDIT 2022-12-19: It seems since z/OS 2.4, synchronous is the default if header is omitted and that the Docs was defective when this issue is published.)_ Testing on a z/OS 2.4 system without CIM indicates that if the header is omitted, the system would default to purging the job synchronously. See image below.

<img width="852" alt="image" src="https://user-images.githubusercontent.com/13640520/175784246-07168c00-cb8d-4614-bd76-7d4b875357e1.png">

A potential issue would be towards system running JES3 or (E)JES. Since synchronous is only supported on JES2, I am not aware of what will happen when sending a header with the value 2.0 to a JES3 system. Best case scenario would be the system treating it as a asynchronous request instead. However, I do not have access to a JES3 system to test this.

**Comment by skurtz97** [comment]
This issue affects the [Open Mainframe Projects COBOL Programming Course](https://github.com/openmainframeproject/cobol-programming-course) as well, which has a lab component hosted by IBM that does not have CIM enabled.

The zowe-cli is not a component of that course, and requests are made through [Zowe Explorer](https://github.com/zowe/explorer-mvs). 

An example of a problem this causes is the inability to delete jobs without guiding students off track to the `--modify-version "2.0"` flag, which can be an issue for students who get stuck on exercises and wind up with a long list.

![image](https://user-images.githubusercontent.com/71720714/175786704-e5791cf7-f2fc-4366-86f7-57b698a5ea6e.png)
