### ISSUE TITLE
Rewrite daemon implementation for Windows to stop using `named_pipe`

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/zowe-cli#1465]
The `named_pipe` crate has not been updated for a few years and is no longer maintained (see https://github.com/blackbeam/named_pipe/issues/13#issuecomment-1077951662).

The recommended replacement seems to be Tokio: 
https://docs.rs/tokio/latest/tokio/net/windows/named_pipe/index.html

**Comment by dkelosky** [comment]
it would be cool to reintroduce (via extra controls) the ability to allow tcp sockets for the daemon (like `dockerd`). i used to be able to share my daemon with my windows and ubuntu wsl instance.  it's not really noticeable, but tcp when measured appears to be slightly more performant.  

for non-multi user systems and bound to `localhost`, i would much prefer to use tcp 😄

**Comment by Trisk3lion** [comment]
Thumbs up from me for @dkelosky suggestion.

It may also solve issue #1318, because it worked fine with that solution.
