### ISSUE TITLE
zowe config convert-profiles - Error: The stub received bad data

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/zowe-cli#1475]
Reported by an internal user:

Getting failure on
zowe config convert-profiles

Starting a background process to increase performance ...
Waiting for the Zowe daemon to start (1 of 60)
Detected 31 old profile(s) to convert from Zowe v1 to v2.

The following plug-ins will be removed because they are now part of the core CLI and are no longer needed:

@zowe/secure-credential-store-for-zowe-cli
Are you sure you want to continue? [y/N]: y

Uninstalled plug-in: @zowe/secure-credential-store-for-zowe-cli

Converted endevor profiles: A
Converted endevor-location profiles: A, B, C, D
Converted ops profiles: A, B, C, D
Converted ssh profiles: A, B, C, D, E, F
Converted sysview profiles: A, B, C, D
Converted tso profiles: A
Converted zftp profiles: A, B, C, D, E
Converted zosmf profiles: A, B, C, D, E, F

Unexpected Command Error:
Please review the message and stack below.

Contact the creator of handler:
"C:\Users\XXX\AppData\Roaming\npm\node_modules@zowe\cli\node_modules@zowe\imperative\lib\imperative\src\config\cmd\convert-profiles\convert-profiles.handler"

Message:
The stub received bad data.

Stack:
Error: The stub received bad data

**To Reproduce**

1. Run zowe config convert-profiles

**Expected behavior**
Expect successful generation of zowe.config.json

**Details**

* ZOWE Version: [7.2.3]

**Comment by t1m0thyj** [comment]
There may be a limitation where the "config convert-profiles" command doesn't work in daemon mode, and if so we should probably call it out in the command help or in documentation. Will update this issue once I've heard back from the issue reporter.

**Comment by gejohnston** [comment]
Question: Does the command not perform all of its work, or is does it just display a bogus message at the end?

**Comment by t1m0thyj** [comment]
I believe it does not perform all of its work. It stores the zowe.config.json file but fails to write secure credentials to the vault.

My speculation about why this happens is because in daemon mode, the convert profiles handler is unable to sufficiently unload the old SCS credential manager until the daemon is restarted. Outside of daemon mode, we worked around this issue by skipping the load of the credential manager at Imperative initialization time when the CLI arguments contain "config convert-profiles". Kind of a hack, but it was the best solution we could devise to workaround the `Object.freeze` that locks the credential manager in the memory of the current Node.js process once it has been loaded.

**Comment by gejohnston** [comment]
I worked with Mark. His primary problem was due to placing a team configuration in his Zowe home directory and then running in a project directory that needed V1 profiles. Removing the team configuration from his Zowe home directory resolved his problem. Both his V1 project and his V2 now project work. This issue can be closed.
