### ISSUE TITLE
Update npm install command in readme

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/zowe-cli#1480]
The ["Build Zowe CLI from source"](https://github.com/zowe/zowe-cli#build-zowe-cli-from-source) section of the readme suggests the following command:
```
npm install --@zowe:registry=https://registry.npmjs.org --no-package-lock --force
```

The flags are unnecessary and some may cause problems. The command should be replaced with the following:
```
npm install
```

* `--@zowe:registry=https://registry.npmjs.org` is unnecessary because the `@zowe:registry` defined in .npmrc should work
* `--no-package-lock` ignores the dependencies locked down in shrinkwrap for security/compatiblity reasons
* `--force` should generally not be used unless there is an error that requires force to be bypassed

**Comment by omkolte17** [comment]
Hello, may I update the documentation for the same issue?

**Comment by t1m0thyj** [comment]
@omkolte17 Sure, go ahead 🙂 When creating a pull request, please make sure to follow contribution guidelines including signing off your commits as described [here](https://github.com/zowe/zowe-cli/blob/master/CONTRIBUTING.md#sign-all-of-your-git-commits).
