### ISSUE TITLE
Plugins location option

### ISSUE THREAD

**Issue by EmlynWill** [zowe/zowe-cli#1483]
Enhancement suggestion:
I'd like a "plugins install location" option similar to ZOWE_CLI_HOME so that the plugin directory can be separated from the configs. In this way we can pre install the plugins for our users and allow them to update the configs in their own location. We still need ZOWE_CLI_HOME to save the configs in their own/separate location. ZOWE_CLI_HOME will typically be on a network drive whereas the plugins would be on the C: drive.

**Comment by gejohnston** [comment]
The desire to control the location of plugins separately from the Zowe home directory is something that we have heard before and casually discussed within the team. Usually the request stems from a desire to share one common set of plugins amoung an entire group of people.

This is a reasonable enhancement request. We expect it will require some serious design thought and rigorous testing to ensure that we properly accommodate all situations. No work in this area is currently in-progress.

Another consideration will be how to specify the location for the plugin directory. My first inclination would be to use an environment variable to override the default location. However, another of your enhancement requests suggests that the use of environment variables may need to have zowe-cli configuration properties as alternatives. This enhancement might need to go hand-in-hand with that enhancement.

Even if our product management group gives this a moderately high priority, I expect we would take 3 to 6 months to deliver such a feature. Of course we will update you if the status of this request changes. Also, we may solicit your input as we do any design work on such a feature.

**Comment by EmlynWill** [comment]
An environment variable to set the plugins location would be fine for us, we would set it for the users in the same way that we do for ZOWE_CLI_HOME.

**Comment by t1m0thyj** [comment]
Added to the Zowe docs site in https://github.com/zowe/docs-site/pull/2382. The new env var will be documented at the link above once the Zowe 2.3 release goes live.
