### ISSUE TITLE
`Get.USSFile` SDK method does not handle `encoding`

### ISSUE THREAD

**Issue by zFernand0** [zowe/zowe-cli#1495]
https://github.com/zowe/zowe-cli/blob/217bae8691f84a3c92189cc8bee5ccb1628d2360/packages/zosfiles/src/methods/get/Get.ts#L65

Suggestion: Add encoding header to the request 😋 
```typescript
if (options.encoding) {
  const encodingHeader = ZosmfHeaders.X_IBM_TEXT;
  const encodingHeaderKey = Object.keys(encodingHeader)[0];
  const encodingHeaderText = encodingHeader[encodingHeaderKey] + ZosmfHeaders.X_IBM_TEXT_ENCODING + options.encoding;
  encodingHeader[encodingHeaderKey] = encodingHeaderText;
  reqHeaders.push(encodingHeader);
}
```

**Comment by sarthakjdev** [comment]
hey 
Encoding options are not working even in the view ds command for me. 
Any leads for the same? 
The API throws the error with 500, on defining the encoding option with any command.

**Comment by zFernand0** [comment]
The systems hosted by Marist College may not have support for certain functions/features (e.g. zos-logs) and this may include certain code-pages.
However, it is true that certain methods in our SDKs don't seem to pass the encoding option to z/OSMF. 😋

**Comment by FALLAI-Denis** [comment]
Hi,

By default, for USS files, it is not the client (zowe sdk) which must decide on the encoding, but the server (z/osmf), which must use the encoding information declared on the file, and in the absence of a specific encoding, use the IBM-1047 encoding.

**Comment by FALLAI-Denis** [comment]
Hi

Does option "autoconvert", "lang" or "locale" can interfer in upload / download operations on USS file ?
