### ISSUE TITLE
Add progress bars when uploading/downloading large numbers of files.

### ISSUE THREAD

**Issue by AHumanFromCA** [zowe/zowe-cli#15]
It would be nice to see the total progress of file uploads/downloads when dealing with large volumes. Right now the CLI looks to be hung when uploading/downloading a large list of files.

**Comment by ChrisBoehmCA** [comment]
This might be solved by #105 ? I added progress bars to commands that download / upload more than one file

**Comment by ChrisBoehmCA** [comment]
Added progress bars to various upload and download commands in #331
