### ISSUE TITLE
zowe --daemon doesn't give a startup message 

### ISSUE THREAD

**Issue by dkelosky** [zowe/zowe-cli#1506]
Use `set ZOWE_USE_DAEMON=false` and then `zowe --daemon` to start the daemon manually.  Observe that no message is issued but the daemon is active.  Before we used to get a message that the daemon was listening on some `.sock` which is useful to confirm that it is up and running.  Can this message be added back?

**Comment by t1m0thyj** [comment]
The recent disappearance of this message seems like an unintentional consequence of https://github.com/zowe/imperative/pull/865.

**Comment by t1m0thyj** [comment]
Tagging this as a good first issue, it can be fixed here by replacing `Imperative.console` with `new Console("info")`: https://github.com/zowe/zowe-cli/blob/3524ec64fc296e4e60b95caee0e313c0968d2c06/packages/cli/src/daemon/DaemonDecider.ts#L119

@dkelosky For now, setting the environment variable `ZOWE_APP_LOG_LEVEL=INFO` before launching the daemon should be a workaround to override the default log level (WARN) and show the message.
