### ISSUE TITLE
zowe config secure command error should link to documentation 

### ISSUE THREAD

**Issue by dkelosky** [zowe/zowe-cli#1514]
On a Linux system I ran: `/dev/code-review$ zowe config secure` and got this response:

```
Command Error:
Unable to securely save credentials.
Error Details:
Possible Solutions:
 - Reinstall Zowe CLI. On Linux systems, also make sure to install the prerequisites listed in Zowe CLI documentation.
 - Ensure Zowe CLI can access secure credential storage. Zowe CLI needs access to the OS to securely save credentials.
 ```
 
 Ideally, the CLI would return a link in the command output directly to the relevant documentation so that users don't need to search Zowe CLI documentation.

**Comment by t1m0thyj** [comment]
When designing the `zowe config secure` command we discussed the possibility of adding a link here and decided against it. In CLI help text output, we generally prefer to mention keywords to search for in the docs like "Zowe CLI" and "prerequisites", rather than including a direct link to a specific topic on the docs site which could potentially break in the future if content is reorganized. If this issue receives enough upvotes (per the comment above), we may reconsider this 🙂

**Comment by aviVzm05** [comment]
I was trying to create a docker image with zowe V2 pre-built and setup. Got below commands completed.. as per the documentation... 
`FROM node
RUN apt-get update && apt-get install && apt-get install -y gnome-keyring libsecret-1-0 \
    && npm install -g prebuild-install && npm install -g @zowe/cli@zowe-v2-lts`

However, am getting below error when am trying to do `zowe config init --gc`

```
root@e5614c1fe95d:/# zowe config init --gc
Warning:
Unable to securely save credentials. Skipped prompting for credentials.

Possible Solutions:
 - Reinstall Zowe CLI. On Linux systems, also make sure to install the prerequisites listed in Zowe CLI documentation.
 - Ensure Zowe CLI can access secure credential storage. Zowe CLI needs access to the OS to securely save credentials.

Saved config template to /root/.zowe/zowe.config.json
```
is this issue related or am I missing anything here? :(

**Comment by dkelosky** [comment]
This issue is me complaining about the error message not providing me exactly what I need 😄 

You can [disable SCS](https://github.com/dkelosky/rexx-jenkins/blob/master/Dockerfile#L38)  I tailored the dockerfile from @t1m0thyj and @awharn and @plavjanik.  There is also a few [blogs](https://medium.com/zowe/running-zowe-cli-on-jenkins-with-docker-7fd35d4211d0) that touch on Zowe Docker container specifics

**Comment by ATorrise** [comment]
linking to previous issue #1268

**Comment by ATorrise** [comment]
The team has decided against putting links in CLI output because we see it being a future fail point as links break very easily.

**Comment by plavjanik** [comment]
Has the issue of Dan (the error message not providing me exactly what I need) been addressed in a different way since there will not be a link?

**Comment by dkelosky** [comment]
@plavjanik - I like that suggestion.  For example, one solution says "Ensure Zowe CLI can access secure credential storage".  After googling, there is not article or doc I can find that tells me how I can ensure access.
