### ISSUE TITLE
zowe endevor list elements - lists the element short name

### ISSUE THREAD

**Issue by EmlynWill** [zowe/zowe-cli#1515]
**Describe the bug**

"zowe endevor list elements" - lists the element short name instead of the long name for USS elements with element names greater than 8 characters long,

**Expected and actual results**

**Describe your environment**

**Additional context**

--full-output can be used to get the full element name but the user shouldn't need to use this.

**Comment by gejohnston** [comment]
This issue must be addressed by the Endevor plug-in team.
We will ensure that an issue is opened for that team.
After that, we will close this issue.

**Comment by EmlynWill** [comment]
Thanks Gene, where do we post Endevor plug-in issues?

**Comment by gejohnston** [comment]
The mainframe product teams are responsible for the product-specific plugins, in this case the Endevor team.

You can open a Broadcom support issue against the Endevor product for an issue with the Endevor Zowe CLI plugin. That way the issue gets into the hands of the right set of developers.

If you open such an issue yourself, you will directly receive all of the issue tracking information.
However, if you want us to create such an issue on your behalf, just let us know.

**Comment by gejohnston** [comment]
Since there has been no further response on this issue, I am closing it. The issue can be re-opened if necessary.

**Comment by EmlynWill** [comment]
I opened a Broadcom support issue
