### ISSUE TITLE
Receiving unexpected packet type with ssh2 from sdk.

### ISSUE THREAD

**Issue by fbeyl** [zowe/zowe-cli#1516]
### Discussed in https://github.com/zowe/zowe-cli/discussions/1510

<div type='discussions-op-text'>

<sup>Originally posted by **fbeyl** September  8, 2022</sup>
Tried node sdk 'disk space' example but get ssh2 errors. Every now and then there is a succesfull run but then again several 'type errors'.
```
Outbound: Sending KEXECDH_INIT
Outbound: Sending DISCONNECT (3)
node:events:491
      throw er; // Unhandled 'error' event
      ^
Error: Received unexpected packet type 0
```
Difference I see in client.js is added line 710 proto.start();
When I use ssh2 not from sdk but symlinking to outside ssh2 no more errors occur.
ssh2 version used in sdk is 1.4.0 ---> returns error
outside ssh2 version is 1.11.0 ---> returns ok</div>

**Comment by t1m0thyj** [comment]
Thanks for reporting this! It should be fixed in `@zowe/cli@7.6.1` which is available on npmjs.org with the `@next` tag and will be published to the `@zowe-v2-lts` tag soon.
