### ISSUE TITLE
Question: Should `--data-set-type PDS` use our defaults or z/OSMF's defaults

### ISSUE THREAD

**Issue by zFernand0** [zowe/zowe-cli#1540]
Should this `dsorg` be determined based on the provided `dsntype` argument ?

Based on the help, it feels that someone should be able to specify PDS and a `DATA_SET_PARTITIONED` enum should be selected (and its defaults)

---

The only way I could find out this worked is by creating datasets with all allowed values, and here are my results:
- BASIC: `dsorg: PS`
- EXTPREF: `dsorg: PS-E`
- EXTREQ: `dsorg: PS-E`
- HFS: `dsorg: PS`
- LARGE: `dsorg: PS-L`
- PDS: `dsorg: PS` (I expected this to be `dsorg: PO` - might be a z/osmf issue)
- LIBRARY: `dsorg: PS` (I expected this to be `dsorg: PO` - might be a z/osmf issue)
- PIPE: `dynamic allocation error` 🤷 

---
Help text:
```
   --data-set-type | --dst | --dsntype (string)

      The data set type (BASIC, EXTPREF, EXTREQ, HFS, LARGE, PDS, LIBRARY, PIPE)
```

_Originally posted by @zFernand0 in https://github.com/zowe/zowe-cli/pull/1519#discussion_r988000803_

**Comment by FALLAI-Denis** [comment]
Hi

Be carrefull that ACS routines (SMS managed files) can dynamically modify user request and change some parameters of allocation.
