### ISSUE TITLE
Shell.executeSsh function hangs when >6 shells are called  

### ISSUE THREAD

**Issue by Yuliya-Kirkorava** [zowe/zowe-cli#1562]
Hi Team,

I run Uss make command inside executeSsh function. The make calls a lot of other scripts, and I suspect that nested shells are also called there.
When the command finishes execution, it hangs. I think the Promise is not resolved in executeSsh function.

In the code (executeSsh) you exit from shells 8 times:

// exit multiple times in case of nested shells
                    stream.write(`export PS1='$ '\necho ${this.startCmdFlag}\n${command}\n` +
                    `exit $?\nexit $?\nexit $?\nexit $?\nexit $?\nexit $?\nexit $?\nexit $?\n`);
                    stream.end();

If I have >8 shells, executeSsh hangs.

Could you exit from all shells? Or resolve this Promise for another condition?    

Thanks, Yuliya

**Comment by t1m0thyj** [comment]
Related to #1390

**Comment by Yuliya-Kirkorava** [comment]
We dig deeper.. 
Seems the problem is not in the count of created shells. I think '\nexit $?' commands doesn't work in our case.
 The last lines of make command output are:
![image](https://user-images.githubusercontent.com/96059205/201096360-908c2752-e413-4981-9967-4b8ed81c17fd.png)

There are no any exit commands at the end.

When we issue 'ps -ef' command in the terminal, we see two shells runs: 
![image](https://user-images.githubusercontent.com/96059205/201096814-341dbd71-6f2b-4389-bc58-8fdafeac40a5.png)

I changed a command for executeSsh function a little bit. I added echo and some more exits commands after calling make:

Shell.executeSsh(session, `cd ${dir} && make && echo "Hello!" && exit $? \nexit $? \nexit $? \nexit $? \nexit $?`, stdoutHandler);

After that I got the following output:
![image](https://user-images.githubusercontent.com/96059205/201097706-06fe69c7-03d9-4eeb-8beb-d7e9a2121a88.png)

But the output of 'ps -ef' still shows one shell running:
![image](https://user-images.githubusercontent.com/96059205/201098887-9f752fe6-b237-4dbe-85ff-ea3a311ac157.png)

**Comment by t1m0thyj** [comment]
@Yuliya-Kirkorava How is the `executeSsh` method being invoked? Is it with the `zowe zm make` command, or through custom scripting that you have created?

**Comment by Yuliya-Kirkorava** [comment]
Hi Timothy,
I have updated zowe make plugin for Zowe 2.0 and made a lot of modifications there for working with our product build workflow. Indeed, I use 'zowe zm make' command to invoke executeSSh function for running product build using **gmake** command inside (instead of **make**).  But I think it doesn't matter..

The whole product build process takes about 8-10 minutes. Everything works fine right now except the hanging after the last log output. If we run make the second time (after everything has been already built) , it finishes without hanging. It takes about 1-2 minutes.

I see that you have some debuging messages in executeSSh function. If you let me know how to trace the function, I can run it with such option. Let me know what I can do more to help you to investigate the problem.

Thanks, Yuliya

**Comment by t1m0thyj** [comment]
@Yuliya-Kirkorava Since you mentioned that `executeSsh` hangs for the build that takes 8-10 minutes, but works fine for the build that takes 1-2 minutes, I'm curious if this is related to the limitation on number of nested shells that you initially mentioned.

Perhaps the longer build spawns more than 8 shells if it runs more commands. To test this theory, could you try increasing the number of `exit $?` commands from 8 to a much larger number like 20 or 40, and see if it still hangs?

**Comment by Yuliya-Kirkorava** [comment]
@t1m0thyj  
I have already tried to add more exits, it hanged after the last log output as on the 1st screenshot from my previous update. It doesn't matter how many exits were added.
If I specify "&&" between exits, it always exists from bash but it hangs after that (like on the 3rd screenshot).  From the "ps -ef" output I get that shell is still running (on the 4th screenshot).
If I run "kill -SIGHUP _shell_PID_" command, `executeSsh` commans is resolved.

As a temporary solution I added 'kill -SIGHUP $PPID;' after calling make.

**Comment by t1m0thyj** [comment]
Closing this issue because:
* The `[ZM-MAKE]` messages indicate this issue is specific to the [zos-make-plugin](https://github.com/zowe/zowe-cli-zos-make-plugin) which is not actively developed.
* A workaround has been identified in the comment above.

Feel free to reopen the issue or create a new one if you encounter the problem with other SSH commands.
