### ISSUE TITLE
zowe plugins list command gives incorrect results when ZOWE_CLI_ROOT is set

### ISSUE THREAD

**Issue by MichalVasak** [zowe/zowe-cli#1593]
When the environmental variable ZOWE_CLI_ROOT is set (and not pointing to the default location) the command 
"zowe plugins list" gives incorrect results. 

Based on my testing, what happens is that the command returns the content of ~/.zowe/plugins/plugins.json
(the default location for Zowe CLI metadata) instead of the location used by the "zowe plugins install" command:
$ZOWE_CLI_ROOT\data\plugins\plugins.json

Command issued: "zowe plugins list" 

Expected: "zowe plugins list" returns the content of $ZOWE_CLI_ROOT\data\plugins\plugins.json
(which contains up-to-date list of plugins used by Zowe CLI)

Actual: "zowe plugins list" returns the content of ~/.zowe/plugins/plugins.json 
(which contains an outdated plugins list from before the ZOWE_CLI_ROOT environmental variable was set)

**Describe your environment**
Zowe CLI version installed: 7.4.0
Installed plug-ins and their version numbers: Endevor 7.3.0
Node.js and NPM versions installed (run `node --version`, `npm --version`): node v12.18.3, npm 6.14.6
Environment variables in use: ZOWE_CLI_ROOT 
Operating system and version: Windows 10
Shell/terminal (bash, cmd, powershell, etc...):  powershell
Daemon mode enabled or disabled: enabled

**Additional context**
Can be reproduced without even installing a plugin, just by setting ZOWE_CLI_ROOT, editing plugins.json files at the appropriate locations and seeing which one is used to produce "zowe plugins list" output

**Comment by zFernand0** [comment]
Hey @MichalVasak,
The only environment variables that can affect the location or where `.zowe` contents goes are `ZOWE_CLI_HOME` and `ZOWE_CLI_PLUGINS_DIR`
More details: https://docs.zowe.org/stable/user-guide/cli-configuringcli-ev

Could you try with one of those and let us know if the problems still occurs?

**Comment by MichalVasak** [comment]
Hi Fernando,

**Comment by gejohnston** [comment]
The need to restart the daemon is known, documented behavior.

https://docs.zowe.org/stable/user-guide/cli-using-using-daemon-mode/#restart-daemon-mode

**Comment by MichalVasak** [comment]
Ok, thank you John. In that case I'll just close the issue, everything seems to be working according to the doc.
