### ISSUE TITLE
Special characters in JCL when submitting a job not correctly encoded

### ISSUE THREAD

**Issue by juleskreutzer** [zowe/zowe-cli#1596]
**Describe the bug**
When submitting a a JCL job it is possible to use the `MonitorJobs` [link](https://github.com/zowe/zowe-cli/blob/master/packages/zosjobs/src/MonitorJobs.ts) class to check for the job result. Under water, this class is also used by the `SubmitJobs.submitJclNotifyCommon` method.
When submitting a job with a special character, for example `#`, the `MonitorJobs.waitForStatusCommon` method will throw an `HTTP 400: Bad request` error. This is due to the special character not being escaped properly in the [AbstractRestClient](https://github.com/zowe/imperative/blob/ca981d476b7a97fa6129de523c63e1a58000c139/packages/rest/src/client/AbstractRestClient.ts#L416).

**Expected and actual results**
The expected result is that the `MonitorJobs.waitForStatusCommon` method returns an IJob object. The actual result is an error when submitting JCL with a special character in the jobcard: `Error obtaining status for jobname "Jobname" jobid "Jobid"`

When submitting JCL without a special character in the jobcard, it works as expected.

**Describe your environment**
In our environment, it is a standard to name jobs executed by a user in the following format: `<prefix>#<jobname>`, for example `KT#JZOWE`

**Additional context**
[I have created a repo to troubleshoot this issue](https://github.com/juleskreutzer/ZoweSubmitJclNotifyCommon). When executing the VSCode extension locally, follow the following steps:
- Run the extension in debug mode
- Execute the command "Hello World" --> You should see a message that the job has been submitted
- Execute the command "Another Hello World" --> You should see a message that the call failed and the error is logged to the console and the Zowe log folder (~/.zowe/zowe/logs)

Change the jobcard to your requirements, but make sure that the jobname includes a special character like `#`

I already discussed this with @VitGottwald. It is possible that he has another private repo with settings tailored to Broadcom's environment.

**Comment by VitGottwald** [comment]
I was able to reproduce the behaviour from @juleskreutzer repository on our dev systems. The only thing I had to do was to update the JCL to include an accounting id (and remove the rest of unnecessary JOB statement parameters).

**Comment by gejohnston** [comment]
Because this issue prevents our customer from submitting jobs that follow their shop standards, I marked the issue for review.

**Comment by ATorrise** [comment]
Hello, @VitGottwald and @juleskreutzer I am with the CLI team. I have tested the retrieval of a job containing a special character in its 8 character jobname via `MonitorJobs.waitForStatusCommon` without error. Testing also included a file with an accounting id. Wondering if there is any more information you guys can add as it seems that jobnames can utilize special characters without issue.

**Comment by VitGottwald** [comment]
@ATorrise try running 

```
zowe jobs submit ds --wait-for-output 'public.zowe.jcl(br14)'
```

where the contents of `PUBLIC.ZOWE.JCL(BR14)` is

```
//ABC#BR14 JOB (120400030)
//BR14    EXEC PGM=IEFBR14
```

I just did that with Lowe 7.10.4 and got the error:

```
% zowe jobs submit ds --wait-for-output 'public.zowe.jcl(br14)'
Command Error:
Error obtaining status for jobname "ABC#BR14" jobid "JOB60652".
z/OSMF REST API Error:
Rest API failure with HTTP(S) status 400
<!doctype html><html lang="en"><head><title>HTTP Status 400 – Bad Request</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 400 – Bad Request</h1></body></html>
Error Details:
HTTP(S) error status "400" received.
Review request details (resource, base path, credentials, payload) and ensure correctness.

Protocol:  https
Host:      *****************************
Port:      7554
Base Path: api/v1
Resource:  /zosmf/restjobs/jobs/ABC#BR14/JOB60652
Request:   GET
Headers:   [{"X-CSRF-ZOSMF-HEADER":true}]
Payload:   undefined
```

**Comment by VitGottwald** [comment]
The resources path shows an unescaped pound sign: `/zosmf/restjobs/jobs/ABC#BR14/JOB60652`

**Comment by ATorrise** [comment]
@VitGottwald 

After testing this with @t1m0thyj, we've found that there is a new discrepancy in the encoding of characters between us and API ML that requires our getting in touch with them.

<br/>

- We noticed in your output that you had a `BasePath` of `api/v1` indicating that you're accessing z/OSMF through the API Mediation Layer. We've seen issues before where it doesn't handle encoding characters well so we tested to see if this was the cause of the failure and found that it was. 

![image](https://user-images.githubusercontent.com/112635587/217899478-0551beca-a45d-4afe-88c0-0e7477444495.png)

- Afterwards, we checked if this issue has since been reported to APIML or if they've made any changes, which they have: https://github.com/zowe/api-layer/pull/804. They've added support for character encoding (where # would be %23) which they didn't support before. That fixed issues where Zowe CLI tried to pass an encoded data set or job name, and API ML failed to handle it. This seems to be the opposite problem, however. 

To better understand where this issue lies and what should be fixed where, we will be getting in touch with the API ML team to find a path forward.

**Comment by ATorrise** [comment]
@juleskreutzer would you mind confirming that you've also been going through the API ML like @VitGottwald has? For now our team suggests bypassing API ML and connecting to z/OSMF directly instead, if possible. 

On our end, next steps will be making an issue on API ML's repo and linking this discussion there.

**Comment by juleskreutzer** [comment]
Hello @ATorrise 
I ran the following command: `zowe jobs submit ds --wait-for-output 'r276404.jcllib(zoweclit)'`

This results in the following output:
```powershell
PS C:\Users\Jules.Kreutzer> zowe jobs submit ds --wait-for-output 'r276404.jcllib(zoweclit)'
Command Error:
Error obtaining status for jobname "KT#TEST" jobid "JOB97232".
z/OSMF REST API Error:
Rest API failure with HTTP(S) status 400
<!doctype html><html lang="en"><head><title>HTTP Status 400 – Bad Request</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 400 – Bad Request</h1></body></html>
Error Details:
HTTP(S) error status "400" received.
Review request details (resource, base path, credentials, payload) and ensure correctness.

Protocol:  https
Host:      xxxx
Port:      7554
Base Path: ibmzosmf/api/v1
Resource:  /zosmf/restjobs/jobs/KT#TEST/JOB97232
Request:   GET
Headers:   [{"X-CSRF-ZOSMF-HEADER":true}]
Payload:   undefined
```

Same step is executed in the `zoweclit` JCL:
```
//KT#TEST JOB NLD700253170,'KREUTZER,A  G1501110'
//BR14   EXEC PGM=IEFBR14                        
//*                                              
```

Let me know if you need more information

**Comment by VitGottwald** [comment]
@ATorrise did you create an issue in the APIML repo? I do not see any links here so far.

**Comment by ATorrise** [comment]
> @ATorrise did you create an issue in the APIML repo? I do not see any links here so far.

Yes, just created. We can move this conversation to that thread for now https://github.com/zowe/api-layer/issues/2800

**Comment by VitGottwald** [comment]
Thank you @ATorrise !
