### ISSUE TITLE
GHA: Changelog workflow uses the deprecated `set-output` feature

### ISSUE THREAD

**Issue by zFernand0** [zowe/zowe-cli#1618]
https://github.com/zowe/zowe-cli/actions/runs/4068577292/jobs/7007295673
```Warning: The `set-output` command is deprecated```
See the following PR for how to fix this:
- https://github.com/zowe/vscode-extension-for-zowe/pull/2106

**Comment by t1m0thyj** [comment]
Thanks @awharn for fixing this in https://github.com/awharn/check_changelog_action/pull/13 🙂
