### ISSUE TITLE
Document the CLI requirements for /usr/bin/env

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-cli#1628]
## Is your request for enhancement related to a problem? Please describe.
Working with a customer getting an error message it took a while to find out the reason was that the directory.  
`/usr/bin/env` needed to be present.   There was a syntax error because it was ignoring the `#!/usr/bin/env node`

## Describe the solution you'd like
Re-create and then document the error in troubleshooting, and also as a CLI pre-req

## Related doc pages
https://docs.zowe.org/stable/user-guide/systemrequirements-cli
https://docs.zowe.org/stable/troubleshoot/cli/troubleshoot-cli

**Comment by adam-wolfe** [comment]
We have documented the need to have the path to the node executable on the user's PATH environment variable here: https://docs.zowe.org/stable/user-guide/systemrequirements-cli#nodejs
