### ISSUE TITLE
Special characters within dataset and job names

### ISSUE THREAD

**Issue by adam-wolfe** [zowe/zowe-cli#1633]
Several users have reported problems with including special characters ('#') within job and dataset names.

**Comment by adam-wolfe** [comment]
@wolfgang0101 this should be fixed in Zowe CLI v7.12.0 which is available now via npm.

**Comment by Felix-Braun** [comment]
Hello,
is this also planned for the ZOWE Extension in VSCODE?  Or should I open an issue in [zowe/vscode-extension-for-zowe](https://github.com/zowe/vscode-extension-for-zowe)?

**Comment by t1m0thyj** [comment]
> Hello, is this also planned for the ZOWE Extension in VSCODE? Or should I open an issue in [zowe/vscode-extension-for-zowe](https://github.com/zowe/vscode-extension-for-zowe)?

This is also planned for the next release of Zowe Explorer - currently anticipated to be around Apr 24 in sync with Zowe 2.8 release date, unless the team releases a patch update before that. We merged a pull request yesterday for the fix (https://github.com/zowe/vscode-extension-for-zowe/pull/2209).

**Comment by Felix-Braun** [comment]
Thank you 👍
