### ISSUE TITLE
ZOWE as Jenkins plugin

### ISSUE THREAD

**Issue by zszabo14** [zowe/zowe-cli#1636]
**Is your feature request related to a problem or limitation? Please describe.**
zowe can be added to a Jenkins agent image, while the usage is limited, eg profiles, credentials

**Describe the experience you'd like**
zowe should be used as a plugin in declarative and scripted pipeline

**Describe alternatives you've considered**
develop plugin (without nodeJS ?)
- manage plugin config, profiles, credentials, ets
- convert zowe cli functionality as pipeline steps

**Additional context**
Maybe for Travis and Ansible also

**Comment by zFernand0** [comment]
The Jenkins plug-in development is already underway.
Please check out this repo:
- https://github.com/zowe/zowe-zdevops-jenkins-plugin
