### ISSUE TITLE
Special characters in JCL when submitting a job not correctly encoded

### ISSUE THREAD

**Issue by ATorrise** [zowe/zowe-cli#1651]
**Bug Description**
-

I am a member of the CLI team and we've noted [several issues on our repo](https://github.com/zowe/zowe-cli/issues/1633) that actually have to do with the way the CLI and API ML interact. 

When our users access z/OSMF through API ML with special characters in their jobnames, their requests fail. We've seen that you've since added [support for character encoding](https://github.com/zowe/api-layer/pull/804) but now we see issues with handling unencoded characters.

I am reaching out to determine a best path forward, perhaps you'd like our team to handing some of this work load.

**Steps to reproduce**
-

The following documentation was written by @juleskreutzer in [this](https://github.com/zowe/zowe-cli/issues/1596) issue

```
I ran the following command: zowe jobs submit ds --wait-for-output 'r276404.jcllib(zoweclit)'

This results in the following output:

PS C:\Users\Jules.Kreutzer> zowe jobs submit ds --wait-for-output 'r276404.jcllib(zoweclit)'
Command Error:
Error obtaining status for jobname "KT#TEST" jobid "JOB97232".
z/OSMF REST API Error:
Rest API failure with HTTP(S) status 400
<!doctype html><html lang="en"><head><title>HTTP Status 400 – Bad Request</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 400 – Bad Request</h1></body></html>
Error Details:
HTTP(S) error status "400" received.
Review request details (resource, base path, credentials, payload) and ensure correctness.

Protocol:  https
Host:      xxxx
Port:      7554
Base Path: ibmzosmf/api/v1
Resource:  /zosmf/restjobs/jobs/KT#TEST/JOB97232
Request:   GET
Headers:   [{"X-CSRF-ZOSMF-HEADER":true}]
Payload:   undefined
Contents of zoweclit JCL:

//KT#TEST JOB NLD700253170,'KREUTZER,A  G1501110'
//BR14   EXEC PGM=IEFBR14                        
//*                  
```
**Expected behavior**
-

We expect users to be able to include special characters within their job names and to have that work throughout the zowe ecosystem. 

**Screenshots**
-

The below screenshot proves that accessing zOSMF through API ML with a special character job name will error. The same request direct to zOSMF succeeds. 

![image](https://user-images.githubusercontent.com/112635587/219494336-c1060267-0143-4aba-9660-6b18370afa0c.png)

**Additional context**
-
We've compiled an [epic](https://github.com/zowe/zowe-cli/issues/1633) containing the related issues but each issue is also listed below for convenience: 
-  https://github.com/zowe/zowe-cli/issues/1596 
-  https://github.com/zowe/zowe-cli/issues/1073 
- https://github.com/zowe/vscode-extension-for-zowe/issues/1215

**Environment Details**
 - Version and build number: Version 1.28.13 build # n/a
 - Test environment: Broadcom internal system

**API Catalog Web UI (in case of API Catalog issue):**
 - NA

**REST API client (in case of REST API issue):**
 - NA
 
**Willingness to help**

Our team is definitely willing to help - perhaps we can schedule a meeting to talk this through.

**Comment by VitGottwald** [comment]
Is this resolved by https://github.com/zowe/zowe-cli/pull/1663 ?

**Comment by t1m0thyj** [comment]
Yes, I think this is a duplicate of #1596 because we created an issue in the API ML repo to discuss the topic of special character encoding with their team, and it came back to us 🙂 Closing for now, we can follow up as needed on the epic which is still open: https://github.com/zowe/zowe-cli/issues/1633
