### ISSUE TITLE
23PI2 Planning

### ISSUE THREAD

**Issue by zFernand0** [zowe/zowe-cli#1671]
# Zowe SDK (Node.js and Python), CLI & Plug-ins

## Complex z/OS Jobs and z/OS Files commands 
Enable Zowe CLI users to perform more complex (jobs & files) tasks with single commands.

CLI Squad Plan:
- [x] https://github.com/zowe/zowe-cli/issues/1098
- [x] https://github.com/zowe/zowe-cli/issues/1097

## V3 Pre-release
- [ ] https://github.com/zowe/zowe-cli/issues/1702
- [ ] https://github.com/zowe/zowe-cli/issues/1695
- [ ] https://github.com/zowe/zowe-cli/issues/1703

## Address Items in the CLI and Imperative Backlogs
Take action in accordance with Community Guidelines to support Zowe CLI users and extenders, resolve defects, and implement beneficial enhancements suggested by members of the Zowe community.

CLI Squad Plan:
#### *Enhancements*
- [ ] https://github.com/zowe/zowe-cli/issues/913
- [x] https://github.com/zowe/zowe-cli/issues/935
- [x] https://github.com/zowe/zowe-cli/issues/1673
- [x] https://github.com/zowe/zowe-cli-sample-plugin/issues/84
- [ ] https://github.com/zowe/imperative/issues/899
- [ ] [Stretch] https://github.com/zowe/zowe-cli/issues/1692
- [ ] [Stretch] https://github.com/zowe/imperative/discussions/828
- [ ] [Stretch] https://github.com/zowe/zowe-cli-ftp-plugin/pull/131

#### *Bugs*
- [ ] https://github.com/zowe/zowe-cli/issues/690
- [x] https://github.com/zowe/zowe-cli/issues/1439
- [x] https://github.com/zowe/zowe-cli/issues/1595
- [ ] https://github.com/zowe/imperative/issues/978

#### *[Stretch] Community Upvoted*
- [ ] https://github.com/zowe/zowe-cli/issues/1326
- [ ] https://github.com/zowe/zowe-cli/issues/969
- [ ] https://github.com/zowe/zowe-cli/issues/1034
- [ ] https://github.com/zowe/zowe-cli/issues/1469
- [ ] https://github.com/zowe/zowe-cli/issues/1031
- [ ] https://github.com/zowe/zowe-cli/issues/1566
- [ ] https://github.com/zowe/zowe-cli/issues/866
- [ ] https://github.com/zowe/zowe-cli/issues/1041
- [ ] https://github.com/zowe/zowe-cli/issues/1299
- [x] https://github.com/zowe/zowe-cli/issues/865

## OpenSSF Best Practices Badge
- [ ] https://github.com/zowe/zowe-cli/issues/1352
  - Update shared Zowe spreadsheet with the latest information on the Zowe CLI project

#### Helpful links for OpenSSF Best Practices Badge criteria:
- Passing: https://bestpractices.coreinfrastructure.org/en/criteria/0
- Silver: https://bestpractices.coreinfrastructure.org/en/criteria/1
- Gold: https://bestpractices.coreinfrastructure.org/en/criteria/2

# Zowe CLI / Zowe SDK Roadmap

## (Carry-over) Complex z/OS Jobs and z/OS Files commands 
- _What problem are you solving?_
  - Customers are looking for CLI commands that perform more complex (jobs & files) tasks to reduce scripting and make interactive CLI commands more efficient
- _What are you doing to solve it?_
  - Introduce several new CLI commands capable of performing multiple tasks in a single command
- _When do you plan to start the work?_
  - **CY22Q3**
- _When do you plan to deliver the solution?_
  - **CY22Q4** (delayed until **CY23Q2**)

## (Carry-over) Gold OpenSSF Best Practices Badge (Formerly CII Best Practices Badge)
- _What problem are you solving?_
  - The Zowe Project has not earned the gold OpenSSF Best Practices Badge, a requirement from LF/OMP that ensures the Open Source project satisfies FLOSS (Free/Libre & Open Source Software) [Best Practices criteria](https://bestpractices.coreinfrastructure.org/en/criteria)
- _What are you doing to solve it?_
  - Review requirements and take necessary actions to satisfy them for the gold badge level
- _When do you plan to start the work?_
  - **CY22Q3**
- _When do you plan to deliver the solution?_
  - **CY22Q4** (delayed until **CY23Q3**)

## (Carry-over) Keytar Replacement
- _What problem are you solving?_
  - Mainframe customers demand trustworthy storage of secure values in Zowe CLI. With the sunset of the Atom organization who supplied the Keytar package, we would require an actively maintained alternative for secure credential storage
- _What are you doing to solve it?_
  - Implement a suitable replacement to the Keytar package with minimal impact to our end users
- _When do you plan to start the work?_
  - **CY23Q1**
- _When do you plan to deliver the solution?_
  - **CY23Q3** 

## (Carry-over) Zowe CLI on Unix System Services (USS)
- _What problem are you solving?_
  - Mainframe customers like to experiment with Zowe without requiring desktop software (i.e. SYSPROGS want to run CLI commands on z/OS) as part of their experimentation or enterprise use with Zowe CLI
- _What are you doing to solve it?_
  - Certify and document how to use Zowe CLI on z/OS (USS)
  - Implement secure credential management, otherwise credentials are in plain-text
- _When do you plan to start the work?_
  - **CY23Q1**
- _When do you plan to deliver the solution?_
  - **CY23Q4**

## SDK Conformance and LTS Status
- _What problem are you solving?_
  - Mainframe developers are interested in extending the existing SDKs in order to create applications for their services
- _What are you doing to solve it?_
  - Solidify the SDK Conformance guidelines for:
    - New Services (like CICS SDK)
    - New Programming languages (like Kotlin SDK)
  - Prepare the SDKs technically and logistically for conformance
  - Apply for (and achieve) conformance for existing SDKs
  - Release the SDKs as LTS
- _When do you plan to start the work?_
  - **CY23Q2**
- _When do you plan to deliver the solution?_
  - **CY23Q4** 

## (Stretch) Zowe Client Mentorship Opportunity: Enhancing the Python SDK
- _What problem are you solving?_
  - Consumers of the Python SDK are requesting enhancements, including support for Zowe V2 team configuration files
- _What are you doing to solve it?_
  - Leverage the mentorship program to deliver enhancements to the existing SDK
- _When do you plan to start the work?_
  - **CY23Q2**
- _When do you plan to deliver the solution?_
  - **CY23Q4**

## Postponed Objectives
For more details, please see the [2023 PI1 Planning Objectives](https://github.com/zowe/community/blob/master/Project%20Management/PI%20Planning/23PI1%20Planning/PI%20Planning%20Preparation%20by%20Squad/Zowe%20CLI%20Squad%20-%2023PI1%20Objectives.md)
- Zowe App Store Participation
- In-memory Credential Management & Identity Tokens
- Zowe CLI Containerization

**Comment by adam-wolfe** [comment]
23PI2 has ended.
