### ISSUE TITLE
Open solution for default file allocations settings or templates

### ISSUE THREAD

**Issue by adam-wolfe** [zowe/zowe-cli#1679]
Adapted from: https://github.com/zowe/vscode-extension-for-zowe/issues/1425:

**Is your feature request related to a problem? Please describe.**

User's have no way of specifying templates to be used for allocating data sets. They can select from a list of predefined data set templates (e.g., `data-set-binary`, `data-set-c`, `data-set-classic`, etc.) and specify options on the command to override default allocation settings. However, some users are interested in adding to the list of available data set templates.

**Describe the solution you'd like**

Allow users to define templates that are stored in a "zowe.templates.json" or similarly named file in the user's Zowe home directory that Zowe CLI can use to add additional data set templates under the `zowe zos-files create` command.

Example of a "zowe.templates.json" from https://github.com/zowe/vscode-extension-for-zowe/issues/1425:
```
    "Zowe-Default-Dataset-Allocations": [
       "PDS-FB-80": {
          "name": "Fixed blocked LRECL=80 library",
          "dsorg": "LIBRARY",
          "alcunit": "CYL",
          "primary": 1,
          "secondary": 1,
          "dirblk": 0,
          "recfm": "FB",
          "blksize": 0,
          "lrecl": 80
       },
       "PDS-VB-256": {
          "name": "Variable blocked LRECL=256 library",
          "dsorg": "LIBRARY",
          "alcunit": "CYL",
          "primary": 1,
          "secondary": 1,
          "dirblk": 0,
          "recfm": "FB",
          "blksize": 0,
          "lrecl": 80
       },
       "Loadlib": {
          "name": "Loadlib for program object",
          "dsorg": "LIBRARY",
          "alcunit": "CYL",
          "primary": 10,
          "secondary": 10,
          "dirblk": 0,
          "recfm": "U",
          "blksize": 32760,
          "lrecl": 27998
       },
       "Report": {
        "name": "Sysout capture for LRECL=133",
        "dsorg": "PS",
        "alcunit": "CYL",
        "primary": 10,
        "secondary": 10,
        "dirblk": 0,
        "recfm": "FBA",
        "blksize": 0,
        "lrecl": 133
     }
  ]
```
**Describe alternatives you've considered**

Users could write a script to feed the allocation options to Zowe CLI or they could keep their allocation commands in a text file and copy and paste them into a terminal as needed, however it would be much simpler for users to just enter a `zowe files create` command using their own templates.

**Additional context**

Ideally we would have some interoperability between Zowe Explorer's template solution and the custom templates used by Zowe CLI.

**Comment by gejohnston** [comment]
Does the ability to supply the desired attributes as command-line options to the ‘data-set-partitioned’ keyword or as overrides on the other ‘canned’ dataset keywords not supply the flexibility needed by customers?

**Comment by adam-wolfe** [comment]
Reopening due to user interest.
