### ISSUE TITLE
`zowe --show-inputs-only` always reporting zowe version as v1

### ISSUE THREAD

**Issue by ATorrise** [zowe/zowe-cli#1689]
**Describe the bug**
Flag reports the incorrect version. This flag was not meant to run on just `zowe` but it actually seems like it does work and is just reporting the wrong output. 

Details about the behavior:
1. Command issued: `zowe --show-inputs-only`
2. Expected results: 
![image](https://user-images.githubusercontent.com/112635587/233420756-b532cef6-7086-4a7d-a62f-1876bc5a20ad.png)
3. Actual results:
![image](https://user-images.githubusercontent.com/112635587/233420560-cc5df227-64b4-42f2-b43f-1c3debc59922.png)

**Describe your environment**
- Zowe CLI version installed (run command `zowe --version`): 7.13.0
- Installed plug-ins and their version numbers (run command `zowe plugins list --short`): no plug-ins
- Node.js and NPM versions installed (run `node --version`, `npm --version`): node: v16.18.0 npm: 8.19.2
- Environment variables in use:
- Operating system and version: Windows 10 19.0.45
- Shell/terminal (bash, cmd, powershell, etc...): bash
- Daemon mode enabled or disabled: disabled

**Additional context**

**Comment by ATorrise** [comment]
possible routes for fixing this:
1. remove this option from top level command group as profile information has yet to be loaded and zowe has no way of discerning version
2. if first option isn't possible, return `profileVersion: unknown`

**Comment by ATorrise** [comment]
@zowe/zowe-cli-administrators thinking it might make sense to change `profileVersion` to `configurationVersion` or even just `zoweMajorVersion`??

**Comment by gejohnston** [comment]
This field was used to identify whether the user was using old-school V1 profiles or team configuration (which was introduced in Zowe V2). 

Since we will only use a team configuration (ie, we no longer support or recognize V1 profiles in Zowe V3), perhaps we just remove the `profileVersion`  field altogether?

**Comment by gejohnston** [comment]
Fixed by PR #2073
