### ISSUE TITLE
Add flag to `zowe config profiles` to include file locations 

### ISSUE THREAD

**Issue by ATorrise** [zowe/zowe-cli#1692]
**Describe your enhancement idea**

Add `--locations` optional flag to `zowe config profiles` to provide ease and clarity for users looking for their profile configurations. This idea was proposed after the need for more clarity was expressed internally. 

This command could produce something along these lines: 
![image](https://user-images.githubusercontent.com/112635587/233470535-abeaf906-ea6c-4bc7-a0bf-49bb502206f3.png)

**Comment by awharn** [comment]
I believe we already have some functionality that behaves similarly to this, particularly via the `zowe config list profiles --locations` command, though it is not nearly as concise. From my understanding, a profile can have up to four different locations associated with it, assuming duplication between project and root configuration files, and up to two different locations inside the project and global configuration layers.
