### ISSUE TITLE
v3: Remove deprecated constants, options, and methods

### ISSUE THREAD

**Issue by zFernand0** [zowe/zowe-cli#1694]
⚠️ This does not include the `zowe profiles` group ⚠️ 

---

Full List:
- [x] [Constants.ts](https://github.com/zowe/zowe-cli/blob/master/packages/cli/src/Constants.ts)
- [x] [showAttributes](https://github.com/zowe/zowe-cli/blob/master/packages/cli/src/zosfiles/create/Create.options.ts#L39)
- [x] [ZosTso.constants.ts](https://github.com/zowe/zowe-cli/blob/master/packages/cli/src/zostso/constants/ZosTso.constants.ts)
- [x] [isStderrEmptyForProfilesCommand](https://github.com/zowe/zowe-cli/blob/master/__tests__/__packages__/cli-test-utils/src/TestUtils.ts#L70)
- [x] [ZosFiles.messages.ts](https://github.com/zowe/zowe-cli/blob/master/packages/zosfiles/src/constants/ZosFiles.messages.ts)
- [x] [getSpoolDownloadFile](https://github.com/zowe/zowe-cli/blob/master/packages/zosjobs/src/DownloadJobs.ts#L140)
- [x] [excludePatterns](https://github.com/zowe/zowe-cli/blob/master/packages/zosfiles/src/methods/download/doc/IDownloadOptions.ts#L45)
- [x] [ZosmfSession.ts](https://github.com/zowe/zowe-cli/blob/master/packages/zosmf/src/ZosmfSession.ts)
- [x] [startCmdFlag](https://github.com/zowe/zowe-cli/blob/master/packages/zosuss/src/Shell.ts#L175)
- [x] [SshSession.ts](https://github.com/zowe/zowe-cli/blob/master/packages/zosuss/src/SshSession.ts)
- [x] [zosmfProfile](https://github.com/zowe/zowe-cli/blob/master/packages/cli/src/zosfiles/ZosFilesBase.handler.ts#L80)
prereq:  vNext branch created

**Comment by ATorrise** [comment]
This issue was addressed in https://github.com/zowe/zowe-cli/pull/1981
