### ISSUE TITLE
v3: Conformance Criteria for offline installability 

### ISSUE THREAD

**Issue by zFernand0** [zowe/zowe-cli#1698]
Here are some of the benefits of adding Zowe conformance criteria for offline installability:

1. Flexibility: Organizations can install Zowe CLI Plug-ins in environments where internet connectivity is limited or unavailable.
2. Improved Security: Offline installation eliminates the need to download packages from the internet, which can be a potential source of security vulnerabilities.
3. Improved Reliability: Offline installation provides a more reliable installation process because it eliminates the risk of interruptions that can occur during online installation, such as network connectivity issues or server downtime.
4. Better Control: Offline installation gives organizations better control over the installation process. They can choose when and where to install Zowe, and can also choose which components to install, depending on their specific needs.

**Comment by adam-wolfe** [comment]
This has been added as a best practices for V3 conformance.
