### ISSUE TITLE
v3: Remove V1 profile functionality in vNext (retaining the ability to convert from V1 to V2 configs)

### ISSUE THREAD

**Issue by adam-wolfe** [zowe/zowe-cli#1703]
In the vNext branch, remove support for V1 profiles.

Based on conversations between the CLI and Explorer squads, we should plan to remove most of the V1 profile functionality (i.e., the ability to use v1 profiles to interact with mainframe services).

We should retain the ability to convert a user's profiles from V1 profiles to the V2 team config.

**Comment by gejohnston** [comment]
Delivered this enhancement in PR https://github.com/zowe/zowe-cli/pull/2085
