### ISSUE TITLE
Provide md5 files for the Zowe CLI downloads (core and plugins)

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-cli#1713]
**Is your feature request related to a problem or limitation? Please describe.**
Direct customer request to provide md5 files for the Zowe CLI core and downloads, similar to the z/OS component

**Comment by zFernand0** [comment]
This is somewhat related to the following issue:
- #1326

**Comment by adam-wolfe** [comment]
Unless there are objections, I would recommend SHA-256.

**Comment by t1m0thyj** [comment]
> Unless there are objections, I would recommend SHA-256.

+1... or SHA-512 which is what NPM uses in package-lock.json: https://docs.npmjs.com/cli/v6/configuring-npm/package-lock-json#integrity

**Comment by adam-wolfe** [comment]
SHA512 hashes are now available for Zowe CLI and CLI Plugins on zowe.org.
