### ISSUE TITLE
Command examples are incorrect for 'zowe console issue'. 

### ISSUE THREAD

**Issue by KevinLoesch1** [zowe/zowe-cli#1715]
If you issue the command 'zowe console issue --help-examples', the example statements are incorrect. They do not contain the second required parameter, **console**. Issuing the examples as is will result in an error. 

```
      Display HTML help in browser

 EXAMPLES
 --------

   - Issue a z/OS console command to display the IPL information
   for the system:

      $ zowe issue command "D IPLINFO"

   - Issue a z/OS console command to display the local and
   coordinated universal time and date:

      $ zowe issue command "D T"

   - Issue a Db2 command to display information about the status
   and configuration of DDF:

      $ zowe issue command "\-DB1G DISPLAY DDF"
```

**Comment by gejohnston** [comment]
What version of zowe CLI are you running? Is it a really old version of Zowe CLI? 

The current help displays the following example:

    Issue a z/OS console command to display the local and coordinated universal time and date:
    
        zowe zos-console issue command "D T"

When you issue the command from the help, you get the following result:

    zowe zos-console issue command "D T"
    IEE136I LOCAL: TIME=13.39.14 DATE=2023.135  UTC: TIME=17.39.14 DATE=2023.135

**Comment by KevinLoesch1** [comment]
> Is this correct ? `$ zowe console issue command "D IPLINFO" --console <console name>` `$ zowe issue command "D T" --console <console name>` `$ zowe issue command "\-DB1G DISPLAY DDF" --console <console name>` I think this is the solution but added a placeholder for console name, since specific console names vary system to system. I think you can get it `DISPLAY CONSOLE` command. please correct if I'm wrong

This issue has nothing to do with a console name. It is simply a bug in the help. The examples are missing the command group. 
The command is 'zowe zos-console issue' or 'zowe console issue', not 'zowe issue' .

**Comment by sidharthbh8** [comment]
> > Is this correct ? `$ zowe console issue command "D IPLINFO" --console <console name>` `$ zowe issue command "D T" --console <console name>` `$ zowe issue command "\-DB1G DISPLAY DDF" --console <console name>` I think this is the solution but added a placeholder for console name, since specific console names vary system to system. I think you can get it `DISPLAY CONSOLE` command. please correct if I'm wrong
> 
> This issue has nothing to do with a console name. It is simply a bug in the help. The examples are missing the command group. The command is 'zowe zos-console issue' or 'zowe console issue', not 'zowe issue' .

Sorry my bad should have read the docs first rather than giving a quick fix :")
can I resolve this issue?
`zowe zos-console issue command "D IPLINFO"` 
`zowe zos-console issue command "D T"`
`zowe zos-console issue command "\-DB1G DISPLAY DDF"`
This is correct I believe

**Comment by sidharthbh8** [comment]
hey @KevinLoesch1 can you give some hints on this 
I think packages/cli/zosconsole doesn't contains this issue

**Comment by KevinLoesch1** [comment]
This issue is fixed by the PR https://github.com/zowe/zowe-cli/pull/2064.
