### ISSUE TITLE
Regression-7.4.1 : download data-set-matching option -d does not preserve upper case

### ISSUE THREAD

**Issue by NicolasGaudinPresta** [zowe/zowe-cli#1722]
### Shell script

Here a command-log from my shell script, using 7.4.1 (not tested with newer release, working with 7.4.0) :

```
+ dr=/tmp/tmp.y3NkzRQda5
+ zowe zos-files download data-set-matching ''\''HLQ.PROJECT.**.CSV'\''' -d /tmp/tmp.y3NkzRQda5
+ ls -la /tmp
+ cat '/tmp/tmp.y3NkzRQda5/*'
```

### stderr

`cat: '/tmp/tmp.y3NkzRQda5/*': No such file or directory`

### stdout

```
160 data set(s) were found matching pattern.
160 data set(s) downloaded successfully to /tmp/tmp.y3NkzRQda5

total 14484
drwxrwxrwt. 1 root       root      115 May 25 14:21 .
dr-xr-xr-x. 1 root       root       40 May 25 14:19 ..
...
drwxr-xr-x. 2 1001600000 root    12288 May 25 14:21 tmp.y3nkzrqda5
drwx------. 2 1001600000 root        6 May 25 14:21 tmp.y3NkzRQda5
```

From this it is obvious that Zowe has donwloaded all files in `tmp.y3nkzrqda5` and not `tmp.y3NkzRQda5` as required.

**Comment by adam-wolfe** [comment]
I have been able to reproduce this under OpenSUSE with the current version of Zowe CLI. 

It seems like sequential data sets will be sent to the lowercase directory and PDSs and members end up in the mixed-case directory.
