### ISSUE TITLE
ZOWE SDK List.allMembers add add support for encoding

### ISSUE THREAD

**Issue by kraabrsg** [zowe/zowe-cli#1735]
**Is your feature or enhancement request related to a problem or limitation? Please describe**
When calling "list.allMembers" Mainframe Members containing "§" gets saved as "@" in the Explorer. ( desired codepage would be 1141)

**Describe your enhancement idea**
Add support for encoding when calling listMembers

**Describe alternatives you've considered**
Convert the hex forth and back in our VSCODE extension (converting it to the realname and back if further processing occurs) 

Converting hex strings to fix it. (Annoying).
**Provide any additional context**

**Comment by kraabrsg** [comment]
Will this be added in the future ?

**Comment by zFernand0** [comment]
Hey @kraabrsg,
We have evaluated the enhancement and we will consider it if we can get enough upvotes. 😋

**Comment by t1m0thyj** [comment]
I think this may require IBM to enhance z/OSMF so it supports encoding for the List DS Members endpoint, before we can support it in Zowe CLI and Zowe Explorer.

Currently the endpoint does not seem to support passing an encoding option: https://www.ibm.com/docs/en/zos/2.5.0?topic=interface-list-members-zos-data-set
