### ISSUE TITLE
User not prompted for keyPassphrase if in secure array of ssh profile

### ISSUE THREAD

**Issue by JillieBeanSim** [zowe/zowe-cli#1770]
**Describe the bug**

If user has ssh keys in place and includes the path to it as value for `privateKey` then adds the `keyPassphrase` to the ssh profile's secure array an error is returned `Cannot parse privateKey: Encrypted private OpenSSH key detected, but no passphrase given` but user wasn't prompted for the keyPassphrase.  If the tag `--keyPassphrase` is used with the command or the passphrase is stored under properties in plain text  the connection works.

**Expected and actual results**

User should be prompted for secure values, especially passwords/passphrases, if not already stored securely in keystore.

-->
**Describe your environment**

- Zowe CLI version installed (run command `zowe --version`): 7.17.0
- Installed plug-ins and their version numbers (run command `zowe plugins list --short`):
- Node.js and NPM versions installed (run `node --version`, `npm --version`): node v16.19.0; npm v9.7.2
- Environment variables in use:
- Operating system and version: macos
- Shell/terminal (bash, cmd, powershell, etc...): 
- Daemon mode enabled or disabled: disabled
- For more information, see Gathering information to troubleshoot Zowe CLI

**Additional context**

**Comment by zFernand0** [comment]
As part of this issue, we should:
- Make sure to prompt for every property in the secure arrays that are used by the command
- Prompt for key passphrase if its specified in the secure array and there is no value for it
- Make sure to test that no secure properties are stored in plain text when removed from the secure array and execute in a command that requires set property

**Comment by JillieBeanSim** [comment]
@awharn should this be reopened?  I see work done on cli side but this item is for prompting in VS Code.
