### ISSUE TITLE
Document that Cargo is prerequisite to build Zowe CLI

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/zowe-cli#1774]
Ever since the "zowex" folder was added for the Zowe CLI daemon, Cargo has been required to build it.
But building the daemon is optional for CLI contributors and not part of the `npm run build` script.

Now that we have added the Secrets SDK as package in this repo, Cargo is required for `npm run build` to work.
The reason is that we build Rust bindings to access the native OS APIs for secure credential storage.

Therefore, we should document in the readme that `cargo` as a prerequisite for building Zowe CLI from source.
It can be downloaded here: https://rustup.rs/

**Comment by traeok** [comment]
Initial research shows that the MSRV (Minimum Supported Rust Version) for the Secrets SDK is 1.70.0, which is also the matching Cargo version - we can mention that Cargo/Rust v1.70 is the minimum supported toolchain.
