### ISSUE TITLE
Add --name-only as an alias for --root in zowe config list command

### ISSUE THREAD

**Issue by gejohnston** [zowe/zowe-cli#1797]
The meaning of the --root option is unclear.

Vit Gottwald suggested that users will typically not understand what an option named --root will accomplish.

> There is something similar in `git`. When you do a `git diff` you get a complete diff. But you can pass `--name-only` to only get a list of files. It also works on `git log -p` and other git commands dealing with commits or diffs.

> That said, `zowe config list --locations --name-only` would sound like something easy to understand, especially for anyone who knows git. Would it be possible to add `--name-only` as an alias to `--root`?

**Describe alternatives you've considered**

**Provide any additional context**

**Comment by zFernand0** [comment]
Should we make this a quick v3 change?
I know it does not constitute a breaking change, but maybe we just replace it in V3 😋
