### ISSUE TITLE
Document v3 team config changes

### ISSUE THREAD

**Issue by adam-wolfe** [zowe/zowe-cli#1801]
If we are planning changes to the structure or content of team configs in v3, we should publish this information somewhere in this repository (maybe at https://github.com/zowe/zowe-cli/blob/master/docs/Using%20Team%20Configuration.md) so that extenders and other squads may review it.

**Comment by zFernand0** [comment]
May need to refresh some examples in zowe-docs
- https://docs.zowe.org/stable/user-guide/cli-using-team-configuration-team-leaders
- https://docs.zowe.org/stable/user-guide/cli-using-team-configuration-application-developers

Plus, may need to add some documentation in the repo.

**Comment by adam-wolfe** [comment]
No notable changes to team config planned for V3.
