### ISSUE TITLE
Syntax error for zowe tso issue command 

### ISSUE THREAD

**Issue by HardipinderS** [zowe/zowe-cli#1814]
Getting --cert --cert-key issue. 

I have tried a lot of times and still getting this error while running this command

zowe tso issue command "exec 'Zxxxx.SOURCE(somerexx)'" --ssm

and the error that I'm getting 

Syntax Error:
Invalid file path specified for option:
--cert-file 

You specified:
"https"

The file does not exist

Syntax Error:
Invalid file path specified for option:
--cert-key-file 

You specified:
" "

The file does not exist

Example:

 - Issue the TSO command "status" to display information about jobs for your user
 ID.:

      $ zowe zos-tso issue command "status"

Use "zowe tso issue command --help" to view command description, usage, and options.

The thing is this is the first time I have worked with zowe cli and this is my try to complete the IBMZXplorer series ReXX1 fundamentals https://ibmzxplore-static.s3.eu-gb.cloud-object-storage.appdomain.cloud/REXX1.pdf 
 
I'm stuck on step 7 and honestly need to get this to get my badge and then go for the hiring event and hopefully get a job. I have tried a lot of things and the last thing I can think of is opening the whole codebase and try to figure out where the command is running. 

**Expected and actual results**
basicallly connected to my account and showcasing the ReXX file saying greetings. Please have a look at the link and see Step 7, you will know what is expected.

**Describe your environment**
Windows 11, VS Code, powershell and command prompt

**Additional context**

**Comment by zFernand0** [comment]
Hey @HardipinderS 
Where you prompted for anything (account, hostname, credentials) when running the command:
- `zowe tso issue command "exec 'Zxxxxx.SOURCE(somerexx)'" --ssm`

If so, the step indicates that you may have an invalid configuration
```
If you receive requests for ‘account’, ‘hostname’, ‘userid’, or ‘password’, you almost certainly have
not set the default profiles correctly - go back a couple of steps and correct as needed.
```

---

The error you are getting seems to be either a quoting problem when providing a certificate, or an invalid option being used for providing a hostname.

**Comment by HardipinderS** [comment]
Hey @zFernand0 

Ya, I was hoping for the same tbh. But never got a prompt for accounts, hosts forget about user or passwords. Got fed up with windows and tried on my friend's mac, that is another problem. I tried on own kali system and finally got prompted for user but still gave the error. In the end I tried adding the tags from the beginning. Kind of like 

`zowe tso issue command "exec 'Zxxxxxx.SOURCE(somerexx)'" --ssm -u my_username --pw my_password`

still got the cert error. The last soln that finally worked for me was to ssh into zos and then use zowe. it is a hassle with the amount of flags I have to give every time I issue a command but it got me the certificate so, I'm not complaining. Just have to get the conference thing sorted out.

Sorry for over sharing but wanted you to have the full picture. 


My thought was that somewhere --cert and --cert-key are picking up "https" and " " because even if I try 

`zowe tso issue command "status"`

I get the same error. 

It is not even considering --ru on windows was the exact moment when I was stumped. I have very low knowledge with node packages otherwise would have tried to hack into your package to pinpoint the issue. Hope this helps, let me know if I can help.

**Comment by zFernand0** [comment]
Can you share you `zowe.config.json` file?
And better yet, can you share the output of `zowe config report-env`
https://docs.zowe.org/stable/web_help/index.html?p=zowe_config_report-env

**Comment by HardipinderS** [comment]
Hey @zFernand0  apologies on the delayed reply, I didn't get any notifications for this

zowe.config.json
`{
    "$schema": "./zowe.schema.json",
    "profiles": {
        "zosmf": {
            "type": "zosmf",
            "properties": {
                "port": 10443
            },
            "secure": []
        },
        "tso": {
            "type": "tso",
            "properties": {
                "account": "",
                "codePage": "1047",
                "logonProcedure": "IZUFPROC"
            },
            "secure": []
        },
        "ssh": {
            "type": "ssh",
            "properties": {
                "port": 22
            },
            "secure": []
        },
        "base": {
            "type": "base",
            "properties": {
                "host": "zxp.ibmz.ibm.com",
                "rejectUnauthorized": true
            },
            "secure": [
                "user",
                "password"
            ]
        }
    },
    "defaults": {
        "zosmf": "zosmf",
        "tso": "tso",
        "ssh": "ssh",
        "base": "base"
    },
    "autoStore": true
}`

For zowe config report-env

` zowe config report-env
______________________________________________
Zowe CLI version = 7.18.6
Node.js version = 18.18.0
Node Version Manager version = nvm failed to display any output.
Reason = 'nvm' is not recognized as an internal or external command,
operable program or batch file.
O.S. platform = win32
O.S. architecture = x64

O.S. PATH = C:\Program Files\PowerShell\7;C:\Program Files\Eclipse Adoptium\jdk-8.0.382.5-hotspot\bin;C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\bin;C:\Python311\Scripts\;C:\Python311\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\Python310\Scripts\;C:\Program Files\Python310\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\Git\cmd;C:\Program Files\kubectl;C:\Program Files\helm\windows-amd64;C:\Program Files\IBM\Cloud\bin;C:\Program Files\PuTTY\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\ProgramData\chocolatey\bin;C:\Program Files\Microsoft VS Code\bin;E:\Vagarant\bin;C:\Program Files\Docker\Docker\resources\bin;C:\Program Files\Amazon\AWSCLIV2\;E:\courses_csudh\terraform;E:\node\;C:\Program Files\PowerShell\7\;E:\python_3_10\Scripts\;E:\python_3_10\;C:\Users\HARDIPINDER\.cargo\bin;C:\Python27;C:\Python27\Lib\site-packages\;C:\Python27\Scripts\;C:\Program Files (x86)\Nmap;C:\Users\HARDIPINDER\AppData\Local\Microsoft\WindowsApps;C:\WINDOWS\system32\config\systemprofile\.pyenv\pyenv-win\bin;C:\WINDOWS\system32\config\systemprofile\.pyenv\pyenv-win\shims;C:\Users\HARDIPINDER\AppData\Local\Programs\MiKTeX\miktex\bin\x64\;C:\Users\HARDIPINDER\AppData\Roaming\npm

ZOWE_CLI_HOME = undefined
    Default = C:\Users\HARDIPINDER\.zowe
ZOWE_APP_LOG_LEVEL = undefined
ZOWE_IMPERATIVE_LOG_LEVEL = undefined
No other 'ZOWE_' variables have been set.


______________________________________________
NPM information:

    NPM version = 9.8.1
    Shell = C:\WINDOWS\system32\cmd.exe
    Global prefix = C:\Users\HARDIPINDER\AppData\Roaming\npm
        The directory above contains the Zowe Node.js command script.
    Global root node modules = C:\Users\HARDIPINDER\AppData\Roaming\npm\node_modules
    Global config = C:\Users\HARDIPINDER\AppData\Roaming\npm\etc\npmrc
    Local prefix = C:\Users\HARDIPINDER
    Local root node modules = C:\Users\HARDIPINDER\node_modules
    User config = C:\Users\HARDIPINDER\.npmrc

    node bin location = E:\node\node.exe
    cwd = C:\Users\HARDIPINDER
    HOME = C:\Users\HARDIPINDER


______________________________________________
Zowe CLI configuration information:

    Zowe daemon mode = off
    Zowe config type = V1 Profiles
    Available profiles:
        tso profiles:
            zxplore
        zosmf profiles:
            zxplore
            zxplore_jobs
            zxplore_uss

______________________________________________
Installed plugins:
______________________________________________

This information contains site-specific data. Redact anything required
by your organization before sending this information to outside companies.`

Let me know if I can give any other information.

**Comment by adam-wolfe** [comment]
@HardipinderS You may need to change `"rejectUnauthorized": true` to `false` in the base profile.
