### ISSUE TITLE
Automate migration of code changes from daily to beta to latest

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/zowe-cli#182]
The migration of changes from daily to beta to latest could be automated to reduce time spent on manual delivery processes.

Controller Tasks

- [ ] Create controller project that runs every 2 weeks
       Assigned: No one
       Status: Not Started
    - [ ] Beta code is moved to latest then master code is moved to beta
- [ ] Create version bump step
       Assigned: No one
       Status: Not Started
    - [ ] Bump version email sent out asking what to bump the master -> beta move to. (list the specific version of MAJOR/MINOR/Patch
    - [ ] Bump version of latest strips off any prerelease from migrated beta code.

Child of #135

**Comment by zFernand0** [comment]
daily and beta are no longer used
