### ISSUE TITLE
Still recommending v1 behavior in readme

### ISSUE THREAD

**Issue by ATorrise** [zowe/zowe-cli#1820]
**Describe the bug**
We are recommending v1 behavior in our typedoc that pulls from our readme https://docs.zowe.org/stable/typedoc/#contribution-guidelines 
![image](https://github.com/zowe/zowe-cli/assets/112635587/3fc9bfa6-3973-4291-8ecd-132e76b8f6d7)

**Expected and actual results**
Should instead recommend `zowe config init`

**Comment by zFernand0** [comment]
This is still a valid issue.

https://github.com/zowe/zowe-cli?tab=readme-ov-file#configuring-zowe-cli
https://github.com/zowe/zowe-cli/tree/master/packages/cli#configuring-zowe-cli
