### ISSUE TITLE
ZOWE VIEW DATA-SET do not display content of a dataset without the range parm

### ISSUE THREAD

**Issue by billpereira** [zowe/zowe-cli#1824]
**Describe the bug**

When issueing the zowe view data-set command without passing any range it is not displaying the content of a data-set

ubuntu@zxplore:~$ zowe files view data-set "zXP.PUBLIC.SAMPDATA"
ubuntu@zxplore:~$ zowe files view data-set "zXP.PUBLIC.SAMPDATA" --range 0-5
009935798840    ELIHU    POHLING    37-4701817    #0891F9    1G4PP5SK3D4225898
009962900385    HAYDON    SALLING    93-7303153    #26F7DA    JTDKN3DU0F0935083
009974021411    ALBERTINA    TARBATT    63-1877813    #BC23B6    1GYS4AEF7BR952759
009997007246    LORRIE    TICK    14-2891963    #A98EE8    5N1AR2MM6DC874906
009997226734 CONSTANCE    DUNRIGE    37-2768401    #A62190    WBAYE8C55ED509623

The command works with small datasets, so probably issue is related to the limit of data it is able to handle, but it do not give any feedback just do not display it.

**Expected and actual results**
This happened while trying the zowe cli with zxplore
1. Command issued: zowe files view data-set "zXP.PUBLIC.SAMPDATA"
2. Expected results: content of the sequential dataset
3. Actual results: nothing displayed

**Describe your environment**

- Zowe CLI version installed (run command `zowe --version`):
ubuntu@zxplore:~$ zowe --version
7.18.7
- Installed plug-ins and their version numbers (run command `zowe plugins list --short`):
ubuntu@zxplore:~$ zowe plugins list --short
No plugins have been installed into your CLI application.
- Node.js and NPM versions installed (run `node --version`, `npm --version`):
ubuntu@zxplore:~$ node --version && npm --version
v20.8.1
10.1.0
- Environment variables in use:

- Operating system and version:
ubuntu@zxplore:~$ env
SHELL=/bin/bash
PWD=/home/ubuntu
LOGNAME=ubuntu
XDG_SESSION_TYPE=tty
MOTD_SHOWN=pam
HOME=/home/ubuntu
LANG=C.UTF-8
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
SSH_CONNECTION=192.168.64.1 55319 192.168.64.60 22
LESSCLOSE=/usr/bin/lesspipe %s %s
XDG_SESSION_CLASS=user
TERM=xterm-256color
LESSOPEN=| /usr/bin/lesspipe %s
USER=ubuntu
SHLVL=1
XDG_SESSION_ID=15
XDG_RUNTIME_DIR=/run/user/1000
SSH_CLIENT=192.168.64.1 55319 22
XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop
PATH=/home/ubuntu/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
SSH_TTY=/dev/pts/1
_=/usr/bin/env

- Shell/terminal (bash, cmd, powershell, etc...):
bash

**Additional context**
Noticed the behavior while using a Ubuntu VM with ZXPLORE environment

**Comment by awharn** [comment]
Hello, we are looking into this issue. Can you please run `zowe config report-env` and respond with the output, with any site specific data removed?

**Comment by awharn** [comment]
This appears to be the same root cause as in #1805 and #1813

**Comment by KevinLoesch1** [comment]
This issue is corrected with version [7.18.9](https://github.com/zowe/zowe-cli/pull/1838).
