### ISSUE TITLE
Show strings instead of regexes for allowed values in CLI help

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/zowe-cli#1863]
> Do we want to show regexes like this in the CLI help output? I think users are more likely to be familiar with wildcards which are simpler to read (e.g., `apimlAuthenticationToken*`)
> 
> I'm just curious about this, not requesting a change - because I assume it would require enhancing Imperative to support displaying "allowed values" in a different format.

_Originally posted by @t1m0thyj in https://github.com/zowe/zowe-cli/pull/1734#discussion_r1279406406_

**Comment by zFernand0** [comment]
Now that imperative is in the same monorepo, would we consider this to be a good first issue?
The contributor may need to think a bit more than in most other good first issues, but it might be a good one to get someone introduced to the codebase 😋

**Comment by t1m0thyj** [comment]
The regexes introduced in https://github.com/zowe/imperative/pull/380 may result in undesired `^` and `$` in the output:

 --format | -f (string)

      Format of the displayed output.

      Default value: namevalue
      Allowed values: namevalue, namevaluecolor, csv, json


$ zowe ops show rule QA * --ops-p ops11restapi -f NAME

Syntax Error:
Invalid value specified for option:
--format (-f)

You specified:
NAME

The value must match one of the following regular expressions:
[ '^namevalue$', '^namevaluecolor$', '^csv$', '^json$' ].

**Comment by JTonda** [comment]
Notes for Implementation: To display strings if the plugin defined them as such, other wise display as regular expression.
