### ISSUE TITLE
`zowe auth login` examples are incorrect

### ISSUE THREAD

**Issue by adam-wolfe** [zowe/zowe-cli#1865]
**Describe the bug**
It appears that this issue is not specific to `zowe auth login`. In some instances the command group is excluded from the examples provided in help text for commands.

`zowe auth login --help-examples` shows invalid commands:

```
 EXAMPLES
 --------

   - Log in to an API ML instance to obtain or update the token
   stored in your base profile:

      $ zowe login apiml

   - Log in to an API ML instance to obtain a token without
   storing it in a profile:

      $ zowe login apiml --show-token
```

**Expected and actual results**

The examples should be changed to `zowe auth login apiml` and `zowe auth login apiml --show-token`.

**Describe your environment**

Zowe CLI version 7.16.4

**Additional context**

**Comment by zFernand0** [comment]
Making this a good first issue now that the imperative source has been migrated here 😋

**Comment by adam-wolfe** [comment]
Removing good first issue since this appears to be more complicated than initially thought.

**Comment by KevinLoesch1** [comment]
This issue is fixed by PR https://github.com/zowe/zowe-cli/pull/2064.
