### ISSUE TITLE
v3: Make the `ImperativeError.errorCode` property a `number`

### ISSUE THREAD

**Issue by zFernand0** [zowe/zowe-cli#1869]
Moving the `errorCode` from a string to a number in the `ImperativeError` class can bring several benefits. Firstly, using a number for error codes can help reduce the amount of memory used, as numbers take up less space than strings. Secondly, it can improve code efficiency by enabling faster comparisons. Additionally, using a number can also make it easier to integrate with other systems and programming languages, as numbers are a more universally recognized data type. Finally, it can improve the overall clarity of the code, as using numbers for error codes can make the code more concise and easier to read.

**Source:**
https://github.com/zowe/imperative/blob/30e580a4f539a338fc60420f9660749bafc3d131/packages/error/src/ImperativeError.ts#L89-L91

**Comment by adam-wolfe** [comment]
Consider revisiting when planning for V4.
