### ISSUE TITLE
v3: Deprecate `base` profiles in favor of `nesting` team profiles

### ISSUE THREAD

**Issue by zFernand0** [zowe/zowe-cli#1870]
The `base` profiles have been a standard feature in Zowe CLI configuration management for many years. However, they have some limitations in terms of flexibility and reusability. As a result, the nesting structure of "team profiles" has been introduced to address these limitations. By deprecating the `base` profiles and replacing them with the more flexible nesting structure, teams can now reuse profile properties much more easily. The nesting structure also provides a more modular approach to configuration management, enabling teams to create more granular configurations that better reflect their unique requirements. By embracing this new structure, organizations can improve their overall efficiency and reduce the time and effort required for configuration management.

**Comment by adam-wolfe** [comment]
If we decided to deprecate this in V3, is there a way that we could tell users with base profiles that base profiles are going away in V4 without being too annoying (for lack of a better word)? Or would it be adequate to just add a note in the documentation?

I.e., how would people learn that base profiles will not be supported in v4 (if that is what we decide to do)?

**Comment by zFernand0** [comment]
We could the deprecation information in multiple places:
1. On hover over the `properties` of a base profile
    ![image](https://github.com/zowe/zowe-cli/assets/37381190/b27c5212-2fc9-4763-a13f-6a4964033695)
2. As a comment right below the `"type": "base"` (if it doesn't exist) after a command is executed. May need to place this in a common location (`config.load`?) so that ZE can take advantage of this as well.
    ![image](https://github.com/zowe/zowe-cli/assets/37381190/2a8ae9f2-d262-4803-bfb6-0df6f14449be)
3. As a warning, whenever a `zowe config` command is issued

**Comment by adam-wolfe** [comment]
Remaining concerns:
- Some users feel that team config is already complicated and are not comfortable with nesting profiles. 
- What do we gain by removing base profiles, or what do we lose by keeping base profiles a part of team config?
