### ISSUE TITLE
v3: Enhance `RestClient` to support a key-value object of query parameters

### ISSUE THREAD

**Issue by zFernand0** [zowe/zowe-cli#1872]
**Benefits**
Passing an object for query parameters instead of making everyone construct the entire endpoint has several benefits:

1. Simplifies the construction of the endpoint: Constructing an entire endpoint can be cumbersome and error-prone, especially if the endpoint has many query parameters. By passing an object for query parameters, the user only needs to create a single object, which can be easily modified and extended.
2. Increases readability: Passing an object for query parameters can make the code more readable and self-explanatory. The name of the properties in the object can give a clear indication of what each parameter is for.
3. Facilitates extensibility: When new query parameters need to be added, it is much easier to add a new property to an existing object than to modify the entire endpoint. This makes the code more modular and facilitates extensibility.
4. Reduces the risk of errors: When constructing an entire endpoint, there is a higher risk of making mistakes, such as typos, missing or misplaced parameters, etc. By passing an object for query parameters, the risk of errors is reduced since the object is validated before being passed to the endpoint.
5. Simplifies testing: Testing an endpoint with many query parameters can be challenging, especially if each parameter has many possible values. By passing an object for query parameters, it is much easier to test the endpoint since the object can be easily modified and different test cases can be created by changing the values of the properties.

Here is a small python example that may help illustrate the idea.
```python
>>> requests.get(
...     'https://api.github.com/search/repositories',
...     params={'q': 'requests+language:python'}
... )
```
Source: https://realpython.com/lessons/query-string-parameters/

**Comment by traeok** [comment]
Something to consider before implementing this feature is the potential for a user to inject or pollute query parameters. See this presentation for examples of query pollution: https://owasp.org/www-pdf-archive/AppsecEU09_CarettoniDiPaola_v0.8.pdf

If we plan to implement this feature, we should sanitize the query parameters as much as possible to prevent users from chaining unwanted parameters.
