### ISSUE TITLE
Allow plugins to override the default credential manager

### ISSUE THREAD

**Issue by adam-wolfe** [zowe/zowe-cli#1878]
In order to support custom credential managers, Imperative will need to provide the following:
1. a "mapping" for each credential manager that specifies:
    - the name of the Zowe CLI plugin that provides the credential manager override functionality (e.g., "@org/cred-override")
    - the name of the VS Code extension that provides the credential manager override functionality (e.g., "org.cred-override")
    - a display name (e.g., "Org Credential Manager")
2. Add plugin post-install and pre-uninstall actions to automatically update imperative.json when a plugin that overrides the default credential manager is installed or removed.
3. Enhancement to Imperative warnings for invalid credential manager overrides. If Imperative detects an invalid credential manager override configuration, an error message shall be displayed that:
    - Tells the user that their credential management configuration is invalid
    - Lists all valid credential managers
    - Lists all currently installed credential manager plugins
4. Add "credentialManager" property to the options object passed to the ProfileInfo constructor.

**Comment by zFernand0** [comment]
Hey @adam-wolfe,
Should this Epic be closed?
