### ISSUE TITLE
Fix yargs parsing string arguments as numbers

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/zowe-cli#1881]
TL;DR Yargs parses string arguments as numbers if they look like numbers, which may be unexpected behavior for methods that expect string values.

> After seeing the context of zowe/zowe-cli#1883, I think I understand why 🙂 It seems like the default behavior of the yargs parser is to parse any options that look like numbers as numbers ([source](https://github.com/yargs/yargs-parser#parse-numbers)). This is undesirable behavior for jobid which should be parsed as a string regardless of whether a user enters it in the format `JOB1234` or just `1234`. Is this correct?
> 
> The solution in this PR will fix the issue for this command and any command handlers that call `toBeDefinedAndNonBlank`. But I wonder if there are any other places where we may hit a similar issue if command handlers call other methods that are expecting a string and receive a number instead.
>
> I am ok with approving this PR as-is if we believe it is the best solution. Alternatively, the behavior of yargs could be overridden (see [here](https://github.com/yargs/yargs/blob/main/docs/api.md#parserConfiguration)) to only parse options of type `number` as numbers and never parse items of type `string`. I don't know if we would consider that a bug fix, or a potentially risky breaking change?

_Originally posted by @t1m0thyj in https://github.com/zowe/imperative/pull/857#pullrequestreview-1049752029_

**Comment by t1m0thyj** [comment]
This issue can happen with the `--encoding` option as well, when the `IBM-` prefix is missing (e.g. `939` instead of `IBM-939`):
> When trying to run
> zowe jobs view spool-file-by-id [jobid] [spoolFileId]
> I get this error message:
> ```
> Unexpected Command Error:
> Please review the message and stack below.
> Contact the creator of handler:
> "/usr/local/node-v20.15.0-linux-x64/lib/node_modules/@zowe/cli/lib/zosjobs/view/spool-file-by-id/SpoolFileById.handler"
> Message:
> encoding.trim is not a function
> Stack:
> TypeError: encoding.trim is not a function
>     at GetJobs.<anonymous> (/usr/local/node-v20.15.0-linux-x64/lib/node_modules/@zowe/cli/node_modules/@zowe/zos-jobs-for-zowe-sdk/lib/GetJobs.js:405:38)
>     at Generator.next (<anonymous>)
>     at /usr/local/node-v20.15.0-linux-x64/lib/node_modules/@zowe/cli/node_modules/@zowe/zos-jobs-for-zowe-sdk/lib/GetJobs.js:18:71
>     at new Promise (<anonymous>)
>     at __awaiter (/usr/local/node-v20.15.0-linux-x64/lib/node_modules/@zowe/cli/node_modules/@zowe/zos-jobs-for-zowe-sdk/lib/GetJobs.js:14:12)
>     at GetJobs.getSpoolContentById (/usr/local/node-v20.15.0-linux-x64/lib/node_modules/@zowe/cli/node_modules/@zowe/zos-jobs-for-zowe-sdk/lib/GetJobs.js:398:16)
>     at SpoolFileByIdHandler.<anonymous> (/usr/local/node-v20.15.0-linux-x64/lib/node_modules/@zowe/cli/lib/zosjobs/view/spool-file-by-id/SpoolFileById.handler.js:41:67)
>     at Generator.next (<anonymous>)
>     at fulfilled (/usr/local/node-v20.15.0-linux-x64/lib/node_modules/@zowe/cli/lib/zosjobs/view/spool-file-by-id/SpoolFileById.handler.js:15:58)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> ```
> This is on a server. It works on my machine :grinning:
> How can I fix this?
> Node version: v20.15.0
> Zowe version: 7.28.2

https://openmainframeproject.slack.com/archives/CC8AALGN6/p1722846168243069

**Comment by t1m0thyj** [comment]
Tried setting the yargs parser configuration in `YargsConfigurer.ts`:
```javascript
yargs.parserConfiguration({
  "parse-numbers": false,
  "parse-positional-numbers": false
})
```

This prevents numbers from being parsed at all, even for args of type `number`. It seems that yargs is unable to smartly determine whether an argument should be parsed as a number or not, so we may need to add such logic ourselves.

**Comment by traeok** [comment]
`yargs` has a `coerce` function that allows you to specify the coercion function for specific keys. I haven't used yargs much but it might be useful for resolving the string/number parsing issue - we could programmatically filter the list of args based on type and then override `yargs` behavior to attempt parsing those args as numeric. But depending on how yargs is used within the CLI, we might not be able to do this without pre-fetching all the numeric arguments ahead of time.

**Comment by t1m0thyj** [comment]
I like the idea of the yargs `coerce` function - we should investigate this, although not sure if we'll be able to access the command definition from within the coercion function to determine what type of argument is being parsed. If not, we may need to parse the arguments ourselves in the Imperative `CommandProcessor`.
