### ISSUE TITLE
Regenerating schema after plugin install may not include all profile types

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/zowe-cli#1882]
If you have neither the Endevor or Endevor Bridge for Git plug-ins installed and then:
1. Install the Endevor Bridge for Git plug-in first. It will install but fail to validate because the Endevor plug-in is a prereq that is missing.
2. Install the Endevor plug-in second. It will install and update the schema to include new profile types (endevor and endevor-location).

Now you have no plug-in validation errors, but the endevor-bridge-for-git profile type is missing from your schema.
A workaround is to reinstall the Endevor Bridge for Git plug-in (or install any other plug-in that has profiles to trigger a schema update).

**Comment by zFernand0** [comment]
Related to:
- https://github.com/zowe/vscode-extension-for-zowe/issues/2508

**Comment by traeok** [comment]
I tested this issue again and it still occurs - however, I'm wondering if we should cancel the installation process for a plug-in if it depends on another CLI plug-in that's not installed?

**Comment by JTonda** [comment]
Spike needed: 3 pts
Implementation: Stretch/next PI
