### ISSUE TITLE
Remove deprecated/unstable Utils functions

### ISSUE THREAD

**Issue by zFernand0** [zowe/zowe-cli#1947]
In various places we use `isNullOrUndefined` and it has been deprecated for quite a while (Node v4.0.0)
Maybe we should go back and address some of these in the future?

Items deprecated that we still use:
- [ ] [`IsNullOrUndefined`](https://nodejs.org/api/util.html#util_util_isnullorundefined_object)

P.S. Feel free to update the list

**Comment by JTonda** [comment]
possibly add eslint-deprecation rule
