### ISSUE TITLE
CONTRIBUTING.md should mention sign-off on commits requirement

### ISSUE THREAD

**Issue by mheuzey** [zowe/zowe-cli#1950]
If a sign-off on all commits is a requirement for pull requests, this should be noted in CONTRIBUTING.md. This applies to zowe/zowe-cli as well.

A couple examples from other repositories:

- [Contribution Process](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#contribution-process)
- [Sign your work](https://github.com/opencontainers/distribution-spec/blob/master/CONTRIBUTING.md#sign-your-work)

**Comment by adam-wolfe** [comment]
Closing since Imperative is no longer in a separate repository.
