### ISSUE TITLE
Allow minor/patch versions for Zowe/imperative packages

### ISSUE THREAD

**Issue by roman-kupriyanov** [zowe/zowe-cli#1968]
**Is your feature or enhancement request related to a problem or limitation? Please describe**

Zowe/imperative package depends on numerous packages and all of them specified with a strict version selector (e.g. `yargs@15.3.1`). Since they are updating not frequently, it is always a chance to stuck with unsupported/deprecated versions of the transitive dependencies. Relaxing the rules may help extenders to update the transitive dependencies on their side, to possibly be up to date with some latest bug and vulnerability fixes.

**Describe your enhancement idea**

Allow the minor/patch versions of the dependencies to be specified in Zowe/imperative's `package.json` with `^` or at least `~` selectors (e.g. `yargs@^15.3.1` or `yargs@~15.3.1`).

**Describe alternatives you've considered**

Alternatively, we are using a resolution mechanism with `yarn`, but sometimes it is impossible to resolve the dependencies correctly.

**Provide any additional context**

None.

**Comment by JTonda** [comment]
Potential conformance criteria for v3 so that plug-ins are kept safe after versions constraints are loosened.

**Comment by adam-wolfe** [comment]
Resolved by https://github.com/zowe/zowe-cli/pull/1975. To be available in V3.
