### ISSUE TITLE
Add data set creation template for COBOL source codes and compiler listings

### ISSUE THREAD

**Issue by patricktiu** [zowe/zowe-cli#1972]
**Is your feature or enhancement request related to a problem or limitation? Please describe**

There are no data set templates to create PDSE data sets to hold a large number of COBOL source code, copybooks, and compiler listings.

**Describe your enhancement idea**
- Provide a default COBOL source code data set creation template that creates a PDSE type of data set to hold a large number of COBOL source codes and copybooks
- Provide a default compiler listing data set creation template that can store the COBOL compiler listings.

**Describe alternatives you've considered**

**Provide any additional context**

**Comment by adam-wolfe** [comment]
Thanks for your contribution, but as mentioned in the PR, we have decided to take a different approach.
