### ISSUE TITLE
Add a default template for creating a PDSE

### ISSUE THREAD

**Issue by adam-wolfe** [zowe/zowe-cli#1988]
**Is your feature or enhancement request related to a problem or limitation? Please describe**

When users enter the `zowe files create` command, the list of options do not mention PDSEs, though a user could use `zowe files create pds "DSNAME" --dst LIBRARY` and specify other options to create a PDSE. 

**Describe your enhancement idea**

Add a template for creating PDSEs, e.g., `zowe files create pdse`. 

**Describe alternatives you've considered**

The `--dst LIBRARY` option can create a PDSE, though users looking for the option may be confused by the current list of options.

**Provide any additional context**

**Comment by zFernand0** [comment]
I believe this is already implemented.
![image](https://github.com/zowe/zowe-cli/assets/37381190/288afecd-4b4b-4d05-830e-b6a395c471c4)
