### ISSUE TITLE
Incorrect output/results when issuing zowe zos-files compare on Windows using the --seqnum false option.

### ISSUE THREAD

**Issue by KevinLoesch1** [zowe/zowe-cli#1992]
When executing the **zowe zos-files compare** on Windows using the **--seqnum false**, erroneous data may be included in the output and could potentially give an incorrect compare result. 

![image](https://github.com/zowe/zowe-cli/assets/102045561/24aca5e1-7345-4025-aa5e-10499279e78a)

- Operating system and version: Windows

**Comment by adam-wolfe** [comment]
Resolved by #1993.
