### ISSUE TITLE
Allow persistent setting for --max-concurrent-requests

### ISSUE THREAD

**Issue by JTonda** [zowe/zowe-cli#20]
_From @ChrisBoehmCA on October 1, 2018 14:21_

The --max-concurrent-requests option on download all members introduced in (Add --max-concurrent-requests option to download all-members command) could have a persistent way to store the setting such as a profile field, especially because a similar option may be introduced on other commands. Or when (Imperative: Allow CLIs to be developed with profiles and command option precedence) is implemented, the user could set an environmental variable to control this setting

_Copied from original issue: gizafoundation/brightside#273_

**Comment by tucker01** [comment]
After imperative changes in zowe/imperative#34 and zowe/zowe-cli#18, you will be able to persist any option in a profile. However, you'll have to enter it manually in the YAML file (no set commands for arbitrary key/value pairs yet).

**Comment by MikeBauerCA** [comment]
Environment variables can be used to control this setting. Closing.
