### ISSUE TITLE
zowe auth login apiml creates a V1 profile

### ISSUE THREAD

**Issue by gejohnston** [zowe/zowe-cli#2005]
**Describe the bug**

When you have no V1 profiles or team-configuration, and you specify all options on a *'zowe auth login apiml'* command, the command will store the results in a V1 profile. Since V1 profiles will become inoperable in Zowe V3, the *'auth login'* command will be useless in this particular scenario.

**Expected and actual results**

- Ensure that you have no V1 profiles or team config file.
- Issue the following command
```
zowe auth login apiml --host YourHostName --port YourPort --user YourUser --password YourPassword --ru false
```
- When asked if you want properties stored on disk, answer 'y'.
- The properties are stored in a V1 profile.

The command should store the properties in a team configuration file.

**Describe your environment**

$ zowe --version
7.21.1

$ node --version
v20.10.0

Any OS, any command shell.

**Additional context**

**Comment by t1m0thyj** [comment]
When this issue is addressed, should restore tests that were temporarily disabled in https://github.com/zowe/zowe-cli/blob/e57fa089a10b44b66b5083a32642ed423123c3ce/packages/cli/__tests__/auth/__system__/cli.auth.login.apiml.system.test.ts

**Comment by KevinLoesch1** [comment]
I've reviewed the code and this is working as originally intended. If no team config is defined then it will revert back to v1 profile mode. Support for v1 profiles is being removed in Zowe v3. The behavior in v3 will be to always use team config.
