### ISSUE TITLE
Display the Zowe release as part of the CLI version output

### ISSUE THREAD

**Issue by gejohnston** [zowe/zowe-cli#2028]
**Is your feature or enhancement request related to a problem or limitation? Please describe**

We market Zowe to customers by the Zowe release number. The `zowe --version` command lists a correct version number for the CLI. However, that version does not provide the context of the Zowe release to which this version of the CLI belongs.

**Describe your enhancement idea**

Alter the output of the `zowe --version` command from:
```
zowe --version
8.0.0
```
to something like the following:
```
zowe --version
Zowe release: V3
CLI version: 8.0.0
```

**Describe alternatives you've considered**

We should also alter the response-format-json output to contain the original version property (to provide a degree of backward compatibility) and provide a new release property with the V3 value.

**Provide any additional context**

**Comment by zFernand0** [comment]
Should we also provide the minor level `v3.1` ?

I think we could given that we have to lock down the version that gets bundled.

If we decide to do this, there may be some caveats about the ongoing releases on NPM though 😋
