### ISSUE TITLE
Fix Medium and High Priority bugs in SonarCloud

### ISSUE THREAD

**Issue by balhar-jakub** [zowe/zowe-cli#2032]
As part of the OpenSSF Badge Best Practices, we agreed to fix the issues with medium and high priority found by static scans. 

There are a few open issues within the Sonar Cloud within Imperative. 
- https://sonarcloud.io/project/issues?resolved=false&types=BUG&id=zowe_imperative

**Comment by JTonda** [comment]
Imperative repo was archived.  We will move forward fixing the medium & high severity bugs in zowe-cli:  https://sonarcloud.io/project/issues?resolved=false&types=BUG&id=zowe_zowe-cli
