### ISSUE TITLE
RSE plugin error on submit job with wait for output option (--wfo)

### ISSUE THREAD

**Issue by Thibaut69** [zowe/zowe-cli#2042]
**Describe the bug**

The RSE CLI plugin return me an error while I submit a JCL with option --wfo (wait for output).

**Expected and actual results**

1. Command issued:   **zowe rse submit ds "MYPDS(MYJOB)" --wfo**
2. Expected results:     **same as zowe zos-jobs submit**
3. Actual results: 
**Command Error:
Error obtaining status for jobname "myjobname" jobid "myjobid".
Error Details: An unknown status "COMPLETED" was received.**

-->
**Describe your environment**
Windows 10, cmd.exe

- Zowe CLI version installed (run command `zowe --version`): **7.20.1**
- Installed plug-ins and their version numbers (run command `zowe plugins list --short`): 
**@ibm/rse-api-for-zowe-cli@3.3.3
@zowe/cics-for-zowe-cli@5.0.1**
- Node.js and NPM versions installed (run `node --version`, `npm --version`): **node v20.10.0 npm 10.2.3**
- Operating system and version: **Windows 10**
- Shell/terminal (bash, cmd, powershell, etc...): **cmd**
- Daemon mode enabled or disabled: disabled

**Comment by zFernand0** [comment]
Hey @Thibaut69,
Thank you for opening the issue.

I believe this issue is better suited for the [IBM Z Open Editor](https://github.com/IBM/zopeneditor-about). I have opened it on your behalf.
- https://github.com/IBM/zopeneditor-about/issues/385

Closing!
