### ISSUE TITLE
Add support for handling `*ALIAS` data sets

### ISSUE THREAD

**Issue by zFernand0** [zowe/zowe-cli#2052]
**Is your feature or enhancement request related to a problem or limitation? Please describe**

Today, the SDKs and the CLI have a hard time fully supporting alias datasets. This is partially due to a z/OSMF limitation on how aliases are handled over the `/zosfiles` REST APIs. 
See how the CLI and SDKs handle most CRUD operations: (_see details in https://github.com/zowe/vscode-extension-for-zowe/issues/2699#issuecomment-1942784425_)

**Describe your enhancement idea**

Since alias data sets have a volume of `*ALIAS`, we can attempt to handle creation and deletion a bit differently. Consider the following commands:
- `zowe files create [alias-data-set | alias] <aliasDS> <targetDS>`
  - For example: `zowe files create alias USERID.PUBLIC.CNTL.ALIAS USERID.PUBLIC.CNTL`
  - This will be submitting a job with a small IDCAMS statement
  ```jcl
     //TESTSTEP JOB (IZUACCT),'USERID',CLASS=A,REGION=0M
     //STEP1    EXEC   PGM=IDCAMS
     //SYSPRINT DD     SYSOUT=A
     //SYSIN    DD     *
          DEFINE ALIAS -
               (NAME(USERID.PUBLIC.CNTL.ALIAS) -
               RELATE(USERID.PUBLIC.CNTL) )
     /*

  ```
- `zowe files delete alias <aliasDS>`
  - We can add an the aliases  `alias-data-set | alias` to the `zowe files delete zfs` command,
  - OR we create an entire new command definition with the same underlying API

**Describe alternatives you've considered**

Recommend people to submit their own IDCAMS to create aliases, and use the `zowe files del zfs` to delete them

**Provide any additional context**

Please see the contents of the comment below for more details:
- https://github.com/zowe/vscode-extension-for-zowe/issues/2699#issuecomment-1942784425

**Comment by PowderPop** [comment]
I feel like Aliases used to work, but have recently stopped.  I occasionally create datasets with a prefix to allow sharing, but then create an Alias to follow more regular (userid based conventios) e.g. HLQ.PUBLIC.EXEC is aliased as HLQ.USERID.EXEC.  But when I try to open HLQ.USERID.EXEC it fails thinking it's binary!  It should lookup the alias and proceed to open the related (root) dataset.

**Comment by zFernand0** [comment]
Hey @PowderPop, 
Read and write operations on aliases should still work from the CLI.
The only thing that the CLI does not properly handle (unless users do this with their own JCL) is to create and delete aliases.
For more details on what's supported from the CLI and Zowe Explorer perspective, see the comment below:
- https://github.com/zowe/zowe-explorer-vscode/issues/2699#issuecomment-1942784425
