### ISSUE TITLE
V3: Fix Jobs list example definition

### ISSUE THREAD

**Issue by adam-wolfe** [zowe/zowe-cli#2065]
The referenced example description should be fixed (newline/string concatenation issue):

https://github.com/zowe/zowe-cli/blob/b0325adb2f4eea0a65e08be55b4926fa8eb9490a/packages/cli/src/zosjobs/list/jobs/Jobs.definition.ts#L78

Current state of the description:
![image](https://github.com/zowe/zowe-cli/assets/122040687/daff09e0-157b-44f0-889a-a6e77402031d)

**Comment by ATorrise** [comment]
closed with #2092
