### ISSUE TITLE
Enhancements to dir-to-uss for encoding, file tagging and ignoring files

### ISSUE THREAD

**Issue by matthewpwilson** [zowe/zowe-cli#207]
## Description
This is a proposal for enhancements to `dir-to-uss` (introduced by PR #193) for file encoding, tagging and ignoring to be configured using a metadata file. Also provide an option to delete the destination dir. 

## Motivation
When uploading files and directories to USS, it's necessary to have control over which files are uploaded in binary mode, and which are converted from ASCII to EBCDIC.
`zowe files upload dir-to-uss` provides the `--binary-files` and `-ascii-files` options, however these require each file to be named explicitly, which is tedious and time-consuming.

In addition, many USS utilities can take advantage of file tagging to autoconvert data (e.g. from ISO8859-1 to IBM-1047).  The file upload commands should set tags appropriately (equivalent to `chtag -tc UTF-8 filename`.) 

Also, it can be useful to ignore sets of files to avoid transferring them entirely. 

These issues are particularly relevant when upload applications from a workstation to USS. For example, a Node.js application may contain a large number of files, which are a mixture of binary and text content. It will also contain a `node_modules` directory which should not be transferred as it may contain platform specific code and will be created when npm install is run on z/OS.   Also, if the application was previously deployed to the same location, it's desirable to delete the old directory first to avoid merging. 

## Implementation
A `.zosattributes` file in the source directory can be used to control file conversion and tagging. The `--binary-files` and `--ascii-files` options would override what's specified in file. Also these options should be extended to match wildcards. 

Here's an example of the file:
```
# pattern          local-encoding     remote-encoding
**                 ISO8859-1          ISO8859-1
*.profile          ISO8859-1          EBCDIC
**/*.png           binary             binary
node_modules    -                                         
```

The format is inspired by `.gitignore` and `.gitattributes`. Each line specifies a pattern to match a set of files, with the same [rules as .gitignore](https://git-scm.com/docs/gitignore).
Local encoding specifies the character set of the file found on the local workstation.
Remote encoding specifies the desired character set of the file on USS. It appears the z/OSMF Files REST API doesn't let us specify the target encoding, so we'll get whatever EBCDIC codepage the system is configured for.    Therefore the remote encoding must either match the local encoding, or be EBCDIC. 
If remote encoding is EBCDIC, the file is transferred in text mode and converted.

Otherwise the file is transferred in binary mode.
The remote file is tagged with the remote encoding or as binary.
If '-' is specified for local-encoding, files matching the pattern are not transferred.

**Comment by matthewpwilson** [comment]
My team are wiling to contribute the code for this enhancement, but we'd like to get feedback on the design first.

**Comment by matthewpwilson** [comment]
@dkelosky @solsu01 Here's one of the enhancements we discussed contributing from the CICS team recently. Please let us know your thoughts.

**Comment by dkelosky** [comment]
It looks like @nurra01 already reviewed.  @tucker01 , @ChrisBoehmCA - do you have any comments?

**Comment by tucker01** [comment]
An attributes/control file sounds like it would be preferable to include with source in git/projects. 

If the attribute file allows wild-carding/masking/globs, it might be beneficial to allow the attributes file path to be explicitly specified on the command line. A project could have multiple files scattered throughout different source trees, build/bin directories, etc. and a single glob/wild-carded attributes file with extensions could be handy. 

In addition, I'm not sure how reliable this technique would be, but many file formats contain a "magic number" in the first few bytes that can be used to identify the type. Might be nice if I didn't have to think about the attributes at all. At the very least, for example, vscode can identify if a file appears to be binary (and avoids attempting to render it in the editor).

**Comment by dkelosky** [comment]
@tucker01 - are you talking about https://en.wikipedia.org/wiki/Byte_order_mark ?

**Comment by matthewpwilson** [comment]
> If the attribute file allows wild-carding/masking/globs, it might be beneficial to allow the attributes file path to be explicitly specified on the command line.

This is similar to .gitignore which supports a global file.  I think it would be still be useful to pick up a file from the current working directory without it having to be explicitly specified though. 

> but many file formats contain a "magic number" in the first few bytes that can be used to identify the type

I'm not sure it would sufficient to be able to detect binary/text files though. Even if we know it's a text file, we still need to know whether the user wants the file transferred as is, or converted to EBCDIC.

**Comment by matthewpwilson** [comment]
I previously said I'd implement a new `--delete-destination` option, however I don't think this is needed anymore as we now have `zowe files delete uss --recursive` which can be used for this.
