### ISSUE TITLE
Breaking Change in User/Password/Token Order of Precedence 

### ISSUE THREAD

**Issue by dkelosky** [zowe/zowe-cli#2109]
**Describe the bug**
This commit is technically a breaking change for Zowe CLI.  
https://github.com/zowe/imperative/commit/262f4fc84411e075e8e3af77ba2f8e663119be7d#diff-14634f70cce872732119d82fadcf7046800005fd18cca5ce7b7081672b9fdd2aL466

This changes the behavior in authentication order of precedence. 

**Expected and actual results**
Can the change be investigated as to provide an option to revert to the old behavior?  

**Describe your environment**

**Additional context**

**Comment by gejohnston** [comment]
Fixed as part of the pull request "Reinstate token precedence over password in AbstractRestClient" #2119
