### ISSUE TITLE
Zowe Config Auto-Init Instructions

### ISSUE THREAD

**Issue by dkelosky** [zowe/zowe-cli#2112]
**Describe the bug**

If I run `zowe config auto-init`, the defaults section of the config is generated like this:

```jsonc
    "defaults": {
        "endevor": "caendevorapi",
        // Multiple services were detected.
        // Uncomment one of the lines below to set a different default.
        // "zosmf": "ibmzosmf"
        // "zosmf": "zosmf",
        "base": "base",
    },
```

The comment states `//Uncomment one of the lines below to set a different default.`.  This is super picky, but when you uncomment, this line `// "zosmf": "ibmzosmf"` you get an error in the JSON because of the missing trailing comma. 

**Expected and actual results**

Since this is actually a JSONC file, can a trailing comma be added to this comment line? 

**Describe your environment**

**Additional context**

**Comment by adam-wolfe** [comment]
This issue was resolved in v7.25.2.
