### ISSUE TITLE
V3: Update deps behind latest major release

### ISSUE THREAD

**Issue by adam-wolfe** [zowe/zowe-cli#2120]
**Is your feature or enhancement request related to a problem or limitation? Please describe**
With the on-going community discussion around top-level dependency currency, the CLI squad should plan to review and either update out-of-date dependencies or provide a justification for keeping the version that is currently in use.

This would likely only apply to V3.

**Describe your enhancement idea**
We should review the following top-level dependencies that are behind the latest major version and update those that can be updated without introducing breaking changes for extenders. 

```[tasklist]
### Top-level dependencies that are behind the latest major release
- [ ] chalk
- [ ] find-up
- [ ] jest-diff
- [ ] stack-trace
- [ ] string-width
- [ ] strip-ansi
- [ ] wrap-ansi
```

**Describe alternatives you've considered**

**Provide any additional context**

**Comment by awharn** [comment]
All of these are using ESM in newer versions, which are incompatible with CommonJS.

**Comment by adam-wolfe** [comment]
Ah, OK. We can use that info for a TSC exception if necessary.
