### ISSUE TITLE
UX: Make the CLI easier to use :yum:

### ISSUE THREAD

**Issue by zFernand0** [zowe/zowe-cli#2124]
**Is your feature or enhancement request related to a problem or limitation? Please describe**

Users may find it hard to find the right syntax for the commands that they want to issue.
```shell
> zowe help # this fails because it doesn't have the `--` in front
> zowe files listds SYS1.PARMLIB # this fails because of the invalid `listds` key
> zowe files list ds SYS1.PARMLIB -ru false # this fails because `-ru` gets split into `-r true -u false` 
```

**Describe your enhancement idea**

After some discussion with a few team members, we could:
1. Provide an interactive help approach (like `manpage`) when running `zowe help`
2. Provide an interactive approach to the commands (with tab auto-completion)
3. Provide examples under each option in the help and web-help, see picture below

**Describe alternatives you've considered**

N/A

**Provide any additional context**

Hopefully this helps visualize the enhancement idea about adding examples closer to the options (instead of at the bottom)
![image](https://github.com/zowe/zowe-cli/assets/37381190/7ad314eb-5980-40d5-b0f4-89a24b0a7e1d)

**Comment by t1m0thyj** [comment]
```
$ zowe help
Command Error:
Command failed due to improper syntax
Unknown group: help
Did you mean: zftp?

Command entered: "help"
Use "zowe --help" to view groups, commands, and options.
```

Perhaps we could mention web help more prominently since it offers an easier way to browse example commands?
`Use "zowe --help" or "zowe --help-web" to view groups, commands and options."`
