### ISSUE TITLE
Enhancements to issuing shell command

### ISSUE THREAD

**Issue by ChrisPark89** [zowe/zowe-cli#214]
## Description
Issue a z/OS UNIX command and echo the output.

## Motivation
Users often have a need to run individual commands on z/OS USS, for example as part of deploying an application. They could of course have a separate SSH session, but this is not as convenient or easy to script as part of a workflow. Our primary use-case is running 'npm install' on the target system as part of deploying a Node.js application on z/OS. 

## Design
Use ssh connection or submit BPXBATCH jcl through z/OSMF.
There are two options for how the command would look like. 

### 1.  Default to SSH connection and provide a --jcl flag to submit via JCL

```zowe zos-uss|uss issue command "npm install"  [ --cwd /mypath/myapp ] [ --jcl ]```

**Command Options**
--cwd : current working directory where the command will be executed.
--jcl : execute command by submitting JCL instead of SSH.

**Examples**
`zowe zos-uss|uss issue command "npm install"`
`zowe zos-uss|uss issue command "npm install" --jcl`
`zowe zos-uss|uss issue command "npm install" --cwd "/home/user/myapp"`

### 2. Have two separate commands for SSH and JCL

```zowe zos-uss|uss issue jcl "npm install"  [ --cwd /mypath/myapp ]```
```zowe zos-uss|uss issue ssh "npm install"  [ --cwd /mypath/myapp ]```

**Command Options**
--cwd : current working directory where the command will be executed.

**Examples**
`zowe zos-uss|uss issue jcl "npm install"`
`zowe zos-uss|uss issue ssh "npm install"`
`zowe zos-uss|uss issue ssh "npm install" --cwd "/home/user/myapp"`

### SSH
Uses an interactive SSH connection to execute the command. The connection is closed after the command is executed.

- Zowe ssh profile
Uses a new Zowe profile for ssh to contain the host, port number, username, password, and privateKey.
- SSH connection
Users can use a public key and a private key pair instead of a username and a password to connect to the ssh server
  - username / password
  - Private/Public key pair 
  - The public key has to be stored on the server side. (USSHOME/.ssh/authorized_keys)
  - The user can specify the path of the secret key in the zowe ssh profile.
- A SSH server must be running on the host.
- Output from the command is displayed line by line, which would be useful for commands that have intermediate progress messages or long output, for example "npm install".
- Users can terminate the execution of the command part way through using a key sequence to send  SIGINT signal to the server (e.g. CTRL+C in UNIX)
- This is the default and preferred implementation.

### JCL
Submit JCL to execute command via BPXBATCH using z/OSMF Jobs API.
- Use zosmf profile
- Poll for completion of the job then download the spool files to get stdout/stderr. This means output from the command would arrive in one big chunk.
- Uses z/OSMF profile.
- This could be provided as a 'fallback' implementation for users who do not have an SSH server configured on z/OS.

### The return code 
The return code will be set to mirror the response from the command on USS.

**Comment by matthewpwilson** [comment]
@solsu01 @dkelosky @stevenhorsman Here's the other proposed contribution from the CICS team.

**Comment by ChrisPark89** [comment]
The CICS team is willing to contribute the code for this enhancement. We already tried and saw it working, but we'd like to get feedback on the design before we work on it further.

**Comment by dkelosky** [comment]
For the fallback implementation, it seems like the existing `zowe jobs submit` group could suffice.  Users could construct JCL to invoke BPXBATCH with whatever site specific JCL requirements needed (CLASS, MSGCLASS, Job name, account info, etc.).

Would you establish and drop an SSH connection for every command?

**Comment by dkelosky** [comment]
I think we've used [`oshell`](https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.3.0/com.ibm.zos.v2r3.bpxa500/useoshell.htm) as a fall back too.

**Comment by matthewpwilson** [comment]
`oshell` is probably a neater option, it avoids issues around jobcards and constructing JCL for each command.  It still does require the user to know about it though, which an application from a distributed background probably wouldn't.

**Comment by matthewpwilson** [comment]
> Would you establish and drop an SSH connection for every command?
I think we'd have to, as the SSH client is pure JavaScript so would go away when the `zowe` process terminated. 
The user could string together multiple commands with `;` in a single invocation of zowe if they wanted to.

**Comment by markcocker** [comment]
> The user could string together multiple commands with `;` in a single invocation of zowe if they wanted to.

If the command string is past directly the shell, I would expect the following to work:

`A ; B`  – Run A and then B, regardless of the success or failure of A
`A && B`  – Run B only if A succeeded
`A || B`  – Run B only if A failed

**Comment by ChrisBoehmCA** [comment]
If a fallback option such as `oshell` is implemented, I recommend separating it into another command. Having two sets of connection options for z/OSMF vs. SSH on one command would be a little confusing in my opinion.

**Comment by markcocker** [comment]
@ChrisBoehmCA I think this issue can be closed now the code has been merged.
