### ISSUE TITLE
Add `encoding` support to `zowe files search ds` command

### ISSUE THREAD

**Issue by awharn** [zowe/zowe-cli#2161]
**Is your feature or enhancement request related to a problem or limitation? Please describe**

There is no way to provide an encoding to the `zowe files search ds` command. If all of my data-sets and members are not in the standard IBM-1047 encoding, then I cannot search them.

**Describe your enhancement idea**

Pass on the `encoding` option in on `SearchOptions.GetOptions.encoding` in the CLI handler. The API should handle the rest.

**Describe alternatives you've considered**

**Provide any additional context**

**Comment by adam-wolfe** [comment]
Adding the `keep` label since this is something we will need to address.
