### ISSUE TITLE
replace yamljs dependency with maintained alternative 

### ISSUE THREAD

**Issue by recaph** [zowe/zowe-cli#2163]
Looks like yamljs author is not active in a long time. Please replace with popular library like https://github.com/nodeca/js-yaml or more maintained alternative like https://www.npmjs.com/package/yaml. There are multiple violations reported on this dependency in Blackduck.

https://github.com/zowe/zowe-cli/blob/a1bf9b2057dca998674a18bb9f316683ca172270/packages/imperative/package.json#L80

Comment on yaml.js repo from 2017:
``
Development of this library has slowed-down

I am still using yaml.js in production for some projects, it works fine in all the situations I needed it. That said, I am not actively working with raw javascript environments (mostly using [haxe](https://haxe.org/) now, if you are curious), thus I don't have much bandwidth to actively provide support to the posted issues asking for new features or bugfixes that don't affect my own use cases of the library. If this situation is an issue for you, I suggest you use [js-yaml](https://github.com/nodeca/js-yaml) which is a great and pretty feature-complete yaml parser and dumper for javascript. Pull Requests are still welcome, as long as they don't break the current set of unit tests!

Thanks 🙏
``

**Comment by gejohnston** [comment]
yamljs will be removed from the Zowe V3 release, when changes to create a different project-level base profile name are merged into our next branch.

Removal of yamljs from Zowe V2 is a separate consideration.

**Comment by recaph** [comment]
@gejohnston good to know... could you point me to the branch name where profile name changes are happening or link to the commit?

**Comment by gejohnston** [comment]
@recaph  The branch to change the generated base profile name is still local on my PC. Once unit tests pass, I will open a pull request for that change. I will post a link to that PR at that time.

**Comment by gejohnston** [comment]
@recaph Other priorities have postponed the testing of the project-level base profile name. So, I have not created a pull request yet. The branch containing those changes is:

    https://github.com/zowe/zowe-cli/tree/projectBase

**Comment by gejohnston** [comment]
Closed as part of Pull request "Generate different base profile names for global and project configs"  https://github.com/zowe/zowe-cli/pull/2194
