### ISSUE TITLE
A failure occurred during CICS bundle pushing

### ISSUE THREAD

**Issue by VAranouski** [zowe/zowe-cli#2190]
Hi team,
I'm trying to deploy a node.js application to a cics region and I've got the following error:

C:\Work\Mainframe API\Zowe-build\MainframeAPI-Express>zowe cics-deploy push bundle --name MFAPI --overwrite
Command Error:
A failure occurred during CICS bundle pushing.
 Reason = Failure occurred creating a zosmf session: cli_1.ZosmfSession.createBasicZosmfSession is not a function

Could you please advise.

[Slack Message](https://openmainframeproject.slack.com/archives/CC8AALGN6/p1720089344741259)

**Comment by zFernand0** [comment]
Hey @VAranouski,
This seems to be an issue with the CIC-deploy plug-in. 😋 

Please feel free to follow up on the following issue:
- https://github.com/IBM/zowe-cli-cics-deploy-plugin/issues/353
