### ISSUE TITLE
Untested and undocumented function: Upload.FileToUSSFile

### ISSUE THREAD

**Issue by JTonda** [zowe/zowe-cli#22]
_From @AHumanFromCA on September 28, 2018 18:40_

The following function is undocumented and not tested by unit tests.

https://github.com/zowe/zowe-cli/blob/99f596da314f7a7426e068ef70d4c57b52b5c9e5/packages/zosfiles/src/api/methods/upload/Upload.ts#L388-L449

_Copied from original issue: gizafoundation/brightside#269_

**Comment by MikeBauerCA** [comment]
This method has been documented and now has a unit test.
