### ISSUE TITLE
Events: Add `onPluginsInstalled` event to the list of `ZoweSharedEvents`

### ISSUE THREAD

**Issue by zFernand0** [zowe/zowe-cli#2202]
**Note:** Could be implemented with an `onSchemaUpdate` type of event on the global layer.

Motivation
---

Now that the event operator and processor have been created, it would be cool to emit a new event during the post-install script for plug-ins that indicates a new plug-in was installed, notifying other inquiring processes/applications of this change. 

Also within this script, we can incorporate a check for daemon mode (since the plug-in will be installed in the same process and we don't need to communicate to another process), and call for an automatic restart of the daemon if user is in daemon-mode that way the user won't have to remember (and possibly need to troubleshoot) to restart their daemon everytime they install a new plug-in.

_Originally posted by @ATorrise in https://github.com/zowe/zowe-cli/issues/1348#issuecomment-2223855396_

**Comment by JTonda** [comment]
Consider additional events like onPluginsChanged.
