### ISSUE TITLE
Enhance secureFields method to optionally return arg value, type, and name

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/zowe-cli#2206]
> For the VSCode user I want to offer a webview that shows the existing values and allow the user to over type.
>
> If we use secureFields and we are provided the argValue, argType and argName - that would suffice. 
> With that, we can present existing values and allow the user to overtype and then we can put the updates path values back into the vault in the same manner that zowe config secure —gc does currently.
> 
> I will be able to validate that an entered value is correct - if it is argType user I can ensure that it is a valid TSO format. If for example rejectunauthorized were a secure field and therefore presented by secureFields , I can ensure that the field is treated as a Boolean and validated as such.
> I don’t thing much more would be necessary beyond that.

_Originally posted by @davidkjackson54 in https://github.com/zowe/zowe-cli/issues/2185#issuecomment-2233271410_

**Comment by davidkjackson54** [comment]
Providing this additional information would also allow zowe config secure —gc to also then take advantage of the information.
Currently that zowe command does no validation of the entered user data so a user entering a TSO userid currently can enter any value even if invalid.  Also existing values are not presented to the user yet the user can skip over existing values without actually being aware of what that value is. This update would allow existing values to be presented and allow the user to change or skip at least aware of the current value.
