### ISSUE TITLE
Create USS file delete function in zosfiles Delete.ts

### ISSUE THREAD

**Issue by Colin-Stone** [zowe/zowe-cli#223]
Doesn't look like there is a hook to allow USS file deletion in brightside core. Offering to implement this.

**Comment by Colin-Stone** [comment]
Thanks Chris.. For info, I would also like to put together a USS based VSCode extension like the existing dataset one that's available. The delete function is the only piece not yet available.

**Comment by ChrisBoehmCA** [comment]
It'd be cool to have both an API function and a CLI command for this. Thanks for offering to help

**Comment by Colin-Stone** [comment]
Included in lts increment https://github.com/zowe/zowe-cli/pull/252
