### ISSUE TITLE
upload file via zosmf could fail

### ISSUE THREAD

**Issue by kraabrsg** [zowe/zowe-cli#2235]
**Describe the bug**

https://github.com/zowe/zowe-cli/discussions/2227

**Expected and actual results**

Please give feedback

**Describe your environment**

custom vscode extension (using javascript sdk) on WIN 10, communication with Mainframe via zosmf.

**Comment by adam-wolfe** [comment]
See https://github.com/zowe/zowe-cli/discussions/2227

**Comment by zFernand0** [comment]
Hey @kraabrsg,
not sure if you got a chance to look at Andrew's response here:
- https://github.com/zowe/zowe-cli/discussions/2227#discussioncomment-10400273
