### ISSUE TITLE
Option to display API URL for the Zowe command

### ISSUE THREAD

**Issue by EmlynWill** [zowe/zowe-cli#2248]
**Is your feature or enhancement request related to a problem or limitation? Please describe**

enhancement request

**Describe your enhancement idea**

For Zowe commands to have a "--show-URL" option to print out the URL without performing the command.
We have Zowe CLI on our desktops but not always on our servers (as we can't install there), so we use the REST API URL calls instead.
The URL calls aren't always easy to work out or find the right doc.

For example, command
zowe zos-tso issue command "time" --show-URL 
would respond with the API call URL including headers (assuming that you have your zowe config files and defaults set up correctly)

**Describe alternatives you've considered**

POSTMAN and the various docs for each product

**Provide any additional context**

**Comment by adam-wolfe** [comment]
May be able to add this option to ZosmfBaseHandler and communicate with individual SDKs (e.g., tso, files, jobs, etc.).
