### ISSUE TITLE
Enhancement Request: Allowing Multiple Users to Share only Plugins

### ISSUE THREAD

**Issue by dkelosky** [zowe/zowe-cli#225]

**Comment by dkelosky** [comment]
On a share system environment (like Linux), it would be nice to have a single installed instance of the Zowe CLI and plugins without having to share profiles.

**Comment by ChrisBoehmCA** [comment]
Comment on implementation by Peter Haumer on slack: 

> ... I have to switch to each user account now in the dockerfile to run the zowe plugin install for each and if new users get added at usage time then those new users has to do it also. There should be a zowe plugin install -g myplugin that installs them globally even if it would require a sudo to do that.

Personally I like the `install -g` suggestion! But I guess you'd need some rational default for where the global plugin directory would be and a way to configure it

**Comment by gejohnston** [comment]
The recent addition of the ZOWE_CLI_PLUGINS_DIR environment variable enables all users to point to a common location to find plugins. While that is a different implementation than what was suggested, ZOWE_CLI_PLUGINS_DIR should accomplish the intended goal.
