### ISSUE TITLE
ProfileInfo API fails to load base profile when Global User Config exists

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/zowe-cli#2273]
**Actual Behavior**
When a Global User Config w/o base profile is created to override some properties of a Global Config with base profile, then ZE doesn't load the base profile.

**Expected Behavior**
The ProfileInfo API should merge Global Config and Global User Config layers and load the base profile.

**Steps to Reproduce**
1. Create a Global Config that includes a base profile with host property.
2. Create a Global User Config that contains only a zosmf profile with port property.
3. Try to use the zosmf profile in Zowe Explorer and notice missing hostname errors.

**Additional Details**
https://github.com/zowe/zowe-cli/blob/606d579cdd5b070cdffd949926152b94b60dcd44/packages/imperative/src/config/src/ProfileInfo.ts#L559-L564

This is the relevant code. I think it could be fixed by adding the following between lines 561-562:
```typescript
            if (!realBaseProfileName && osLoc.user) {
                layerProperties = this.mLoadedConfig.findLayer(false, osLoc.global)?.properties;
                realBaseProfileName = layerProperties?.defaults.base;
            }
```

**Comment by zFernand0** [comment]
Related to [ZE e2e testing](https://github.com/zowe/zowe-explorer-vscode/blob/c1d216b24c38b645bc193f251501156bfb0ce136/packages/zowe-explorer/__tests__/__integration__/bdd/step_definitions/profiles/UpdateCredentials.steps.ts#L25-L27)

```typescript
When(/a user who has profile with (.*) auth in team config/, function (authType: string) {
    // TODO: We need to copy from Global Config until Imperative API is fixed
    // See https://github.com/zowe/zowe-cli/issues/2273
```
