### ISSUE TITLE
Add --attributes flag to zowe zos-files upload file-to-uss

### ISSUE THREAD

**Issue by Benjamin-Barda** [zowe/zowe-cli#2274]
* **Is your feature or enhancement request related to a problem or limitation? Please describe**

At the moment the only way to specify file encoding in file-to-uss command is to use the `--encoding` option.  

* **Describe your enhancement idea**

Similar to the behaviour of dir-to-uss it would be helpful the addition of the `--attributes`  option in file-to-uss command as well.

**Comment by JTonda** [comment]
We believe that zosattributes might help.  We will come back with proper recommendations soon.
