### ISSUE TITLE
`zowe zos-logs list logs` command assumes time is now from Client

### ISSUE THREAD

**Issue by awharn** [zowe/zowe-cli#2336]
**Describe the bug**

The command assumes the date and time from the client perspective. This can cause logs to be omitted, or the command to fail, if the server time differs from the client time (usually off by a few seconds to a minute). The API uses the server time for now if no time is passed. By default, we should not be passing the client time to the server, but let the server use its current time to get the most up to date logs (and prevent errors).

**Expected and actual results**

**Describe your environment**

**Additional context**

**Comment by t1m0thyj** [comment]
Reopening until the fix is backported to V2
