### ISSUE TITLE
Validation of data set names / uss files in create workflow commands produces malformatted error message

### ISSUE THREAD

**Issue by ChrisBoehmCA** [zowe/zowe-cli#234]
The error message contains [object Object] which at least should be fixed

```
$ zowe wf create wfds "namehere" --ds "**BADDATASET" --owner myid --sn system
Command Error:
Register workflow: Error: Expect Error: [object Object]Wrong format of USS path or DSNAME supplied.
```

I know in previous iterations of the CLI, we've done this kind of validation of parameters. However maintaining a regex for data set names can be error prone, especially since international characters like `£` can be used in some regions for data sets. It's easy to miss a valid data set name format. For these reasons, in other commands in core we've decided to not validate data set names or USS files. I would consider removing the validation and letting z/OSMF return an error message about the bad path/ DS name

@tucker01 
@muzikovam

**Comment by muzikovam** [comment]
Ok, you can assign me.

**Comment by ChrisBoehmCA** [comment]
Thanks! Hmm I tried to assign you but your name doesn't come up in the list, sorry

**Comment by abastyr** [comment]
I will take this :).
