### ISSUE TITLE
When using zowe zos-files upload file-to-uss it is failing to convert the line encodings from Windows-style to Unix style as we suspected

### ISSUE THREAD

**Issue by ChrisAtkinson1** [zowe/zowe-cli#235]
The original file has \n while the zowe uploaded has \r\n.

This means trying to run an uploaded bash script errors on USS.

Eg Upload this - 
#!/bin/bash
for ((i=1; i<=20; i=i+1))
do 
      echo $i
      echo "some data for the file" >> SleepFile.txt

done
      sleep 10s
echo FINISHED;

Running gives....

sleep.sh
./sleep.sh: line 2: syntax error near unexpected token `$'\r''
'/sleep.sh: line 2: `for ((i=1; i<=20; i=i+1))

**Comment by matthewpwilson** [comment]
According to the z/OSMF doc:
https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.1.0/com.ibm.zos.v2r1.izua700/IZUHPINFO_API_PutWriteUnixFile.htm
> Line Feed characters are left intact. 
However this is not very handy from a user point of view.  If uploading a file to z/OS using FTP in text mode, line terminators are converted.  So I think we'd either need to ask for this to be implement in z/OSMF or implemented the conversion in Zowe CLI
