### ISSUE TITLE
Update build agents to use node 10

### ISSUE THREAD

**Issue by JTonda** [zowe/zowe-cli#26]
_From @tucker01 on September 18, 2018 15:7_

We should update the build agent images to use node 10 (or ideally, devise a scheme to test under all supported releases of nodejs). 

_Copied from original issue: gizafoundation/brightside#255_

**Comment by lyzla01** [comment]
@tucker01 didn't you already addressed this issue?

**Comment by MikeBauerCA** [comment]
We now use GitHub actions and test under all supported releases of node and against Mac, Ubuntu, and Windows.
