### ISSUE TITLE
zowe CLI zosmf check status fails with self-signed certificate error

### ISSUE THREAD

**Issue by mdfmike** [zowe/zowe-cli#298]
After installing zowe and zowe CLI 1.0.1 I am unable to successfully execute zosmf check status.
I later tried a zospt zosmf check - which was successful.
I had previous success with this for all of my prior zowe CLI installs (0.9.3, 0.9.4, and 0.9.5).

**Command example:**
zowe zosmf check status --host zosmf-xxxxx.net --port 443 --user myuserid --password ********

**Command fails with:**

z/OSMF REST API Error:
http(s) request error event called
Error: self signed certificate in certificate chain
Error Details:
HTTP(S) client encountered an error. Request could not be initiated to host.
Review connection details (host, port) and ensure correctness.

Host:      zosmf-xxxxx.net
Port:      443
Base Path:
Resource:  /zosmf/info
Request:   GET
Headers:   [{"X-CSRF-ZOSMF-HEADER":true}]
Payload:   undefined

**Comment by ChrisBoehmCA** [comment]
Hi, 

The CSRF part is just a header that we append to our requests. The real error is that there is a self-signed certificate in the chain.  Not sure why this was working for you before. Maybe you had an existing profile with --ru false specified or maybe the certificate on your z/OSMF instance recently changed. You need to either use `--reject-unauthorized false` on the command or download the certificate from z/OSMF and add it to your accepted certificates via the environmental variable `NODE_EXTRA_CA_CERTS`

https://developer.ibm.com/node/2017/03/02/extend-nodes-built-ca-certificate-store-using-node_extra_ca_certs/
https://nodejs.org/api/cli.html#cli_node_extra_ca_certs_file

**Comment by mdfmike** [comment]
I’m sorry, but, I don’t understand what command you are referring to “You need to either use --reject-unauthorized false on the command”.
Version 1.0.1 is the first version where I had any problems connecting to z/OSMF via the CLI.  Other than re-running (just completed) the ./zowe-install.sh zowe server installation scripts – I’m not sure how to proceed any further with the certificate related commands/issues.

The most recent option I tried today was: 
1-	Manually run: scripts/apiml_cm.sh –action clean
2-	deleted the zowe 1.0.1 runtime directories
3-	rerun the zowe-install.sh script under UID 0
4-	apiml_cm.sh --action setup     - successful
5-	chown –R the zowe execution directories to IZUSVR:IZUADMIN
6-	restart ZOWESVR 
7-	Test CLI access to z/OSMF (failed – Error: self signed certificate in certificate chain) 
8-	Manually run: 
a.	scripts/apiml_cm.sh --action trust-zosmf --zosmf-keyring IZUKeyring.IZUDFLT --zosmf-userid IZUSVR

9-	recycle ZOWESVR
10-	Test CLI access to z/OSMF (failed – Error: self signed certificate in certificate chain) 

These are the certificate names – (masked)

Listing entries in the z/OSMF keyring (IZUKeyring.IZUDFLT):

Keystore type: JCERACFKS
Keystore provider: IBMJCE

Your keystore contains 6 entries

*Company Name* ROOT CA, Mar 25, 2019, trustedCertEntry,
Certificate fingerprint (SHA1): *********************************************
*Company Name* INTER CA, Mar 25, 2019, trustedCertEntry,
Certificate fingerprint (SHA1): *********************************************
zOSMFCA, Mar 25, 2019, trustedCertEntry,
Certificate fingerprint (SHA1): *********************************************
ENTRUST ROOT CA, Mar 25, 2019, trustedCertEntry,
Certificate fingerprint (SHA1): *********************************************
DefaultzOSMFCert.IZUDFLT, Mar 25, 2019, keyEntry,
Certificate fingerprint (SHA1): *********************************************
ENTRUST INTER CA, Mar 25, 2019, trustedCertEntry,
Certificate fingerprint (SHA1): *********************************************

**Comment by ChrisBoehmCA** [comment]
Sorry, I meant to use `--ru false` on the check status command, and when creating a profile with Zowe CLI.  If your z/OSMF certificates are self-signed, `--ru false` or adding the certificate  to the NODE_EXTRA_CA_CERTS variable are the only way to use the CLI successfully.   Maybe @dkelosky can advise on how to download and add  the certificate to your trusted certificates for Node.JS if you would prefer that to setting --ru false. 

The ZOWESVR is as far as I know not related to the CLI (the CLI only talks to z/OSMF)  so I'm afraid recycling it won't help.

**Comment by Alexandru-Dumitru** [comment]
Hello @mdfmike . Please know that almost all actions that you have described are related to API Mediation Layer and it's respective certificate management, which have nothing to do with the CLI part. When you issue the command `zowe zosmf check status`, you are communicating directly to your z/OSMF service and not with the API ML instance.

Could you try running `zowe zosmf check status --host zosmf-xxxxx.net --port 443 --user myuserid --password ******** --reject-unauthorized` and see if this helps? Also, how does your zosmf profile looks like? 

By issuing `zowe profiles list zosmf --sc` do you have `rejectUnauthorized:` set to  `false` or `true` ?

Thanks

**Comment by mdfmike** [comment]
For the initial CLI test - (before using profiles) I use the full zowe status command:
zowe zosmf check status --host ****.****.****.net --port **443 --user ******* --password *******.

*** I just added the "--ru false " option to the "zowe zosmf check status" command line and I obtained a successful connection. Thanks.  
I also added the following to my Windows Powershell environment variables as an interim solution:
set "ZOWE_OPT_REJECT_UNAUTHORIZED=FALSE"

**Comment by Alexandru-Dumitru** [comment]
> For the initial CLI test - (before using profiles) I use the full zowe status command:
> zowe zosmf check status --host ****.****.****.net --port **443 --user ******* --password *******.
> 
> *** I just added the "--ru false " option to the "zowe zosmf check status" command line and I obtained a successful connection. Thanks.
> I also added the following to my Windows Powershell environment variables as an interim solution:
> set "ZOWE_OPT_REJECT_UNAUTHORIZED=FALSE"

That's one way to go 👍 . I would suggest to update your profile, to keep this option as close as possible to the profile used to connect to z/OSMF. As an alternative, you have the option to overwrite all the connection options (i.e. profile fields) with in-line parameters. This means that if the profile is defined with `--ru true`, you can still pass just the `--ru false` with your commands, to overwrite it.

For a permanent solution, and to be able to keep the `--ru true`, you would have to set the proper certificate in your node environment, as Chris suggested. 

To update your profile, you can use: `zowe profiles update zosmf your_profile --ru false`

**Comment by Alexandru-Dumitru** [comment]
Closing this issue, as product works as designed.
