### ISSUE TITLE
Embed OWASP dependency scan into pipeline

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-cli#302]
As sub-issue of https://github.com/zowe/zowe-install-packaging/issues/406:

The changes should allow the pipeline:

- to run OWASP dependency scan per commit on every branch,
- to run OWASP dependency scan on daily basis if the repository is not actively developing.

**Comment by ChrisBoehmCA** [comment]
Hi, what is the purpose of this dependency checking? For security vulnerabilities? We do already use `npm audit` on Zowe CLI

**Comment by jackjia-ibm** [comment]
@ChrisBoehmCA yes it's about dependency checking.

@MarkAckert @nkocsis I believe `npm audit` is the backend tool GitHub vulnerability alerts scanning is using. Should this be sufficient from vulnerability scan point of view?

**Comment by jackjia-ibm** [comment]
Closing this issue with a side Jenkins job created to generate OWASP report. The main reason is the scanning is slow and if we add to each pipeline, it will slow down the build process a lot.
