### ISSUE TITLE
Invalid zos-files create command 'dsntype' option: PDS

### ISSUE THREAD

**Issue by dkelosky** [zowe/zowe-cli#309]
Here are data set name types I see in ISPF:
![image](https://user-images.githubusercontent.com/14940561/55486656-b0542400-55fa-11e9-9a07-161eed7276ef.png)

However, if I run a command with `--dst PDS` I get an error:
```
$ zowe files create pds "xxx.CAHCHECK.LOADLIB" --bs 32760 --db 20 --rf U --dst PDS --rl 15476 --sz 10CYL --vs xxxxxx
Command Error:
Invalid zos-files create command 'dsntype' option: PDS
```

Is this expected?

**Comment by dkelosky** [comment]
FYI, if you omit the `--dst PDS` the data set is created successfully as a PDS.

**Comment by ChrisBoehmCA** [comment]
related?: #52  #53

**Comment by MarkAckert** [comment]
No longer reproducible in Zowe v1 or Zowe v2, and PDS is listed as an option for dsntype in the CLI. Closing.
