### ISSUE TITLE
Should zos-file upload dtu ignore hidden files?

### ISSUE THREAD

**Issue by matthewpwilson** [zowe/zowe-cli#312]
`zowe zos-files upload dtu` `@latest` ignores hidden files (any filename beginning with a .). It looks this has always been the behaviour for non-recursive uploads, but recursive uploads previously did upload hidden files, this was changed by 81711d3.  
Now the behaviour is consistent, but I'm wondering if this is the intended behaviour? It might be useful to give the user the option.

My solution for #207 (PR coming soon) would allow the user to explicitly ignore any files by creating a metadata file similar to .gitignore.

**Comment by zFernand0** [comment]
Seems like this was addressed by adding the `.zosattributes` file 😋 
Closing. 
Please feel free to reopen with a comment if needed 😉

**Comment by t1m0thyj** [comment]
Reopening because the `.zosattributes` file does not allow you to override the default behavior of ignoring hidden files.

**Comment by adam-wolfe** [comment]
The user may include the --include-hidden flag to upload hidden files.
