### ISSUE TITLE
Directories with Space fail to upload using zos-files upload

### ISSUE THREAD

**Issue by ChrisAtkinson1** [zowe/zowe-cli#314]
If you have directory with spaces it fails with the following error.

Files with spaces now work.

$ zowe zos-files upload dir-to-uss "dir_spacetest" "//u//atkinc//jesttest//manual" --zosmf-p zosmf26
Unexpected Command Error:
Please review the message and stack below.
Contact the creator of handler:
"C:\Users\CHRISTOPHERAtkinson\Documents\ZoweStuff\ZOWEDEV\FILE2\zowe-cli\lib\zosfiles\src\cli\upload\dtu\DirToUSSDir.handler"
Message:
Request path contains unescaped characters
Stack:
TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters
at new ClientRequest (_http_client.js:115:13)
at Object.request (https.js:281:10)
at Promise (C:\Users\CHRISTOPHERAtkinson\Documents\ZoweStuff\ZOWEDEV\FILE2\zowe-cli\node_modules@zowe\imperative\lib\rest\src\client\AbstractRestClient.js:82:39)
at new Promise ()
at ZosmfRestClient.performRest (C:\Users\CHRISTOPHERAtkinson\Documents\ZoweStuff\ZOWEDEV\FILE2\zowe-cli\node_modules@zowe\imperative\lib\rest\src\client\AbstractRestClient.js:60:16)
at Function.putExpectString (C:\Users\CHRISTOPHERAtkinson\Documents\ZoweStuff\ZOWEDEV\FILE2\zowe-cli\node_modules@zowe\imperative\lib\rest\src\client\RestClient.js:208:34)
at Function. (C:\Users\CHRISTOPHERAtkinson\Documents\ZoweStuff\ZOWEDEV\FILE2\zowe-cli\node_modules@zowe\imperative\lib\rest\src\client\RestClient.js:66:37)
at Generator.next ()
at C:\Users\CHRISTOPHERAtkinson\Documents\ZoweStuff\ZOWEDEV\FILE2\zowe-cli\node_modules@zowe\imperative\lib\rest\src\client\RestClient.js:17:71
at new Promise ()

**Comment by Alexandru-Dumitru** [comment]
Hi @ChrisAtkinson1. Do you still have this issue? 

I ran some simple tests, but couldn't replicate it:

Windows directory structure:

```console
C:\Users\dumal01>dir /D/S "test dir"
 Volume in drive C has no label.
 Volume Serial Number is 22E4-E0CB

 Directory of C:\Users\dumal01\test dir

[.]          [..]         file.txt     [test dir 2]
               1 File(s)              9 bytes

 Directory of C:\Users\dumal01\test dir\test dir 2

[.]         [..]        file2.txt
               1 File(s)             10 bytes

     Total Files Listed:
               2 File(s)             19 bytes
               5 Dir(s)  361,523,245,056 bytes free
```

I was successful in running `zowe files upload dtu`, even with `-r` flag:

```console
C:\Users\dumal01>zowe files upload dtu "test dir" "/a/dumal01/space_test_dir"
success: true
from:    C:\Users\dumal01\test dir
to:      /a/dumal01/space_test_dir


Directory uploaded successfully.

C:\Users\dumal01>zowe files upload dtu "test dir" "/a/dumal01/space_test_dir" -r
success: true
from:    C:\Users\dumal01\test dir
to:      /a/dumal01/space_test_dir


Directory uploaded successfully.
```

Result on USS being:

```console
DUMAL01:/a/dumal01: >ls space_test_dir
file.txt
DUMAL01:/a/dumal01: >cat space_test_dir/file.txt
"file"
DUMAL01:/a/dumal01: >ls -r space_test_dir
test dir 2  file.txt
DUMAL01:/a/dumal01: >ls -R space_test_dir

space_test_dir:
file.txt    test dir 2

space_test_dir/test dir 2:
file2.txt
```

Even with the exact command format from your example, I was able to upload it. I included a file with spaces in the name, just for the sake of it:

```console
C:\Users\dumal01>dir /S/D dir_spacetest
 Volume in drive C has no label.
 Volume Serial Number is 22E4-E0CB

 Directory of C:\Users\dumal01\dir_spacetest

[.]                   [..]                  file with space.txt   file.txt
               2 File(s)             29 bytes

     Total Files Listed:
               2 File(s)             29 bytes
               2 Dir(s)  361,522,786,304 bytes free
```
Command:
```console
C:\Users\dumal01>zowe files upload dtu "dir_spacetest" "//a//dumal01//dir_spacetest"
success: true
from:    C:\Users\dumal01\dir_spacetest
to:      //a//dumal01//dir_spacetest


Directory uploaded successfully.
```
And, result on USS:
```console
DUMAL01:/a/dumal01: >ls -R dir_spacetest

dir_spacetest:
file with space.txt  file.txt
DUMAL01:/a/dumal01: >cat dir_spacetest/file\ with\ space.txt
"file with space"
DUMAL01:/a/dumal01: >
```

I am running on Zowe CLI version `4.1.0`, installed from the latest branch. 
Would be good to get more info regarding your use-case, so we can pin-point where the issue is.
Thanks.

**Comment by lukecolpo** [comment]
Hello @Alexandru-Dumitru , is this issue still actively in progress? If there are any tasks or tests surrounding it, i would love to help out.

**Comment by Alexandru-Dumitru** [comment]
Hi @lukecolpo. I have no updates on this one, as I was waiting for the reply. 
Thanks for offering to help out. 
Hi @ChrisAtkinson1, do you still have this issue? Could you provide an update, please?

If this is not valid anymore, we should close it.

**Comment by ChrisAtkinson1** [comment]
Yes I still see the issue

Command reports working - but the sub directory does not upload the directory with the spaces in it.

zowe zos-files upload dir-to-uss "dir_spacetest" "//u//atkinc//jesttest//manual" --zosmf-p zosmf2c -r
success: true
from:    C:\Users\CHRISTOPHERAtkinson\Documents\ZoweStuff\ZOWEDEV\test\test3\dir_spacetest
to:      //u//atkinc//jesttest//manual


Directory uploaded successfully.

[dir_spacetest.zip](https://github.com/zowe/zowe-cli/files/3350040/dir_spacetest.zip)

**Comment by ChrisAtkinson1** [comment]
This is working for me correctly now.
