### ISSUE TITLE
Zowe Webinar (do not assign) - Help text URL link broken from VS Code

### ISSUE THREAD

**Issue by solsu01** [zowe/zowe-cli#320]
zowe --h displays the help text for the CLI.

In this display, there's a line that says "for additional zowe CLI documentation, visit <URL>."

![image](https://user-images.githubusercontent.com/35504644/55801578-5e9d1500-5aa4-11e9-8b15-a7d0c3691474.png)

Clicking on this link from VS-code gives me a 404 error on the browser. My guess is that this is because of the period at the end of the line which is being interpreted by the VS Code terminal as part of the URL.

![image](https://user-images.githubusercontent.com/35504644/55801591-6361c900-5aa4-11e9-8051-100cb061484d.png)

**Comment by MikeBauerCA** [comment]
It is a valid issue and will be resolved by the PR I opened during the webinar (https://github.com/zowe/zowe-cli/pull/323).
