### ISSUE TITLE
Tab completion for Zowe-CLI

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/zowe-cli#324]
I would like tab completion to be implemented so that I can use the CLI more efficiently

**Comment by Alexandru-Dumitru** [comment]
Hi @MikeBauerCA . It seems that we already have this Enhancement proposal in our backlog. https://github.com/zowe/zowe-cli/issues/285. It was actually opened by you some time ago. Do we really need it 2 times ? just wondering.. Thanks

**Comment by MikeBauerCA** [comment]
You are absolutely correct. I had added this as part of a webinar and forgot to remove it. Thank you. Closing as a duplicate of #285.
