### ISSUE TITLE
`zowe files upload ftds` fails on `GET`.

### ISSUE THREAD

**Issue by dkelosky** [zowe/zowe-cli#325]
To write a file, it seems like [PUT](https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.3.0/com.ibm.zos.v2r3.izua700/IZUHPINFO_API_PutWriteDataSet.htm) should be all that's necessary.   

However, I have several data sets (the latter two are archived):
- `user.WORK.JCL`
- `user.WORK.JCL.OLD2`
- `user.WORK.JCL.BACKUP`

If I download a file:
`zowe files download ds "user.WORK.JCL(SOMEMEM)"`

Then try to upload:
`zowe files upload ftds somemem "user.WORK.JCL(SOMEMEM)"`

I get a failure on `GET`:
```
$ zowe files upload ftds somemem "user.work.jcl(cashcreq)"
Command Error:
z/OSMF REST API Error:
Rest API failure with HTTP(S) status 500
rc:       4
reason:   3
details:
  - DMS2987 DATA SET CATALOGED TO CA DISK PSEUDO-VOLUME ARCIVE

  - DMS2987 CA DISK HAS ARCHIVED user.WORK.JCL.OLD2

  -
  - DMS2971 DO YOU WANT TO RESTORE THE DATA SET? (Y/N)
category: 2
message:  ServletDispatcher failed - received TSO Prompt when expecting TsoServletResponse


Error Details:
HTTP(S) error status "500" received.
Review request details (resource, base path, credentials, payload) and ensure correctness.

Host:      tso1
Port:      443
Base Path:
Resource:  /zosmf/restfiles/ds?dslevel=user.work.jcl
Request:   GET
Headers:   [{"X-IBM-Attributes":"base"},{"X-IBM-Max-Items":"0"},{"X-CSRF-ZOSMF-HEADER":true}]
Payload:   undefined
```

It seems like some upfront checking is occurring that does a `GET` but causes problems for additional LLQs which are archived.

Is there a way to bypass the `GET`?  Is this necessary?

**Comment by ChrisBoehmCA** [comment]
There is currently no way to bypass the get. From looking at the code, it looks like this is done to determine whether the target data set is a PDS or PS. Looks like it's just to validate that you are not trying to upload multiple files to a non-pds data set. The check could potentially be removed.

**Comment by dkelosky** [comment]
Are the z/OSMF errors sufficient by themselves if you try to upload multiple files to a non-PDS?  If so, it seems this would be the desirable route.

**Comment by ChrisBoehmCA** [comment]
Looking closer at the code,  it's in a shared method that handles both multiple uploads to members and a single upload to a data set. The shared method uses the List.dataSet API to determine whether we are uploading to a PDS or not. Could be refactored to have two separate methods and then we wouldn't need to List data sets before uploading since we would know whether we wanted to upload just one file or multiple

**Comment by dkelosky** [comment]
Thanks - is it fair to categorize as a bug?  I'm not sure it was intended that for uploading to a data set: `HLQ.TARGET` that `HLQ.TARGET.*` must not be archived.

**Comment by dkelosky** [comment]
Thanks guys
