### ISSUE TITLE
CLIReadme.md is generated with formatting errors

### ISSUE THREAD

**Issue by markcocker** [zowe/zowe-cli#326]
The [CLIReadme.md](https://github.com/zowe/zowe-cli/blob/master/docs/CLIReadme.md) is generated and contains the following formatting errors:
 
1. Under the "Options" heading, when the text in bullet points flow to a new paragraph, they are not indented as they should be. There are many instances of this - for one example see the screen shot below the "For more information..." sentences should be indented to the same level as the preceding bullet.
2. Under the heading "Examples", the first bullet is not formatted as a bullet in markdown. There are many instances of this - for one example see red box in screen shot.

<img width="799" alt="Formatting errors" src="https://user-images.githubusercontent.com/15351000/55813994-a728f280-5ae5-11e9-8044-85a331876ef3.png">

3. When the script is used to generate a .md file for plugins in the "Examples" section the plugin name is missing. For example in https://github.com/IBM/zowe-cli-cics-deploy-plugin/blob/master/docs/CLIReadme.md#command-bundle says `zowe deploy bundle --name EXAMPLE --bundledir /u/example/bundleDir` when it should have the plugin name `zowe cics-deploy deploy bundle --name EXAMPLE --bundledir /u/example/bundleDir`

**Comment by ChrisBoehmCA** [comment]
Hi, 

I think we fixed the first two which should be deployed soon. For `#3`, I think the help generator is normally called after a plugin is initialized and the root command of the plugin (e.g. `cics`) is generated.

What I would do for `#3` is edit the definition you're passing to the help generator to include the root command for your plugin. Hopefully that would fix your example. Let me know

```
 {
   name: "yourpluginname",
   description: "yourplugindescription",
   type: "group",
   children:  theFullCommandTreeHere
}
```

**Comment by matthewpwilson** [comment]
> What I would do for `#3` is edit the definition you're passing to the help generator to include the root command for your plugin.

Thanks, this did the trick.

**Comment by markcocker** [comment]
@ChrisBoehmCA Thanks for the updates and suggestions.
