### ISSUE TITLE
Improve error message for missing positional argument

### ISSUE THREAD

**Issue by JTonda** [zowe/zowe-cli#34]
_From @MikeBauerCA on September 4, 2018 16:29_

**Canonical Story Form:**
As Michelle, I would like the "missing positional" syntax error messages to include a well-formed example that serves as a model, so that I can adjust my command to match the model.  

**Current Syntax Error Message:**
```
$ zowe zos-files create data-set-binary

Syntax Error:
Missing Positional Option:
dataSetName

Option Description:
The name of the data set that you want to create

Use "zowe zos-files create data-set-classic --help" to view command description, usage, and options.
```

**Proposed Format:**
```
$ zowe zos-files create data-set-binary

Syntax Error:
Missing Positional Argument:
dataSetName

Argument Description:
The name of the data set that you want to create

Example: 

- Create an empty binary partitioned data set (PDS) with
  default parameters:

      $ zowe zos-files create data-set-binary NEW.BINARY.DATASET 

Use "zowe zos-files create data-set-binary --help" to view command description, usage, and options.
```
_Copied from original issue: gizafoundation/brightside#228_

Depends on zowe/imperative#71

**Comment by JTonda** [comment]
_From @jelaplan on September 6, 2018 15:49_

Questions
1. Is there a story for prompting the user for the positional arguments?
2. The error message today refers to Missing Positional Option. Can we make it Missing Positional Argument to be consistent and accurate. Note that we discussed some months back about the user of the terms arguments, options, flags, and parameters. In general an argument is the value in a key value pair whereas option or parameter is the key. So, in this case, the language is not only inconsistent, it is wrong.

**Comment by tucker01** [comment]
Hi @jelaplan, 

1. Currently we do not have plans to include prompting for arguments. For reference, our reasoning is that prompting introduces a complication in non-interactive environments, which is a large part of the intent for zowe-cli. There are also talks of creating an interactive zowe-cli, where prompting, auto-completion, and other "human user" features would be suitable. Nothing set in stone.
2. Please review the "Proposed Format" above to ensure it aligns with your thinking. 

Thanks!

**Comment by AHumanFromCA** [comment]
So are we just displaying one example in the output or every example available on the command? 

If just one example, does each command now have to specify a missing positional example or should I use magic to determine which of the available examples to pull from?

**Comment by jelaplan** [comment]
I like it. Tying in examples plays to the favorite part of help by giving a concrete instructions. 

Can we remove the line breaks? Seems unnecessary and disjoint. 
Syntax Error:
Missing Positional Argument: dataSetName
Argument Description: The name of the data set that you want to create

@AHumanFromCA I'm ok with using the first example. @MikeBauerCA pointed out that some commands, such as CICS commands have a lot of examples because there are variations on use. We can go with the one example and see how it goes.

**Comment by AHumanFromCA** [comment]
@MikeBauerCA Just making sure since this will be a change in imperative. We are now saying that the first example listed for any command in any cli powered by imperative will be the default listed in missing positional help.

This leads me to this, what should I do to handle the possibility of a command with no examples? Omitting the example section and skipping straight to the help command would be the logical choice. Keep in mind we are talking about a generic cli that could choose to work in this way and not zowe-cli.

**Comment by AHumanFromCA** [comment]
Fixed the bug:

```
$ zd files upload ftds

Syntax Error:
Missing Positional Argument: inputfile
Argument Description: The local file that you want to upload to a data set

Syntax Error:
Missing Positional Argument: dataSetName
Argument Description: The name of the data set to which you want to upload the file

Example:

 - Upload file contents to a sequential data set named "ibmuser.ps":

      $ zowe zos-files upload file-to-data-set "file.txt" "ibmuser.ps"

Use "zowe files upload ftds --help" to view command description, usage, and options.
```

```
$ zd files create bin

Syntax Error:
Missing Positional Argument: dataSetName
Argument Description: The name of the data set that you want to create

Example:

 - Create an empty binary partitioned data set (PDS) with default parameters:

      $ zowe zos-files create data-set-binary NEW.BINARY.DATASET

Use "zowe files create bin --help" to view command description, usage, and options.
```

**Comment by tucker01** [comment]
Note that the majority of other syntax error messages include the line breaks: 
```
Syntax Error:
Missing Required Option:
--user (-u)

Option Description:
Mainframe (z/OSMF) user name, which can be the same as your TSO login.

Use "zowe tso stop as --help" to view command description, usage, and options.
```
If we're changing one, we might consider changing the rest for consistency.

**Comment by AHumanFromCA** [comment]
Should I hold off on testing until we get this settled down? I don't want to constantly be going in and fixing tests.

**Comment by tucker01** [comment]
If @jelaplan, mind taking a look at the above "missing required option" text?

**Comment by jelaplan** [comment]
I like it. I'm pro eliminating carriage returns for key value pairs.

**Comment by jelaplan** [comment]
Is there a way for me to get notifications when there are changes to the issue or when I'm mentioned via @jelaplan ?

**Comment by AHumanFromCA** [comment]
I think you can choose to watch the repo and it will send you emails.

**Comment by jelaplan** [comment]
I have the watch button clicked. I'm not sure what else I can do.
