### ISSUE TITLE
workflow list active-workflows --workflow-name command doesn't support workflow with space in it

### ISSUE THREAD

**Issue by rjmaomao** [zowe/zowe-cli#347]
Hi,

When using CLI to list workflows from a zosmf , the _zowe wf ls aw_ command can list all the active workflow. But when I use _--wn_ to list a specified workflow, it failed when there's space in the workflow name. I'm running on windows7 with node v8.12.0.  I didn't see explanation in help page states that workflow name which contains space is not supported to use --wn.  Am I missing anything here?  Thanks in advance!

_$ zowe wf ls aw  --host hostname --port xxxx --user xxxx --pass xxxx
workflowName                              workflowKey                          workflowDescription
**Test_Workflow_Demi**                        fbc9709c-8a2c-4a94-b494-e5fafa9be10a test
**daily monitor and email**                   042f25e2-3ab0-4b27-af60-35b145dd8bbf Implement daily monitor via workflow and send email notifications to operators_
                                       
_$ zowe wf ls aw --wn "**daily monitor and email**"   --host hostname --port xxxx --user xxxx --pass xxxx
Command Error:
List workflow(s) TypeError: Request path contains unescaped characters_

_$ zowe wf ls aw --wn "**Test_Workflow_Demi**"   --host hostname --port xxxx --user xxxx --pass xxxx
workflowName    workflowKey                          workflowDescription
Test_Workflow_Demi fbc9709c-8a2c-4a94-b494-e5fafa9be10a test_

**Comment by ChrisBoehmCA** [comment]
Looks like a bug. Probably we need to URL encode the workflow name when passing it to z/OSMF
