### ISSUE TITLE
Make @zowe/cli available in npmjs.org

### ISSUE THREAD

**Issue by zFernand0** [zowe/zowe-cli#349]
After migrating the scope of this component to `@zowe` (#264), we want to provide it via the public NPM registry.

Tasks:
- [x] Create CD pipeline to publish from the Artifactory registry to NPM
      Assigned: @zFernand0 
      Status: Completed

**Comment by matthewpwilson** [comment]
Which of the current npm tags will be available in the npmjs.org repo?

**Comment by zFernand0** [comment]
Hey @matthewpwilson,
The tags available are only `@daily` and `@latest` which constitute forward development of the Zowe CLI.
See [the package versions](https://www.npmjs.com/package/@zowe/cli?activeTab=versions) for more info.
https://www.npmjs.com/package/@zowe/cli?activeTab=versions

**Comment by zFernand0** [comment]
CD pipeline added to [version-controller](https://github.com/zowe/zowe-cli-version-controller/blob/master/scripts/deploy-zowe-cli-all.groovy)

**Comment by matthewpwilson** [comment]
@zFernand0 thanks. At what point would lts-incremental be made available on npmjs.org then?

**Comment by ChrisBoehmCA** [comment]
We're not allowed to publish the package with the name `@brightside/core` to public npm under Zowe. So lts-incremental on public npm will have to wait until the next major release of Zowe at which point the package name will change to `@zowe/cli` like it is in the `@latest` version
