### ISSUE TITLE
Improve error message for invalid action/object

### ISSUE THREAD

**Issue by JTonda** [zowe/zowe-cli#35]
_From @MikeBauerCA on September 4, 2018 16:26_

When a syntax error is encountered, offer a suggestion on the available actions and objects if applicable.

E.g. bright files create file
file is not a valid object to create. Available objects to create are data-set-binary, data-set-c, data-set-classic, data-set-partitioned, and data-set-sequential.
For example, issue "bright files create data-set-binary user.bin" to create an executable data set named user.bin.
Issue bright files create -h for additional help.

*Accept feature with PM when complete (both 227 and 225 in this sprint)
8 point story

Spike Research in Sprint 5 to determine what is possible to implement in Sprint 6.  1 point.

Research concluded that the above request is achievable within the current architecture. Estimate to complete is now at a 5 point story.

Remaining tasks:
- [ ] Implement coding changes
   Status: In Progress
   Assigned:  @PeteSwauger 

- [x] Update snapshots
   Status: Completed
   Assigned: @PeteSwauger 

- [x] Integration tests
   Status: Completed
   Assigned: @PeteSwauger 

- [ ] Code Review
   Status: Not Started
   Assigned: @ChrisBoehmCA 

- [x] UX Review
   Status: In Progress
   Review: @jelaplan 

_Copied from original issue: gizafoundation/brightside#227_

**Comment by JTonda** [comment]
_From @jelaplan on September 6, 2018 15:56_

We talked about having engineers explore whether it is possible to offer this summary to see if it is possible.

**Comment by JTonda** [comment]
_From @jelaplan on September 6, 2018 15:59_

In this situation where a user types bright files create file, the error they receive is
Command Error:
Unknown argument: file
Command failed due to improper syntax

1.	It refers to file as an argument. But, we refer to these as options. Note that we discussed some months back about the user of the terms arguments, options, flags, and parameters. In general an argument is the value in a key value pair whereas option or parameter is the key. So, in this case, the language is not only inconsistent, it is wrong.

**Comment by JTonda** [comment]
_From @jelaplan on September 6, 2018 16:1_

If I type the following, I'm given inaccurate erors
bright files delete file "xxxxx01.public.test03" -f
Command Error:
Unknown arguments: f, dsz, xxxxx01.public.test03
Command failed due to improper syntax
2.	It says that f is an unknown argument which is inaccurate. f is a valid option.

**Comment by JTonda** [comment]
_From @zFernand0 on September 10, 2018 15:3_

Hi @jelaplan,
I'm unable to see how the command will return `dsz` as an unknown argument if `file` was the first invalid argument.
Is `dsz` just a typo, or should we be worried that it's there?
```
bright files delete file "xxxxx01.public.test03" -f
Command Error:
Unknown arguments: f, dsz, xxxxx01.public.test03
Command failed due to improper syntax
```

Here is what I see.
```
$ bright files delete file "test.dataset" -f
Command Error:
Unknown arguments: f, file, test.dataset
Command failed due to improper syntax
Error Details:
Unknown arguments: f, file, test.dataset
```

**Comment by JTonda** [comment]
_From @ChrisBoehmCA on September 10, 2018 15:10_

Regarding your issue number 2 @jelaplan, I don't think we would be able to determine that `-f` is a valid option if you haven't specified a valid command. If you specify `delete file`, since that command doesn't exist and we can't determine which command you intended to specify, any other options you specify along with it will be invalid.

**Comment by PeteSwauger** [comment]
[ErrorMessageImprovement3.docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b97b898b22c920011a0f8c3/125516c66e82c728ace21e0d46cd86882c90aeac9cfabe44a174fd843b4931762401ad3f23c7af6aaf50740b0a0c0abe4b4a5a16aea8d829a2e269218a5d08e9d16d5d71923c18f9ba830da313f871d51bdaebe5c01982fa3737e682854e3b1a061c8bf95e32a89149cd4abb.docx)
