### ISSUE TITLE
Failed to create workflow due to system name not recognized 

### ISSUE THREAD

**Issue by rjmaomao** [zowe/zowe-cli#352]
Hi,

I failed when trying to use following CLI command to create a workflow. It reported system doesn't exist. But as can you see the screenshot attached below, the system name is correct.

Could you please help to take a look to see if there's anything wrong or if I missed anything? Thanks!

_rjmaomao@IBM502-PC0HJRUJ ~/test
$ bright zos-workflows create workflow-from-uss-file "monitorworkfow" --uss-file "/J80/tmp/huangxc/pmops.xml" --system-name "UTCPLXJ8.J80" --owner "ownerid" --assign-to-owner --overwrite --user xxx --pass xxxx --host hostname --port xxxx  --reject-unauthorized false
Command Error:
Creating z/OSMF workflow with uss file: /J80/tmp/huangxc/pmops.xml failed. More details:
Error: z/OSMF REST API Error:
Rest API failure with HTTP(S) status 400
messageText: IZUWF0015E: The request failed because system **"UTCPLXJ8.J80" does not exist**. Select a valid system.
messageID:   IZUWF0015E_

![sysname](https://user-images.githubusercontent.com/44960894/56859675-d46c1080-69c0-11e9-88fb-f58e4dc08cba.png)

**Comment by rjmaomao** [comment]
Looks like we should only use J80 instead of UTCPLXJ8.J80, which is sysplex name plus image name.

**Comment by ChrisBoehmCA** [comment]
Thanks for the info. Is your issue resolved now?

**Comment by muzikovam** [comment]
There will be also command that lists system names which you can use in workflow commands :) ( https://github.com/zowe/zowe-cli/pull/348 )

**Comment by rjmaomao** [comment]
The command to list the system names is very useful, hope we can try that command soon.  My current issue had been resolved. But I have a question. I know zosmf can manage two different sysplex at the same time. What if the image name is the same for different sysplex? Then it can't tell which image it should use by just the system name? May be UTCPLXJ8.J80 is better than J80?

**Comment by melvl01** [comment]
The system name is actually nickname of the system on which the workflow is to be created. So it is good practice to use the unique nickname that is specified for the system definition in the z/OSMF Systems task. 
From IBM doc - "The nickname is 1 - 40 characters long; the valid characters are alphanumeric characters (A-Z, a-z, and 0-9), hyphens (-), and special characters ($ _ # @). "  
Hope this help...

**Comment by ChrisBoehmCA** [comment]
It seems this issue has been resolved
