### ISSUE TITLE
Enhance infrastructure to allow for hidden aliases

### ISSUE THREAD

**Issue by JTonda** [zowe/zowe-cli#36]
_From @MikeBauerCA on September 4, 2018 16:8_

Introduce imperative infrastructure enhancement to support defining an alias with a "hidden" attribute. Aliases with the hidden attribute could be used to invoke commands but would not appear in help menus.

Use Case:
To adhere to UX standards of having at most 1 alias for a command group
To change command names while supporting old commands in a seamless way.

Acceptance Criteria:
Imperative users can define group aliases which do not appear in help menu but function as a valid command when invoked.

depends on issue 38 in AML (link)

_Copied from original issue: gizafoundation/brightside#226_

**Comment by MikeBauerCA** [comment]
Still a valid enhancement request. This would be beneficial for UX & command deprecation.
