### ISSUE TITLE
A command for creating USS files and directories

### ISSUE THREAD

**Issue by ChrisBoehmCA** [zowe/zowe-cli#368]
@Colin-Stone  already created the APIs required to expose this command. Just need to create the handler and associated tests

**Comment by cycaoecw** [comment]
@ChrisBoehmCA is that mean need adding command like `zowe files create uss`?

**Comment by dogboydog** [comment]
Yes (that's me). Maybe a separate command for creating a directory vs. creating a file. Open to others' opinions on that one. Might be nice to be able to create a directory recursively too similar to `mkdir -p`

**Comment by cycaoecw** [comment]
@dogboydog Thanks for your suggestion! I just finish the command but using option to identify creating directory or file. Let me separate it.
For the option `-p`, it seems the API not support it, is that mean we need to do that on command level?

**Comment by dogboydog** [comment]
Ah I see. It was just an idea, if the API doesn't support it it could always be added later as an enhancement on the CLI side
