### ISSUE TITLE
Improve syntax and usage diagram

### ISSUE THREAD

**Issue by JTonda** [zowe/zowe-cli#37]
_From @MikeBauerCA on September 4, 2018 15:15_

Canonical
As Michelle, I want clear diagram that shows how to complete my Brightside command so that I can quickly understand how to issue Brightside commands.

```
bright files create -h 

USAGE 
---- 
bright files  <group>

Where <group> is one of the following: 

GROUPS
---- 

create
....
```

```
bright files create -h 

USAGE 
---- 
bright files create <command>

Where <command> is one of the following: 

COMMANDS
---- 

data-set-classic
....
```

Description
Brightside is enhanced to provide a clear and complete syntax diagram

Acceptance Criteria
Syntax diagram is technically accurate... e.g. optional parameters are in []
*Accept feature with PM when complete (both 227 and 225 in this sprint)
5 point story

## Tasks

- [x] Update Imperative
       Assigned: @AHumanFromCA 
       Status: Complete
- [x] Confirm changes with @jelaplan
       Assigned: @AHumanFromCA 
       Status: Complete
- [x] Ensure tests pass in zowe-cli
       Assigned: @ChrisBoehmCA 
       Status: Complete

Depends on zowe/imperative#105

_Copied from original issue: gizafoundation/brightside#225_

**Comment by mheuzey** [comment]
I would like to see this as well. When I first looked at the Usage section in the help menu, I was confused why a required parameter was in [braces], which from my experience with help menus I believed to indicate optional parameters.

I don't think any of the commands have too complicated a Usage section, but for reference IEEE has published some detailed guidelines on the topic here: http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html
