### ISSUE TITLE
"npm install" results in E401

### ISSUE THREAD

**Issue by liuxh0** [zowe/zowe-cli#377]
Hi,

I'm very new to Zowe. After cloning the reposity, `npm install` fails with error 401:
```
npm WARN deprecated formatio@1.2.0: This package is unmaintained. Use @sinonjs/formatio instead
npm WARN deprecated samsam@1.3.0: This package has been deprecated in favour of @sinonjs/samsam
npm WARN deprecated text-encoding@0.6.4: no longer maintained
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm ERR! code E401
npm ERR! Unable to authenticate, need: Basic realm="Artifactory Realm"
```

I have already read `README`: I have performed `npm login`, `npm config set @zowe:registry https://api.bintray.com/npm/ca/brightside` and `npm install --registry https://registry.npmjs.org`. But I can't log in to gizaartifactory.jfrog.io because I don't have username/password.

Does somebody have an idea?

**Comment by ChrisBoehmCA** [comment]
Hi. 

Use npm install --registry https://registry.npmjs.org instead of npm install when working with the project to override the giza artifactory setting in .npmrc. Then you shouldn't need any authentication. We need to remove the npm config set @zowe:registry line though. You don't need to do that anymore as @zowe packages are hosted on public npm now.

**Comment by liuxh0** [comment]
Hi @ChrisBoehmCA ,

Thank you for your help. Actually I did `npm install --registry https://registry.npmjs.org` before. After I deleted lines in .npmrc in the project, it works.

Maybe they are not accessible from outside or without credential?
```
@brightside:registry=https://gizaartifactory.jfrog.io/gizaartifactory/api/npm/npm-release/
@zowe:registry=https://gizaartifactory.jfrog.io/gizaartifactory/api/npm/npm-release/
```

**Comment by CampaUTN** [comment]
If you are using a private registry, the .npmrc token may be expired

**Comment by hardikbhatt1-gep** [comment]
do below two commands
1) npm logout
2)vsts-npm-auth -config .npmrc
