### ISSUE TITLE
Zowe CLI Zowe REST plugin

### ISSUE THREAD

**Issue by phaumer** [zowe/zowe-cli#389]
The Zowe CLI not only provides a set of commands for for interacting with z/OS, but also a great SDK for client applications to utilize. The Zowe VS Code extension is an example of a client that uses the CLI and its abstractions to implements views for working with MVS, USS, and JES. The CLI codebase is organized around various abstraction such as profiles as well as separation of concerns (api/method and cli/<method> packages) that allow extension and alternative implementations.

The core CLI currently has only been implemented for utilizing z/OSMF as the REST API to access and interact with z/OS for files, uss, jobs etc. However, not all z/OS customer have z/OSMF configured or sometimes prefer using alternative commercial solutions provided by the different vendors in the past. Also the Zowe project has plans on providing z/OSMF independent REST APIs with the ZSS project. The assumption is that the ZSS implementation will utilize the same REST API specification that is currently published for zowe/data-sets.

To support these REST APIs as alternatives with the CLI we need a plugin that allows switching the CLI commands to a profile that uses these implementations instead of z/OSMF.

We propose to implement this incrementally by starting with a plugin that uses the current Zowe REST API publish in the Gateway and then once more ZSS functionality becomes available add support for it as well until it is ready to be used as the primary target for this plugin.

Test cases for the success of this work would allow user to create such profiles and use the current CLI files commands without any changes interchangeably as well as use other clients such as the VS Code extension without changes as well.

**Comment by ChrisBoehmCA** [comment]
Sounds like a cool idea to make Zowe CLI available to shops without z/OSMF. However it's not currently possible to influence/overwrite core commands via a plugin. You can only introduce new commands to the CLI. This is one of the design principles of the Imperative Framework upon which Zowe CLI is based. But it would definitely be possible to build a plugin that surfaces similar commands to a new command group like zss-files, zss-jobs etc. 
@tucker01

**Comment by dkelosky** [comment]
Hi @phaumer - I spoke with @tucker01 (one of the lead devs on the CLI effort) after our chat.  We'd like to understand your use case a bit better.  Some questions for our upcoming call:

Would you support z/OSMF, ZSS, FTP, and other back-ends from this new single plugin group?  

Would data be normalized depending on it's source?  

What common options would you support across groups (e.g. job correlator, sysplex routing options, etc )?

When would an end user want to change between using z/OSMF or ZSS as a backend?

Thanks,

**Comment by stevenhorsman** [comment]
[https://ibm.box.com/s/k81fkou00wwxxbgo389cfsorlsefjvsk](My dumb powerpoint summary as discussed on 17th July architecture call)

**Comment by 1000TurquoisePogs** [comment]
I'd be interested in helping with this abstraction, time permitting. I think we could have some shared libraries here that are just data shapers that don't care about whether the consumer is the UI or the CLI since they're both JS & network based. The hard parts would seem to be how to add the layer of indirection to existing frameworks without breaking backward compatibility, and a future-proof way of registering backend provider capabilities & shape of data.

**Comment by dkelosky** [comment]
Thanks for sharing the powerpoint @stevenhorsman. Can you share a few example scenarios of when you would switch backends (to capture the use case a little better)?  I'm curious if you would switch because of features provided by one over the other or for fail over (if one becomes unavailable) or for some other reason.

**Comment by stevenhorsman** [comment]
Hey Dan, I just tried to capture the second hand info that's been kicking around, so I'm not 100% sure, but from what I've heard seems to be combination of reasons:
1) The ability to support customers/platforms (longer term) where z/OSMF isn't available  for whatever reason
2) Fail over when things go wrong with 1 provider (BC have a scenario around this)
3) Support for new features - so far I think this is mostly hypothetical, but I've heard people suggest that z/OSMF might not be able to provide new features as quickly as the open source community can.

**Comment by tucker01** [comment]
@dkelosky, @phaumer, and others had a call last week regarding this proposal. @dkelosky, let's try to summarize the discussion when we get a chance and follow up on this thread.
