### ISSUE TITLE
Support search of content within the CLI help pages

### ISSUE THREAD

**Issue by jelaplan** [zowe/zowe-cli#406]
**Goal**: Support search of content within the online help.  Search is a common approach to address findability. We originally had a search command prior to the introduction of Imperative. 

**Overarching problem**: Improving the Findability and Discoverability of Capabilities and Functionality. We hear customers explain that they can't find what they are looking for. Also they don't understand the capabilities of the CLI so we need better ways to reveal that information.

* E.g. $ zowe search “list” 
* Support wildcards * and $ for single character
* Support options to narrow scope. For example
   * --description 
   * --group
   * --examples
   * --options
   * --segment => the segment name - i.e., thename of a group, action, object.

**Comment by gejohnston** [comment]
Since the time that this issue was created, the zowe --help-web command was created which displays the help in a browser. That help display is easier to navigate and supports search. Since the web help achieves the requested capability, I am closing this issue.
