### ISSUE TITLE
Publish CLI help pages to HTML like is done with Git

### ISSUE THREAD

**Issue by jelaplan** [zowe/zowe-cli#413]
**Goal**:  Publish CLI help pages to HTML like is done with Git. Once a help page is open in a browser, it is much easier to search and find things, cut and paste, etc. A terminal has limitations for reading, searching, and consuming documentation.  A web browser has many advantages, such as rich formatting, built in copy and paste, search, hyperlinks to related content, indexes, tables of content, bookmarking etc.  We know that users are more comfortable with a browser than a terminal and we've seen customers use the CLI reference PDF in place of or to augment the CLI help pages. 

**Overarching problem**: Improving the Findability and Discoverability of Capabilities and Functionality. We hear customers explain that they can't find what they are looking for. Also they don't understand the capabilities of the CLI so we need better ways to reveal that information.

**Comment by jelaplan** [comment]
I reviewed the [CLI help pages](https://zowe.github.io/docs-site/latest/web_help/index.html) this afternoon and found a few issues with the search
- If you search and then switch the view to list view or tree view, it doesn't repeat the search. I would expect it to switch and redo the search. 
- I can't search full text. This means that  common things that a user would search on don't appear, such as the term 'examples' and search results are very limited for terms like 'profile' which appear in many groups.  This is a weakness of the HTML version relative to the PDF version. While the HTML has a lot of advantages, full text search is an exception. It would be possible to show the full text in HTML as well to support full text searching.
- Search finds results at one level but not lower levels. For example, if you search on job, it finds the zos-jobs group but doesn't highlight that term in actions and objects. But f you search on  create , it finds that term in three actions. 

@timgerstel @tucker01 @RASakach @MikeBauerCA

**Comment by jelaplan** [comment]
This page seems closely related to other help pages that we see on Zowe and DocOps and we might add a linkages from the CLI Help web pages to those. There is a related issue to this idea. https://github.com/zowe/zowe-cli/issues/412

**Comment by jelaplan** [comment]
The styling on this page doesn't follow the [Zowe guildlines](https://zowe.github.io/docs-site/latest/contribute/guidelines-ui/colors.html#color-palette).  I think it would add credibility to apply styling that more closely matches the Zowe guidelines. 

@timgerstel @tucker01 @RASakach @MikeBauerCA @jayenzi

**Comment by tucker01** [comment]
@MikeBauerCA, for the option that's being added to commands, should these items be considered MVP?

For the third bullet (not highlighting the actions/commands). It seems that in some cases (for example if you search `cics`) it does work and it some cases it doesn't. This seems like a defect.

For the other bullets, what do we think about adding these as individual enhancement requests?

Thanks for the feedback!

**Comment by MikeBauerCA** [comment]
I agree with adding these requests as individual enhancement requests. I will take care of that and reference them in this issue. As far as MVP for the option that is being added to the commands, I would suggest we address the defects (bullets 1 & 3). We can update the styling of the help and consider offering a version of html help that allows for searching all the help content.

**Comment by MikeBauerCA** [comment]
See issues #469, #470, #471, and #472

**Comment by tjohnsonBCM** [comment]
Closing as web help is now a feature of Zowe CLI and individual enhancements have been created for all the requests.
