### ISSUE TITLE
Failing unit tests on Windows

### ISSUE THREAD

**Issue by tjohnsonBCM** [zowe/zowe-cli#417]
Several unit tests in the `dirToUSSDir/scenarios with .zosattributes file` suite are failing on Windows due to different path separator characters. Here is an example of the error resulting from one such failing test:
```
Error: expect(jest.fn()).toHaveBeenCalledWith(expected)
Expected mock function to have been called with:
  "test/path/uploadme"
as argument 1, but it was called with
  "test\\path\\ignoreme".
  "test/path/uploadme"
as argument 1, but it was called with
  "test\\path\\uploadme".
```
@matthewpwilson

**Comment by ChrisBoehmCA** [comment]
Sorry I missed this during review by the way

**Comment by matthewpwilson** [comment]
Thanks for spotting this, I'll sort it out
