### ISSUE TITLE
Add `zowe zos-files list fs` command

### ISSUE THREAD

**Issue by tjohnsonBCM** [zowe/zowe-cli#429]
Implement command for listing mounted z/OS file systems as documented [here](https://www.ibm.com/support/knowledgecenter/SSLTBW_2.1.0/com.ibm.zos.v2r1.izua700/IZUHPINFO_API_GetListUnixFilesystems.htm#IZUHPINFO_API_GetListUnixFilesystems).

Usage: `zowe zos-files list zfs [options]`

Options:
```
--path | -p (string)
  Specifies the path where the file system is mounted.
  This option and --fsname are mutually exclusive.
--fsname | -f (string)
  Specifies the name of the mounted file system.
  This option and --path are mutually exclusive.
--max-length | --max (number)
  Specifies the maximum number of items to return.
  Default value: 1000
```

Examples:
```
To list all mounted file systems:
  $ zowe zos-files list zfs

To list file systems mounted to a specific path:
  $ zowe zos-files list zfs -p /a/ibmuser

To list file systems mounted with a specific name:
  $ zowe zos-files list zfs -f MY.ZFS
```

**Comment by tucker01** [comment]
This was merged to master, but I'm going to add the tag to port to lts-incremental.

**Comment by tjohnsonBCM** [comment]
Before porting to lts-incremental, this command should be changed to `zowe zos-files list fs` (dropping the `z`), since it is not specific to ZFS and can list other types of Unix file systems.

The reasoning behind this change is that according to [the IBM docs for z/OSMF](https://www.ibm.com/support/knowledgecenter/SSLTBW_2.1.0/com.ibm.zos.v2r1.izua700/IZUHPINFO_API_RESTFILES.htm), the API endpoint for this command is `/zosmf/restfiles/mfs`. For commands that are specific to ZFS (`zos-files create/delete zfs`), the endpoint is `/zosmf/restfiles/mfs/zfs`.

**Comment by tucker01** [comment]
Also, looks like we need an API system test as well.

**Comment by cycaoecw** [comment]
@tucker01 should I change it to fs?

**Comment by tucker01** [comment]
It's our fault having the original issue `list zfs`... we didn't make the connection until we went to create other filesystem commands (mount/unmount/etc.) that you can do more than zfs. 

If you would like to make the changes that would be excellent. It's up to you.

**Comment by tjohnsonBCM** [comment]
Along with changing `zfs` to `fs`, `file-system` should be added as a long form of the command `fs`.

**Comment by cycaoecw** [comment]
@tucker01 yes, let me

**Comment by tucker01** [comment]
Awesome thanks!

**Comment by zFernand0** [comment]
wasn't this issue addressed by #496

**Comment by tucker01** [comment]
> @tucker01, was this issue addressed by #496?

It's in master, but I'm not sure what we want to do about porting to lts

**Comment by zFernand0** [comment]
> > @tucker01, was this issue addressed by #496?
> 
> It's in master, but I'm not sure what we want to do about porting to lts

@MikeBauerCA, Is there a date in which we would stop porting thing over to lts-incremental?
I assume it will be the same as the Zowe 2.0 date, is that correct?

**Comment by MikeBauerCA** [comment]
@zFernand0 it is a case by case basis depending on the complexity involved in porting the enhancement and the value of the enhancement to our `@lts-incremental` users. There is currently no date set for disallowing minor enhancements to the `@lts-incremental` branch. As you suggest, it will likely be similar to the Zowe 2.0 solution date, whenever that is announced.

**Comment by tjohnsonBCM** [comment]
Since the release of `@zowe-v1-lts`, now `@lts-incremental` only receives patches and no more enhancements.
