### ISSUE TITLE
Integrity checksum fails when installing @daily

### ISSUE THREAD

**Issue by matthewpwilson** [zowe/zowe-cli#439]
```
npm install @zowe/cli@daily
npm ERR! code EINTEGRITY
npm ERR! sha1-ePdG7XCiCnG9sZzl6J1yY6UGIVc= integrity checksum failed when using sha1: wanted sha1-ePdG7XCiCnG9sZzl6J1yY6UGIVc= but got sha512-YTLDfzJmNvcZKAw31GYu/8oACs2z9b8qu22aDhzsj3etdp8nzfZaGyZpL3ZM5ovQ0J0dKedwh6wwcbkehFusBg== sha1-Cuezk/bNbrxd4bl0isL7IidgwyY=. (33193 bytes)
```
[2019-06-05T11_37_56_549Z-debug.log](https://github.com/zowe/zowe-cli/files/3256968/2019-06-05T11_37_56_549Z-debug.log)

**Comment by zFernand0** [comment]
Hi @matthewpwilson, 
Sorry for the inconvenience and thank you for opening the issue.
We noticed a deployment problem and a fix is already in the works 😄

**Comment by zFernand0** [comment]
A new daily version should be published tonight. Please feel free to check it out and let us know.
Apologies for the wait.

**Comment by matthewpwilson** [comment]
Unfortunately I'm still seeing this. It seems to be complaining about `@zowe/perf-timing@1.0.3-alpha.201902201448`

**Comment by zFernand0** [comment]
@matthewpwilson,
There is a new version out there. 
https://www.npmjs.com/package/@zowe/cli/v/5.8.1-alpha.201906111217

Please let me know if you still see the problem.

**Comment by matthewpwilson** [comment]
Thanks @zFernand0, unfortunately it still fails for me in the same way

**Comment by zFernand0** [comment]
@matthewpwilson,
Could you please try again?
`@zowe/cli@5.8.1-alpha.201906131621` was recently published

**Comment by matthewpwilson** [comment]
Thanks very much @zFernand0, it's working now.
