### ISSUE TITLE
E041 error even npm login

### ISSUE THREAD

**Issue by cycaoecw** [zowe/zowe-cli#445]
Hi, I got E041 error when issue `npm install --registry https://registry.npmjs.org`.

> npm ERR! code E401
> npm ERR! Unable to authenticate, need: Basic realm="Artifactory Realm"
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/cy/.npm/_logs/2019-06-08T07_54_11_309Z-debug.log

Please note that i performed `npm login`

> CYdeMacBook-Pro:zowe-cli cy$ npm login
> Username: cyroom
> Password: 
> Email: (this IS public) 
> Logged in as cyroom on https://registry.npmjs.org/.

May i get any suggestion?

**Comment by zFernand0** [comment]
Given that the current access restrictions of Artifactory, the workaround is to remove the local npmrc file and the package-lock (if there is any) and then do a regular `npm install`.
We hope to remove these restrictions in the near future.
