### ISSUE TITLE
Should Brightside file operation handle £ (or other currency character)?

### ISSUE THREAD

**Issue by JTonda** [zowe/zowe-cli#46]
_From @lyzla01 on August 16, 2018 18:52_

Question originated in Uploading directory changes file name by @dkelosky 

Conversation Log:

From dkelosky:

@lyzla01 how does this transformation work with file names that contain a £? in a previous version of brightside, users could not upload to members containing £ because of some data set name validation. Is this regex a form of the same problem?

From lyzla01:

The transformation will not work with £. IBM doc does not mention any other currency character beside $ is valid in a node name of a data set. If we decided to support the special currency character, then we might have to revisit the logic and think if there are other currency characters that we missed.

From dkelosky:

We had an issue open about this from validate. They could not upload a local file with a £ symbol. That was on the old code, so there is no test for this scenario.

If my code page is set differently, can I upload to a data set containing £?:

![](https://user-images.githubusercontent.com/14940561/43013051-a16b664c-8c15-11e8-8cc0-3a8760e0b3f2.png)

From lyzla01:

Data set naming rules:

https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.1.0/com.ibm.zos.v2r1.ikjp100/ikjp10056.htm

The question that we needed to answer is how does other currency character other than $ is valid. Does this a special property of QWS? what happen when we view the dataset via zOSMF?

_Copied from original issue: gizafoundation/brightside#184_

**Comment by dkelosky** [comment]
I'll close this in place of future work that will be part of #632
