### ISSUE TITLE
L2 Diagnostics playbook for CLI and related extensions

### ISSUE THREAD

**Issue by Colin-Stone** [zowe/zowe-cli#463]
As a L2 support rep,
I want to have a playbook detailing how to diagnose problems on zowe CLI or an associated component so that I can save L3/dev and quickly respond to raised problems.

Collect collateral that provides troubleshooting information, Gotchas, support slack channels
MustGather information such as:
- Location of Log files
- List of installed plugins
- Version of CLI installed.

Anything else we think they would need

**Comment by Colin-Stone** [comment]
I have created a new branch on the docs repo called "trouble". In it I have started to restructure the existing troubleshooting section so that it contains links and descriptions of what someone would need to understand/appreciate before attempting to analyze an issue. Not necessarily L2 specific but a generic single place to find the MustGather information.

**Comment by tucker01** [comment]
I have some stuff I can add to this from our internal wikis. Should I dump it here or under the branch? (it's along the lines of "must/should gather")

**Comment by Colin-Stone** [comment]
Thanks @tucker01 that would be perfect. Dump it in "trouble" branch and ultimately we can bounce it around the team. 

I'm wrestling with how much could/should we add that is more L2 orientated?. Should that be separate and part of the so called "L2 playbook". Any thoughts?. 

For example, should we describe how to create a Git issue and the information that is required or even a template?. I think we should reasonably expect issues raised to describe how to recreate the problem in a state that had no customer/proprietary information.

**Comment by tucker01** [comment]
We should definitely create a template for github issues. We can include how to add the template to the L2 doc.

**Comment by tucker01** [comment]
I added a few items (https://github.com/zowe/docs-site/commit/3d5ffce4547b5fea408a4d1db31f2c87d0a4fcde). Hope I placed them in the correct spots. Please correct as needed 😄.

**Comment by Colin-Stone** [comment]
That's great, thanks Jason. I added the z/OS troubleshooting under troubleshoot like this..
![image](https://user-images.githubusercontent.com/30794003/60815505-b1639700-a18f-11e9-8be0-7c49124f52c7.png)
