### ISSUE TITLE
List command throws error when using an hlq with an archived file

### ISSUE THREAD

**Issue by JTonda** [zowe/zowe-cli#47]
_From @norjo14 on July 24, 2018 19:44_

When trying to use the list command "bright files list ds" in brightside, if the hlq specified includes a data set that has been archived it throws an error and will not list any of the data sets.  This is the error:

Command Error:
z/OSMF REST API Error:
Rest API failure with HTTP(S) status 500
rc:       4
reason:   3
details:
  - DMS2987 DATA SET CATALOGED TO CA DISK PSEUDO-VOLUME ARCIVE                                                          
  - DMS2987 CA DISK HAS ARCHIVED NORJO14.CA11.SPFLOG1.LIST                                                              
  -
  - DMS2971 DO YOU WANT TO RESTORE THE DATA SET? (Y/N)
category: 2
message:  ServletDispatcher failed - received TSO Prompt when expecting TsoServletResponse

Error Details:
Resource: /zosmf/restfiles/ds?dslevel=norjo14
Request: GET
Headers: [{"X-CSRF-ZOSMF-HEADER":true}]
Payload: undefined

_Copied from original issue: gizafoundation/brightside#162_

**Comment by JTonda** [comment]
_From @tucker01 on July 24, 2018 20:15_

Can you please update with the command response.

**Comment by JTonda** [comment]
_From @dogboydog on July 26, 2018 18:36_

Thanks for alerting us to this. We think this is an issue introduced with z/OSMF maintenance and we're in contact with IBM about it.

**Comment by JTonda** [comment]
_From @zFernand0 on August 21, 2018 17:53_

This issue has been addressed by IBM and there is a fix available.
http://www-01.ibm.com/support/docview.wss?uid=isg1PI95006

**Comment by JTonda** [comment]
_From @mheuzey on October 4, 2018 17:54_

This issue still occurs when using the -a option. I'm not sure whether the fix has been applied yet, but it sounds like it addresses an issue with a timeout occurring. The error here states that the system "received TSO Prompt when expecting TsoServletResponse," so I don't think it's timing out.

**Comment by ChrisBoehmCA** [comment]
Maybe someone could email Joey  Zhu at IBM about this issue... it causes some problems using the VS Code extension and using the `zowe files ls ds data.set -a` command

**Comment by dkelosky** [comment]
To tie this together for a somewhat related issue (although a refactor to fix it): #325

**Comment by gejohnston** [comment]
The root cause of this issue seems to be represented by https://github.com/zowe/vscode-extension-for-zowe/issues/235

Closing this issue with the intention of tracking the problem with #235.
