### ISSUE TITLE
Web help styling needs adjustments to follow Zowe guidelines

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/zowe-cli#471]
Review/resolve differences between the current web help styling and the [Zowe guidelines](https://zowe.github.io/docs-site/latest/contribute/guidelines-ui/colors.html#color-palette)

**Comment by zFernand0** [comment]
Updated URL: https://docs.zowe.org/stable/contribute/guidelines-ui/colors

**Comment by JTonda** [comment]
Action was taken to update web help to match guidelines in the past therefore we are closing this issue.  There has not been any mention of this since.
