### ISSUE TITLE
Allow 'grouping' of profiles across groups so that a single zowe profiles command can set the default profile across groups the 

### ISSUE THREAD

**Issue by PeteSwauger** [zowe/zowe-cli#477]
Add new 'profiles' command to set all group profile defaults to the profile assigned to the class specified.
      
            zowe profiles set-class SYS1
      
Option to assign a class to a profile:

     $ zowe profiles create zosmf-profile zosAPIML --host zosAPIML --port 2020 --user ibmuser --password myp4ss --reject-unauthorized false --base-path basePath --class SYS1
      
     $ zowe profiles create ims-profile ims123 --host zos123 --port 1490 --user ibmuser --pass myp4ss --plex PLEX1 --ich zos124 --icp 1491 --class --SYS1
      
     $ zowe profiles create cics-profile cics123 --host zos123 --port 1490 --user ibmuser --password myp4ss --class SYS1
      
Rules:
      
      If a group does not have a profile assigned to the class no change is made for that group.  
      
      In each group only allow one profile to be set to a specific class.  Allow changing a group profile assigned to a class to another profile in that group.
      
      Add 'list' command to display defined 'class' values.

      Add 'list' command to display profiles assigned to a specific 'class' with '--show-contents' option.
      
      Add 'list' command to list all groups' default profile with '--show-contents' option.

**Comment by dan-jast** [comment]
I think this is a great write up for what we are looking for around groupings of profiles. Having this ability would reduce the amount of work that goes into scripting with the Zowe CLI against multiple z/OS systems. If the need for this use case needs to be expanded upon, I can provide examples. 

The only thing I am a bit weary of is the wording we choose for these "groups". RACF has both "groups" and "classes", so I would want to make sure it is known these are not some type of RACF mechanism.

**Comment by PeteSwauger** [comment]
The term 'family' came to mind after I opened the issue.  I prefer 'family' to 'class'.

**Comment by dan-jast** [comment]
I like that better as well. Great work Pete!

**Comment by MarkAckert** [comment]
Zowe v2 team config has greatly changed the CLIs configuration process, and I believe it addresses this need. Zowe CLI v1 will not be enhanced, so the recommendation will be to migrate to Zowe v2 for profile groups with hierarchical property inheritance, which supports the notion of default (base) values. If you do not think Zowe v2 team config supports your need, please re-open the issue. Thank you!
