### ISSUE TITLE
Create.ts API `cmdType`

### ISSUE THREAD

**Issue by JTonda** [zowe/zowe-cli#48]
_From @dkelosky on July 20, 2018 17:50_

On this API, :
```
    public static async dataSet(session: AbstractSession,
                                cmdType: CreateDataSetTypeEnum,
                                dataSetName: string,
                                options?: Partial<ICreateDataSetOptions>): Promise<IZosFilesResponse> {
```

`cmdType` should probably be `dataSetType`:
![image](https://user-images.githubusercontent.com/14940561/43017140-1612b3da-8c23-11e8-882b-1af37a57b864.png)

However, if I include `CreateDataSetTypeEnum` and also `dsorg` in which appear to conflict (PARTITIONED type with `dsorg: "PS"`), it seems like my data set is not created.  How are `CreateDataSetType` and `dsorg` intended to be used?

_Copied from original issue: gizafoundation/brightside#158_

**Comment by JTonda** [comment]
_From @zFernand0 on August 23, 2018 15:59_

The `cmdType` is more used to determine which set of default options to use from Create.defaults.ts.

Maybe we should add more information to the JSDoc comment to specify that it's used to determine what defaults will be used.

**Comment by JTonda** [comment]
_From @zFernand0 on August 28, 2018 13:41_

@dkelosky, 
1. Do you think we should add more information to the JSDoc comment?
2. Based on the previous comment, should this really be tagged as a bug?

**Comment by MikeBauerCA** [comment]
Yes, we should add more info to the JSDoc comment. Removing bug label.
