### ISSUE TITLE
I got error "Cannot read property 'host' of undefined"

### ISSUE THREAD

**Issue by LiangXuehongBJ** [zowe/zowe-cli#481]
Hi, When I issue console command, I got error like this. 
[root@lxrh4 lib]# zowe console issue command "d iplinfo"
Command Preparation Failed:
Cannot read property 'host' of undefined
[root@lxrh4 lib]# zowe files list all-members stud01.jcl
Command Preparation Failed:
Cannot read property 'host' of undefined

I am using zowe 1.2.
And I am running zowe cli 1.2 on ZLinux with node as following:
[root@lxrh4 lib]# node -v
v8.16.0
[root@lxrh4 lib]# npm -v
6.4.1

And also I did not found any log under zowe/zowe/logs/zowe.log
Thanks.

**Comment by Alexandru-Dumitru** [comment]
Hello @LiangXuehongBJ. Do you have a valid zosmf profile created? Can you issue `zowe zosmf check status` successfully? 
Another option is to pass connection details directly on the command line, like `--user xxx`. `--pass xxx`, `--host xxx`, `--port xxx`.

**Comment by LiangXuehongBJ** [comment]
> Hello @LiangXuehongBJ. Do you have a valid zosmf profile created? Can you issue `zowe zosmf check status` successfully?
> Another option is to pass connection details directly on the command line, like `--user xxx`. `--pass xxx`, `--host xxx`, `--port xxx`.

Hi I found only root user will get this error. 
Regular user works fine.

**Comment by Alexandru-Dumitru** [comment]
The profiles are read from the users' home directory. This means that you created the profile while logged in as a normal user. Do you have any profile defined in `/root/.zowe/profiles/zosmf` * ? If not, try to run `zowe profiles create zosmf` while connected as root, and see if this solves the issue.

\* I assume root's home is `/root`.

**Comment by LiangXuehongBJ** [comment]
> The profiles are read from the users' home directory. This means that you created the profile while logged in as a normal user. Do you have any profile defined in `/root/.zowe/profiles/zosmf` * ? If not, try to run `zowe profiles create zosmf` while connected as root, and see if this solves the issue.
> 
> * I assume root's home is `/root`.

First  I create zosmf profile as root and run zowe cli the command  I mentioned before as root. it got error.
But I run “zowe zosmf check status”, it works fine. 

Then I create zomsf profile as regular user (just use useradd to add a user) and run zowe cli. There is no that error for all commands.

**Comment by zFernand0** [comment]
@LiangXuehongBJ is this still an issue ?

**Comment by XuehongBJLiang** [comment]
Let's close this issue.
