### ISSUE TITLE
Encoding: CLI Error for zos-tso command group when account contains '#'

### ISSUE THREAD

**Issue by MarkAckert** [zowe/zowe-cli#485]
When trying to issue a zos-tso command with an account that contains the character `#`, the CLI command fails and an opaque error message is returned.  When issuing the command with `%23` instead of `#` it succeeds.

CLI command and output:
```
 zowe --version
5.9.1

zowe zos-tso issue command "NETSTAT CONN (PORT <SOME_PORT>" --user <user> --pass <password> --host <LPAR_HOST> --port <zosmf_port> --account ACCT#
Command Error:
Expect Error: [object Object]No servlet key was supplied.
```

z/OSMF log:
```
Ýtx00000000000135D5:<user>@<LPAR> (POST) /zosmf/tsoApp/tso?acct=ACCT¨   
2019-07-16T19:04:28.681Z!001C0F34!com.ibm.zoszmf.util.tso.session.TsoController!
handleError(uiResponse, requestLocale, userName, tsoASID, ex)                   
SEVERE: userName: <USER>; tsoASID:0; Exception:IZUG1102E: The TSO/E address space was not started because the following TSO/E parameters or values are missing or have incorrect syntax: proc, chset, cpage, rows, cols. Specify any missing parameters or values, and correct any syntax errors.                              
```

Working command (output omitted):
`zowe zos-tso issue command "NETSTAT CONN (PORT <SOME_PORT>" --user <user> --pass <password> --host <LPAR_HOST> --port <zosmf_port> --account ACCT%23`

**Comment by ChrisBoehmCA** [comment]
Looks like you gotta  `encodeURIComponent` the account number (and maybe other query parameters)

**Comment by MatthewB19** [comment]
Has this already been fixed by any chance? 
I couldn't replicate the issue on either version 5.15.0 or version 2.31.1.
I took a quick look at the commit history, but this doesn't seem to have been specifically addressed.

**Comment by tjohnsonBCM** [comment]
@MarkAckert Could you check if you still experience this issue? We tested this with the lts-incremental and master versions of Zowe, and the command worked with `ACCT#`.
