### ISSUE TITLE
z/OSMF REST API Error: ssl3 :wrong version number

### ISSUE THREAD

**Issue by UHaider** [zowe/zowe-cli#486]
I am on Windows 7 64 bit using npm version 6.10.1 and node version is v10.13.0.
I installed zowe-cli (2.29.3) using online method.  When I issue the following commands

- zowe zosmf check status --zosmf-profile omptest
- zowe zosmf check status --zosmf-profile omptest --reject-unauthorized false

I get the following error

Command Error:
z/OSMF REST API Error:
http(s) request error event called
Error: write EPROTO 12632:error:1408F10B:SSL routines:ssl3_get_record:wrong vers
ion number:openssl\ssl\record\ssl3_record.c:252:

Error Details:
HTTP(S) client encountered an error. Request could not be initiated to host.
Review connection details (host, port) and ensure correctness.
...
...

If I access https://host:port/zosmf on internet explorer with ssl3 disable I get the login page titled "IBM z/OS Management Facility" asking for login. 

On google chrome do not get the login page but a page with saying "Your connection is not private" with "NET::ERR_CERT_AUTHORITY_INVALID".

**Comment by fbeyl** [comment]
check version openssl and eventually upgrade

**Comment by dkelosky** [comment]
Can you confirm that you can access a z/OSMF API through another non-browser client, via something like `cURL`?:
```
curl --user your_user:your_password --header "X-CSRF-ZOSMF-HEADER: true" https://host:port/zosmf/restjobs/jobs  --insecure
```

**Comment by UHaider** [comment]
After input from Jack,  I learned that I had the wrong port for zosmf. Updating the port and running 

> zowe zosmf check status --zosmf-profile omptest

results in 

> Command Error:
> z/OSMF REST API Error:
> http(s) request error event called
> Error: self signed certificate in certificate chain
> Error Details:
> HTTP(S) client encountered an error. Request could not be initiated to host.
> Review connection details (host, port) and ensure correctness.
> 

And following runs successfully.
> zowe zosmf check status --zosmf-profile omptest --reject-unauthorized false

Sorry for the noise and if it caused any confusion. I am new to zowe and learning. I think this can be closed.

**Comment by dkelosky** [comment]
Thank you

**Comment by AyberkTatoglu** [comment]
@UHaider I have the same error can you tell me the correct port, please?

**Comment by fbeyl** [comment]
Try 10443

**Comment by fbeyl** [comment]
Try 10443

**Comment by AyberkTatoglu** [comment]
I am trying like that and still gives the error, but it works well when I try to connect with vs code.

ayberks-mbp:~ ayberk$ zowe zosmf check status --host https://195.212.29.160 --port 10443 --user ###### --password ########## --ru false
Command Error:
z/OSMF REST API Error:
http(s) request error event called
Error: getaddrinfo ENOTFOUND https://195.212.29.160 https://195.212.29.160:10443
Error Details:
HTTP(S) client encountered an error. Request could not be initiated to host.
Review connection details (host, port) and ensure correctness.

Host:      https://195.212.29.160
Port:      10443
Base Path: 
Resource:  /zosmf/info
Request:   GET
Headers:   [{"X-CSRF-ZOSMF-HEADER":true}]
Payload:   undefined

**Comment by AyberkTatoglu** [comment]
Sorry the host should be "192.86.32.67". But same error.

**Comment by fbeyl** [comment]
And if you try without specifying https:// in the --host parameter

**Comment by AyberkTatoglu** [comment]
It worked thanks a lot again :)
