### ISSUE TITLE
The zowe CLI does not honor the environment variables http_proxy nor https:proxy

### ISSUE THREAD

**Issue by jguillaumes** [zowe/zowe-cli#498]
The http_proxy and https_proxy environment variables are the standard way to configure a global network proxy in Linux style systems. It looks the zowe command line does not use those variables when trying to establish connection to the zosmf or api mediation layer server.

Alternatively, an option to set the https proxy in the command line and/or the profile would be nice to have.

Rationale: in our environment the contractor developers are not allowed to directly access the mainframes from their VPN and have to use a proxy to reach them, so they can't use the CLI (they can, however, use the Zowe Desktop, and can invoke the APIs using curl or other tools that honor the proxy environment variables).

**Comment by dkelosky** [comment]
Hi @jguillaumes - if we implemented something like this, would it be acceptable to use differently named env vars / cli parms, e.g. `ZOWE_CLI_HTTP_PROXY` instead of the Linux names?  Do your contractors typically set these env vars themselves on their own machines?  

If we prioritized implementing this, which proxy setting should be begin experimenting with first, `http` or https`?  

Lastly, would you be available to help test / verify an approach?  We can contrive our own test environment, but it would be ideal to verify in a real setup.  

Thanks

**Comment by dkelosky** [comment]
Could you also share how you tested this before and what errors you observed to narrow this down?  

For example, if your proxy is via `http` instead of `https`, Zowe CLI will probably receive SSL errors since it unconditionally uses `https` when making a connection.

**Comment by jguillaumes** [comment]
Hello,

To reproduce the problem you must have a system without direct access to the mainframe but with the possibility of using a http/https proxy to get into it. I will assume it is a linux system. You should have ZOWE CLI, Visual Studio Code and the corresponding extension installed.

Test 1:  without any proxy definition, try to get a dataset list from the CLI and from Visual Studio Code. Both attempts should fail (usually with a "host name not found" error). If they don't then you HAVE direct access so the proxy is not necessary.

Test 2: Define the environment variables http_proxy and https_proxy to point to your actual proxy address (adding username and password to the URL if necessary). Then:
- The CLI access will fail again with a "host name not found" error because ZOWE CLI is not using the proxy.
- The Visual Studio Code access will SUCCEED, since VSC takes care of using the proxy.

Unfortunately, the use of http_proxy and https_proxy is CUSTOMARY but not STANDARD. Some unix programs use those variables, others use those variables in uppercase (HTTP_PROXY and HTTPS_PROXY) and others do not use them at all. The git command use http_proxy and https_proxy, for instance. Other programs use an additional variable (no_proxy or NO_PROXY) to exclude URLs and addresses from proxying. The details can be a little bit embroiled.

Maybe the most reasonable way to tackle the problem is to IGNORE the environment variables at all and add the proxy information to the ZOSMF profile so the user can specify it via ```zowe profiles create``` and ```zowe profiles update```, but then this can collide with the proxy managenent that Visual Studio Code does by itself.

**Comment by dkelosky** [comment]
Adding @MarkAckert for his experience to comment...

Hi @jguillaumes - in some simple onsite testing I set my `--host` in the z/OSMF profile to be the host of the proxy and could connect.  Have you tested this approach?  

Is your proxy `http`?  Zowe CLI will not be able to connect in this case without code changes.  

For test 2, that makes sense.  We don't reference `http_proxy` or `https_proxy` in our code.

Thanks

**Comment by MikeBauerCA** [comment]
@jguillaumes were you able to test using @dkelosky's suggestion of specifying the host of the proxy in `--host` ?

**Comment by jguillaumes** [comment]
Hello. No, sorry... I've been struggling with other (more boring) tasks.

I havent tested it and, to be honest I don't understand how to do it. Example:
- My zowe host (the one running the APIML) is zowes4.xxxx.xx port 7554
- My current http/https proxy is http://192.168.0.91:3128
How do I specify both items in the --host parameter? Maybe I'm missing something trivial here...

**Comment by Joe-Winchester** [comment]
@MikeBauerCA and @dkelosky - many thanks for making progress with this.  Does it need to be included in the list of topics for the next PI or is already in flight and being covered ?

**Comment by MikeBauerCA** [comment]
Yes, I added it as an objective for the upcoming PI. These objectives are currently in box but I will move them into our community GitHub soon.

**Comment by zFernand0** [comment]
Hey @jguillaumes,

Could you try installing this test CLI version? It's an offline bundle for PR #909.

[zowe-cli-6.26.0-498-http-support.4590b7c.zip](https://github.com/zowe/zowe-cli/files/5961069/zowe-cli-6.26.0-498-http-support.4590b7c.zip)

Please unzip the file, open a terminal, `cd <path/to/unzipped/file>`, and run `npm i -g zowe-cli-6.26.0-498-http-support.4590b7c.tgz`

You should be able to run your CLI commands and fully qualify your connection details like:
`zowe files list ds HLQ.* --protocol http --host <my-http-proxy-IP> --port <my-http-proxy-port>`
