### ISSUE TITLE
Download API JSDoc

### ISSUE THREAD

**Issue by JTonda** [zowe/zowe-cli#50]
_From @dkelosky on July 13, 2018 19:31_

Download.dataset returns a `IZosmfFilesResponse` object which references "commands".  At the API usage, is `commandResponse` actually the data set content?
![image](https://user-images.githubusercontent.com/14940561/42710340-a76e557c-86b1-11e8-840b-961697cecd80.png)

_Copied from original issue: gizafoundation/brightside#153_

**Comment by JTonda** [comment]
_From @zFernand0 on August 29, 2018 12:12_

`commandResponse` is basically a success message that gets forwarded to the handler, which doesn't seem very useful for API usage only.
On the other hand, `apiResponse` is the guy that contains the content of the downloaded data set.

Two possible solutions for this misunderstanding, let's vote (:+1: or :-1:)
(If you have a new solution please feel free to add it)

**Comment by JTonda** [comment]
_From @zFernand0 on August 29, 2018 12:13_

- Add more explicit JSDoc comments. (This is probably the quickest solution)

**Comment by JTonda** [comment]
_From @zFernand0 on August 29, 2018 12:13_

- Remove `commandResponse` all together from `IZosmFilesResponse`, and let the command handlers format their own messages (if needed) since API users wouldn't really care about the command messages.

**Comment by MikeBauerCA** [comment]
Closing in favor of https://github.com/zowe/zowe-cli/issues/865
