### ISSUE TITLE
Wrong Message Displayed when using --rfj

### ISSUE THREAD

**Issue by jellypuno** [zowe/zowe-cli#502]
Wrong Prefix and Owner  displayed when using --rfj. 

`λ zowe jobs list jobs -p RESUME  --rfj
{
  "success": true,
  "exitCode": 0,
  "message": "List of jobs returned for prefix \"XXXXXXX\" and owner \"RESUME\"",
  "stdout": "",
  "stderr": "",
  "data": []
}`

**Comment by zFernand0** [comment]
It would be nice to add an integration test around this 😄

**Comment by zFernand0** [comment]
https://github.com/zowe/zowe-cli/blob/c8f1d2afdc4c32b5f4c537df2bfd11fd1d5cf517/packages/zosjobs/src/cli/list/jobs/Jobs.handler.ts#L34-L48

**Comment by tjohnsonBCM** [comment]
Fixed in #506 (master) and #507 (lts-incremental)
