### ISSUE TITLE
Wrong Integration test for zosjobs list jobs command

### ISSUE THREAD

**Issue by Alexandru-Dumitru** [zowe/zowe-cli#505]
While looking at #502 , I noticed the Integration test is wrong. Instead of having `zowe zos-jobs list -h` we have `zowe zos-jobs view -h` in the script.
https://github.com/zowe/zowe-cli/blob/a6d6c42fc029abfd6573134650d574e8aa2d5fcc/packages/zosjobs/__tests__/__integration__/cli/list/__scripts__/list_help.sh#L1-L11

We would need to update this bash script and also the snapshot:
https://github.com/zowe/zowe-cli/blob/a6d6c42fc029abfd6573134650d574e8aa2d5fcc/packages/zosjobs/__tests__/__integration__/cli/list/__snapshots__/cli.zos-jobs.list.integration.test.ts.snap

**Comment by tjohnsonBCM** [comment]
Fixed in #506 (master) and #507 (lts-incremental)
