### ISSUE TITLE
Web help - Link out to the CLI Reference PDF guide. 

### ISSUE THREAD

**Issue by jelaplan** [zowe/zowe-cli#510]
The CLI Reference guide offers a single file view of all the help. This has an advantage of full text search and saving locally to the user's file system. 
https://zowe.github.io/docs-site/latest/CLIReference_Zowe.pdf

See also 
[#415](https://github.com/zowe/zowe-cli/issues/415) 
[#472 Web help - search all help content](https://github.com/zowe/zowe-cli/issues/472)

**Comment by tjohnsonBCM** [comment]
Full text search is now available when "Flat View" is selected: https://docs.zowe.org/stable/web_help/index.html?v=1

**Comment by gejohnston** [comment]
The referenced issues have been closed as addressed. I believe that the ability to search the flat view of web help addresses the concerns.
