### ISSUE TITLE
Allow renaming data sets and data set members

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/zowe-cli#520]
Allow data sets and data set members to be renamed via the CLI:
https://www.ibm.com/support/knowledgecenter/SSLTBW_2.1.0/com.ibm.zos.v2r1.izua700/IZUHPINFO_API_PutDataSetMemberUtilities.htm

**Comment by cycaoecw** [comment]
@MikeBauerCA I am trying add the command for rename the dataset, but i got following error when call the API. Do you have any idea of the error? The dataset Z40396.DS.OLD already allocated in my ISPF.

> Command Error:
> z/OSMF REST API Error:
> Rest API failure with HTTP(S) status 500
> category: 16
> rc:       16
> reason:   1
> message:  Unhandled exception in TsoServlet
> details: 
>   - bad allocation
> 
> 
> Error Details:
> HTTP(S) error status "500" received.
> Review request details (resource, base path, credentials, payload) and ensure correctness.
> 
> Host:      192.86.32.67
> Port:      10443
> Base Path:  
> Resource:  /zosmf/restfiles/ds/Z40396.DS.NEW
> Request:   PUT
> Headers:   [{"Content-Type":"application/json"},{"charset":"UTF-8"},{"X-CSRF-ZOSMF-HEADER":true}]
> Payload:   '{"from-dataset":{"dsn":"Z40396.DS.OLD"},"request":"rename"}'

**Comment by MikeBauerCA** [comment]
@cycaoecw thank you for picking this up!

@tucker01 @zFernand0 @Alexandru-Dumitru any thoughts?

**Comment by zFernand0** [comment]
Hey @cycaoecw,
I'm afraid there is no official documentation for this error except that it's an unexpected error. See [IBM Category definitions](https://www.ibm.com/support/knowledgecenter/SSLTBW_2.2.0/com.ibm.zos.v2r2.izua700/IZUHPINFO_API_RESTFILES_Error_Categories.htm)

The error could be related to various different things, for example missing one of the required options for the rename operation based on the API Doc [here](https://www.ibm.com/support/knowledgecenter/SSLTBW_2.4.0/com.ibm.zos.v2r4.izua700/IZUHPINFO_API_PutDataSetMemberUtilities.htm#IZUHPINFO_API_PutDataSetMemberUtilities)

For example if those are Partitioned Data Sets then the payload needs to be a bit different.
`{"from-dataset":{"dsn":"Z40396.DS.OLD","member":"*"},"request":"rename"}`

Question on this topic.
Are we going to ask for a `replace` flag in case the DS already exists?

**Comment by MikeBauerCA** [comment]
We should not overwrite an existing data set automatically without ensuring this is what the user intended. My suggestion is to ask for a `replace` flag in the case the DS already exists.

**Comment by cycaoecw** [comment]
@zFernand0 Thanks for your checking, i try to add `"member":"*"` in playload but still same error. My command is trying to rename PDS Z40396.DS.OLD to Z40396.DS.NEW. And the the PDS Z40396.DS.NEW is not existing. You may refer following.

> CYdeMacBook-Pro:zowe-cli cy$ zowe files list ds Z40396.DS
> Z40396.DS.OLD
> CYdeMacBook-Pro:zowe-cli cy$ zowe files rename ds Z40396.DS.OLD -t Z40396.DS.NEW
> Command Error:
> z/OSMF REST API Error:
> Rest API failure with HTTP(S) status 500
> category: 16
> rc:       16
> reason:   1
> message:  Unhandled exception in TsoServlet
> details: 
>   - bad allocation
> 
> 
> Error Details:
> HTTP(S) error status "500" received.
> Review request details (resource, base path, credentials, payload) and ensure correctness.
> 
> Host:      192.86.32.67
> Port:      10443
> Base Path:  
> Resource:  /zosmf/restfiles/ds/Z40396.DS.NEW
> Request:   PUT
> Headers:   [{"Content-Type":"application/json"},{"charset":"UTF-8"},{"X-CSRF-ZOSMF-HEADER":true}]
> Payload:   '{"from-dataset":{"dsn":"Z40396.DS.OLD","member":"*"},"request":"rename"}'
> CYdeMacBook-Pro:zowe-cli cy$ zowe files list ds Z40396.DS
> Z40396.DS.OLD
> CYdeMacBook-Pro:zowe-cli cy$

**Comment by jalel01** [comment]
@Alexandru-Dumitru @crawr @jellypuno any ideas how we can assist @cycaoecw here?

**Comment by jellypuno** [comment]
hi @cycaoecw, 

if you want to rename the dataset only, try to remove the `"member":"*"` in the body. My request looks like this and it works for me:

`https://hostname:port/zosmf/restfiles/ds/PUNJE01.JCL.RENAME`
`{"request":"rename", "from-dataset":{"dsn":"PUNJE01.JCL"}} `

Maybe this can help as well: https://www.ibm.com/support/knowledgecenter/SSLTBW_2.1.0/com.ibm.zos.v2r1.izua700/IZUHPINFO_API_PutDataSetMemberUtilities.htm

**Comment by cycaoecw** [comment]
@jellypuno that's good question, but the dataset i want to rename to is using my profile, i suppose should be no issue. Let me just try via 3270 and let you know the result.

**Comment by jellypuno** [comment]
@cycaoecw any updates?

**Comment by cycaoecw** [comment]
@jellypuno sorry be late, i just try to rename using JCL via 3270 and it works.
<img width="821" alt="Screen Shot 2019-10-16 at 10 04 10 PM" src="https://user-images.githubusercontent.com/15675572/66926794-3698fa80-f061-11e9-94d8-773f9f15132f.png">

**Comment by jellypuno** [comment]
@cycaoecw do not use idcams to rename the dataset. this is a different utility. try to rename it via 3.4 (Data Set List Utility) by typing R next to your dataset.

**Comment by cycaoecw** [comment]
@jellypuno Just try try to rename it via 3.4 (Data Set List Utility) by typing R next to dataset, and it work too.
![Screen Shot 2019-10-19 at 10 27 55 AM](https://user-images.githubusercontent.com/15675572/67136630-5bf15880-f25b-11e9-82e2-5b8237c6a38d.png)

**Comment by CForrest97** [comment]
@cycaoecw, are you still looking at this issue? If not I'd like to propose breaking this issue down into the following issues

- Add API support for renaming a data set
- Add API support for renaming a data set member
- Add API support for specifying the enqueue type of the to data set member

- Add CLI support for renaming a data set
- Add CLI support for renaming a data set member
- Add CLI support for specifying the enqueue type of the to data set member

**Comment by cycaoecw** [comment]
@CForrest97 actually i suspect it may due to API issue. But i dont know how to check. Please go ahead to bread down the issue. I think it will help.

**Comment by CForrest97** [comment]
@cycaoecw Okay great thanks
Ive created the following issues
#571 #572 #573 #574 #575 #576 
Which should cover this entire issue
