### ISSUE TITLE
Allow copying of data sets and data set members

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/zowe-cli#521]
Allow data sets and data set members to be copied via the CLI:
https://www.ibm.com/support/knowledgecenter/SSLTBW_2.1.0/com.ibm.zos.v2r1.izua700/IZUHPINFO_API_PutDataSetMemberUtilities.htm

**Comment by jelaplan** [comment]
If we are going to support copying, wouldn't it make sense to combine this with move as well?

**Comment by MikeBauerCA** [comment]
Within a given LPAR, rename may satisfy this requirement. However, we may want to consider copying/moving data sets and data set members between LPARs that do not have shared DASD.

**Comment by jelaplan** [comment]
I created some mockups for copying and moving members and datasets in the Zowe Explorer extension for VS Code. 

Copy:  https://ent.box.com/s/8of9ou71akjstybjbljy99x3lu6vlac2
Rename:  https://ent.box.com/s/qw5r2u9dfgo9uaz8r8a0kteoi3s5076c

**Comment by CForrest97** [comment]
I have added the following issues which I believe encapsulate this issue
#578 #579 #580 #581
