### ISSUE TITLE
Allow recalling a migrated data set from the CLI

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/zowe-cli#524]
Allow migrated data sets to be recalled from the CLI:
https://www.ibm.com/support/knowledgecenter/SSLTBW_2.1.0/com.ibm.zos.v2r1.izua700/IZUHPINFO_API_PutDataSetMemberUtilities.htm

**Comment by Colin-Stone** [comment]
This functionality would be great to allow VSCode extension to show when a dataset is in a migrated state and provide the recall and.. migrate dataset etc

When implementing can we therefore support hmigrate, hrecall and hdelete too?.

**Comment by Pranay154** [comment]
I propose breaking this issue down into two parts:
Allow recalling a migrated data set from the CLI #524
API
     Add functionality for Migrating
CLI
     Add functionality for Migrating (Display API call)
Benefit of breaking it down is that once the API side of it created, it can be used and then the CLI can connect to it

**Comment by Pranay154** [comment]
Closing Issue, created new issues regarding proposal above.
Issues created : #555 , #556
