### ISSUE TITLE
No response while issuing MVS command

### ISSUE THREAD

**Issue by rjmaomao** [zowe/zowe-cli#529]
Hi,

I'm running with Zowe CLI version 2.24.2. I have created a zosmf profile and want to use it to run some logger command. 

The profile works well, I can tell by running other MVS command.
_zowe zos-console issue command "D XCF" --zosmf-profile zosmfplx1
 IXC334I  23.14.54  DISPLAY XCF 324
    SYSPLEX UTCPLXJ8:   JA0               JB0               JC0
                        JD0               JE0               JF0           JG0_
Then I ran the logger command to list all the log streams in the system. But I didn't get any response. 
 _zowe zos-console issue command "D logger,l" --zosmf-profile zosmfplx1_

Checked from mvs side, in syslog, I can see that the command was executed under my console name and there were output there. 
_JG0      2019253 23:13:09.44 RENJINCN 00000290  D LOGGER,L_

Not sure why I didn't get response on zowe cli side? This command have a very large output, do you think it's because the output too large caused the issue? Could you please help on this issue? How can I get the output from the command? 

Thanks!

**Comment by tucker01** [comment]
Hi @rjmaomao, sorry for the trouble. I suspect what might be happening is a delay in response from the command on MVS causing us to end the command without displaying any data. If you issue `zowe console issue cmd -h` the help has a detailed explanation of some things to be aware of... In summary, with z/OS consoles, there isn't an indication of "how much" data will be returned via a command, so Zowe CLI does it's best to collect what it can in most circumstances. In this instance, you should try using the `--wait-to-collect` option. It tells Zowe CLI to wait the specified number of seconds before checking for more data. You can also use the `--follow-up-attempts` option to specify the number of times the command will check for response data before returning to you. 

Start by trying the following:
```
zowe console issue cmd "d logger,l" --wtc 5
```

If you don't see everything, try increasing the number. If you get to 60 or so and still don't see a response (and you're sure that it wouldn't take 60-120 seconds if you issued the command on a traditional z/OS console) then we can do some investigation and explore some alternatives available in the CLI.

Also, I tried the command on our dev LPAR and I was able to receive a response, so there doesn't appear to be a deviation in behavior with `D LOGGER,L`... e.g. some console commands might not send responses back to the originating console.

**Comment by rjmaomao** [comment]
Hi @tucker01, thank you for the answer, I tried --wtc 20 and was able to get the response. Could you please tell me if I don't specify this option, how many seconds does zowe wait for by default?

**Comment by tucker01** [comment]
Zowe CLI does not wait by default, but does issue additional collection attempts until there is no more response data. In most cases, this is sufficient... however, if the command takes some time to product any response data, your situation may be encountered. This is why we added the options for waiting and collection attempts.

**Comment by rjmaomao** [comment]
Thank you @tucker01 , I'll close this issue.
