### ISSUE TITLE
ZosFiles should allow additional values for the DSnType option

### ISSUE THREAD

**Issue by JTonda** [zowe/zowe-cli#53]
_From @zFernand0 on June 29, 2018 13:59_

Even though z/OS MF prevents us from configuring data sets with different "data-set types" (`dsntype`), we should allow for more values other than `LIBRARY`

brightside/packages/zosfiles/src/api/methods/create/Create.ts

 case "dsntype": 
     // Key to create a PDSE.  Only valid value is LIBRARY (as far as I know) 
     switch (tempOptions.dsntype.toUpperCase()) { 
         case "LIBRARY": 
             break; 
         default: 
             throw new ImperativeError({msg: ZosFilesMessages.invalidDsntypeOption.message + tempOptions.dsntype}); 
     } 

_Copied from original issue: gizafoundation/brightside#142_

**Comment by JTonda** [comment]
_From @PeteSwauger on August 29, 2018 13:20_

Researched and tested successfully: LIBRARY, HFS, PDS, LARGE, BASIC.  EXTREQ and EXTPREF (as shown on 3270 3.2 screen) didn't work.  More research needed to see if supported by ZOSMF.

EXTREQ   - indicates that an extended dataset is required.  
EXTPREF  - indicates that an extended dataset is preferred.

**Comment by hogstrom** [comment]
I executed a POST request following the sample [here](https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.3.0/com.ibm.zos.v2r3.izua700/IZUHPINFO_API_CreateDataSet.htm#CreateDataSet) .  This is to a z/OSMF 2.3 instance

Seems as if z/OSMF accepts the dsntype ... is this an error in formation of the REST request in Imperative?

Target URL
https://my.z.host/zosmf/restfiles/ds/USER1.REST.TEST.NEWDS04

Body
```
{
  "volser": "T70502",
  "unit": "3390",
  "dsorg": "PO",
  "alcunit": "TRK",
  "primary": 10,
  "secondary": 5,
  "dirblk": 10,
  "avgblk": 500,
  "recfm": "FB",
  "blksize": 400,
  "lrecl": 80,
  "dsntype": "PDS"
}
```
Info Screen Shot
https://imgur.com/a/zErVIzy

Used BasicAuth

Received response
```
HTTP/1.1 201 Created
X-Powered-By: Servlet/3.0
Content-Type: application/json; charset=utf-8
Content-Length: 0
X-IBM-Txid: tx000000000000000C
Content-Language: en-US
Set-Cookie: LtpaToken2=[ ... snip ... ]; Path=/; Secure; HttpOnly
Connection: Close
Date: Tue, 28 May 2019 20:08:23 GMT
Expires: Thu, 01 Dec 1994 16:00:00 GMT
Cache-Control: no-cache="set-cookie, set-cookie2"
```

**Comment by Colin-Stone** [comment]
I think that now z/OSMF has changed in 2.3 this now becomes a bug in CLI so we should allow those dsntypes supported to be accepted and passed through

**Comment by tehbone** [comment]
For reference, does have the acceptable values documented:
https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.3.0/com.ibm.zos.v2r3.izua700/IZUHPINFO_API_RESTFILES_JSON_Documents.htm#RESTFILES_JSONDocumentSpecifications__docCreateSecPAr

They are BASIC, EXTPREF, EXTREQ, HFS, LARGE, PDS, LIBRARY, PIPE.

**Comment by Colin-Stone** [comment]
This was completed several months ago
