### ISSUE TITLE
How can I specify several variables in the command (zowe zos-workflows create  --VS?

### ISSUE THREAD

**Issue by George0013** [zowe/zowe-cli#531]
How can I specify several variables in the command (zowe zos-workflows create workflow-from-uss-file "testworkflow" "SYS2" --vs destination = CTA1 --vs firstvar=aaaaaa secondvar=bbbbb .....

**Comment by uzust01** [comment]
Hello, @George0013
Try this:
zowe zos-workflows create workflow-from-uss-file --uss-file "a/user/ussFile" --system-name "SYS1" --owner "userID" --variables "var1=value1,var2=value2,var3=value3"

**Comment by George0013** [comment]
Hello, @uzust01,
I'm afraid it doesn't work, it only works with one variable.

zowe zos-workflows cre wfuf "testworkflow" --uf "/SYS2/workflow/workflow_ConnectDirect.xml" --sn "SYS2" --ow "U529279" --ov --vs "destino=CTA1,indsn_TC0Z=u529279.temp.wlm,outdsn_CTA1=u529279.temp.wlmj"
Command Error:
Creating z/OSMF workflow with uss file: /SYS2/workflow/workflow_ConnectDirect.xml failed. More details:
Error: z/OSMF REST API Error:
Rest API failure with HTTP(S) status 400
messageText:            IZUWF5003E: The specified parameter name or parameter value "indsn_TC0Z:u529279.temp.wlm" is not valid.
validSingletonInstance: true
messageID:              IZUWF5003E

Anyway, I can always do it with the "variable in file" that works well.

**Comment by tucker01** [comment]
Should we mark this with the bug label?

**Comment by uzust01** [comment]
Thanks for pointing this out, @George0013 
@tucker01 , I will take a look

**Comment by uzust01** [comment]
I did a little research and it seems like we are building the variables object in a way defined by IBM documentation. This looks like a Rest API validation error from z/OSMF itself. The only description of the error I found was this: 
[IZUWF5003E](https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.2.0/com.ibm.zosmfworkflows.messages.help.doc/IZUWF5003E.html)

**Comment by George0013** [comment]
Hi,
It seems to be correct, the variables are: destination, indsn_TC0Z and outdsn_CTA1j
They are the same that I have put with the option "variable in file".

---------------------------
zowe zos-workflows cre wfuf "testworkflow" --uf "/SYS2/workflow/workflow_ConnectDirect.xml" --sn "SYS2" --ow "U529279" --ov --vs "destino=CTA1,indsn_TC0Z=u529279.temp.wlm,outdsn_CTA1=u529279.temp.wlmj"
Command Error:
Creating z/OSMF workflow with uss file: /SYS2/workflow/workflow_ConnectDirect.xml failed. More details:
Error: z/OSMF REST API Error:
Rest API failure with HTTP(S) status 400
messageText: IZUWF5003E: The specified parameter name or parameter value "indsn_TC0Z:u529279.temp.wlm" is not valid.
validSingletonInstance: true
messageID: IZUWF5003E

-----------------------------


thk

**Comment by uzust01** [comment]
@George0013 , can you please send me the variable definition and in the meantime can you try with the same command but use upper case for the data set name. 
U529279.TEMP.WLM

**Comment by George0013** [comment]
Hi @uzust01 ,
Yes, with uppercase variables it works correctly.

Thank you very much.

**Comment by uzust01** [comment]
You are welcome, @George0013 

@tucker01 , if you would like to keep this issue open I can "fix" it by extending the example and the option description.

**Comment by George0013** [comment]
The incident can be closed.
Thank you

**Comment by tucker01** [comment]
> You are welcome, @George0013
> 
> @tucker01 , if you would like to keep this issue open I can "fix" it by extending the example and the option description.

It would be great to update the examples and descriptions to help people avoid this snag in the future.

**Comment by George0013** [comment]
@tucker01  I'm sorry, I didn't understand you well, I agree  reopen it.

**Comment by tucker01** [comment]
Help has been updated.

**Comment by George0013** [comment]
Thank you very much
