### ISSUE TITLE
Mark profile connection options as required in the CLI help

### ISSUE THREAD

**Issue by jelaplan** [zowe/zowe-cli#538]
The create profile command requires host, user, and password.   It doesn't require port which has a default of 443 nor reject unauthorized which is defaulted to true. 

My idea is to mark what is required in the CLI help content. 

I think it might also be useful to make user and password optional and prompt for those if they are missing. This ties into efforts on the VS Code extension where a user can create a connection without storing the user name and password.

**Comment by tucker01** [comment]
This seems like two separate issues. Would you mind splitting these up? It would also be helpful if we could provide example of how these enhancements would look and operate. Thanks.

**Comment by jelaplan** [comment]
Jason, I could make this into two issues but I'm not sure what the two are.  I guess one is to mark some fields required in the CLI Help. The other is about making the user and pw optional and prompt. 

I think where this is leading is to make the user name and password optional in the profile. We won't need to mark them as required. In that case, if the user types a command that uses such a profile, the system will prompt them for those, much like it does today if the user types --password prompt*. But, in this case, the user won't need to type the option. I can mock that up for the team. 

There will be mockups for the VS Code extension as well that I can share.

**Comment by zFernand0** [comment]
For making user and password optional, see #583

**Comment by jelaplan** [comment]
During the implementation of the profile independence in VS Code, the T&C team made user name and password optional. The extension can create a new profile absent those two fields. If the user then goes to the CLI and uses that profile, they will be required to enter a user name and password. @Richelle showed me the error message that will appear. 
![image](https://user-images.githubusercontent.com/3207260/68893205-a77c1280-06f2-11ea-9dd6-5cab6c81baed.png)

**Comment by jelaplan** [comment]
Jason had asked for an example of how the enhancements might look. I put some things in bold to draw attention. I made u and p required but of course if those are not required going forward then we wouldn't mark them as such. 

 ZOSMF CONNECTION OPTIONS
 ------------------------

   --host  | -H (string)

      The z/OSMF server host name. **Required option**. 

   --port  | -P (number)

      The z/OSMF server port.
      
      Default value: 443

   --user  | -u (string)

      Mainframe (z/OSMF) user name, which can be the same as your TSO login. **Required option**.

   --password  | --pass | --pw (string)

      Mainframe (z/OSMF) password, which can be the same as your TSO password. **Required option**.

**Comment by jelaplan** [comment]
@tucker01 I split out the prompting feature into https://github.com/zowe/zowe-cli/issues/587

**Comment by MikeBauerCA** [comment]
As mentioned in https://github.com/zowe/vscode-extension-for-zowe/issues/373#issuecomment-562696447, I believe the Zowe CLI should be enhanced so that all profile fields are optional and when running a command if an option is not supplied and there is no default value, the user is prompted.

Profiles themselves are optional, so I do not see why they would have a required field.

**Comment by awharn** [comment]
We have since moved forward with the prompting logic, and the options are no longer required.
