### ISSUE TITLE
Support the IBM z/OSMF header that allows record (support for VB binary)

### ISSUE THREAD

**Issue by tucker01** [zowe/zowe-cli#539]
z/OSMF has three data types when uploading/downloading members (binary, record, and text). We currently support binary and text, but do not support record:

https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.1.0/com.ibm.zos.v2r1.izua700/IZUHPINFO_API_GetReadDataSet.htm

**Comment by tucker01** [comment]
Currently, if you have a data set with `RECFM=VB` and you attempt to download and upload using the `--binary` option. The records are not maintained correctly. 

Original Member:
```
record 1
record 2 
record 3
```
After download then upload:
```
record 1record 2record 3
```

**Comment by fbeyl** [comment]
I think this issue deserves high priority. Not only for variable records but also for fixed record that have mixed contents it would be VERY usefull. Most batch jobs use mvs sequential datasets that have records composed of computational (packed-decimal, zoned-decimal, ... ) fields and with characterfields fields (containing text). This mixture in a record makes it impossible to download as text (with conversion) or binary (without conversion would be possible but record structure gets lost), "X-IBM-Data-Type = record" header allows to download and upload keeping record structure without conversion.
Without this possibility I now download datasets using "Postman" software, update (I use hexeditor in ebcdic mode) and upload using "Postman" which is devious.
For debugging this option seems indispensable to me.

**Comment by MikeBauerCA** [comment]
@fbeyl @tucker01 this has been implemented in the most recent versions of Zowe CLI `@next` and `@zowe-v1-lts` on public npm. If you try it out, please provide us with feedback. Thanks!

**Comment by MikeBauerCA** [comment]
You should see the addition of a `--record` option on the commands.

**Comment by fbeyl** [comment]
Ok, will do that. Thx.

**Comment by fbeyl** [comment]
Ok works. I can send an example (download, modify contents: add bytes to record, upload) if you like.

**Comment by MikeBauerCA** [comment]
Thanks for letting us know! If you are willing to share those details, I'm always interested in seeing how folks are using the product 👍
