### ISSUE TITLE
Command Preparation Failed: Cannot read property 'host' of undefined

### ISSUE THREAD

**Issue by lvuono** [zowe/zowe-cli#541]
Setting up the zowe cli - was issuing commands thru zowe zos-tso specifying host information on the command line with no problem.  After I setup some zosmf and tso profiles.  After defining the profiles, I was no longer able to issue the commands, receiving error message **Command Preparation Failed: Cannot read property 'host' of undefined**.  This happened even when specifying the profiles on the command line.  After setting default profiles via the zowe commands I was able to issue TSO commands successfully

**Comment by dogboydog** [comment]
Related: https://github.com/zowe/imperative/issues/43

**Comment by tucker01** [comment]
For those that encounter this until fixed:

**If you have profiles:**
1. List profiles with `zowe profiles list <type>`
2. Copy the one you want to use as the default
3. Set the default with `zowe profiles set <type> <one_you_copied_in_step_2>`

**If you don't have profiles**
Navigate to your `~/.zowe/profiles` directory (`~` is your home directory). For the type that is causing the trouble (for example `zosmf`, used in core `zos-blah` commands) delete that directory and try rerunning the command... **NOTE:** Only do this if you do NOT have profiles. You will delete all profiles for that type by deleting the directory.

**Comment by tjohnsonBCM** [comment]
Fixed in https://github.com/zowe/imperative/pull/304
