### ISSUE TITLE
@zowe/cli as an npm dependency runs plugin validation

### ISSUE THREAD

**Issue by dkelosky** [zowe/zowe-cli#548]
If I want to use the `@zowe/cli` Node.js APIs, I install it as a dependency and get the following:
```
$ npm install --save @zowe/cli

> @zowe/cli@6.1.0 postinstall C:\dev\electron\electron-jquery-bootstrap\node_modules\@zowe\cli
> node ./scripts/validatePlugins

Since you re-installed Zowe CLI, we are re-validating any plugins.

_____ Validation results for plugin '@zowe/zos-make-for-zowe-cli' _____

*** Warning: The version value (^5.5.0) of the plugin's '@zowe/cli' property is incompatible with the version value (6.1.0) of the zowe command's 'version' property.

This plugin has warnings, but its commands and framework overrides will still be available.

_____ Validation results for plugin '@zowe/zowe-cli-sample-plugin' _____

*** Warning: The version value (^5.14.2) of the plugin's '@zowe/cli' property is incompatible with the version value (6.1.0) of the zowe command's 'version' property.

This plugin has warnings, but its commands and framework overrides will still be available.
npm WARN bootstrap@4.3.1 requires a peer of popper.js@^1.14.7 but none is installed. You must install peer dependencies yourself.
npm WARN electron-min@0.1.0 No repository field.

+ @zowe/cli@6.1.0
added 101 packages from 58 contributors and audited 995 packages in 16.994s
found 7 vulnerabilities (1 low, 6 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details
```

I could `--ignore-scripts` but shouldn't have to in this special case.  Perhaps the "core" API packages can be exported and used as a package apart for the CLI without the `postInstall` run?

**Comment by tjohnsonBCM** [comment]
Perhaps the CLI could check in its postinstall script whether it is being globally installed, and if not then skip the plugin validation.

**Comment by zFernand0** [comment]
> Perhaps the "core" API packages can be exported and used as a package apart for the CLI

Maybe this ties into what we are calling NodeJS SDK? Should this be treated as a separate npm package (say `@zowe/cli-core`) which contains APIs and interface definitions (and no postinstall and no `bin` in pacakge.json)? 
That way, other apps can just call that instead of relying on the CLI (unless they intend to use any of the commands - `bin` in `@zowe/cli`)

**Comment by t1m0thyj** [comment]
@dkelosky Can this issue be closed now that Zowe SDK packages have been published? 😋

**Comment by dkelosky** [comment]
As long as Plug-in validation doesn’t occur when using the SDK, closing makes sense to me 🙂
