### ISSUE TITLE
Brightside unable to access credential manager in Linux when user login via ssh or telnet

### ISSUE THREAD

**Issue by JTonda** [zowe/zowe-cli#55]
_From @lyzla01 on June 26, 2018 20:53_

Issue Summary:
User will not be able to access credential manager to create, edit or load credential in Linux system when they accessed it via ssh or telnet.

Technical background:
Current implementation of Brightside credential manager is using lib-secrete installed in Linux system does not support user who is accessing the system via ssh or telnet.  This issue is caused by no d-bus session is being created when user login via console. 

Note: This is making the integrating with Jenkins become much harder to control and options are very limited.

_Copied from original issue: gizafoundation/brightside#139_

**Comment by JTonda** [comment]
_From @BrandonJenkins14 on June 27, 2018 13:39_

Can you please elaborate on what a user needs to DO to get around this issue? I'd like to document this as a known-issue in DocOps. Thanks.

**Comment by JTonda** [comment]
_From @AHumanFromCA on June 27, 2018 13:50_

Well they could do one of two things:

1. Don't use ssh or telnet as their connection. (i.e. always use bash)
2. Place the command to unlock their keyring followed by any other commands they want to run in a shell script then execute the shell script under the dbus-launch command.
    - Also if you doc this, please don't make any mention to gnome-keyring. The document there mentions the gnome-keyring because that is what keyring I chose to use in our environment.

**Comment by JTonda** [comment]
_From @AHumanFromCA on June 29, 2018 14:0_

We should probably track any fixes for this in the imperative repo as well.

**Comment by lyzla01** [comment]
This issue is resolved zowe/imperative#28
