### ISSUE TITLE
SSH Handler throws an uncaught exception when a connection is refused

### ISSUE THREAD

**Issue by tucker01** [zowe/zowe-cli#554]
```
Error: connect ECONNREFUSED <hostname>:22
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
Command Error:
connect ECONNREFUSED <hostname>:22
Imperative encountered an unexpected exception
Command entered: "zowe uss issue ssh ls -la ..."
Use "zowe uss issue --help" to view groups, commands, and options.
Error Details:
connect ECONNREFUSED <hostname>:22
```

The connection is refused and an uncaught exception is generated (perhaps a promise rejection, etc. is not being handled?). 

@ChrisPark89 @chrisparkibm Any ideas here?

**Comment by ChrisPark89** [comment]
@tucker01 I had a look and yes you are right. Some of the exceptions generated by ssh2 module wasn't handled properly. I'll fix it soon. Thanks.
