### ISSUE TITLE
bright plugins install causes error

### ISSUE THREAD

**Issue by JTonda** [zowe/zowe-cli#56]
_From @SujaySolomonCA on June 6, 2018 12:12_

It seems to have gotten the filemaster target magically. I was just looking to get help for bright plugins install. I issued bright plugins install --h which did bring up the help properly.

`$ bright plugins install
Imperative CLI Framework plug-ins can gain control of your CLI application legitimately during the execution of every command. Install 3rd party plug-ins at your own risk. CA Technologies makes no warranties regarding the use of 3rd party plug-ins.

...
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @brightside/filemasterplus@0.0.1-20
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\***REMOVED***\AppData\Roaming\npm-cache\_logs\2018-06-06T12_07_46_638Z-debug.log
Command Error:
Install Failed
Error Details:
Command failed: npm install "@brightside/filemasterplus@0.0.1-20" --prefix C:\Users\***REMOVED***\.brightside\plugins\installed -g --registry https://registry.npmjs.org/`

_Copied from original issue: gizafoundation/brightside#126_

**Comment by JTonda** [comment]
_From @AHumanFromCA on June 6, 2018 12:15_

`bright plugins install` is a valid command that will attempt to reinstall plugins found in plugin.json (as per design in imperative)

So is the bug that you got the npm error? (and not the fact that `bright plugins install` returned no help?)

**Comment by JTonda** [comment]
_From @SujaySolomonCA on June 6, 2018 12:18_

I didn't realize that it was intended. I thought issuing any command without --h will bring up help. I am not sure why strayed away from every command needing group, object, target option[s]. To me, it's inconsistent  UX.

**Comment by JTonda** [comment]
_From @AHumanFromCA on June 6, 2018 12:23_

So my understanding was that most actual commands (the last thing in the line in this case) require `-h` for help.

As per the plugin group deviating from the UX standard, this was talked about but we never got the time to go back and fix it to add an arbitrary action to satisfy the requirement.

I think the structure would have been something like `cli plugins install plugin <plugin...>` so you would issue: `bright plugins install plugin filemaster endevor db2` to install the 3 plugins we currently have.

**Comment by JTonda** [comment]
_From @SujaySolomonCA on June 6, 2018 12:31_

There is a feature in 18PI3 for "UX improvements", we should try to achieve the command syntax consistency as part of this feature. @MikeBauerCA

**Comment by JTonda** [comment]
_From @AHumanFromCA on June 6, 2018 12:37_

I think making this change should be easy. I mean all we are essentially doing is increasing the length of the command and adding another level to get help at.

One thing to note: there will only ever be one "object" under each action in plugins. I do not foresee any additional "objects" being placed under these groups.

Another thing to note: this change should be tracked in imperative's repo since that is where the code change will be. This change will be a **Major** change so we will have to update brightside to a 2.0 pre-release in order to add this in.

**Comment by JTonda** [comment]
_From @SujaySolomonCA on June 6, 2018 12:46_

We should get John LaPlante's take on this.

**Comment by JTonda** [comment]
_From @SujaySolomonCA on July 2, 2018 14:56_

I agree with @PeteSwauger. I expected help to show up as well.

**Comment by JTonda** [comment]
_From @AHumanFromCA on July 2, 2018 15:15_

What is the timeline for when we want this to be released?

This change is a  **Major** change and will require Brightside to be bumped to 2.0 since we are GA with 1.0

**Comment by JTonda** [comment]
_From @zFernand0 on July 2, 2018 16:15_

Hello all,

The reason for my downvotes is simply because we should be consistent with our own statements.

When we "refactored" the list commands, we went with the argument that other listing mechanisms and Operating Systems do leave it empty (Like a Linux-ish `ls` command).

And now I strongly believe that we should be consistent with how other package managers let you install things. 

Feel free to look at:
- NPM (Node Package Manager) manages node.js libraries
- APT (Advanced Packaging Tool) manages packages for various Linux distributions
- YUM (Yellowdog Updater Modified) package management tool for RPM (RedHat Package Manager) based Linux systems (Example: Oracle Linux).

And there are more.

**Comment by JTonda** [comment]
_From @jelaplan on July 3, 2018 19:16_

I'm with Sujay and Pete. I have ran into this before. I would type $bright and get help then $bright files and get help and keep drilling down that way but at the leaf, it changes behavior and executes the command. The lack of consistency is going to foul a lot of people. A second issue is that the system should be able to anticipate that the statement is incomplete. Our standard approach to an icomplete command is to fall back to showing the help. If we don't show the help, we should at least handle it more gracefully rather than run through a whole bunch of process that takes minutes to finish as is the case with the profiles command. The system should be able to detect a command without an argument and either prompt the user for the argument or simply tell the user that they need a argument. This problem fall under a long understood heuristic named error prevention - see item 5 in this list. https://blog.prototypr.io/10-usability-heuristics-with-examples-4a81ada920c

**Comment by JTonda** [comment]
_From @SujaySolomonCA on July 5, 2018 0:40_

@zFernand0 I would argue that Brightside is *not* a package manager, and has other UX norms that need to be kept consistent. I understand that the "bright plugins" group provides some package management functionality, but it is not a standalone package management tool like npm. IMO, the Brightside UX norms should take precedence over being consistent other stand-alone package managers.

**Comment by MikeBauerCA** [comment]
Closing as we will not be adding another level to the commands at this point. With regards to plugin management, I think the next step would be to maintain this in the single shared configuration that has been introduced for validation in `@zowe/cli@next`. Maybe allow for multiple package managers to be used as well.
