### ISSUE TITLE
Port Etag functionality from @lts-incremental to @master

### ISSUE THREAD

**Issue by Alexandru-Dumitru** [zowe/zowe-cli#596]
Recent PR https://github.com/zowe/zowe-cli/pull/588 was accepted in @lts-incremental branch. It would be good to have the same updates in @master

**Comment by Alexandru-Dumitru** [comment]
This one also needs to go in during the porting: https://github.com/zowe/zowe-cli/pull/610

**Comment by zFernand0** [comment]
Ported!
Thanks @Alexandru-Dumitru
