### ISSUE TITLE
Refactor Download.dataSet method in @lts-incremental

### ISSUE THREAD

**Issue by Alexandru-Dumitru** [zowe/zowe-cli#597]
I noticed in [packages/zosfiles/src/api/methods/download/Download.ts](https://github.com/zowe/zowe-cli/blob/lts-incremental/packages/zosfiles/src/api/methods/download/Download.ts) for the `dataSet` method we are using directly calls to `ZosmfRestClient` to get the content of the data set, but in `ussFile` we call `Get.USSFile` which in turn calls `ZosmfRestClient`. The issue is that we also have `Get.dataSet` which is basically duplicating the code in `Download.dataSet`.

I propose that we refactor `Download` class and have more consistency and less code to maintain by calling as well `Get.dataSet` from `Download.dataSet`. This action should not introduce any breaking change.

Something to take into consideration is that in @master, `Download` methods are calling directly `ZosmfRestClient` so I would agree on the opposite action as well, meaning to refactor `Download.ussFile` to call directly `ZosmfRestClient` and remove dependency on `Get.USSFile` while keeping code integrity.

**Comment by tjohnsonBCM** [comment]
@Alexandru-Dumitru Is this refactoring still needed now that @lts-incremental is only receiving patch updates?

**Comment by Alexandru-Dumitru** [comment]
@tjohnsonBCM No, I guess not 😄 . Thanks
