### ISSUE TITLE
Expose Etag option via CLI 

### ISSUE THREAD

**Issue by Alexandru-Dumitru** [zowe/zowe-cli#598]
PR https://github.com/zowe/zowe-cli/pull/588 added option to request and pass an Etag while working with data sets and uss files. This feature is implemented only at the API level, since there was a need in https://github.com/zowe/vscode-extension-for-zowe/milestone/12.
We should look into exposing this feature via the CLI as well. 

Things to consider:
- how do we return the Etag on download for a single file
    - print to console? (needs scraping and storing)
    - assign some local environment variable which user can read afterwards?
    - combination of both?
- how do we return Etags when downloading a PDS (all members)
- passing Etag while uploading a single file should be pretty straightforward (optional parm, something like --etag _string_)
- how do we pass Etags (if we have them for each file) when uploading a directory to USS or PDS

Please, feel free to add your suggestions on this topic.

Thanks

**Comment by dkelosky** [comment]
@Alexandru-Dumitru and @zFernand0,

Fernando had a nice API idea for RestClient, but if it's too difficult to implement, I was wondering if this would suffice for now for what you need: https://github.com/zowe/imperative/issues/318#issuecomment-551188955
