### ISSUE TITLE
zos-files help changes

### ISSUE THREAD

**Issue by JTonda** [zowe/zowe-cli#60]
_From @PeteSwauger on May 30, 2018 16:17_

Updated text below:

   create | cre  Create z/OS data sets
   delete | del  Delete z/OS data sets
   download | dl Download content from z/OS data sets and USS files
   invoke | call Invoke various z/OS utilities
   list | ls     List the details for z/OS data sets and the members in the data sets
   upload | ul   Upload files to z/OS data sets

_Copied from original issue: gizafoundation/brightside#120_

**Comment by JTonda** [comment]
_From @zFernand0 on August 20, 2018 15:24_

The help for `bright zos-files` reads:
![image](https://user-images.githubusercontent.com/37381190/44349491-24c2c400-a46b-11e8-81bd-e394353a6d80.png)

I assume the issue is that we don't always say `z/OS data sets`, and we should.

@PeteSwauger, any comments?

**Comment by MikeBauerCA** [comment]
I'd vote to drop the "z/OS" from "z/OS data sets" for the upload and download commands - just trying to keep the short help short. What do you think @zFernand0? I think it is good to leave "z/OS utilities" alone.

**Comment by zFernand0** [comment]
100% agree with `keep the short help short`.

Does that mean that we want to leave the `z/OS Data Sets` in the long descriptions (e..g `zowe files create --help`)?

**Comment by MikeBauerCA** [comment]
I don't have a strong opinion as those descriptions are okay to be a little longer. But the long descriptions should all be consistent. And the short descriptions should all be consistent.
