### ISSUE TITLE
"zowe zos-jobs submit stdin" command is not working

### ISSUE THREAD

**Issue by LUCASMA96** [zowe/zowe-cli#601]
Client version:
```
zowe --version
2.32.1
```

I am trying to run the following code shell script. In the file "gen_compiler.txt" there is a JCL code,  I basically bring it to the variable "gen_compiler" replacing some variables and then I run the stdin command:

```
#!/bin/bash

#testing command

member="EC2CID2"
gen_compiler=$(cat ./base/gen_compiler.txt | sed "s/<program>/$member/g" | sed "s/<language>/PLIEDB/g" | sed "s/<rexx_param>/$member/g")

echo "$gen_compiler" | zowe zos-jobs submit stdin
```

I am getting the following error:

<img width="1200" alt="image" src="https://user-images.githubusercontent.com/28960846/69250670-e0066b00-0b8e-11ea-869e-a9dceca6b149.png">

**Comment by ChrisBoehmCA** [comment]
It seems like the code for submit standard in didn't make it into the Submit.shared.handler in the lts-incremental branch which might be causing this problem.  Should hopefully be a simple fix

**Comment by LUCASMA96** [comment]
The issue has already been fixed! Thank you so much for your support!
