### ISSUE TITLE
zowe uss issue ssh command name

### ISSUE THREAD

**Issue by dkelosky** [zowe/zowe-cli#603]
Should `zowe uss issue ssh` be `zowe uss issue command` instead?  

More like:
- `zowe tso issue command`
- `zowe console issue command`

**Comment by fbeyl** [comment]
For the sake of completeness only, since the connection is to z/OS Openssh shouldn't it be
 zowe ssh issue command ?

**Comment by Jazzy-Jeff** [comment]
Hi all, going to work on this issue. Can someone please assign me? Looks like I may not have permission to do so. Thanks!
