### ISSUE TITLE
Issue in Allocate Data Set

### ISSUE THREAD

**Issue by savita2426** [zowe/zowe-cli#609]
We have multiple commands for allocating data set in Zowe like:

1. data-set-binary | bin - Create executable data sets
2. data-set-c | dsc - Create data sets for C code programming
3. data-set-classic | classic - Create classic data sets (JCL, HLASM, CBL, etc...)
4. data-set-partitioned | pds - Create partitioned data sets (PDS)
5. data-set-sequential | ps - Create physical sequential data sets (PS)
  
But when we execute below 4 commands , it will create PDS only.
•	data-set-binary | bin 
•	data-set-c | dsc 
•	data-set-classic | classic
•	data-set-partitioned | pds 
 
1.	Does that mean we can allocate only 2 types of data set—Partitioned and Sequential ?
Can you suggest us how we can differentiate from inputs that user wants to create Partitioned data set or Sequential.
 
2.	We have an input Data Set Type in these commands. Allowed values are—BASIC, PDS and LIBRARY. 
Please share other allowed values for Data Set Type if left.

**Comment by dkelosky** [comment]
Which version of Zowe CLI do you have installed?

For: 
```
C:\>zowe -V
6.1.0
```

We have:
```
COMMANDS
 --------

   data-set-binary | bin      Create executable data sets
   data-set-c | dsc           Create data sets for C code programming
   data-set-classic | classic Create classic data sets (JCL, HLASM, CBL, etc...)
   data-set-partitioned | pds Create partitioned data sets (PDS)
   data-set-sequential | ps   Create physical sequential data sets (PS)
   data-set-vsam | vsam       Create a VSAM cluster
   uss-directory | dir        Create a UNIX directory
   uss-file | file            Create a UNIX file
   zos-file-system | zfs      Create a z/OS file system
```

Perhaps you can try your use case with the installed version from `npm install -g @zowe/cli`?

**Comment by savita2426** [comment]
Hi, 
We have 2.31.1 version of Zowe.
Currently, we have moved forward with 2 commands in our use case i.e.
1. data-set-partitioned | pds Create partitioned data sets (PDS)
2. data-set-sequential | ps   Create physical sequential data sets (PS)

I think you can close this issue for now.
