### ISSUE TITLE
Incorrect links and spelling in CLIReadme.md

### ISSUE THREAD

**Issue by JDUNNIN** [zowe/zowe-cli#613]
1. zos-files download/list data-set links to delete data-set command. This is because they are using the same # ref.
2. ssh-profile update has misspellings of "private" in the example

**Comment by zFernand0** [comment]
I believe this could be resolved in the Imperative.helpGenerator. 
That way it's fixed everywhere : )

**Comment by JDUNNIN** [comment]
The code to generate the CLIReadme.md is in `/gulp/DevelopmentTasks.ts`. Looking at this I've spotted that there are more links which don't resolve to the correct place because of the same #ref value.
