### ISSUE TITLE
zowe cli files upload ftds timeout

### ISSUE THREAD

**Issue by pbartak** [zowe/zowe-cli#622]
This timeout appears to be received from z/OSMF. Is there a way to modify the request via zowe cli to increase the timeout interval?

error: 
  message: 
          z/OSMF REST API Error:
      Rest API failure with HTTP(S) status 500
      rc:       4
      reason:   1
      category: 2
      message:  receiveResponseHeader: timeout receiving response (>30 secs): TsoServerConnection(USER=xxxxxxx, ASID=0x00fe, QID=0x0005001b)

**Comment by awharn** [comment]
For anyone finding this issue, the option `--response-timeout` was added, and can increase the timeout to up to 10 minutes (600 seconds), the maximum allowed value of the z/OSMF API.
