### ISSUE TITLE
Downloading all members of the dataset changes their names in lowercase

### ISSUE THREAD

**Issue by zimlu02** [zowe/zowe-cli#631]
The following command to download all members of the specified dataset renames all files in lowercase:

zowe files dl am "mydsn.files.asm" -d myfiles -e asm

This definitely matters in case of assembler files that use references to macros in uppercase format only.

To download an HLASM file and all its macros we need to preserve their exact names.
Parameter to specify the case of downloaded files would be a great help.

**Comment by MikeBauerCA** [comment]
I agree with preserving the exact names.

Ideally, I think this would be the default behavior. However, changing the default behavior would be a breaking change that might impact many scripts.

Perhaps a flag to change the behavior to preserve the uppercase format would be a good first step. 

I recognize the same behavior when downloading a single member so this flag should be added to the `zowe files download ds` command as well.

**Comment by zFernand0** [comment]
I may not understand the full implications of this, however, I believe that if you were to use the CLI to upload them back, they will all be uploaded in uppercase. Someone can correct me if I'm wrong though.

I'm not saying we couldn't improve, I'm just trying to provide some piece of mind : )

**Comment by zimlu02** [comment]
That's correct - from that perspective, it would rather make more sense to keep it uppercase all the time, wouldn't it? As Mike mentioned, keep it as a default. 
Anyway - for the use case I've mentioned initially, we need all locally downloaded files to stay uppercase. We're talking about hundreds of files referenced in the case-sensitive code.

**Comment by liuxh0** [comment]
Hi all,
I'm trying to follow this issue. As I understand, we want an additional option for download to keep folders and files in original case (which is always uppercase), right?

**Comment by zimlu02** [comment]
Correct, this issue is about being able to download folders and files in the **original case**.
(whether it is always uppercase or not is actually not relevant)

**Comment by liuxh0** [comment]
Then I will try to create a PR asap :-)
