### ISSUE TITLE
Add Support for Code Page Setting Through Zowe CLI

### ISSUE THREAD

**Issue by dkelosky** [zowe/zowe-cli#632]
We've had several requests to support alternate code pages through Zowe CLI and should support code page for Zowe CLI file operations via [PH15263](https://www-01.ibm.com/support/docview.wss?rs=63&uid=isg1PH15263).

**Comment by F-LEMANER** [comment]
Hello,
Is codepage setting available now ?
My config : z/OSMF 2.3 ZOWE 1.9
Thanks and regards

**Comment by dkelosky** [comment]
Hi @F-LEMANER  - not yet.  Are you also using Zowe CLI on your workstation or only using the Zowe "Desktop" (browser-based Zowe UI)?

**Comment by F-LEMANER** [comment]
Hello, I'm not using CLI because I'm not a developper. As zOS system engineer I have installed ZOWE and just use JES and MVS explorers to validate the installation. But our developpers want to use CLI.

Do you have an planned date for support of codepage ?
Regards

**Comment by Marty850** [comment]
I'm also very interested in this feature for CLI! ZOWE file upload is useless for us because of that issue and it would be such a great possibility to do automatic deployment.

I'm checking the satus of this issue every week ;-)

**Comment by dkelosky** [comment]
Sorry for the delay - we will be working on this in the coming weeks.

**Comment by FALLAI-Denis** [comment]
Hi
Please, see comment in [#260](https://github.com/zowe/vscode-extension-for-zowe/issues/260#issuecomment-634991101).

**Comment by dkelosky** [comment]
@venkatzhub do you have any insight to add here?

**Comment by dkelosky** [comment]
@Marty850 the code is completed and should be available on the next published release - `6.14.0`
