### ISSUE TITLE
secondary allocation doesn't compute to 10% when creating data-sets

### ISSUE THREAD

**Issue by Alexandru-Dumitru** [zowe/zowe-cli#635]
## Problem

In help, it is stated that if we use `--size` when creating a data set, the secondary allocation will be ~10% of primary. This does not happen, and it always allocates to the value of 1.

Issue was raised in #zowe-cli slack channel.
## Version
User's version: 2.32.1
I tested on: 2.36.0

## Reason

Was looking through source code and found that the `--ss` option gets a default value of 1 if it is not specified, thus the condition to calculate 10% of primary is never met. It is either 1, the default, or other value passed by user via cli with `--ss` optional param.

https://github.com/zowe/zowe-cli/blob/150814dfa668ebcb0171a05d234904d4c5c14572/packages/zosfiles/src/api/methods/create/Create.ts#L49
https://github.com/zowe/zowe-cli/blob/150814dfa668ebcb0171a05d234904d4c5c14572/packages/zosfiles/src/api/methods/create/Create.ts#L93

## Desired outcome
If `--size` is used, then 10% should be computed and used for secondary allocation.
If neither `--size` and `--ss` are used, then they both should default to 1, as expected.

**Comment by zFernand0** [comment]
There might be a few more implications behind this one.
Notes:
- Exposure of the primary allocation option (Description, definition, ...)
- Default Secondary IFF `Size == null` and `Primary != null`
- Add/modify test for "new" option
- Create test that captures this bug : )
