### ISSUE TITLE
"bright help" does not display top level help

### ISSUE THREAD

**Issue by JTonda** [zowe/zowe-cli#64]
_From @MikeBauerCA on May 16, 2018 11:33_

We should handle this situation better. My suggestion would be to display the help for the user.

![help](https://user-images.githubusercontent.com/35504792/40114496-2af8c6d4-58db-11e8-97b8-e8ffb145676a.PNG)

_Copied from original issue: gizafoundation/brightside#72_

**Comment by JTonda** [comment]
_From @dogboydog on May 16, 2018 11:44_

Hi, 

We could make "help" always work as --help possibly. We didn't in the past because there was a `bright help` group of commands. If we don't think we'll implement that group (might be good to start thinking of an alternative name for that group for searching help, displaying explanations etc) then I think it'd be good to make this an optional feature of imperative

**Comment by JTonda** [comment]
_From @MikeBauerCA on May 16, 2018 11:55_

We should also consider improving our help when users mistype. 

Instead of 
![typo](https://user-images.githubusercontent.com/35504792/40115200-a4788894-58dd-11e8-942a-f9ac5a2e6119.PNG), 
perhaps we inform the user of how they can get to the help and what groups are available. We need to work with UX on this effort. It seems in the case of the screenshot I provided, we were unable to determine that the user was attempting to issue bright zos-console.

**Comment by JTonda** [comment]
_From @dogboydog on May 16, 2018 12:34_

True! I think it would be good to enhance the "did you mean" to work better in general, to work with suggesting full commands instead of just groups. If you type a few more letters, you'll probably get `zos-console` as a suggestion, but I guess the "Levenshtein distance" between `zos-con` and `zos-jobs` must be shorter

**Comment by jelaplan** [comment]
Seee 127 Re-introduce the Help Group into the Imperitive based CLI

**Comment by gejohnston** [comment]
These behaviors have since been implemented in the product.
