### ISSUE TITLE
Not possible to issue db2 commands via zowe zos-console

### ISSUE THREAD

**Issue by Marty850** [zowe/zowe-cli#641]
I noticed that it's not possible to run db2 commands via zos-console because of the '-'.

Example:
zowe zos-console issue command "-db1t display ddf"
Command Error:
Unknown arguments: 1, d, b, t
Command failed due to improper syntax
Command entered: "zowe zos-console issue command --1 true --d true --b true --t  display ddf"
Available commands are "command".
Use "zowe zos-console issue --help" to view groups, commands, and options.
Error Details:
Unknown arguments: 1, d, b, t

**Comment by ChrisBoehmCA** [comment]
This does seem to be a bug, but does this work for you?

`zowe console issue command "\-db1t display ddf"`

**Comment by Marty850** [comment]
Hi @ChrisBoehmCA,
yes, it works! Thank you very much.
I think it would be good to fix it or to document the escape character \ in the CLI reference ;-)
Kind regards
Martin

**Comment by katsoohoo** [comment]
Can I take a look at this issue? Need someone to assign me again :)

**Comment by t1m0thyj** [comment]
@katsoohoo Sure, go for it 🙂 I've assigned the issue to you
