### ISSUE TITLE
Document example of deleting data set members

### ISSUE THREAD

**Issue by JDUNNIN** [zowe/zowe-cli#643]
Currently I can create a member in a data set by uploading from a file (or std-in) e.g.
```
Upload file contents to a PDS member named "ibmuser.pds(mem)":
zowe zos-files upload file-to-data-set "file.txt" "ibmuser.pds(mem)"
```

Once I've used this member and no longer need it, I would like to be able to delete the data set member using a command like:

`zowe zos-files delete data-set-member "ibmuser.pds(mem)"`

I only see the ability to delete the whole data set
```
Delete the data set named 'ibmuser.pds':
$ zowe zos-files delete data-set "ibmuser.pds" -f
```
or delete part of z/OS file system
```
Delete the z/OS file system 'HLQ.MYNEW.ZFS':
$ zowe zos-files delete zos-file-system "HLQ.MYNEW.ZFS" -f
```
If either of these commands do work for data set members, I think the examples provided in `zowe-cli/docs/CLIReadme.md` should be expanded to include this use case.

**Comment by awharn** [comment]
Looking at the z/OSMF documentation, and our implementation of the command, it is possible to delete a dataset member by issuing the command `zowe zos-files delete data-set "ibmuser.pds(mem)"`. However, I do not believe this is documented anywhere, and should be added to documentation.

**Comment by JDUNNIN** [comment]
> Looking at the z/OSMF documentation, and our implementation of the command, it is possible to delete a dataset member by issuing the command `zowe zos-files delete data-set "ibmuser.pds(mem)"`. However, I do not believe this is documented anywhere, and should be added to documentation.

Thanks for confirming! I just spotted deleting members in the Zowe VSCode documentation. Before this I was reluctant to try in case it deleted the whole data set by mistake.

Adding to the documentation in example section would be good.
