### ISSUE TITLE
CLI does not support Rexx which uses ISPF 

### ISSUE THREAD

**Issue by markons** [zowe/zowe-cli#645]
I'm testing a Rexx module which uses the ISPEXEC service, which will be shown as erroneus, see screenshot. 
Is it possible at all to call ISPF services when I call the Rexx module by using the ZOWE TSO as in the screenshot?
  
![image](https://user-images.githubusercontent.com/2115566/72965533-dbdc1100-3dbc-11ea-89ca-ef415c03fd0e.png)

**Comment by dkelosky** [comment]
I want to look at this more - I tried two examples, one in CLIST - `KELDA16.CLIST(EXAMPLE)`:

```
ISPEXEC CONTROL ERRORS RETURN 
```

And one in REXX - `KELDA16.CLIST(EXAMPLE2)`:

```
/* REXX */                 
Address ISPEXEC            
"CONTROL ERRORS RETURN"    
```

For the CLIST I get:

```
C:\dev>zowe tso issue command "ex 'kelda16.clist(example)'"
IKJ56455I KELDA16 LOGON IN PROGRESS AT 07:34:04 ON JANUARY 23, 2020
IKJ56951I NO BROADCAST MESSAGES
READY

ISPS118L SERVICE NOT INVOKED. A VALID ISPF ENVIRONMENT DOES NOT EXIST.
READY
```

For the one in REXX:

```
C:\dev>zowe tso issue command "ex 'kelda16.clist(example2)'"
IKJ56455I KELDA16 LOGON IN PROGRESS AT 07:34:14 ON JANUARY 23, 2020
IKJ56951I NO BROADCAST MESSAGES
READY

     3 *-* "CONTROL ERRORS RETURN"
       +++ RC(-3) +++
READY
```
I think the CLIST error message: `ISPS118L SERVICE NOT INVOKED. A VALID ISPF ENVIRONMENT DOES NOT EXIST.` gives better details into the problem.

**Comment by fbeyl** [comment]
If you want to use ispf in rexx ispf libraries must be allocated before. This can be done in the tso logon procedure or in the rexx. Zowe adresses z/osmf to start tso session and invoke rexx in it. I think the default logonprocedure does not contain these allocs but you can define one that does and pass that logonproc to zowe in the profile or in the command as --logon-procedure.
This is not a zowe issue but a tso logonproc setup problem.

**Comment by markons** [comment]
Dear all,

thanks for the hint, I will checkit out.

Regards


Am Di., 18. Feb. 2020 um 22:02 Uhr schrieb fbeyl <notifications@github.com>:

**Comment by markons** [comment]
Hi all,

perhaps this one could be the solution:

[image: image.png]

Regards

Am Mi., 19. Feb. 2020 um 13:50 Uhr schrieb Gabor Markon <markons@gmail.com>:

**Comment by fbeyl** [comment]
The image in comment is not visible

**Comment by fbeyl** [comment]
Might be the ispf profile allocation that's missing.

**Comment by fbeyl** [comment]
What you want to achieve has to be done in two phases. 1)The zowe tso command starts a clist or rexx which allocates the necessary libraries (if they're not in logonproc) and 2) starts your rexx with ispf by using the ISPSTART CMD(yourrexx). The ispstart command builds the ispf environment and from then on all ispf functionality is available to your rexx.

**Comment by markons** [comment]
Thank you for the clarification!

Am Do., 20. Feb. 2020 um 22:38 Uhr schrieb fbeyl <notifications@github.com>:

**Comment by FALLAI-Denis** [comment]
In the case of a rexx program using ISPF functions, the rexx program must run under the control of ISPF, with a hierarchy: 
1) TSO : IKJEFTxx
2) ISPF : ISPSTART
3) Rexx : CMD(xxx)
5) ISPF services 

I suggest calling a Rexx « bootstrap » that will start ISPF that will start the target Rexx program.

**Comment by awharn** [comment]
This issue appears to have been resolved over 2 years ago. Therefore, the issue is being closed. If it is not resolved, please re-open the issue.
