### ISSUE TITLE
Enhancement request for zos-files create [dsn] like [dsn] command

### ISSUE THREAD

**Issue by JTonda** [zowe/zowe-cli#65]
_From @lyzla01 on April 19, 2018 21:12_

From my experience with creating z/OS data set via 3270 panel, most of the time I do not want to create a brand new data set where I came up with all of the attributes.  But instead I wanted to create a data set that have similar attribute to another data set that was created by someone else.  

There for it would be nice if I can issue something like 
```
Bright files create [new dsn] like [old dsn]
```
to create a new data set that have same attributes of the old data set.
or 
```
Bright files create [new dsn] like [old dsn] [overwrite attributes]
```
to create a new data set that have similar attributes of the old data set with the only different are the overwrite attributes.    

_Copied from original issue: gizafoundation/brightside#25_

**Comment by JTonda** [comment]
_From @dogboydog on April 19, 2018 21:20_

I have wanted this exact feature before! Would definitely be a good command to have.

**Comment by JTonda** [comment]
_From @zFernand0 on April 20, 2018 11:38_

That's an awesome suggestion.
We just have to make @MikeBauerCA aware of this useful feature and get it prioritized :smiley:

**Comment by JTonda** [comment]
_From @AHumanFromCA on April 20, 2018 13:1_

I like this idea too. +1

**Comment by JTonda** [comment]
_From @MikeBauerCA on April 20, 2018 13:51_

Great idea! To conform to the current structure, what do we think about:

`bright files create data-set-like <old dsn> <new dsn> [overwrite attributes]`

**Comment by JTonda** [comment]
_From @dkelosky on April 26, 2018 14:49_

@MikeBauerCA There will likely be a plugin (developed by another team) to accomplish this or something close to it.  We'll have to coordinate doing something like this to prevent duplicating efforts.

**Comment by ChrisBoehmCA** [comment]
Mark Eddy and I  were discussing this enhancement. I think it would be a great addition. Here's how I think it could work:

`zowe zos-files create data-set-like  model.data.set  new.data.set -v TSU`
* Call  the list data set with attributes API to get the attributes of the 'model' data set. Map these attributes where appropriate to the format accepted by the create data set API. 
* Provide all of the data set attributes as CLI options as in the other 'create data set' commands
* Merge the attributes together, with the CLI options specified by the user taking precedence
* Create the data set

**Comment by tucker01** [comment]
In the meantime (before a dedicated command is available 😄 ), you can do the following:

```
$ zowe tso issue cmd "ALLOCATE DATASET('PUBLIC.TEST.LIKE') LIKE('PUBLIC.LIB.CNTL')"
IKJ56455I LOGON IN PROGRESS AT 09:30:21 ON JUNE 26, 2019
IKJ56951I NO BROADCAST MESSAGES
READY

READY

```
There is no real response from the command, but the data-set should be created (errors will appear if there is a problem).

**Comment by ChrisBoehmCA** [comment]
Thanks for the workaround : D

**Comment by t1m0thyj** [comment]
> Mark Eddy and I were discussing this enhancement. I think it would be a great addition. Here's how I think it could work:
> 
> `zowe zos-files create data-set-like model.data.set new.data.set --vs TSU`
> 
> * Call  the list data set with attributes API to get the attributes of the 'model' data set. Map these attributes where appropriate to the format accepted by the create data set API.
> * Provide all of the data set attributes as CLI options as in the other 'create data set' commands
> * Merge the attributes together, with the CLI options specified by the user taking precedence
> * Create the data set

A command like this now exists in Zowe CLI:
`zowe zos-files create data-set NEW.DATASET --like EXISTING.DATASET --lrecl 1024`
