### ISSUE TITLE
zowe-cli-plugin does not install

### ISSUE THREAD

**Issue by markons** [zowe/zowe-cli#661]

**Comment by markons** [comment]
C:\Users\H19257984\AppData\Roaming\npm>node --version
v10.16.0

C:\Users\H19257984\AppData\Roaming\npm>npm -v
6.9.0

C:\Users\H19257984\AppData\Roaming\npm>node -v
v10.16.0

C:\Users\H19257984\AppData\Roaming\npm>zowe -V
2.31.2

![image](https://user-images.githubusercontent.com/2115566/73752338-15b7fa80-4761-11ea-85ed-da3446dbe3dc.png)

**Comment by zFernand0** [comment]
Hey @markons,
I noticed you are using the Zowe-cli-package for 1.5.0 (based on your path), and you are trying to install the sample plugin  from the tutorials?

Is it possible to grab the latest available Zowe CLI package (should be 1.7.0)

**Comment by zFernand0** [comment]
Hey @markons,
Is this still an issue? 
It could be related to a circular dependency on the sample plugin too. : )

**Comment by markons** [comment]
Hi,

Sorry, I had no time to test ( production issues in my shop). Thanks first.

Regards

2020. febr. 12., Sze 15:22 dátummal Fernando Rijo Cedeno <
notifications@github.com> ezt írta:
