### ISSUE TITLE
setMessage accepts values, but no doc on usage

### ISSUE THREAD

**Issue by scifipony** [zowe/zowe-cli#663]
In IHandlerResponseDataApi find:
    /**
     * Sets the JSON response API "message" property. Can optionally be logged. The intent is to provide a short
     * summary on the response JSON object (for display and other purposes).
     * @param {string} message
     * @param {...any[]} values
     * @returns {string}
     * @memberof IHandlerResponseDataApi
     */
    setMessage(message: string, ...values: any[]): string;

What are the values used for?  This is not documented.  Is this something like printf in the C stdlib, and if so, what's the replacement syntax.

Besides the github file, Googling setMessage get only one relevant hit, but it uses string templates instead of values:
https://github.com/zowe/zowe-cli/issues/502

Any info would be helpful, and if there is any, please update the file at:
https://github.com/zowe/imperative/blob/master/packages/cmd/src/doc/response/api/handler/IHandlerResponseDataApi.ts

**Comment by tjohnsonBCM** [comment]
The values get passed to the method `TextUtils.formatMessage` which is defined here: https://github.com/zowe/imperative/blob/master/packages/utilities/src/TextUtils.ts#L251

It appears that `values` can be supplied in 2 different formats:
* A list of values to be inserted into the string `message` ("printf" style)
* An object containing key-value pairs to be rendered in the Mustache template string `message`

Additional documentation for the method `IHandlerResponseDataApi.setMessage` would be welcome 😄

**Comment by apsychogirl** [comment]
Hi, Can I make the amendments in the document? 
@tjohnsonBCM

**Comment by tjohnsonBCM** [comment]
@apsychogirl Feel free to assign yourself to the issue and open a PR with added documentation 😄

**Comment by Nike682631** [comment]
is this issue still open or a pr has already been made?

**Comment by t1m0thyj** [comment]
@Nike682631 This issue is still open, feel free to work on it 😄

**Comment by namanpatel1112** [comment]
Made PR: https://github.com/zowe/imperative/pull/616

**Comment by namanpatel1112** [comment]
PR is merged into master branch. I'll close this issue now. :)
