### ISSUE TITLE
Unable to delete profile

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/zowe-cli#665]
If you have unsecure profiles, then install the secure-credential-store plugin and try to delete an unsecure profile, a failure message results. I had to first overwrite the profile (create command with `--ow` flag) before I could delete it. 

Deleting a profile is a local action and should not require a profile to be loaded.

**Comment by tjohnsonBCM** [comment]
Fixed in https://github.com/zowe/zowe-cli-scs-plugin/pull/7
