### ISSUE TITLE
"zowe zos-files" command returns 0 when attempting to upload file to a non-existing data set

### ISSUE THREAD

**Issue by MatthewB19** [zowe/zowe-cli#667]
When I try to upload a file to a data set using `zowe zos-files` and the data set does not exist, Zowe CLI returns the API response (failure) with the correct error (`IKJ56228I DATA SET MB891192.ABCDK NOT IN CATALOG OR CATALOG CAN NOT BE ACCESSED`) but the actual return code of the `zowe` command is `0` (success)

Reading the comments in #436, it seems like the command itself should return `1` (failure) because of the error

**Comment by tjohnsonBCM** [comment]
Thanks for reporting this, closing because it is the same as #567
