### ISSUE TITLE
Contributing.md needs enhanced with information on how to open issues

### ISSUE THREAD

**Issue by JTonda** [zowe/zowe-cli#67]
_From @MarkAckert on April 17, 2018 12:27_

[MIGRATED]

It's nice the fact that we now have a CONTRIBUTING.md file.
However, there is no information on how to open an issue.

So, it would be nice if had some information there given that GitHub itself recommends you to see the contributing guidelines.

![a705c702-3e57-11e8-92f8-bdd0969e9a77](https://user-images.githubusercontent.com/37381232/39053634-8828a990-447d-11e8-9108-9e8eccb0ac29.png)

_Copied from original issue: gizafoundation/brightside#11_

**Comment by JTonda** [comment]
_From @AHumanFromCA on April 20, 2018 13:32_

@zFernand0 Are you suggesting that we should also do Issue and PR templates?

Also should we have a similar issue opened up for imperative cli?

**Comment by MarkAckert** [comment]
Closing this issue. The process to open issues is clear and we've added templates which help users identify what information they should supply.
