### ISSUE TITLE
Update shebang line in linux-environment-setup.sh

### ISSUE THREAD

**Issue by kdbeall** [zowe/zowe-cli#673]
In [linux-environment-setup.sh](https://github.com/zowe/zowe-cli/blob/master/tools/linux-environment-setup.sh) consider updating the shebang 
from `#!/bin/bash` to `#!/usr/bin/env bash`.

Changing to the shebang to `#!/usr/bin/env bash` allows handling the case where bash is installed in a different directory.

**Comment by piculet** [comment]
Hi @zFernand0, I'd like to work on this issue.

**Comment by zFernand0** [comment]
Hey @piculet, 
Feel free to assign yourself to the issue and open a PR. :+1:
