### ISSUE TITLE
Testing infrastructure improvements

### ISSUE THREAD

**Issue by JTonda** [zowe/zowe-cli#68]
_From @MarkAckert on April 17, 2018 12:26_

[MIGRATED]

Few items need to be addressed (considered, etc.) for Brightside testing:

Should the "pretest" task globally install Brightside for usage in the CLI tests?

For SetupTestEnvironment we should consider setting the cliHomeEnvVar to the imperative config home ENV var for Brightside (overriding the home directory). This way, test data (logs, profiles, etc.) can be placed in a subdirectory of __results__/data for review & test isolation purposes. Docker was experimented with for this purpose, however docker presents a "barrier to entry" for developers (required as a dependency and often difficult to configure on Windows 7 machines) and can be slow.

As of right now, the CLI tests use the users (developers) profiles. We should consider (especially after addressing 2 in this list) creating profiles as part of the tests. This way, we can control the systems & users for system tests.

_Copied from original issue: gizafoundation/brightside#10_

**Comment by JTonda** [comment]
_From @tucker01 on April 26, 2018 15:28_

Most of this is addressed in PR Introduce + use utilities to easily create and clean up profiles from test properties 
No longer uses the global profiles during the tests. It will create the profiles in an isolated data area under `__tests__`.

The final outstanding topic is should we install/npm link automatically during the tests.

**Comment by ChrisBoehmCA** [comment]
This has been solved by the work Chris W. did to run using the locally compiled version of the CLI rather than the globally installed one
