### ISSUE TITLE
User field in SSH profile should be secure

### ISSUE THREAD

**Issue by ghost** [zowe/zowe-cli#682]
The password field of an SSH profile is secure, but the user field is not.
https://github.com/zowe/zowe-cli/blob/f5d82918db5cce5aa8eec4a4c4fbf63bbcd49503/packages/imperative.ts#L172-L180

Changing a profile field from non-secure to secure could be a breaking change depending on how it is handled. We should consider making this change in a backwards compatible way, that could migrate an existing SSH profile with user stored insecurely to have it stored securely.

**Comment by MikeBauerCA** [comment]
@t1m0thyj this would be possible with the new team configuration approach since you can securely store any property you want, is that correct?

**Comment by t1m0thyj** [comment]
That's right, a benefit of team config is that it should be possible to store SSH user securely now 🙂 But we should still update the SSH profile schema to set `secure=true` for the user property.
