### ISSUE TITLE
Renaming Profiles

### ISSUE THREAD

**Issue by jelaplan** [zowe/zowe-cli#702]
The update command of profiles allows changing most values but not the name of the profile. This would be a helpful addition. 
zowe → profiles → update → zosmf-profile

**Comment by FALLAI-Denis** [comment]
One solution could be to create a new profile from an existing profile.
For that it would be necessary that the command "zowe profiles create" accepts in parameter the reference to another profile.

**Comment by gejohnston** [comment]
The Zowe V1 release is in maintenance mode, so no enhancements will be made to that release. The profile commands are deprecated in V2, so no enhancements to those command are planned in V2 either.
