### ISSUE TITLE
MVS explorer codepage

### ISSUE THREAD

**Issue by F-LEMANER** [zowe/zowe-cli#704]
Hello,
When reading a file via z/OSMF ISPF , French accuentued caracters are correctly displayed because I set codepage 1147 France Euro instead of 1047 USA

![image](https://user-images.githubusercontent.com/63342548/79985661-3dd71000-84ab-11ea-8270-468ff07edf84.png)

With ZOWE MVS explorer, display is incorrect 

![image](https://user-images.githubusercontent.com/63342548/79985798-6ced8180-84ab-11ea-9033-eab95bb225e6.png)

Where is it possible to specify a codepage ?
Thanks and regards

**Comment by dkelosky** [comment]
Similar to https://github.com/zowe/zowe-cli/issues/705#issuecomment-617807777

**Comment by F-LEMANER** [comment]
Issue reopened in zlux-server-framework
