### ISSUE TITLE
MVS Explorer Fetch members failed for USR$.B024522.CNTL

### ISSUE THREAD

**Issue by F-LEMANER** [zowe/zowe-cli#705]
Hello,
We have MVS datasets containing the $ character in their name 

![image](https://user-images.githubusercontent.com/63342548/79991364-89d98300-84b2-11ea-8b45-9ffb342482b9.png)

I'm unable to read them, I got message Fetch members failed for USR$.B024522.CNTL

![image](https://user-images.githubusercontent.com/63342548/79991758-f05ea100-84b2-11ea-933a-0fb4ac5de33f.png)

Running ZOWE 1.9

**Comment by dkelosky** [comment]
Hi @F-LEMANER - I think this would be for the zowe desktop repos.  @1000TurquoisePogs - is https://github.com/zowe/zlux-server-framework/issues the right spot for this?

**Comment by F-LEMANER** [comment]
Yes sorry, I put this issue in the wrong directory

**Comment by F-LEMANER** [comment]
Issue reopened in zlux-server-frmawork
