### ISSUE TITLE
Invalid JSON on zowe zos-files ls

### ISSUE THREAD

**Issue by pj892031** [zowe/zowe-cli#708]
When I tried call "zowe zos-files ls uss-files /a/plape03" on ca32, it ends with an error:

Command Error:
The get request appeared to succeed, but the response was not in the expected format:
Unexpected token n JSON at position 18591
Error Details:
Unexpected token n JSON at position 18591

Probably this folder contains a special file name or encoding is incorrect

**Comment by Alexandru-Dumitru** [comment]
I can see 2 things there that look strange:

**Comment by pj892031** [comment]
I have now a similar issue:

```
$ zowe ssh issue cmd "ls"
Command Preparation Failed:
Unexpected token m in JSON at position 0
```

It was about the wrong ssh profile, it was not related to the specific folder with strangely named files. It was fixed by overriding the profile.

I guess the root cause was updating a password. I have set a new password directly via credentials store in windows instead of overriding all profiles.

**Comment by adam-wolfe** [comment]
No further action is planned regarding this issue. If this issue persists, please feel free to reopen the issue and provide further information.
