### ISSUE TITLE
zowe login fails ungracefully without APIML host and port

### ISSUE THREAD

**Issue by gejohnston** [zowe/zowe-cli#726]
**Situation**:

- A user fails to realize that (s)he must create a base profile before using tokens.
- The user has heard about tokens and the login command.
- The user jumps in and tries to the run the login command

**Result**

- A harsh stacktrace error occurs after an UnhandledPromise about hostname being undefined.
- Technically, this is correct, but it looks like the command is broken.
- The current output is shown below.

**Desired behavior**
- A message telling the user what (s)he has done wrong, or should do differently.
- Avoid looking like a crash.

```
-> zdev auth login apiml
Authentication required. Enter user name: joheu02
Authentication required. Enter password : ********
(node:1496) UnhandledPromiseRejectionWarning: Error: Expect Error: Required parameter 'hostname' must be defined
    at C:\ourstuff\repos\imperative\lib\expect\src\ImperativeExpect.js:174:23
    at Array.forEach (<anonymous>)
    at Function.keysToBeDefined (C:\ourstuff\repos\imperative\lib\expect\src\ImperativeExpect.js:172:14)
    at Function.keysToBeDefinedAndNonBlank (C:\ourstuff\repos\imperative\lib\expect\src\ImperativeExpect.js:200:26)
    at Session.buildSession (C:\ourstuff\repos\imperative\lib\rest\src\session\AbstractSession.js:132:35)
    at new AbstractSession (C:\ourstuff\repos\imperative\lib\rest\src\session\AbstractSession.js:33:26)
    at new Session (C:\ourstuff\repos\imperative\lib\rest\src\session\Session.js:27:9)
    at ApimlAuthHandler.<anonymous> (C:\ourstuff\repos\imperative\lib\imperative\src\auth\handlers\BaseAuthHandler.js:70:29)
    at Generator.next (<anonymous>)
    at fulfilled (C:\ourstuff\repos\imperative\lib\imperative\src\auth\handlers\BaseAuthHandler.js:15:58)
(node:1496) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1496) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by gejohnston** [comment]
If the user tries to supply the required host and port on the command line, the login command issues a different exception error, presumably because it has no base profile into which to store the token.

```
-> zdev auth login apiml --host usilca32.lvn.broadcom.net --port 60004
Authentication required. Enter user name: joheu02
Authentication required. Enter password : ********
(node:11632) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of undefined
    at ApimlAuthHandler.<anonymous> (C:\ourstuff\repos\imperative\lib\imperative\src\auth\handlers\BaseAuthHandler.js:86:37)
    at Generator.next (<anonymous>)
    at fulfilled (C:\ourstuff\repos\imperative\lib\imperative\src\auth\handlers\BaseAuthHandler.js:15:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:11632) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11632) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by awharn** [comment]
What do we want to do if a user doesn't have a base profile to store the token into? Can we assume  they want the show token behavior and just print it to the command line?

**Comment by gejohnston** [comment]
My initial thought was that we would display an error saying that you must create a base profile before you can login. However, if I were to channel my inner John Laplante, I think that prompting the user for the profile name would be the preferred path. If we create the profile, would we also store the host and port that were supplied on the command line?

I mention how one should use the login command in the document that I am writing. So, I would like to determine what we will do, even if we do not implement it for a little while. Maybe we can reach a team decision in our standup?

**Comment by awharn** [comment]
Sounds like a plan. Apart from that, how should we handle the missing host and port? Should we modify the CredsForSessCfg.ts in imperative and just prompt for host and port if they are not specified?

**Comment by gejohnston** [comment]
If we prompt for base profile name, I suppose that we should also prompt for host and port if they are missing. You raise a good question. Should we prompt for host and port in CredsForSessCfg so that such prompts can happen for all commands? Or should we only prompt for host and port in the login command? Doing something automatically for everyone is a good thing. I do wonder if we are overlooking some scenario where that might not be appropriate for some command? More stand-up discussion I guess.

**Comment by awharn** [comment]
I think that we should prompt for host and port in CredsForSessCfg, because that code sets up a REST session. You can't really do much in a REST session if you don't have an endpoint to connect to...

As for prompting for a name and creating a base profile on the login command, I am more concerned. I would assume that doing `--st` to show the token would not create a new profile in that case. But what happens if someone is at a secure site and forgets to specify that flag? You have captured their user, password, host, and port. You have a token. And now you are creating a profile, and, unless the SCS is installed (which it might not be if the user is not supposed to store these things), it is now in plain text on disk, complete with everything you need to connect to that endpoint.

**Comment by dkelosky** [comment]
Great points @awharn - prompting for `login` makes sense but perhaps not for all commands?

Also it seems you recommend that when you `login` without `--st` and don't have a profile, we should throw an error and make them create one or use `--st` to have the most secure experience?

**Comment by awharn** [comment]
I think that would be the best course of action. We can give them options for how to resolve the problem, and they can make that decision based on their environment.

**Comment by gejohnston** [comment]
Since login is prompting for a number other things, if the user does not have a base profile, the login command could ask the user a yes/no question about whether the user wants us to automatically create a base profile for him/her.

**Comment by gejohnston** [comment]
@dkelosky - What are  your reservations about automatically prompting for missing host & port for any command?

**Comment by dkelosky** [comment]
No reservations - my questions was trying to see if I interpreted @awharn's position correctly.  I think that I did not 😄

**Comment by gejohnston** [comment]
In my local source, I added prompts for host and port to our (renamed) imperative utility. The prompts work fine. However, because the definition of ZOSMF_OPTION_PORT and BASE_OPTION_PORT have a default of 443, there is always a value in the command arguments. Thus we never prompt for port. We just use port 443.

The command below prompts for host, not for port, user, and password. It gets an error because APIML is not running on 443. This is not wrong behavior, given our configuration. Do we think that our default of 443 will work for most customers? I assume so, otherwise we would not have set it as the default.
```
-> zdev zos-files list data-set "JOHEU02.ISPF.ISPPROF"
Enter the host name of your service: usilca32.lvn.broadcom.net
Authentication required. Enter user name: joheu02
Authentication required. Enter password : ********
Command Error:
z/OSMF REST API Error:
http(s) request error event called
Error: connect ECONNREFUSED 10.175.84.32:443
Error Details:
HTTP(S) client encountered an error. Request could not be initiated to host.
Review connection details (host, port) and ensure correctness.

Host:      usilca32.lvn.broadcom.net
Port:      443
Base Path: api/v1
Resource:  /zosmf/restfiles/ds?dslevel=JOHEU02.ISPF.ISPPROF
Request:   GET
Headers:   [{"X-IBM-Max-Items":"0"},{"X-CSRF-ZOSMF-HEADER":true}]
Payload:   undefined
```

If I supply the port on the command line, I get prompted for everything else, and the command works.
```
-> zdev zos-files list data-set "JOHEU02.ISPF.ISPPROF" --port 60004
Enter the host name of your service: usilca32.lvn.broadcom.net
Authentication required. Enter user name: joheu02
Authentication required. Enter password : ********
JOHEU02.ISPF.ISPPROF
```

I am planning to create PRs for imperative and CLI to add this modification. You can post objections here to prevent me from doing so and save us all some time.

**Comment by tjohnsonBCM** [comment]
@gejohnston I copied the command option definitions for z/OSMF profiles to reuse them for base profiles, without giving much thought to the default value for port.

I think it could be confusing for multiple profile types to have the same default port. Since APIML and z/OSMF are two distinct services, they can't run on the same port. Additionally, other like CICS have a different default port for their profile types.

For base profiles, I think it may be warranted to remove the default value of port and require users to enter it. If base profiles are used outside of the context of "auth login" to store global values, a default port may not be desired.

**Comment by gejohnston** [comment]
@tjohnsonBCM It may be reasonable to remove the default of 443 from BASE_OPTION_PORT. I will do that as part of my PR for the replacement of CredsForSessCfg with ConnectionPropsForSessCfg.

However, the lack of prompting for port remains the same. We still pick up the 443 value because it is 'virtually' in the zosmf profile because of the 443 default in ZOSMF_OPTION_PORT.

I temporarily removed the default port value from ZOSMF_OPTION_PORT, and I was able to see a successful prompt. I plan to leave the 443 default in ZOSMF_OPTION_PORT, because it has been there a long time, and removing it might introduce breakage.

**Comment by tjohnsonBCM** [comment]
> However, the lack of prompting for port remains the same. We still pick up the 443 value because it is 'virtually' in the zosmf profile because of the 443 default in ZOSMF_OPTION_PORT.

Makes sense, I was forgetting about this. The `auth login` command shouldn't be affected by this though, since it doesn't have a z/OSMF profile associated with it.

**Comment by gejohnston** [comment]
@tjohnsonBCM - You are correct about the login command, which is probably the most useful situation for prompting the user for the port number.
```
-> zdev auth login apiml
Enter the host name of your service: usilca32.lvn.broadcom.net
Enter the port number for your service: 60004
Enter user name: joheu02
Enter password : ********
Login successful.
```

@awharn - What behavior did you conclude should be implemented when no base profile has been created? Automatically create it? Ask the user if we can automatically create it? Give an error telling the user to create it? Something else?

**Comment by tjohnsonBCM** [comment]
Prompts were added for host and port if missing, as well as a prompt asking if the user is OK with having their connection details stored on disk in a base profile if none exists yet.
