### ISSUE TITLE
Submit Job and Wait for Some Status Before Returning Control (and w/out Downloading All Job Output)

### ISSUE THREAD

**Issue by dkelosky** [zowe/zowe-cli#73]
I would like to submit a job (or perhaps target an already-running job by jobid) and be notified when the job completes so that I can more easily write deployment / test scripts for assembler programs.

**Comment by knrt10** [comment]
On it

**Comment by tjohnsonBCM** [comment]
> I would like to submit a job (or perhaps target an already-running job by jobid) and be notified when the job completes so that I can more easily write deployment / test scripts for assembler programs.

I believe this is now possible with the `--wait-for-active` and `--wait-for-output` flags on the `zos-jobs submit` commands. Can this issue be closed?

**Comment by dkelosky** [comment]
This works great - thanks!
