### ISSUE TITLE
Profile creation should not use environment variables

### ISSUE THREAD

**Issue by FALLAI-Denis** [zowe/zowe-cli#730]
Hi,

A profile is used to save default values.
As such, when creating a new profile, ("zowe profiles create"), the default values already declared in environment variables should not be used for creating the profile.

At runtime, the search order for the parameters must be:
1) command parameters
2) profile settings
3) parameters defined by environment variables

The use cases below, (run with Windows), show the consequences of the valuation of environment variables on the creation of the profile, in particular the variable ZOWE_OPT_PASSWORD valued with "PROMPT*" which requests the entry of the password during the creation of the profile, which is absolutely not the expected result, (the password must be entered each time an order is executed and must not be saved in the profile).

1) undef all previously defined ZOWE_OPT_xxx

```
>set ZOWE_OPT_PASSWORD=
>set ZOWE_OPT_REJECT_UNAUTHORIZED=
>set ZOWE_OPT_USER=
``` 

2) define a new profile without environment variable defined

```
>zowe profiles create zosmf HOST1 -H HOST1 -P 8443
Profile created successfully! Path:
C:\Users\<user>\.zowe\profiles\zosmf\HOST1.yaml
host:               HOST1
port:               8443
user:               null
password:           null
rejectUnauthorized: true
Review the created profile and edit if necessary using the profile update command.
```

3) define enviroment variable ZOWE_OPT_USER

`>set ZOWE_OPT_USER=USER01`

4) define a new profile with environment variable ZOWE_OPT_USER : user code is wrongly associated with profile

```
>zowe profiles create zosmf HOST2 -H HOST2 -P 8443
Profile created successfully! Path:
C:\Users\<user>\.zowe\profiles\zosmf\HOST2.yaml
host:               HOST2
port:               8443
user:               managed by @zowe/secure-credential-store-for-zowe-cli  <== !!!
password:           null
rejectUnauthorized: true
Review the created profile and edit if necessary using the profile update command.
```

5) define environment vairable ZOWE_OPT_REJECT_UNAUTHORIZED

`>set ZOWE_OPT_REJECT_UNAUTHORIZED=false`

6) define new profile with ZOWE_OPT_USER and ZOWE_OPT_REJECT_UNAUTHORIZED

```
>zowe profiles create zosmf HOST3 -H HOST3 -P 8443
Profile created successfully! Path:
C:\Users\<user>\.zowe\profiles\zosmf\HOST3.yaml
host:               HOST3
port:               8443
user:               managed by @zowe/secure-credential-store-for-zowe-cli  <== !!!
password:           null
rejectUnauthorized: false  <== !!!
Review the created profile and edit if necessary using the profile update command.
```

7) define environment variable ZOWE_OPT_PASSWORD with "PROMPT*"

`>set ZOWE_OPT_PASSWORD=PROMPT*`

8) define new profile with ZOWE_OPT_USER, ZOWE_OPT_REJECT_UNAUTHORIZED, and ZOWE_OPT_PASSWORD : password is wrongly associated with profile (user code too)

```
>zowe profiles create zosmf HOST4 -H HOST4 -P 8443
"password" Description: Mainframe (z/OSMF) password, which can be the same as your TSO password.
Please enter "password":    <== !!! ask for password...
Profile created successfully! Path:
C:\Users\<user>\.zowe\profiles\zosmf\HOST4.yaml
host:               HOST4
port:               8443
user:               managed by @zowe/secure-credential-store-for-zowe-cli  <== !!!
password:           managed by @zowe/secure-credential-store-for-zowe-cli  <== saved password !!!
rejectUnauthorized: false  <== !!!
Review the created profile and edit if necessary using the profile update command.
```

**Comment by FALLAI-Denis** [comment]
According to the online documentation (https://docs.zowe.org/stable/user-guide/cli-configuringcli.html#understanding-command-option-order-of-precedence), the priority order of the parameters of a ZOWE CLI command is:
1) Arguments and options that you specify directly on the command line.
2) Environment variables that you define in the computer's operating system. For more information, see Defining Environment Variables
3) User profiles that you create.
4) The default value for the argument or option.

I think the order of priority should be:
1) Arguments and options that you specify directly on the command line.
2) User profiles that you create.
3) Environment variables that you define in the computer's operating system. For more information, see Defining Environment Variables
4) The default value for the argument or option.

An environment variable must not hide a parameter specified in a profile.

**Comment by gejohnston** [comment]
The Zowe V1 release is in maintenance mode, so no enhancements will be made to that release. The profile commands are deprecated in V2, so no enhancements to those command are planned in V2 either.
