### ISSUE TITLE
Use of the "PROMPT*" value on a profile creation

### ISSUE THREAD

**Issue by FALLAI-Denis** [zowe/zowe-cli#731]
Hi, 

Using the value "PROMPT*" for the --password parameter when creating a profile should not require entering the password, but should save the value "PROMPT*" in the profile.

It is only when the profile is used with another command that the password must be entered.

```
>zowe profiles create zosmf HOST1 -H HOST1 -P 8443 -u MYUSER --pw "PROMPT*" --ru false
"password" Description: Mainframe (z/OSMF) password, which can be the same as your TSO password.
Please enter "password":
Profile created successfully! Path:
C:\Users\<user>\.zowe\profiles\zosmf\HOST1.yaml

host:               HOST1
port:               8443
user:               managed by @zowe/secure-credential-store-for-zowe-cli
password:           managed by @zowe/secure-credential-store-for-zowe-cli
rejectUnauthorized: false

Review the created profile and edit if necessary using the profile update command.
```

**Comment by zFernand0** [comment]
The idea of prompting the user every time if they explicitly use some indicator (say a flag called `--always-prompt`) sound really nice.
However, I believe that changing the behavior of the `prompt*` value may be considered a breaking change depending on the way users interact with it today.

**Comment by dkelosky** [comment]
@gejohnston could comment, but I think with some upcoming changes, we'll be prompting for password when it is absent from the profile in a future zowe CLI update.

**Comment by gejohnston** [comment]
While it does not alter the behavior of the "PROMPT*" option in the creation of a profile, upcoming functionality may provide an alternate way to achieve the desired result.

None of host, port, user, or password will be required options in a profile. If a command is run, and any one of those options have *NOT* been supplied, the command will prompt for the missing value. In the example below, host and port were in a profile, but user and password were not.

```
zowe zos-files list data-set "MYUSER.ISPF.*"
Enter user name: myuser
Enter password : ********
MYUSER.ISPF.ISPPROF
```

**Comment by gejohnston** [comment]
The Zowe V1 release is in maintenance mode, so no enhancements will be made to that release. The profile commands are deprecated in V2, so no enhancements to those command are planned in V2 either.
