### ISSUE TITLE
For USS files where the encoding is set, use this when retrieving files

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-cli#740]
**Problem**
USS tagging is not respected when transfering files

**Proposed solution**
Add a CLI command to retrieve the tags, e.g.
`zowe files chtag request "filename"`
that returns the tagging of the file.  

Also allow `zowe files download uss "filename"` to respect the tagging, so if the USS file is already tagged as ISO8559-1 then transfer it as binary.

Not sure if this should be a default behavior change and the always convert files is an error, or whether it should be a new option on `zowe files download uss "filename" -autocvt` or similar.

**Background**
USS allows files to be tagged which records the codepage used to store the data.  The screen shot belows shows the file ascii.txt that is tagged as ISO8559-1, ebcdic.txt tagged as IBM-1047 and untagged.txt which isn't tagged.

![image](https://user-images.githubusercontent.com/28100302/84907026-97724a00-b0aa-11ea-92bf-6d9807e37cb8.png)

In the sample above ascii.txt contains ASCII encoded txt and ebcdic.txt contains EBCDIC text.  

When doing a retrieve of the file from z/OSMF it is possible to set a header to specify the datatype, for example in the first screen shot below the get request returns the ASCII data treating it as EBCDIC encoded

![image](https://user-images.githubusercontent.com/28100302/85001844-14a1cb80-b14c-11ea-905f-a86e1441c01f.png)

If the header X-IBM-Data-Type is set to anything non-null then conversion occurs

![image](https://user-images.githubusercontent.com/28100302/85005173-57fe3900-b150-11ea-851c-ceea58a2de7b.png)

It is possible to retrieve the encoding of the file using the PUT API and specifying a request body of `{"request":"chtag","action":"list"}` and a Content-Type of application/json

![image](https://user-images.githubusercontent.com/28100302/84908578-8a565a80-b0ac-11ea-8a38-84692976d2c2.png)

**Comment by dkelosky** [comment]
For completeness (playing with encoding a lot lately ), there is also the file format settings from `extattr`.  `ls -H` can display these (see instances of `bin`):
```
/a/kelda16/test:ls -HT
total 40
- untagged    T=off -rwx------  nl     1 KELDA16  OMVSUSRG      14 Jun 10 15:51 test.txt
t ISO8859-1   T=on  -rwx------  bin    1 KELDA16  OMVSUSRG      14 May 29 14:41 testa.txt
- untagged    T=off -rw-r--r--  ----   1 KELDA16  OMVSUSRG      14 Jun 17 21:12 testb.txt
m UTF-8       T=off -rwx------  bin    1 KELDA16  OMVSUSRG       6 Jun 17 21:18 testc.txt
b binary      T=off -rw-rw----  ----   1 KELDA16  OMVSUSRG      14 Jun 17 21:20 testd.txt
```

Candidates for binary downloading with the `--autoconv` flag:
- `b binary`
- `m UTF-8`
- `t ISO8859-1`
- `m ISO-8859-1` 

For more info on [`chtag`](https://www.ibm.com/support/knowledgecenter/SSLTBW_2.2.0/com.ibm.zos.v2r2.bpxa500/chtag.htm).

**Comment by dkelosky** [comment]
Side note, we have the `.zosattributes` to [control how files are uploaded](https://github.com/zowe/zowe-cli/issues/207).

**Comment by Joe-Winchester** [comment]
Tks for the link to `.zosattributes` which is a nice solution, perhaps one can be found where if `.zosattributes` is present then it controls conversion, however in its absence the extended attribute (if set) is used for the case where someone just use raw CLI or raw Zowe Explorer hooked up to z/OSMF to do editing.
