### ISSUE TITLE
Unable to submit jobs from local file containing logical not character "¬"

### ISSUE THREAD

**Issue by ChrisBoehmCA** [zowe/zowe-cli#742]
The character ¬ is used to represent "not" in JCL IF statements. 

When submitting through the CLI, the job ends up with a JCL error. There is some encoding issue and the character isn't recognized. 

```
STMT NO. MESSAGE                                                 
       3 IEFC620I UNIDENTIFIABLE CHARACTER . ON THE IF STATEMENT 
```

`zowe jobs submit local-file example.jcl`
example.jcl: 
```
{{insert_job_card_here}}
//STEP1  EXEC PGM=IEFBR14          
//IFNOABND  IF (¬STEP1.ABEND) THEN  
//NOABEND  EXEC PGM=IKJEFT01       
//*                                
//SYSTSPRT DD   SYSOUT=*           
//SYSTSIN  DD   *                  
 TIME                              
/*                                 
//         ENDIF              
```

Re-creation in Postman. Couldn't get it to work by changing any headers

[zosmf.postman_collection.json.zip](https://github.com/zowe/zowe-cli/files/4798894/zosmf.postman_collection.json.zip)

**Comment by ChrisBoehmCA** [comment]
Thanks to @dkelosky for this workaround:

Use "^" in your local file instead of "¬" and z/OSMF will translate it to "¬". Tested working. However this may still cause issues for people unaware of the workaround or those who download JCL from z/OS to submit later etc.

**Comment by dkelosky** [comment]
Thanks @ChrisBoehmCA.  I think it's partly a code page / encoding consideration too.  If your 3270 emulator is set to 037, `¬` is x'5F'.  `^` is x'5F' in 1047.

**Comment by bruce2359** [comment]
Rather than coding the ¬ as not character, code NOT
//STEP1  EXEC PGM=IEFBR14               
//IFNOABND  IF  **(NOT STEP1.ABEND)**  THEN 
//NOABEMD  EXEC PGM=IKJEFT01            
/*                                      
//SYSTSPRT DD SYSOUT=*                  
//SYSTSIN DD *                          
 TIME                                   
/*                                      
//      ENDIF

**Comment by bruce2359** [comment]
The title **Unable to submit jobs from local file containing logical not character "¬"** is not precise, as the job was submitted successfully, but failed with JCL error check.  It's a nit, I know, but ...
