### ISSUE TITLE
zowe files command fails with region size error

### ISSUE THREAD

**Issue by bobanero** [zowe/zowe-cli#746]
I'm setting up a new user account to perform builds through jenkins via zowe.  I'm getting a failure when I run any **zowe files** commands.  Below is output of a **zowe files list ds**.  It seems like a zosmf problem.  I verified that I could login to zosmf with the new account, and that I could start ISPF in zosmf and set the region to 4096 and login PROC to IZUFPROC.  All the settings seem to be the same as the settings for my personal account which works properly.  I can't figure out what I'm missing.

 **>zowe files list ds "bldccs."
Command Error:
z/OSMF REST API Error:
Rest API failure with HTTP(S) status 500
rc:       4
reason:   2
details:
  - REGION SIZE 0065536 EXCEEDS LIMIT SIZE 0004096
  - REENTER -
category: 2
message:  login: received unexpected TSO LOGON prompt:TsoServerConnection(USER=BLDCCS, ASID=0x0142, QID=0x004f0019)

Error Details:
HTTP(S) error status "500" received.
Review request details (resource, base path, credentials, payload) and ensure correctness.

Host:      tso1.lvn.broadcom.net
Port:      443
Base Path:
Resource:  /zosmf/restfiles/ds?dslevel=bldccs.
Request:   GET
Headers:   [{"X-IBM-Max-Items":"0"},{"X-CSRF-ZOSMF-HEADER":true}]
Payload:   undefined**

**Comment by MikeBauerCA** [comment]
To prevent these errors, ensure that you have a TSO maximum region size of at least 65536 KB for the z/OS system. Here is the relevant z/OSMF documentation -> https://www.ibm.com/support/knowledgecenter/SSLTBW_2.2.0/com.ibm.zos.v2r2.izua300/izuconfig_LogonProcSetup.htm

**Comment by bobanero** [comment]
Thank you.  That's what I missed.  The new account did not have TSOMSIZE set properly in TSS.
