### ISSUE TITLE
Zowe SDKs - sample use cases

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/zowe-cli#752]
Similar to how Zowe CLI use cases are provided in zowe/zowe-cli-sample-scripts, sample Zowe SDK use cases should be provided.

**Comment by t1m0thyj** [comment]
@MikeBauerCA Can this be closed now that [zowe/zowe-sdk-sample-scripts](https://github.com/zowe/zowe-sdk-sample-scripts) exists?

**Comment by MikeBauerCA** [comment]
Yes, it can. Thanks!
