### ISSUE TITLE
defaultProfile value in meta.yaml file not cleared if default profile is deleted

### ISSUE THREAD

**Issue by PeteSwauger** [zowe/zowe-cli#76]
Delete the profile designated as the default.  The defaultProfile value in the *meta.yaml file is not cleared.

**Comment by AHumanFromCA** [comment]
Correct me if I am wrong but this is kind of a duplicate of zowe/imperative#43?

**Comment by PeteSwauger** [comment]
Yes, but these one's title is much clearer!

**Comment by AHumanFromCA** [comment]
I could change the title of the other one if that helps?

**Comment by PeteSwauger** [comment]
Sure.  I'll close this one.
