### ISSUE TITLE
This plugin has command errors. No plugin commands will be available. DB2 CLI

### ISSUE THREAD

**Issue by kumahara10** [zowe/zowe-cli#765]
Hi Team,
I am trying to install DB2 Plugins so that i can communicate with db2 through zowe cli.
While i install the DB2 plugins, there are some warning however the plugin gets downloaded and i can even list the plugin.
But the zowe db2 commands are not active. I checked the old issues but couldnt help me much, Raising this new one if anyone can help me to fix this. it will be really greatful.
![{8830D3CD-15AE-48F9-804A-08EEDB65EA5F} png](https://user-images.githubusercontent.com/68424841/87793186-36729900-c845-11ea-8814-a4cc9aca9876.jpg)
![{6BF5546C-F2B7-473E-9808-8E49EF2DC721} png](https://user-images.githubusercontent.com/68424841/87793265-4f7b4a00-c845-11ea-84c8-c124fd7b0a01.jpg)
![{9B1EBF86-01AC-42E6-A8A8-FA675959AAFE} png](https://user-images.githubusercontent.com/68424841/87793323-628e1a00-c845-11ea-8e22-6b5a7d421bc5.jpg)

**Comment by MikeBauerCA** [comment]
@kumahara10, what is your zowe CLI version (`zowe --version`)?

**Comment by kumahara10** [comment]
C:\Users\km892448>zowe --version
2.36.4

**Comment by MikeBauerCA** [comment]
Okay, one issue is that you are trying to install on an older (non-v1-lts) version of the CLI. You can upgrade by issuing `npm install -g @zowe/cli@zowe-v1-lts`.

**Comment by kumahara10** [comment]
![error](https://user-images.githubusercontent.com/68424841/87795778-d2ea6a80-c848-11ea-9b12-2cbd150429d0.jpg)

**Comment by MikeBauerCA** [comment]
Please uninstall the db2 plug-in and reinstall. `zowe plugins uninstall @zowe/db2-for-zowe-cli` then `zowe plugins install @zowe/db2-for-zowe-cli@zowe-v1-lts`.

**Comment by kumahara10** [comment]
![1](https://user-images.githubusercontent.com/68424841/87796496-b8fd5780-c849-11ea-94e8-e83c5c38ebaa.jpg)
![2](https://user-images.githubusercontent.com/68424841/87796513-bdc20b80-c849-11ea-9164-ab7b82addc7c.jpg)

**Comment by kumahara10** [comment]
do you mean that the version of zowe is 2.36.4 and I am trying to install DB2 plugin old version?
zowe plugins install @zowe/db2-for-zowe-cli@zowe-v1-lts ( is this the old one?)
This is what it has in the zowe.org documentation, not sure which and where is the latest which is compatible with zowe 2.36.4 version

**Comment by tjohnsonBCM** [comment]
@kumahara10 Looks like you're using Node.js 14 (NODE_MODULE_VERSION 83). This version is not yet supported by Zowe CLI.

Zowe CLI supports only LTS (Long Term Support) versions of Node.js. Please uninstall Node.js 14 and install the latest LTS version (currently 12.18.2, which can be downloaded from https://nodejs.org).

**Comment by MikeBauerCA** [comment]
You have the correct versions for the Zowe CLI and Db2 Plugin now (both zowe-v1-lts). You installed `@zowe/cli@zowe-v1-lts` so you are now at version number 6.18.0. Thanks @tjohnsonBCM for seeing the Node version issue.

**Comment by kumahara10** [comment]
is that a node issue and what needs to be done ? because my node version is 14.5.0
C:\Users\km892448>node --version
v14.5.0

**Comment by tjohnsonBCM** [comment]
@kumahara10 
> Please uninstall Node.js 14 and install the latest LTS version (currently 12.18.2, which can be downloaded from https://nodejs.org).

**Comment by kumahara10** [comment]
perfect , it's working now, thanks so so much!!!!!!

**Comment by MikeBauerCA** [comment]
Glad to hear it! :)
