### ISSUE TITLE
Download system tests leave behind files

### ISSUE THREAD

**Issue by Pranay154** [zowe/zowe-cli#769]
When I run the download system tests, files get left behind for me.

<img width="356" alt="Screenshot 2020-07-21 at 13 32 52" src="https://user-images.githubusercontent.com/37961978/88055559-1dc0f680-cb57-11ea-8dc2-e6663d854947.png">

<img width="364" alt="Screenshot 2020-07-21 at 13 33 02" src="https://user-images.githubusercontent.com/37961978/88055577-23b6d780-cb57-11ea-8064-1b660b055656.png">

Are these intended to be left? I'm assuming not.

**Comment by zFernand0** [comment]
similar to #700

**Comment by Pranay154** [comment]
@zFernand0 Didn't notice, will close this issue 👍
