### ISSUE TITLE
Test independent packages in monorepo

### ISSUE THREAD

**Issue by ghost** [zowe/zowe-cli#786]
Replace/extend the top level Jest config in package.json with Jest config in each package subfolder. This could go either in package.json or a separate file jest.config.js.

Fix broken imports in tests, after restructuring has been completed in #783.

Also add a "test" NPM script in each package's package.json. Then `lerna run test` should run the "test" script in all package folders. Also create separate NPM scripts "test:unit", "test:integration", and "test:system" to run only one type of test where applicable.

**Comment by zFernand0** [comment]
We may reopen this issue if the conversation about splitting jest configuration comes up again.
