### ISSUE TITLE
Update build automation for monorepo

### ISSUE THREAD

**Issue by tjohnsonBCM** [zowe/zowe-cli#787]
Rewrite the top level package.json file after separate packages have been created. Most dependencies can be removed. NPM scripts and Gulp tasks should be rewritten to call Lerna.

**Comment by zFernand0** [comment]
There is also the option in which the top level gulp tasks just perform their actions (e.g. updateLicense) on the meaningful files and exclude everything else (e..g node_modules, lib, ...)
`npm run build` on `fix-global-scripts` to find out more 😋
