### ISSUE TITLE
CLI options inline with classical mainframe JCL options

### ISSUE THREAD

**Issue by aviVzm05** [zowe/zowe-cli#788]
Current command line options for creating dataset include details like --record-length (--rl), --record-format(--rf) etc. 
Can additional options be included to get these in sync with classic options we know from mainframes. For example consider below example with lrecl/recfm.  since we already know these for so many years, it is easier to get the CLI build done easily and is less confusing too..

Essentially getting the options in sycn with TSO ALLOCATE.

  --record-format  | --rf (string) | **--recfm**

      The record format for the data set (for example, FB for "Fixed Block")

      Default value: FB

   --record-length  | --rl (number) | **--lrecl**

      The logical record length. Analogous to the length of a line (for example, 80)

      Default value: 80

**Comment by MikeBauerCA** [comment]
Very nice suggestion, thanks for the feedback 👍  Typically, we only have one alias for command options, but I believe this would be worth making an exception. @jelaplan, what do you think?

**Comment by aviVzm05** [comment]
@MikeBauerCA thank you..  i was trying to learn contributing and if this is okay, i'd like to try with this with your help....i'm in slack btw.:)

**Comment by jelaplan** [comment]
I agree it's a pretty good idea. Having been doing some research on data sets lately it does seem that the se five letter or so abbreviations are very common in well recognized by a lot of people.
