### ISSUE TITLE
Problem installing Zowe CLI from local package into USS

### ISSUE THREAD

**Issue by AHumanFromCA** [zowe/zowe-cli#79]
Received this issue from the OMP slack channel:

```
unzip zowe-cli-bundle.zip from USS directory /u/carruth/zowe-0.9.1/files/
---> zowe-cics-1.1.0-next.201809271925.tgz
---> zowe-cli-2.0.0-next.201809251404.tgz
node v8.12.0    npm  v6.4.1
npm cache clean
errors ....
2730 verbose npm  v6.4.1
2731 error code ELIFECYCLE
2732 error errno 1
2733 error @brightside/core@2.0.0-next.201809251404 postinstall: `node ./scripts/validatePlugins`
2733 error Exit status 1
2734 error Failed at the @brightside/core@2.0.0-next.201809251404 postinstall script.
2734 error This is probably not a problem with npm. There is likely additional logging output above.
2735 verbose exit [ 1, true ]
```

I have reached out and asked for some more of the stripped out details. Will add them here if I receive any.

**Comment by MikeBauerCA** [comment]
Notes: zowe cli bundle is now available outside of the PAX, zowe CLI cannot run on USS until Node 8 or greater is available in that environment.

**Comment by AHumanFromCA** [comment]
I did a search for this issue in slack and I can't seem to find any references to USS before November 15th. Thinking that this has rolled out of our workspace. Without the ability to get in contact with the person having the issue, this issue is closed.
