### ISSUE TITLE
Association of a base profile with a service profile by best matching common options (replace "default" by "best matching" profile selection)

### ISSUE THREAD

**Issue by FALLAI-Denis** [zowe/zowe-cli#798]
Base profiles are useful so as not to redeclare the same options in all services profiles.
Only one base profile can be declared by default, and if you want to use a base profile other than the default base profile with a service profile, you must explicitly declare the base profile to be used (or déclaring this base profile as default).

When working with multiple z/OS partitions, and having declared a base profile for each z/OS partition, this can quickly become restrictive.

It would be necessary to be able to associate a base profile with a service profile, either explicitely at creation of the service profile, or automatically at execution of a command using the service profile, by selection of reconciliation criterias (in especially the HOST option): select the base profile which shares the most common options with the current service profile.

### Use case

defined profiles:
```
zowe profiles create base BASE1 -H HOST1 -u user1 --pw pass1
zowe profiles create base BASE2 -H HOST2 -u user2 --pw pass2
zowe profiles create zosmf ZOSMF1 -H HOST1 -P 1234 ...
zowe profiles create zosmf ZOSMF2 -H HOST2 -P 1234 ...
```
running this zosmf command:
`zowe zos-jobs list jobs -zosmf-p ZOSFM2`
should use base profile BASE2 because of same host option HOST2 in both profiles.
Same if:
`zowe profiles set-default zosmf ZOSFM2`
`zowe zos-jobs list jobs`
should use base profile BASE2

By extension, a command should be able to select a service profile based on the options specified on the command, rather than using the default service profile.
Running this zosmf command:
`zowe zos-jobs list jobs -H HOST2`
should use service profile ZOSMF2, which should use base profile BASE2.

**Comment by FALLAI-Denis** [comment]
Hi,

After consideration and a few mishaps in the implementation of base profiles, I think that the idea of ​​automatically associating a base profile with a service profile, or a command, is ultimately a source of problems, and of various malfunctions in ZOWE CLI plugins or extensions for VS Code (or others) which use ZOWE CLI plugins and profiles.

I think a base profile should always be explicitly associated with a service profile, or a ZOWE CLI command, but never automatically inferred.

Each service profile should therefore have a "--base-profile" option allowing to explicitly associate a base profile when it is created, which could then be overloaded during the execution of a command (force the base profile to use for command).

Deleting a base profile should only be possible if no service profile references it.

In addition, the names of the properties, and the abbreviations in commands, of the profiles should be administered globally, and that:
* the same information uses the same property name in all profiles (base and service)
* that the same property name is not used to manage different information.

For example, the "port" property is ambiguous if used in a base profile:
* z/OSMF port: should be named "zosmf-port"
* API Mediation Layer port: should be named "apiml-port"
* DDF DB2 port: should be named "ddf-port"
* CICS CMCI port: : should be named "cmci-port"
* Endevor Web Services port: : should be named "ews-port"

Abbreviation "--bp" : "--base-profile" or "--base-path" ?

**Comment by MikeBauerCA** [comment]
Awesome feedback and thanks for giving our base profiles a try @FALLAI-Denis! We are working to improve profiles, especially to help new Zowe CLI users get started easier. We are planning to allow all profile options to be specified in a single base profile. The structure of the base profile would be adjusted to solve the "port" property issue you highlighted - https://github.com/zowe/zowe-cli/issues/749.

In regards to associating profiles, that could add complexity to the user experience. You would need to recall which base profiles were associated with which service profiles and that could become a maintenance burden. It may be easier to just specify the host in each service profile at that point. Any property specified in a service profile will override what is in the base. The primary intent of the base-profile was to provide support for Tokens, MFA, SSO via the Zowe API Mediation Layer. Although, it does provide a number of benefits outside of that scope.

Besides base profiles, another way to reduce profile maintenance today is to consider automating the creation of your profiles in a script. Please consider reviewing tip 5 in this [blog](https://medium.com/modern-mainframe/zowe-cli-tips-tricks-79607b8dbd4e).

**Comment by gejohnston** [comment]
This enhancement is related to "profiles" commands. The "profiles" commands are deprecated in Zowe V2 and so those commands will no longer be enhanced. The Zowe V2 team configuration enables profiles to be nested inside other profiles. This capability may address this use-case. I am closing this issue, but if team configuration does not address these needs, you may open a new issue that is more specific to V2 team configuration.
