### ISSUE TITLE
zowe zos-files copy data-set : no replace option

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-cli#808]
@zszabo14 commented on [Mon Aug 31 2020](https://github.com/zowe/community/issues/748)

**Is your feature request related to a problem or limitation? Please describe.**
zowe zos-files copy data-set doesn't have a REPLACE option

**Describe the experience you'd like**
please add REPLACE option

**Describe alternatives you've considered**

**Additional context**

---

@Joe-Winchester commented on [Tue Sep 01 2020](https://github.com/zowe/community/issues/748#issuecomment-684747800)

Thank you @zszabo14 for this enhancement request for the Zowe CLI.  I've moved the git issue to their repo https://github.com/zowe/zowe-cli and they'll be able to respond to it there.  Cheers !

**Comment by MikeBauerCA** [comment]
Thanks for the request! It does appear that this is supported by the z/OSMF API and would just need added to our CLI/SDK -> https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.2.0/com.ibm.zos.v2r2.izua700/IZUHPINFO_API_PutDataSetMemberUtilities.htm
