### ISSUE TITLE
Syntax error message issue

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/zowe-cli#81]
When a command is issued using an invalid group name, the error message does not communicate that the invalid group name is the issue. It also suggests appending --help. However, that will not help in this situation.

![image](https://user-images.githubusercontent.com/35504792/46960487-ac444200-d06c-11e8-87ef-e1d744fff3bd.png)

**Comment by zFernand0** [comment]
Seems like this issue may have been resolved over time
Here is what it looks like in  `@zowe-v2-lts` 
![image](https://user-images.githubusercontent.com/37381190/184408416-231dd959-dc11-4bf7-94a5-0e59e7361fd5.png)

It will suggest running `--help` from the last known group (which is `zowe` for this command)
