### ISSUE TITLE
Enable use of a pattern to restrict what member names are returned from listing of PDS members

### ISSUE THREAD

**Issue by martindamp** [zowe/zowe-cli#810]
Currently when listing members from a PDS it is not possible to use a search parameter to restrict the returned member names to only the names that match the given pattern.  

This feature is supported by z/OSMF. have a look here : https://www.ibm.com/support/knowledgecenter/SSLTBW_2.4.0/com.ibm.zos.v2r4.izua700/IZUHPINFO_API_GetListDataSetMembers.htm

It is very an important feature to implement into zowe-cli, because lots of enterprise organizations do have PDS's with large number of members(>200.000),
and its very slow to pull all those member names all the time.  Furthermore we experience other problems when listing PDS with large number of members.

**Comment by bearou** [comment]
Agree with @martindamp - and finds it strang that this is not implemented already.

**Comment by ThomasNellemann** [comment]
Adding pattern to the query will improve the usability immensely.

**Comment by Rune-Christensen** [comment]
We could definitely use this in our shop :-)

**Comment by dkelosky** [comment]
Is this on the `zowe files list am` command?  Would you like a `--pattern` keyword as is used by the z/OSMF REST API?
