### ISSUE TITLE
zowe profile doesnt support passphrase

### ISSUE THREAD

**Issue by zszabo14** [zowe/zowe-cli#817]
We just realized, that zowe cli doesn't support passphrase (zOSMF login also)

**Comment by dkelosky** [comment]
Are you unable to use passphrases when logging into the z/OSMF UI or authenticating with z/OSMF REST APIs?

**Comment by zszabo14** [comment]
Hi,

Both, I cannot login to zOSMF web portal and I cannot login using the CLI (the profile is created, but when I run any command, login fails I already opened an issue to add a new function to validate the profile after creation)

The RACF attributes for this user: ATTRIBUTES=NOPASSWORD PASSPHRASE

**Comment by dkelosky** [comment]
I think the first step will be to pursue z/OSMF access with your passphrase.  After that, CLI access should seamlessly follow

**Comment by zszabo14** [comment]
Hi, the issue is fixed. It was our fault.

But, we experienced an issue ( I think this is also related to our environment setup, but maybe others can find it also)
We found that a user has access problems. when he was running any CLI commands:
`  - ICH408I USER(zoweuser ) GROUP(DEFLT1  ) NAME(xxxxxxxxxxxxxxxxxxx  )
  -   **SYS1.SIEALNKE** CL(DATASET ) VOL(SIBRC1)
  -   INSUFFICIENT ACCESS AUTHORITY
  -   FROM SYS1.* (G)
  -   ACCESS INTENT(READ   )  ACCESS ALLOWED(NONE   )
  - IEC150I 913-38,IFG0194E,WWFJNKS,IZUFPROC,ISPLLIB,6034,SIBRC1,
  - SYS1.SIEALNKE
  - IKJ56642I USER NOT AUTHORIZED TO DATA SET+
  - IKJ56641I ISPSTART ENDED DUE TO ERROR+
  - READY`
 
In our environment it is configured so, the users are able to execute from SYS1.* without direct access. Why ZOWE needs access to it?

**Comment by dkelosky** [comment]
Hi - I would expect `zowe jobs list jobs` to not have this problem.  Other commands, like `zowe files` starts up TSO address spaces on behalf of the user behind the scenes (z/OSMF actually does this).  In that case, the default proc used it `IZUFPROC` which is the `ISPLLIB` DD and that `SYS1.SIEALNKE` data set in its concatenation.  

Perhaps the z/OSMF installation documentation covers the requirements of end user's access requirements for the DDs referenced in this PROC.

**Comment by gejohnston** [comment]
This behavior was due to incorrect server configuration. Therefore, I am closing this issue.
