### ISSUE TITLE
zosmf meta yaml not updated during npm update

### ISSUE THREAD

**Issue by jellypuno** [zowe/zowe-cli#818]
I have updated my zowe CLI via NPM today. I did this because I wanted the encoding option to display on Zowe Explorer.
But I noticed that after the update the zosmf meta yaml was not updated so the encoding option is not there.

![image](https://user-images.githubusercontent.com/45042840/93213456-281cfc80-f764-11ea-962c-aa06bc0e8292.png)

**Comment by MikeBauerCA** [comment]
I think @tjohnsonBCM and @awharn were discussing this potential issue. @jellypuno, are you able to create a profile via Zowe CLI with the encoding option?

**Comment by jellypuno** [comment]
Q: Is there a way for Zowe Explorer to get the schema (based on type) in the node modules folder? I saw this IMetaProfile but I am not sure if I could use or how to use it.

**Comment by jellypuno** [comment]
> I think @tjohnsonBCM and @awharn were discussing this potential issue. @jellypuno, are you able to create a profile via Zowe CLI with the encoding option?

Yes. This is visible via CLI

**Comment by MikeBauerCA** [comment]
After you create a profile via the CLI, is the meta file updated?

**Comment by jellypuno** [comment]
@MikeBauerCA Tried it now and nope, meta is not updated. but encoding is in my profile

![image](https://user-images.githubusercontent.com/45042840/93217192-fd817280-f768-11ea-92c5-13e93c952bbb.png)

**Comment by awharn** [comment]
As far as I know, the meta file is only updated once a user deletes the old one from `~/.zowe/profiles/<profile>/<profile>_meta.yaml` and issues a profile command via the CLI. That isn't a great solution - I plan on investigating this issue further once we get some time.

**Comment by zFernand0** [comment]
Howe about adding a few APIs for meta_file manipulation as part of the config SDK package?
1. get meta file by profile type?
2. delete meta file by profile type?

**Comment by jellypuno** [comment]
Yah. we need this. especially pt. 1

The meta config is updated in node modules so if we could read that rather than read the physical file that would be awesome.

**Comment by MikeBauerCA** [comment]
I want to note that we are considering moving away from these meta files to instead have JSON schema: https://github.com/zowe/zowe-cli/issues/749#issuecomment-675633146

**Comment by phaumer** [comment]
What if the schema becomes inconsistent with the existing profiles? There needs to be a hook for extensions to perform a migration as well.

**Comment by dkelosky** [comment]
The JSON schema allows for a `$schema` keyword to reference a specific schema (for example, different versions).

 Agreed on migration - we'll have to spend a lot of time communicating and making sure we help with migration and be backward compatible.

**Comment by zFernand0** [comment]
This is a V1 enhancement and since Zowe V1 is on maintenance mode, we won't be implementing this new feature.
