### ISSUE TITLE
z/OSMF REST API Error: http(s) request error event called Error: connect ECONNREFUSED

### ISSUE THREAD

**Issue by Shriram2693** [zowe/zowe-cli#822]
Hi Team,

I'm new to this zowe cli. I have my own mainframe user name and credentials to develop and test the same. I thought to use zowe cli to establish a connection to my mainframe.

I have created my zosmf profile using the host and port of my mainframe followed by --ru false and NODE_TLS_REJECT_UNAUTHORIZED=0 to bypass the cert checks. But whenever i try to check the connection status i'm getting below error:

C:\Users\E060780>zowe zosmf check status

(node:4952) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
Command Error:
z/OSMF REST API Error:
http(s) request error event called
Error: connect ECONNREFUSED XX.XXX.XX.XX:XXX
Error Details:
HTTP(S) client encountered an error. Request could not be initiated to host.
Review connection details (host, port) and ensure correctness.

Host:      XX.XXX.XX.XX
Port:      XXX
Base Path: basePath
Resource:  /zosmf/info
Request:   GET
Headers:   [{"X-CSRF-ZOSMF-HEADER":true}]
Payload:   undefined

masked the host and port. But the same host and port is being used to connect my mainframe thru Connection Central.

I would like to know what is this error exactly and how to fix this. Because, i use the same host name and port to connect my mainframe thru Topaz which is working.

Kindly help on this.

Thanks,
Shriram K S

**Comment by Shriram2693** [comment]
adding logs:

[2020/09/17 13:38:28.400] [DEBUG] [CheckStatus.js:43] Endpoint: /zosmf/info
[2020/09/17 13:38:29.099] [DEBUG] [ZosmfRestClient.js:69] Encountered an error trying to parse causeErrors as JSON  - causeErrors is likely not JSON format
[2020/09/17 13:38:29.102] [DEBUG] [AbstractRestClient.js:502] Error was processed by overridden processError method in RestClient ZosmfRestClient

**Comment by ChrisBoehmCA** [comment]
I'm not familiar with Connection Central or Topaz but please be aware that the host and port must be the host and port of z/OSMF on your z/OS system, not the host and port that you use to connect to the 3270/green screen. The issue resolved by --reject-unauthorized has a different error message so I don't think that's it.  You won't be able to use most of the base Zowe CLI  commands until z/OSMF and its REST APIs are configured and working.
