### ISSUE TITLE
Zowe CLI Exit Code 0 for Errors

### ISSUE THREAD

**Issue by dkelosky** [zowe/zowe-cli#831]
For example (on windows): `zowe jobs -g && echo %ERRORLEVEL%` results in an exit code `0` although the command itself reports `Command Error:`.

This exit code should probably be a non-zero value.

**Comment by zFernand0** [comment]
After some discussion, we determined that it will be best to add a try/catch somewhere in the command processor and set the error code to 1 (if it's not set already)

---

This could be considered a `good first issue`. The majority of the time might be spent finding the right location. 😋
