### ISSUE TITLE
Question: How I can obtain the Zowe CLI version programmatically using JavaScript API 

### ISSUE THREAD

**Issue by plavjanik** [zowe/zowe-cli#838]
I am writing a TypeScript tool based on https://medium.com/zowe/how-to-quickly-build-applications-using-the-zowe-cli-npm-package-part-1-98998ea81d5d and I would like to check and report the version of the Zowe CLI that is used. Is there a JavaScript API that I call and get the version?

**Comment by dkelosky** [comment]
I'm not sure we have a clean way to do that the way you're programmatically calling Zowe CLI methods.  Perhaps if you went down the route of initializing imperative this might work, but I don't think that's needed in your case. 

@ChrisBoehmCA - do you have any clever ideas? 😄

**Comment by ChrisBoehmCA** [comment]
Is this too hacky? 

```
const version = require('../node_modules/@zowe/cli/package.json').version;
console.log(`The version is ${version}`);
```

**Comment by gejohnston** [comment]
An approach was described to accomplish the desired operation. This issue has had further activity in over a year, so I am closing this issue.
