### ISSUE TITLE
Return user with created session

### ISSUE THREAD

**Issue by katelynienaber** [zowe/zowe-cli#839]
Hello!

In Zowe Explorer, we require the user's HLQ (the `user` field in their profile) to do some actions, like issuing commands or searching automatically for the user's jobs.

We don't want to ask them _again_ for their HLQ/user if they are already authenticated via APIML (ie. using a base profile, without user/password stored in the service profile)...but in this particular case we don't have access to their HLQ, since it isn't stored in either profile.

If a call to CLI function `createBasicZosmfSessionFromArguments` always returned a session with the `user` field included, we wouldn't have to ask people to enter their HLQ again, before we can run these actions.

**Comment by dkelosky** [comment]
@plavjanik - is there a safe way to decode the `apimlAuthenticationToken` such that we could reliably extract a user ID regardless of the authentication provider?  
For example, if a decode a token, I see my user ID under the `sub` key:

`{"alg":"RS256"}{"sub":"MYUSER","dom":"SAFRealm","ltpa": ...` 
  
However, I'm wondering if this format is documented, and if it's acceptable to decode a token to obtain the user ID.  Should we rely on some endpoint instead to get an ID?  Do you have other ideas?

**Comment by pinpan** [comment]
The client app should call the ZAAS query endpoint for token validation. The sub claim is parsed from zOSMF and LTPA JWT. IDT (identity token) from SAF has it as well. The validateJWT method invoked when GW query endpoint is called parses the token and returns: userName, JWT string and validity status of the token.

**Comment by pinpan** [comment]
Zaas Client library can be used to simplify this in JAVA.

**Comment by dkelosky** [comment]
Thank you @pinpan !

We'll look at `api/v1/gateway/auth/query` for obtaining a user.  @katelynienaber - would it be ok to have a separate zowe cli api call to obtain the user from a token instead of adding it as a getter to the session object?

**Comment by jellypuno** [comment]
> Thank you @pinpan !
> 
> We'll look at `api/v1/gateway/auth/query` for obtaining a user. @katelynienaber - would it be ok to have a separate zowe cli api call to obtain the user from a token instead of adding it as a getter to the session object?

so we call this zowe cli api to get the user first then create session api?

**Comment by plavjanik** [comment]
Yes, `/api/v1/gateway/auth/query` is the safest way. The client does not need to parse the JWT token itself, since we can have different token providers with different algorithms and claims, it is not easy to be sure that it can parse all possible tokens. `/api/v1/gateway/auth/query` shields clients from this. Also, it knows what is the right cookie name, so the client can pass the cookie(s) returned by `/login` without understanding what is the cookie name for the token.

**Comment by katelynienaber** [comment]
@dkelosky it should be fine...I would like to ask some of the IBM folks this afternoon if they think it will affect extenders in some way

**Comment by katelynienaber** [comment]
@dkelosky It looks like this is fine! Thanks for checking first :)
