### ISSUE TITLE
Test Zowe CLI on USS

### ISSUE THREAD

**Issue by JTonda** [zowe/zowe-cli#84]

**Comment by ChrisBoehmCA** [comment]
The current version of Node.js on USS is 6.x, which doesn't have `Object.entries` and other features that we use of Node 7. 

```
[2018/11/01 11:11:03] [FATAL] [Imperative.js:169] TypeError: Object.entries is not a function
    at PluginManagementFacility.loadAllPluginCfgProps
```

So we are not currently compatible with running zowe CLI on USS but we may become compatible if IBM ports node 8+

Thanks to Karan for testing this
