### ISSUE TITLE
Cannot install Zowe from the source

### ISSUE THREAD

**Issue by abastyr** [zowe/zowe-cli#856]
Hello, I have problems installing Zowe from the source based on the documentation.

If I try to install it, I run into a following problem with a missing package version:

```npm
npm ERR! Can't install C:\Users\ab634601\Documents\development\sandbox\zowe\zowe-cli: Missing package version

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ab634601\AppData\Roaming\npm-cache\_logs\2020-11-09T12_05_47_569Z-debug.log

```

If I add the package version to `package.json`, I then get a following issue:

```npm
npm ERR! code ENOENT
npm ERR! syscall rename
npm ERR! path C:\Users\ab634601\AppData\Roaming\npm\node_modules\.staging\@zowe\cli-1b8edd5f\node_modules\@babel\code-frame
npm ERR! dest C:\Users\ab634601\AppData\Roaming\npm\node_modules\.staging\@babel\code-frame-4adefc22
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\ab634601\AppData\Roaming\npm\node_modules\.staging\@zowe\cli-1b8edd5f\node_modules\@babel\code-frame' -> 'C:\Users\ab634601\AppData\Roaming\npm\node_modules\.staging\@babel\code-frame-4adefc22'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ab634601\AppData\Roaming\npm-cache\_logs\2020-11-09T12_03_35_739Z-debug.log
```

The problem there is that NPM expects the node_modules to have a subfolder `.staging`, but all the modules are directly in the node_modules folder such as `node_modules\@babel`

**Comment by t1m0thyj** [comment]
Hi @abastyr, you should be able to run the `npm install -g` command from inside the "packages/cli" directory.

We recently restructured the Zowe CLI repo to separate the CLI and SDKs into separate packages, so the docs need to be updated here to mention that `cd packages/cli` must be run before NPM install.

**Comment by abastyr** [comment]
> Hi @abastyr, you should be able to run the `npm install -g` command from inside the "packages/cli" directory.
> 
> We recently restructured the Zowe CLI repo to separate the CLI and SDKs into separate packages, so the docs need to be updated here to mention that `cd packages/cli` must be run before NPM install.

Hi, that did work. However, I have also made some changes in the `Workflows` package, and running `npm install -g` in that folder seems not to work. Is there any way how to make this work? Thanks.

**Comment by abastyr** [comment]
> Hi @abastyr, you should be able to run the `npm install -g` command from inside the "packages/cli" directory.
> 
> We recently restructured the Zowe CLI repo to separate the CLI and SDKs into separate packages, so the docs need to be updated here to mention that `cd packages/cli` must be run before NPM install.

Hi, that has helped. But it raised another question:

If I make changes in multiple packages, what is the process there? Should I use `npm install -g` in those folders, as well? And what should be the order?

**Comment by t1m0thyj** [comment]
If you make changes to multiple packages and rebuild them locally, the changes should automatically take effect because the SDK packages are linked to your globally installed CLI.

You can verify that the packages are linked by navigating to `C:\Users\<user>\AppData\Roaming\npm\node_modules\@zowe\cli\node_modules\@zowe`.

The arrow at the bottom left of some of the folder icons shows that those folders are linked.

![image](https://user-images.githubusercontent.com/22344007/98979763-bfdf6280-24e9-11eb-8ec0-14537d1727b6.png)

**Comment by katsoohoo** [comment]
I just hit this issue as well when trying to build and install Zowe CLI from source. Could I take up this task for the doc change?

**Comment by t1m0thyj** [comment]
Hi @katsoohoo, feel free to assign yourself the issue in GitHub and make the doc update 🙂

**Comment by katsoohoo** [comment]
@t1m0thyj Hmm, seems like I don't have the privileges to do that.

**Comment by t1m0thyj** [comment]
@katsoohoo Sorry seems like privileges to assign issues is limited, didn't realize that. Still feel free to work on this issue 🙂 and if you want it assigned to you, react to this message with 👍 and I'll assign it
