### ISSUE TITLE
Require NPM v7 to build from source

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/zowe-cli#864]
Suggestion to migrate this project to use NPM v7. It supports NPM workspaces which make managing a Lerna monorepo much easier.

Only developers would need to update their version of NPM to build the CLI from source. Users who consume the CLI from packages or the NPM registry would not be affected.

Pros:
- Dependency management will be greatly improved - single package-lock file, Lerna change detection can ignore dev deps
- We can use Git deps while developing branches like "json-config-next" to consume the "next" branch of Imperative

Cons:
- We need to update Imperative to use `--legacy-peer-deps` on plugin install
- Different format of package-lock files will be created, but it is backwards compatible

**Comment by dkelosky** [comment]
this works for me - I'm on v7 already

**Comment by t1m0thyj** [comment]
NPM v7 adoption for Imperative is blocked by https://github.com/npm/cli/issues/2277

**Comment by t1m0thyj** [comment]
Migrated to npm@7 workspaces in https://github.com/zowe/zowe-cli/pull/1006
