### ISSUE TITLE
IZosFilesResponse in SDK Refers to Commands

### ISSUE THREAD

**Issue by dkelosky** [zowe/zowe-cli#865]
The `IZosFilesResponse` object that is returned from the `zosfiles` SDK packages contains a `commandResponse`:
```typescript
export interface IZosFilesResponse {
    /**
     * indicates if the command ran successfully.
     * @type {boolean}
     */
    success: boolean;

    /**
     * The command response text.
     * @type{string}
     */
    commandResponse: string;

    /**
     * The api response object.
     * @type{*}
     */
    apiResponse?: any;
}
```

Outside the context of the Zowe CLI though, `commandResponse` doesn't make much sense.  Can this be reworked for SDK / API users?

**Comment by gejohnston** [comment]
To avoid introducing a breaking change, we do not want to change the property names, but we can change the comments to reflect that the properties could be used for other purposes than a CLI command.
