### ISSUE TITLE
Ensure Zowe CLI installs cleanly without Python, C++ compiler

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/zowe-cli#87]
We tried to improve the installation experience by removing keytar and associated prerequisites (Python v2.7, C++ compiler, etc.). However, we still have node-report as an optional dependency which requires some of these prerequisites. Following our installation instructions should result in a clean install without any errors. I believe that following our updated installation instructions will result in installation errors due to our optional dependency on node-report.

We should consider whether node-report is required for us to effectively support the CLI. If it is, then we will need to include the prerequisites so that we can properly support it. Otherwise, we should remove it to simplify the installation process.

**Comment by AHumanFromCA** [comment]
Resolved in https://github.com/zowe/imperative/commit/a3fc4d7fdb318be750d7372701ffdd4a5570cdc9 ... I think
