### ISSUE TITLE
Sensitive terminology in Zowe CLI + Plugins

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/zowe-cli#872]
Identify sensitive terminology in the CLI source code + documentation to assess the effort to adjust it as per guidelines: zowe/zlc#199. I reviewed the source in GitHub and could not find any issues other than potentially the reference to the "master" branch.

**Comment by dkelosky** [comment]
For now, we're targeting `master` only if it's paired with `slave` which doesn't apply here.

**Comment by MichaelABroadcom** [comment]
The documentation has been scanned for sensitive terminology. The documentation does not have any sensitive terminology.
