### ISSUE TITLE
Mounting zFS filesystems with automatic growing

### ISSUE THREAD

**Issue by plavjanik** [zowe/zowe-cli#873]
The z/OS `mount` command allows passing additional options via `-o`, for example: `-o aggrgrow` that allows the zFS to grow automatically. Is it possible to pass this option in Zowe CLI when the mount is done using `zowe zos-files mount file-system`?

**Comment by MikeBauerCA** [comment]
This does not appear to be supported by the z/OSMF REST API that is currently being leveraged: https://www.ibm.com/support/knowledgecenter/SSLTBW_2.4.0/com.ibm.zos.v2r4.izua700/IZUHPINFO_API_MountUnixFile.htm

**Comment by zFernand0** [comment]
IS this a good candidate to convert to a Discussion? 😋
