### ISSUE TITLE
Zowe Check Status

### ISSUE THREAD

**Issue by jellypuno** [zowe/zowe-cli#875]
I am experiencing an error if I try to check the zosmf status using a profile that doesn't have a username and password or a token. Please correct me if I am wrong, as far as I know, you do not need a username and password to call zosmf/info. Did this change?

![image](https://user-images.githubusercontent.com/45042840/102196339-11e81f00-3ec0-11eb-869d-0d0533c85fd9.png)

**Comment by t1m0thyj** [comment]
This is related to #724. You are correct that the zOSMF endpoint being called does not require user/password 🙂 But the way zOSMF profiles/sessions work currently in the CLI, they always expect user/password to be provided in addition to host/port.

**Comment by gejohnston** [comment]
This question was answered. This issue has had no further activity in over a year, so I am closing this issue.
