### ISSUE TITLE
Create and document an issue template for the zowe-cli repo

### ISSUE THREAD

**Issue by tucker01** [zowe/zowe-cli#89]
We should create an issue template for the zowe-cli repo. All issues should follow a consistent (and ideally parse-able) format.

Problems being solved:  As it currently stands, we are not receiving relevant information in the issues.  
Customers may be struggling to construct issues and gather appropriate information.

Acceptance Criteria:
Bug Fix Template:
- Steps to reproduce?
  - Expected and actual behavior
- Zowe CLI Version
- Can check for existing known issues here and known workarounds here
- OS
- Node JS and NPM version (can give them the commands to issue)
- Plugins list
- Attach log file (give location)

Enhancement Template:
- Zowe CLI Version
- What problem are you trying to solve?
- Do you have a current workaround?

**Comment by MikeBauerCA** [comment]
We could create something similar to https://github.com/zowe/community/issues/new/choose

**Comment by zFernand0** [comment]
Work in progress 😋
