### ISSUE TITLE
Store secrets in password management system

### ISSUE THREAD

**Issue by kdbeall** [zowe/zowe-cli#891]
**Is your feature request related to a problem or limitation? Please describe.**
Storing passwords in plaintext is an acceptable risk, but not ideal.
Using a password management system would be an improvement in overall security.

* [OWASP Key Management Cheat Sheet](https://cheatsheetseries.owasp.org/cheatsheets/Key_Management_Cheat_Sheet.html)

**Describe the experience you'd like**
* Users may store their secrets within a password management system.
* Users who use plaintext passwords may migrate to using password management system.
* Users who continue to use plaintext passwords are not impacted with addition of password management support.
* Users of Windows, macOS, and Linux all supported.
* Default operating-system password management systems used.

~~ **Existing libraries for cross-platform password management** ~~
* [Go go-keyring](https://github.com/zalando/go-keyring)
* [Python keyring](https://pypi.org/project/keyring/)

**Comment by MikeBauerCA** [comment]
@Joe-Winchester @kdbeall yes, we plan to integrate the secure credential store plug-in into the core Zowe CLI by default at the next major Zowe release. We will have a version available for validation soon.
