### ISSUE TITLE
Support alternative config template for API ML

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/zowe-cli#892]
Support an `--apiml` flag on the "zowe config init" command.

When this flag is specified, a different format of config template would be generated that omits hostname for LPAR1, and replaces port with base-path for profile types that contain both the port and base-path fields.

**Comment by MikeBauerCA** [comment]
In addition, we can leverage the API Mediation Layer enhancement described in zowe/api-layer#873 to automatically set up all configuration information to access all available services registered to the API ML.

The CLI UX may be similar to: 
- User issues `zowe config init --apiml`
- User responds to prompts for creds
- User issues useful commands without needing to specify any connection info (e.g. `zowe files list ds ...`, `zowe endevor generate element ...`, etc.)

If multiple instances of a single service type (e.g. z/OSMF) are registered to the API ML, then they would need to select the instance that they want to connect to.

**Comment by MikeBauerCA** [comment]
Draft doc for new endpoints: https://github.com/zowe/docs-site/pull/1520 - relevant properties:

- basepath for each service - `apiml.apiInfo.basePath`
- name of service - `serviceId`
- mult services of a type - not sure how to determine the type, maybe `apiml.apiInfo.apiId` ?
- SSO conformance - `apiml.authentication.supportsSso`
