### ISSUE TITLE
Shift order of precedence from command handlers to core SDK

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/zowe-cli#895]
Currently, all client applications built on the Zowe SDK must implement logic to handle order of precedence. We want this order of precedence to be standard across client applications:
1. Options supplied by the application (e.g. command line options)
2. Environment variables (e.g. ZOWE_OPT_HOST)
3. Service profiles (e.g. z/OSMF default profile)
4. Base profiles (typically used for sharing information needed for accessing multiple services like creds/tokens or even host/port if all services are accessed via the API Mediation Layer)

To simplify the development effort for those building apps on the SDK and ensure a standard order of precedence is being followed, we should shift the order of precedence from our command handlers to our core SDK. Extenders will call a single API to get all the info they need to run the operation and this will ensure a standard order of precedence.

Goal will be to provide this by mid-Zowe-21PI1

**Comment by dkelosky** [comment]
And we'll add to this that we'll conditionally load our new config json if it exists.

**Comment by gejohnston** [comment]
It seems like the following story may be a prerequisite for this issue.

US722896 - Refactor Config class and add comments

**Comment by gejohnston** [comment]
Some possible ideas:

- currConfig: json = getConfigFromDisk( )
    - it calls Config.load(...)
    - In currConfig the consumer can see stuff like:
        - is old profile or new team config
        - path to config file
        - is global or project
        - various profile types
        - list of default profiles
        - list of secured properties

- propsToUse: json = getResolvedProperies(currConfig: json, operation: ???, propertyOverrides: json)
    - Consumer supplies the currConfig retrieved from getConfigFromDisk( )
    - Consumer supplies the desired operation
        - Don't know what that should be or how to specify it yet?
    - Consumer supplies property overrides.
        - Such overrides would be retrieved by the consumer from the user's command-line or from GUI prompts
    - The function combines the property values from
        - currConfig
        - overrides property values found in environment variables
        - overrides property values supplied in propertyOverrides
        - returns the result to the consumer in some format

- Additional functions could accept currConfig as a parameter and return other specific information
    - With such additional functions, perhaps the consumers could avoid poking around directly in currConfig?

**Comment by t1m0thyj** [comment]
Agree with the ideas mentioned by @gejohnston. Some additional functionality we may want to expose in these APIs:
* getConfigFromDisk
  * enable/disable project or global config
  * specify project directory
* getResolvedProperties
  * flatten nested profiles
  * merge service profiles with base profile
  * regarding "the desired operation"
    * specify profile type
    * specify additional fields (required or optional)
    * provide prompt callback for missing fields
    * perhaps this would supersede `ConnectionPropsForSessCfg.addPropsOrPrompt`

**Comment by dkelosky** [comment]
a minor detail, but perhaps we should remove `Disk` from the API methods.  Some input will come from env vars and other input may come from hosted config on the network.

**Comment by gejohnston** [comment]
A few of points about "from disk":

1. I do not feel strongly about the names at this point.
2. The "from disk" was intentional to convey that other sources (environment and command line) were not used by that first function. The second function (getResolvedProperties) combines all sources of input for the requested operation.
3. We may decide that this two-step process is not the right approach.

**Comment by dkelosky** [comment]
I see, thanks

**Comment by gejohnston** [comment]
The proposed ProfileInfo class has evolved to address the needs of VSCode apps. Thus, the focus of ProfileInfo is on arguments only defined within profiles. Further, this type of consumer does not want environment variable overrides.

Concerns about order-of-prcedence are already mostly addressed for command handlers. Perhaps this issue devolves into adding information passed into every command handler to identify which required arguments are missing, and assistance with prompting for those arguments? Today, that assistance is limited to hard-coded connection arguments (like host and port).

**Comment by gejohnston** [comment]
The features of this enhancement request were implemented in the V2 release of Zowe CLI, so I am closing this issue.
