### ISSUE TITLE
Allow for "extension-less" download

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/zowe-cli#90]
By default `bright files download all-members`, adds a .txt extension to all downloaded members. It would be preferrable if no extension was added by default.

Community feedback: I think it would be a good feature to allow "extension-less" download. So I can use the all-members option and not assign a file extension locally.

The community did find value in being able to change the extension though :)
I have found that it will actually help me to assign a file extension (.jcl or .cbl or .cpo). This helps the editor in my IDE assign the correct file extension automatically.

- [x] Update code to allow user to specify "" as input for --extension.
   Status: Completed
   Assigned: @lyzla01
- [ ] Update system test.
   Status: Not Started
   Assigned: @lyzla01 
- [x] Update help text to inform user that ".txt" is the default extension.
   Status: Completed
   Assigned: @lyzla01 
- [ ] Update system test with new test cased.
   Status: Not Started
   Assigned: @lyzla01 

Depends on zowe/imperative#91

**Comment by JTonda** [comment]
Follow up with requester.

**Comment by lyzla01** [comment]
After some discussion with the team, we decided with the following approach:
- Keep ".txt" as the default extension when user does not specify the --extension option.
- Update help text to clearly inform user that ".txt" is the default extension.
- Allow user to specify "" as input for --extension to allow no extension when download data set.
