### ISSUE TITLE
Create detailed design of combined config API

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/zowe-cli#911]
Create a detailed design of a combined config API to enable #895.

Considerations:
Reuse or share, where possible, the prompting for config properties that we already have in our config group.
Consider scope of impact to all existing command handlers
Order of precedence is resolved before an individual command handler gets control... this API is designed to resolve config + env vars... it seems like this should be used in command handlers... if you try to call from command handlers... it would make the passed vars into handlers obsolete... would this require a change to all command handlers? ... a lot of command handlers to change.... could be a lot of impact.
Requirements for SDK method(s):
- conditionally load our new config json if it exists
- provide a finalized **list** of build profile objects
- an indicator if old profiles or config files are in place
  - provide file paths to config files so they can be launched for editing
- reload / refresh config object
- request a type of profile, e.g. only `zosmf` profiles
- indicator if profile is global or project based
- indicator for which profile is default including base profile
- allow for login to store token in the right profile

Would like to avoid global update of command handlers (too much work/risk)... okay with allowing option but support existing command handlers. Could provide list of missing properties instead of moving prompting into SDK...

Meet/review with ZE squad

**Comment by gejohnston** [comment]
I think that this API must also be capable of using old-school profiles, when no team-config exists, like we have done in CLI & imperative in @next. This will give plugins and ZoweExplorer a similar ability to use either profiles-or-config throughout v2-lts, until profiles are completely removed in v3-lts.

**Comment by zFernand0** [comment]
Seems like we've made some progress here.
Wondering if this can be closed 😋
