### ISSUE TITLE
Confirm / document combined config API use by extenders

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/zowe-cli#913]
Confirm / document combined config API implemented in #912 so that extenders can leverage appropriately. Related to #895.

Update Imperative wiki doc, sample CLI plug-in repo, conformance criteria, tutorial-type doc (maybe a blog), publishing imperative API typedoc (related to zowe/imperative#332).

Include documentation around leveraging api for dev of VSCode extensions in imperative wiki documentation.

**Comment by jellypuno** [comment]
Connected Zowe Explorer Epic: https://github.com/zowe/vscode-extension-for-zowe/issues/1181

**Comment by MikeBauerCA** [comment]
One goal of this issue is to provide clear documentation to CLI plug-in developers on how to best make use of the new config available in next.

**Comment by adam-wolfe** [comment]
For reference, see https://docs.zowe.org/stable/typedoc/classes/_zowe_imperative.config
