### ISSUE TITLE
Support Automatic Configuration for API ML users - Research/investigation of endpoints

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/zowe-cli#919]
In support of #892, research implementation and test endpoints.

Draft doc for new endpoints: https://github.com/zowe/docs-site/pull/1520 - relevant properties:

- basepath for each service - `apiml.apiInfo.basePath`
- name of service - `serviceId`
- mult services of a type - not sure how to determine the type, maybe `apiml.apiInfo.apiId` ?
- SSO conformance - `apiml.authentication.supportsSso`

Goal is to have a design doc describing how to leverage these endpoints to automatically create a `zowe.config.json`.

Instead of `port` being a default property for core profiles and possible plug-in contributed profiles, switch it out for `base-path`.

Only need support for SSO conformant services as MVP.

**Comment by zFernand0** [comment]
Should this issue be closed now that we have `zowe config auto-init`?
