### ISSUE TITLE
Support Automatic Configuration for API ML users - Creation / testing of SDK function

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/zowe-cli#920]
In support of #892, implement design developed in #919. 

The ultimate goal is to improve the getting started experience for API ML adopters. Users of the API ML will be able to leverage a new command to generate a config (either project or global) containing the needed information (base-path for each service, is SSO supported) from API ML endpoints. If only one service of a specific type is available, it should be set as the default. If multiple services of a specific type exist, then we select the first returned service of that type as the default, output the list of default services and inform how to change the defaults (edit `zowe.config.json`). The user would need to manually choose the default service for that type by editing the json config. 

For this issue, an SDK function will be developed that can perform such an operation. The CLI command that invokes this function will be developed in a later issue.

Desire to have a method that just returns an object, and a separate method to write to disk.

**Comment by zFernand0** [comment]
Should this issue be closed now that we have `zowe config auto-init`?
