### ISSUE TITLE
Support Automatic Configuration for API ML users - Creation / testing of CLI function

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/zowe-cli#921]
In support of #892, implement design developed in #919 and leverage SDK function developed in #920.

The ultimate goal is to improve the getting started experience for API ML adopters. Users of the API ML will be able to leverage a new command to generate a config (either project or global) containing the needed information (base-path for each service, is SSO supported) from API ML endpoints. If only one service of a specific type is available, it should be set as the default. If multiple services of a specific type exist, then we select the first returned service of that type as the default, output the list of default services and inform how to change the defaults (edit zowe.config.json). The user would need to manually choose the default service for that type by editing the json config. 

Proposed syntax of command(s): `zowe config init --apiml`, `zowe config init --apiml --global`

**Comment by zFernand0** [comment]
Should this issue be closed now that we have `zowe config auto-init`?
