### ISSUE TITLE
Inconsistent naming for "password" in CLI options and profiles

### ISSUE THREAD

**Issue by tucker01** [zowe/zowe-cli#93]
Currently, the profile field for the users z/OSMF password is `pass`.

This forces the exposed CLI option to match (`--pass`) in order for us to take advantage of Imperative's "option precedence" feature.

We'd like to make the profile field, profile create command, and CLI options consistent with "--password". 

This would imply a breaking change that would required users to recreate their profiles. 

Acceptance Criteria:
Name of YAML property is password
Name of option is password
Alias of password is pw

Current State:
Name of YAML property is pass
Name of option is pass
Alias of pass is pw

The problem this would solve is clarity on what is meant by pass.

**Comment by zFernand0** [comment]
**Question**
Should we provide a script so that end-users can update all their profiles?
Or should we at least document the fastest/easiest way to do so?
Or should they just struggle through each profile?
