### ISSUE TITLE
[next] Inconsistent credential name in vault

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/zowe-cli#936]
The first time `zowe config init` is run, credentials are saved to the field "@zowe/cli/secure_config_props".

After running subsequent CLI commands that write secure fields (e.g., `zowe config secure`), the name changes to "Zowe/secure_config_props".

The Imperative credential manager accepts both names, but the expected behavior is that all new credentials should be created with the "Zowe" prefix.

**Comment by t1m0thyj** [comment]
This issue seems to be fixed by https://github.com/zowe/imperative/pull/589 - the first time `zowe config init` is run, credentials are now saved to the field "Zowe/secure_config_props", so I suggest that we close this issue 🙂

**Comment by JTonda** [comment]
Migration away from SCS as a plugin will be handled as part of the migration utility.
