### ISSUE TITLE
[next] Color escape characters not parsed by daemon

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/zowe-cli#938]
The `zowex` binary produces output that looks like this:
```
←[33m DESCRIPTION←[39m
←[33m -----------←[39m

   Manage z/OS jobs.

←[33m USAGE←[39m
←[33m -----←[39m

   zowe zos-jobs <group>

   Where <group> is one of the following:

←[33m GROUPS←[39m
←[33m ------←[39m

   cancel | can  Cancel a job
```

**Environment**
* OS: Windows 10 v2004
* Terminal (daemon/CLI): Powershell-Powershell or Bash-Bash

**Comment by dkelosky** [comment]
@tucker01 says we should have a flag or env var to disable colorization.

**Comment by MikeBauerCA** [comment]
At a minimum, we will want to document this workaround - https://github.com/zowe/zowe-cli/issues/1057#issuecomment-879284686

**Comment by tucker01** [comment]
This issue also extends to progress bars... because the escape codes aren't functioning, the progress bar floods the terminal.

**Comment by gejohnston** [comment]
Size = 8

Maybe the actual code change will be small, but just replicating the scenarios took a long time. Confirming even a subset of the following combinations after making changes will be time consuming. 

- No daemon mode
    - Powershell
        - displays color for error
        - displays color for progress bar
    - CMD
        - displays color for error
        - displays color for progress bar
    - Git bash on windows
        - displays no color for error
        - displays no progress bar

- daemon mode started from powershell
    - Powershell zowex
        - displays no color for error
        - displays escape characters for progress bar
    - CMD zowex
        - displays no color for error
        - displays escape characters for progress bar
    - Git bash on windows zowex
        - displays no color for error
        - displays no color for progress bar

- daemon mode started from CMD
    - Powershell zowex
        - displays escape characters for error
        - displays escape characters for progress bar
    - CMD zowex
        - displays escape characters for error
        - displays escape characters for progress bar
    - Git bash on windows zowex
        - displays color for error
        - displays color for progress bar

- daemon mode started from GitBash
    - Powershell zowex
        - displays no color for error
        - displays escape characters for progress bar
    - CMD zowex
        - displays no color for error
        - displays escape characters for progress bar
    - Git bash on windows zowex
        - displays no color for error, but get 2 copies of each message 
        - displays no progress bar, but get 2 copies of each message
- Did not try an actual Linux system
- Did not try a Mac system

Too many combinations to try all possibilities of FORCE_COLOR=0, but it did not correct the progress bar for CMD window.
- all in CMD window:
    - Set FORCE_COLOR=0
    - start daemon mode
    - run zowex
        - displays no color for error
        - displays escape characters for progress bar
