### ISSUE TITLE
Fatal Error Messages Not Returned to Daemon

### ISSUE THREAD

**Issue by dkelosky** [zowe/zowe-cli#943]
1. Create a `zowe.config.json` which is completely empty
2. Run `zowex config init`
3. Observe no response
4. Run `zowe config init`
5. See output:
```
[2021/02/05 10:02:90] [FATAL] [main.js:52] Error parsing JSON in the file 'C:\dev\asm\make\zowe.config.json'.
Please check this configuration file for errors.
Error details: Unexpected end of JSON input
Line 1, Column 0
```

**Comment by gejohnston** [comment]
This is likely the same problem reported by:

Deamon mode does not report syntax error in zowe.config.json #1190
