### ISSUE TITLE
Secure credentials - Extensions that are secure by default

### ISSUE THREAD

**Issue by VitGottwald** [zowe/zowe-cli#957]
Continuing the line of thought from #950 a bit further, the `{secure: "key.into.secure.credential.store"}` convention could be used to _avoid credential exposure_ in **_extensions_** that consume profiles (e.g. ZOWE Imperative SDK consumers, ZOWE CLI plugins, VSCode extensions like ZOWE Explorer).

The idea is like this:

1. Credentials are specified in `zowe.config.json` as
``` js
{
  "user": {"secure": "plex1.user"},
  "password": {"secure": "plex1.password"},
}
```
2. When the extension calls imperative to read profiles it would be given the option to specify whether credentials should be resolved or not.
3. A caller that does not want to get involved in the business of handling secure credentials and potentially expose them would receive whatever is specified in the config, which would be again
``` js
{
  "user": {"secure": "plex1.user"},
  "password": {"secure": "plex1.password"},
}
```
5. The imperative http client (and any potential future client for ftp or other protocol) would accept credentials with the same convention as defined in the config file:
  - a string value retains its literal meaning of its plain text value
  - an object of the shape `{"secure": "key.into.secure.credential.store"}` tells the client to go grab the data from secure credential store
6. The extension code would pass the credentials to the imperative client in the same shape as it has received them from profiles and would leave it up to the imperative client to interpret them.

_This way the extension code never comes in direct touch with secure credentials and has no way to accidentally expose them_ (e.g. in logs, dialog messages or otherwise).

It allows _extensions_ to be _secure by default_.

**Comment by VitGottwald** [comment]
Number 2. could be implemented in various ways. For example the existing (old) APIs would do credential resolution automatically to stay backwards compatible. Later it could be gradually deprecated (e.g. method alias with the suffix `_dangerously_reading_credentials` added for migration) and entirely removed down the road.

At the same time newly created APIs would not do credential resolution at all and instead provide the literal content from the config.

**Comment by gejohnston** [comment]
As I commented in #950, each secure property does not have its own key. Thus, it is unclear how to correctly postpone the retrieval of the secure value. By the time that an app passes the property to an imperative (or zowe/cli) API function, the JSON path information is typically gone. I think that just the property name is used at that point. Without the JSON path, an API will not have adequate information to find the right value within the credential vault.

**Comment by t1m0thyj** [comment]
After discussion with @VitGottwald, there is another idea for how this could be implemented: Zowe CLI could accept an optional callback for encoding secure values, and call this method when it loads secure profile properties. Zowe Explorer could then make use of this callback, and decode the secure values as late as possible. For example:

Profile loaded by Zowe CLI: `{ user: "admin", password: "123456" }`
Callback method: `function encodeSecureValue(name: string, value: string): SecureBlob`
Profile as seen by Zowe Explorer: `{ user: SecureBlob("user"), password: SecureBlob("password") }`

This idea is a compromise between:
* Zowe Explorer which performs a lot of operations between the time a profile is loaded from disk, and the time that a `Session` is initialized with the profile's connection info. It would be ideal to encode secure credentials in some manner, to prevent their values from getting leaked in logs.
* Zowe CLI which loads the values of all profile properties immediately, whether they are stored securely in plain text. This is convenient for SDK users who want easy access to all of the values, and delaying the loading of secure values would be a significant change to existing behavior.

**Comment by gejohnston** [comment]
Would the functions to encode and decode SecureBlob simply mangle the data to obfuscate the content to the human eye, or are we suggesting that data would be securely encrypted/decrypted?

**Comment by VitGottwald** [comment]
Both options are better than what we have today.

Ideally though, if feasible, the SDK could provide two more helper functions. First one would be a callback that the user could supply as @t1m0thyj  described above. It would generate a token that could be later passed to the second helper function to do an actual (delayed) retrieval from the credential store.

This way there would be no obfuscation or extra secure encryption/decryption, but only delayed extraction from the credential store.

**Comment by t1m0thyj** [comment]
@VitGottwald @gejohnston What do you think of the following approach?

In the `IProfMergedArg` interface documented in zowe/imperative#556, we could add a new property `secureArgs` as documented below:
```typescript
// _______________________________________________________________________
/**
 * The result object from mergeProfileArgs().
 */
export interface IProfMergedArg {
    /**
     * The list of arguments with known values.
     * All of the attributes in IProfPropAttrs will be filled in except
     * when knownArgs[i].propLoc.osLoc (and/or jsonLoc) are not
     * relevant for the type of location (locType).
     */
    knownArgs: IProfArgAttrs[];

    /**
     * The list of required arguments for which no value has been specified.
     * Obviously, the missingArgs[i].propValue attribute will not exist.
     * Note that a generated team configuration template can contain some
     * arguments with an empty string as a value. Such arguments will be
     * contained in this missing list. The other missing arguments will
     * have a missingArgs[i].propLoc, derived from the location of the
     * profile specified to the function mergeProfileArgs().
     */
    missingArgs: IProfArgAttrs[];

    /**
     * The list of arguments with secure values.
     * All of the attributes in IProfPropAttrs will be filled in where possible,
     * except for argValue since the values are sensitive data. Use the method
     * ProfileInfo.credentials.loadSecure to load the value of a secure arg.
     */
    secureArgs: IProfArgAttrs[];
}
```

**Comment by gejohnston** [comment]
The actions of 
[ [next] Secure credential handling for ProfileInfo API #579 ](https://github.com/zowe/imperative/pull/579)
were incorporated into the V2 version of the Zowe CLI.

No further action on this enhancement is targeted for the next 2 calendar quarters. The issue also has less than 5 up-votes by the community. Therefore, this enhancement is being closed. If you feel that this enhancement should continue to be available for community up-votes, you may reopen this issue.
