### ISSUE TITLE
Testing @next config file

### ISSUE THREAD

**Issue by jellypuno** [zowe/zowe-cli#959]
Hello! I am trying out the @next version of zowe cli and I managed to create my own config file. This is how it looks like:

```
{
    "$schema": "./zowe.schema.json",
    "profiles": {
        "dev": {
            "global_properties": {
                "port": <global-port>
            },
            "profiles": {
                "apiml": {
                    "type": "zosmf",
                    "properties": {
                        "host": "<apiml-hostname>",
                        "port": <apiml-port>,
                        "basePath": "api/v1",
                        "rejectUnauthorized": true
                    }
                },
                "zcobol": {
                    "type": "zosmf",
                    "properties": {
                        "host": "<zcobol-hostname>"
                    }
                },
                "ztrial": {
                    "type": "zosmf",
                    "properties": {
                        "host": "<ztrial-hostname>"
                    }
                },
                "mstrbrs": {
                    "type": "zosmf",
                    "properties": {
                        "host": "<mstrbrs-hostname>",
                        "port": "<mstrbrs-port>"
                    }
                },
                "tso": {
                    "type": "tso",
                    "properties": {
                        "account": "",
                        "codePage": "1047",
                        "logonProcedure": "IZUACCT"
                    }
                }
            },
            "apiml": {
                "properties": {}
            },
            "zcobol": {
                "properties": {}
            },
            "ztrial": {
                "properties": {}
            },
            "mstrbrs": {
                "properties": {}
            }
        },
        "default": {
            "type": "base",
            "properties": {
                "rejectUnauthorized": false
            }
        }
    },
    "defaults": {
        "zosmf": "dev.zcobol",
        "tso": "dev.tso",
        "base": "default"
    },
    "plugins": [],
    "secure": [
        "profiles.dev.apiml.properties.user",
        "profiles.dev.apiml.properties.password",
        "profiles.dev.zcobol.properties.user",
        "profiles.dev.zcobol.properties.password",
        "profiles.dev.ztrial.properties.user",
        "profiles.dev.ztrial.properties.password",
        "profiles.dev.mstrbrs.properties.user",
        "profiles.dev.mstrbrs.properties.password"
    ]
}
```

**I have a few observations:**
1. I tried to change `dev.properties` to `dev.global_properties` . It really didn't give an error so I thought it was okay.  But I realized that its not okay I when I try to use a profile that uses the values inside `dev.global_properties`. It replaced my port to 443.

This issue was fixed when I renamed it back to properties.

2. If I try to secure a lot of fields, it doesn't really save it. It jus asks me to input all my user and password and if I try to use the profile then I need to input it again. 

But if I only have 1 or 2 fields in the secure fields then it is saved and I don't have to worry about it again.

Also my `mstrbrs` profile is missing the password in the secure field if you check it using `zowe config list`.

![Capture](https://user-images.githubusercontent.com/45042840/108759699-fac34e80-754c-11eb-8dcb-bfac2371c2dd.PNG)

![image](https://user-images.githubusercontent.com/45042840/108760675-3e6a8800-754e-11eb-8b35-9cc5fd01075c.png)

3. And since no.2 is happening these fields are added in my config file. Which is kind of confusing for me. I thought I had a typo but then it appears after I entered `zowe config secure`. 
```
            "apiml": {
                "properties": {}
            },
            "zcobol": {
                "properties": {}
            },
            "ztrial": {
                "properties": {}
            },
            "mstrbrs": {
                "properties": {}
            }
```

**Comment by t1m0thyj** [comment]
> 1. I tried to change `dev.properties` to `dev.global_properties`. It really didn't give an error so I thought it was okay. But I realized that its not okay I when I try to use a profile that uses the values inside `dev.global_properties`. It replaced my port to 443.

Would this confusion be eliminated by having strict validation of the contents of zowe.config.json? Since `type`, `properties`, and `profiles` are the only property names allowed at this level.

> 2. If I try to secure a lot of fields, it doesn't really save it. It just asks me to input all my user and password and if I try to use the profile then I need to input it again.
> 3. And since no.2 is happening these fields are added in my config file. Which is kind of confusing for me. I thought I had a typo but then it appears after I entered `zowe config secure`.

The cause of this strange behavior is that you need to specify full JSON paths in the "secure" array, so instead of:
```json
    "secure": [
        "profiles.dev.apiml.properties.user",
        "profiles.dev.apiml.properties.password",
    ]
```
this should work:
```json
    "secure": [
        "profiles.dev.profiles.apiml.properties.user",
        "profiles.dev.profiles.apiml.properties.password",
    ]
```
