### ISSUE TITLE
Inconsistent capitalization with z/OS console command

### ISSUE THREAD

**Issue by katsoohoo** [zowe/zowe-cli#961]
Issuing the `zowe zos-console` command displays the following group help text:
```
 GROUPS
 ------

   collect Collect z/OS console command responses
   issue   Issue z/OS Console Commands
```

Should the description of the `issue` group also use lowercased "console commands" like the `collect` group?

**Comment by MikeBauerCA** [comment]
@katsoohoo yes, lowercased "console commands" is preferred.

**Comment by katsoohoo** [comment]
This should be a quick fix. I can take this issue :)

**Comment by zFernand0** [comment]
Seems like this is still an issue:
https://docs.zowe.org/stable/web_help/index.html?p=zowe_zos-console

**Comment by chinmaym07** [comment]
Hey Can I take this issue?
I think I need to change do the required change here 
https://github.com/zowe/zowe-cli/blob/9c7462b2b25437b598d34f2ca93769e6914912d7/packages/cli/src/zosconsole/issue/Issue.definition.ts#L18

**Comment by MikeBauerCA** [comment]
@chinmaym07 yes, please do. Since this your first time contributing to this project, please check out this documentation - https://github.com/zowe/zowe-cli/blob/master/CONTRIBUTING.md#sign-all-of-your-git-commits. As a Linux Foundation project, it is required that commits are DCO signed.
