### ISSUE TITLE
Reponse time tooks always 4-5 seconds

### ISSUE THREAD

**Issue by YvesMichon** [zowe/zowe-cli#965]
Hi,
My commands with ZOWE CLI tooks always at least 4-5 seconds. When i change log levels , i see the REST API call take about an half of seconds. 
What happens during the rest of time ?

### Example: 
zowe zos-files list data-set user

With powershell I've measured the command :
PS Z:\> Measure-Command { zowe zos-files list data-set user }

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 4
Milliseconds      : 948
Ticks             : 49482286
TotalDays         : 5,72711643518519E-05
TotalHours        : 0,00137450794444444
TotalMinutes      : 0,0824704766666667
TotalSeconds      : 4,9482286
TotalMilliseconds : 4948,2286

### Here is the log trace : 
[2021/03/02 16:44:20.814] [TRACE] [main.js:41] Init was successful
[2021/03/02 16:44:21.124] [DEBUG] [List.js:132] Endpoint: /zosmf/restfiles/ds?dslevel=user
[2021/03/02 16:44:21.127] [TRACE] [AbstractRestClient.js:293] Using basic authentication
[2021/03/02 16:44:21.128] [TRACE] [AbstractRestClient.js:518] appendInputHeaders called with options on rest client {"headers":{"Authorization":"Basic aW5lbWljeTpjZXJpdXMwMw=="},"hostname":"host","method":"GET","path":"/zosmf/restfiles/ds?dslevel=user","port":8777,"rejectUnauthorized":false} ZosmfRestClient
[2021/03/02 16:44:21.130] [TRACE] [AbstractRestClient.js:315] Rest request: GET host:8777/zosmf/restfiles/ds?dslevel=user as user user2
[2021/03/02 16:44:21.369] [DEBUG] [AbstractRestClient.js:339] Content length of response is: 14565
[2021/03/02 16:44:21.371] [TRACE] [AbstractRestClient.js:374] Data chunk received...
[2021/03/02 16:44:21.373] [DEBUG] [AbstractRestClient.js:415] onEnd() called for rest client ZosmfRestClient

I've tried with users who have different numbers of files. With 1 ou 16K it's always the same time : 1s for the rest API but 4-5 seconds for the complete command.

**Comment by dkelosky** [comment]
hi @YvesMichon - which version of Zowe CLI are you running?  The remaining time beyond the REST API is likely the setup of Node.js runtime and possibly anti-virus involvement.  

Would you be interested in trying our `[daemon](https://medium.com/zowe/zowe-cli-daemon-mode-29c0dc29c22f)` mode to see how that impacts performance?

**Comment by YvesMichon** [comment]
I use ZOWE CLI 1.19. 
Command zowe -V : 6.26.0. 
What you mean with "setup of Node.js" ?

**Comment by dkelosky** [comment]
Perhaps "startup" would have been clearer - I was meaning the Node.js runtime start up.  

I'm very interested in getting folks to try daemon mode :-) .  It's in "validation" - so there might be some rough edges, but it would be great if you could try this and help shape the final version of daemon mode.  

`Try it Out!` section in the medium blog shows the install steps.  Please let us know if you have questions!

**Comment by YvesMichon** [comment]
@dkelosky I've tried daemon mode and the response times decreases less a second. Good !!
I've a question. Zowe, in daemon mode, is launched one time for all processes on the machine. How does it works within a server ? All calls are serialzed or parallelized ?

**Comment by dkelosky** [comment]
is the response time less than a second or did it only decrease a second?  

You can launch one daemon to service all `zowex` clients.  Calls run in parallel.  There might be some quirks, so please let us know if you find strange issues.  

You can start other daemon processes though - there are environmental variables to control which port the server and client (zowex) communicate over.  The default is 4000.

**Comment by YvesMichon** [comment]
The total response time is less 1 second. Very good for me

What are the environment variables ? How zowex choose the right daemon process ? How to force zowex to use one daemon than another ?
Is there docs somewhere about this new functionnality ?

**Comment by MikeBauerCA** [comment]
Documentation for Early Access Features (just click the links for details) - https://www.npmjs.com/package/@zowe/cli#early-access-features

@dkelosky also authored a [blog](https://medium.com/zowe/zowe-cli-daemon-mode-29c0dc29c22f) on this functionality.

**Comment by MikeBauerCA** [comment]
This is the direct link to this particular early access feature - https://github.com/zowe/zowe-cli/blob/next/zowex/design.md

**Comment by dkelosky** [comment]
Thanks @MikeBauerCA - right now there is only `ZOWE_DAEMON` environment variable that you'd need to set for each running client and server.  You can set env per terminal environment.  We could also consider if we want to expose this port as a command line argument at some point, e.g. `--daemon-port=` or something.   

Here's a quick daemon port adjustment example:
```
C:\dev>set ZOWE_DAEMON=4001
C:\dev>start zowe --daemon
...
[2021/03/03 09:03:51] [INFO] [Processor.js:59] server bound 4001
```

On the same terminal, the env var is set, so `zowex` here would communicate on 4001.

**Comment by YvesMichon** [comment]
Thanks for all. I have all I need. Just a final question. Which version is planned to have this functionnality ?

**Comment by MikeBauerCA** [comment]
This functionality is currently planned for the next major release of Zowe CLI, which will be 7. This will be published in alignment with the next major release of the greater Zowe solution, which will likely be 2. If we continue to hear positive feedback on our early access features, that will help accelerate the publishing of a new major release. There is no tentative date at this time.

**Comment by YvesMichon** [comment]
Thanks. I close this issue.
