### ISSUE TITLE
Cancel Command Request

### ISSUE THREAD

**Issue by dkelosky** [zowe/zowe-cli#97]
Hi @MikeBauerCA,

When can I expect a cancel command to be available through the zowe CLI?  I'm building automation to recycle a server and would like a command to cancel a job by jobid.

Thanks,

**Comment by MikeBauerCA** [comment]
Hello @dkelosky,

Thank you for suggesting this enhancement. We typically schedule these enhancements against milestones. I will inform once this enhancement is scheduled. While it is not in the immediate plan, feel free to open up a pull request :)

Adding a link to the relevant zosmf REST API documentation: https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.1.0/com.ibm.zos.v2r1.izua700/IZUHPINFO_API_PutCancelJob.htm

In the interim, could you cancel the job via a console command?

Cheers,
Mike
