### ISSUE TITLE
ZOWE CLI bad performance

### ISSUE THREAD

**Issue by zszabo14** [zowe/zowe-cli#971]
**Describe the bug**
ZOWE CLI commands are executing very slow. Simple dataset list takes 45 sec (10 dataset in the list). But the zowe list profiles also takes ~30sec. Generally any ZOWE Commands are slow.

(VS Code ZOWE Explorer is way much faster)

**Steps to Reproduce**

**Details**
zowe -V : 6.25.1
node --version : v14.9.0

**Shell Environment Details (if the bug relates to CLI):**
 W10

**Additional context**

**Comment by MikeBauerCA** [comment]
Hi @zszabo14 - we have an early access feature that can greatly improve performance. [Here is a brief blog describing the feature](https://medium.com/zowe/zowe-cli-daemon-mode-29c0dc29c22f). Please follow this thread: https://github.com/zowe/zowe-cli/issues/965 and let us know what you think 👍

**Comment by zszabo14** [comment]
I got these errors after install:
`npm WARN @zowe/provisioning-for-zowe-sdk@7.0.0-next.202102171306 requires a peer of @zowe/core-for-zowe-sdk@^6.24.1 but none is installed. You must install peer dependencies yourself.
npm WARN @zowe/provisioning-for-zowe-sdk@7.0.0-next.202102171306 requires a peer of @zowe/imperative@^4.8.1 but none is installed. You must install peer dependencies yourself.
npm WARN @zowe/zos-console-for-zowe-sdk@7.0.0-next.202102171306 requires a peer of @zowe/core-for-zowe-sdk@^6.24.1 but none is installed. You must install peer dependencies yourself.
npm WARN @zowe/zos-console-for-zowe-sdk@7.0.0-next.202102171306 requires a peer of @zowe/imperative@^4.8.1 but none is installed. You must install peer dependencies yourself.
npm WARN @zowe/zos-uss-for-zowe-sdk@7.0.0-next.202102171306 requires a peer of @zowe/imperative@^4.8.1 but none is installed. You must install peer dependencies yourself.
npm WARN @zowe/core-for-zowe-sdk@7.0.0-next.202102171306 requires a peer of @zowe/imperative@^4.8.1 but none is installed. You must install peer dependencies yourself.
npm WARN @zowe/zos-workflows-for-zowe-sdk@7.0.0-next.202102171306 requires a peer of @zowe/core-for-zowe-sdk@^6.24.1 but none is installed. You must install peer dependencies yourself.
npm WARN @zowe/zos-workflows-for-zowe-sdk@7.0.0-next.202102171306 requires a peer of @zowe/imperative@^4.8.1 but none is installed. You must install peer dependencies yourself.
npm WARN @zowe/zos-jobs-for-zowe-sdk@7.0.0-next.202102171306 requires a peer of @zowe/core-for-zowe-sdk@^6.24.1 but none is installed. You must install peer dependencies yourself.
npm WARN @zowe/zos-jobs-for-zowe-sdk@7.0.0-next.202102171306 requires a peer of @zowe/imperative@^4.8.1 but none is installed. You must install peer dependencies yourself.
npm WARN @zowe/zos-tso-for-zowe-sdk@7.0.0-next.202102171306 requires a peer of @zowe/core-for-zowe-sdk@^6.24.1 but none is installed. You must install peer dependencies yourself.
npm WARN @zowe/zos-tso-for-zowe-sdk@7.0.0-next.202102171306 requires a peer of @zowe/imperative@^4.8.1 but none is installed. You must install peer dependencies yourself.
npm WARN @zowe/zos-files-for-zowe-sdk@7.0.0-next.202102171306 requires a peer of @zowe/core-for-zowe-sdk@^6.24.1 but none is installed. You must install peer dependencies yourself.
npm WARN @zowe/zos-files-for-zowe-sdk@7.0.0-next.202102171306 requires a peer of @zowe/imperative@^4.8.1 but none is installed. You must install peer dependencies yourself.
npm WARN @zowe/zosmf-for-zowe-sdk@7.0.0-next.202102171306 requires a peer of @zowe/core-for-zowe-sdk@^6.24.1 but none is installed. You must install peer dependencies yourself.
npm WARN @zowe/zosmf-for-zowe-sdk@7.0.0-next.202102171306 requires a peer of @zowe/imperative@^4.8.1 but none is installed. You must install peer dependencies yourself.`

**Comment by zszabo14** [comment]
`C:\Users\myuser>start zowe --daemon

C:\Users\myuser>zowex zos-files list data-set "MYHLQ.DEV.*" --responseTimeout 10
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 10061, kind: ConnectionRefused, message: "No connection could be made because the target machine actively refused it." }', src\main.rs:75:54
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

**Comment by t1m0thyj** [comment]
> I got these errors after install:
> `npm WARN @zowe/provisioning-for-zowe-sdk@7.0.0-next.202102171306 requires a peer of @zowe/core-for-zowe-sdk@^6.24.1 but none is installed. You must install peer dependencies yourself. ...`

These warnings only show when installing the `@next` release of Zowe CLI. They are not errors and can be safely ignored.

I'm not familiar with the Zowe daemon error, perhaps @dkelosky can provide more insight on it.

**Comment by dkelosky** [comment]
@zszabo14 - what version response to you get when you run `zowe --version` ?

**Comment by zszabo14** [comment]
zowe --V
7.0.0-next.202102171306

**Comment by dkelosky** [comment]
thanks - are you on windows?

when you ran `start zowe --daemon` did another terminal start up (to run the daemon)?  did it contain any text?

**Comment by zszabo14** [comment]
Yes on W10. Yes a window pops up...

**Comment by dkelosky** [comment]
Did it have any text in it?  For example, which port it started on ?

**Comment by zszabo14** [comment]
zowe --daemon
[2021/03/10 21:03:91] [INFO] [Processor.js:59] server bound 4000

if I use `start zowe --daemon`, then nothing is in the window

**Comment by dkelosky** [comment]
interesting... if you don't mind then, please run `zowe --daemon` then open a new window and try `zowex jobs list jobs` 

Since you mentioned it can take 30 - 40s for a command, please wait that long before trying `zowex jobs list jobs`  

After which, you can run as often as you need.

**Comment by zszabo14** [comment]
OK, now the text appeared...

![image](https://user-images.githubusercontent.com/42870072/110693990-5dbd1280-81e8-11eb-8dc9-820d9b0a0c99.png)

**Comment by dkelosky** [comment]
excellent - is the `zowex` piece running a bit faster?

**Comment by zszabo14** [comment]
yes. the startup test only appeared when the first `zowex` command initiated
btw, can I run it as a service?

**Comment by dkelosky** [comment]
Here are things I've tested so far:
* Windows: start zowe --daemon
* Linux: zowe --daemon &
* pm2: pm2 start <global-npm-location>/node_modules/@zowe/cli/lib/main.js --name zowe-daemon -- --daemon

I dont have much experience windows background services, but this is something we could get on our backlog.  Since this is still in validation, we might have bugs and the foreground terminal is helpful for debugging.  

If you have any luck with the service, can you let us know here?

**Comment by gejohnston** [comment]
The Zowe CLI daemon evolved significantly for its GA release in Zowe V2. It provides the same performance increase as reported in the earlier comments, and its user experience has changed significantly to avoid problems reported in earlier comments. Therefore, I am closing this issue.
