### ISSUE TITLE
zowex client 32-bit version?

### ISSUE THREAD

**Issue by fbeyl** [zowe/zowe-cli#974]
https://github.com/zowe/zowe-cli/releases/tag/native-v0.2.0
I downloaded and tried to test ubuntu version on mint but as my 32-bit system is outdated (to expect in the case of an almost outdated mainframer I suppose) no luck.
I wonder if it would be possible to obtain a 32-bit version?

**Comment by fbeyl** [comment]
@dkelosky You think this is possible?

**Comment by dkelosky** [comment]
I dont think we'll be able to do this easily - right now we use GitHub actions CI tooling to build binaries.  

However, you can likely build the binary on your own machine if you'd like to try.  You'd need to install rust: https://www.rust-lang.org/tools/install 

Then:
* `git clone https://github.com/zowe/zowe-cli`
* `git checkout next`
* `cd zowe-cli/zowex`
* `cargo build`

Would that be an acceptable work around to try this?

**Comment by fbeyl** [comment]
OK got that up and running, thx.
Got an issue with zowex now see hereafter, do I open new issue or continue in this one?

With zowe:
fbeyl@pvslt03 ~ $ iplrest=$(zowe zos-tso send address-space $sko --data "ex (panel) 'PARM'")
fbeyl@pvslt03 ~ $ echo $iplrest
[ { "DSNAME":"VENDOR.PARMLIB" , "SEQ":"1" , "VOLSER":"VPMVSD" , "BLKSIZE":"6160" , "EXTENT":"1" , "SMS":"NO" , "LRECL":"80" , "DSORG":"PO" , "RECFM":"FB" , "CRDATE":"2003.119" , "REFDATE":"2021.071" , "SYSNAME":"S0W1" , "SYSLEVEL":"z/OS 02.03.00 HBB77B0" } , { "DSNAME":"SVTSC.PARMLIB" , "SEQ":"2" , "VOLSER":"VTMVSG" , "BLKSIZE":"6160" , "EXTENT":"1" , "SMS":"NO" , "LRECL":"80" , "DSORG":"PO" , "RECFM":"FB" , "CRDATE":"1997.118" , "REFDATE":"2017.300" , "SYSNAME":"S0W1" , "SYSLEVEL":"z/OS 02.03.00 HBB77B0" } , { "DSNAME":"LVL0.PARMLIB" , "SEQ":"3" , "VOLSER":"VTLVL0" , "BLKSIZE":"6160" , "EXTENT":"7" , "SMS":"NO" , "LRECL":"80" , "DSORG":"PO" , "RECFM":"FB" , "CRDATE":"2007.025" , "REFDATE":"2021.035" , "SYSNAME":"S0W1" , "SYSLEVEL":"z/OS 02.03.00 HBB77B0" } , { "DSNAME":"SYS1.PARMLIB" , "SEQ":"4" , "VOLSER":"VIMVSB" , "BLKSIZE":"27920" , "EXTENT":"1" , "SMS":"NO" , "LRECL":"80" , "DSORG":"PO" , "RECFM":"FB" , "CRDATE":"2017.116" , "REFDATE":"2021.035" , "SYSNAME":"S0W1" , "SYSLEVEL":"z/OS 02.03.00 HBB77B0" } ] READY

With zowex:
fbeyl@pvslt03 ~ $ iplrest=$(zowex zos-tso send address-space $sko --data "ex (panel) 'PARM'")
Command Error:
Onbekende argumenten: (panel), 'PARM'
Command failed due to improper syntax
Command entered: "zowe zos-tso send address-space Z40275-137-aackaaah --data ex (panel) 'PARM' --dcd /home/fbeyl/"
Available commands are "address-space".
Use "zowe zos-tso send --help" to view groups, commands, and options.
Error Details:
Onbekende argumenten: (panel), 'PARM'

Tried escaping but till now no luck.

**Comment by fbeyl** [comment]
Seems response if given twice ?

fbeyl@pvslt03 ~ $ zowex --version
7.0.0-next.202102171306
7.0.0-next.202102171306

fbeyl@pvslt03 ~ $ sko=$(zowex zos-tso start address-space --zosmf-profile "tutosys" --sko);

Z40275-111-aabqaaat

fbeyl@pvslt03 ~ $ 
fbeyl@pvslt03 ~ $ zowex zos-tso start address-space --zosmf-profile "tutosys" --sko;
Z40275-140-aacwaaab
Z40275-140-aacwaaab
fbeyl@pvslt03 ~ $

**Comment by fbeyl** [comment]
Possible workaround: use variable to pass --data

fbeyl@pvslt03 ~ $ cmd="\"ex (panel) 'PARM'\" "fbeyl@pvslt03 ~ $ zowex zos-tso send address-space $sko --data $cmd
[
{
"DSNAME":"VENDOR.PARMLIB"
, 
"SEQ":"1"
, 
"VOLSER":"VPMVSD"
, 
"BLKSIZE":"6160"

**Comment by dkelosky** [comment]
If it's OK - I'll spin these up as new issues.   Please let me know if we can close this one & thank you for trying `zowex`!

**Comment by fbeyl** [comment]
Yes please proceed to closure.

Op ma 15 mrt. 2021 om 14:48 schreef Dan Kelosky ***@***.***>:
