### ISSUE TITLE
IProfile interface doc

### ISSUE THREAD

**Issue by zszabo14** [zowe/zowe-cli#976]
Hi,

I couldn't find the definition of the IProfile Interface in the documentation. (https://docs.zowe.org/stable/typedoc/index.html)

**Comment by t1m0thyj** [comment]
The `IProfile` interface is defined in the zowe/imperative repository. Typedoc for Imperative is currently not hosted online anywhere. 

To view API doc for the `IProfile` interface, you can clone the zowe/imperative repository and run `npm install && npm run typedoc`. This generates Typedoc in the "doc" folder that you can launch in your browser.

**Comment by t1m0thyj** [comment]
The typedoc on Zowe docs site has been updated to include documentation for Imperative and the Zowe Node.js SDKs.

The IProfile interface is documented here: https://docs.zowe.org/stable/typedoc/interfaces/_zowe_imperative.iprofile.html
