### ISSUE TITLE
zowex --version gives output twice 

### ISSUE THREAD

**Issue by dkelosky** [zowe/zowe-cli#977]
Seems response is given twice ?

fbeyl@pvslt03 ~ $ zowex --version
7.0.0-next.202102171306
7.0.0-next.202102171306

fbeyl@pvslt03 ~ $ sko=$(zowex zos-tso start address-space --zosmf-profile "tutosys" --sko);

Z40275-111-aabqaaat

fbeyl@pvslt03 ~ $ 
fbeyl@pvslt03 ~ $ zowex zos-tso start address-space --zosmf-profile "tutosys" --sko;
Z40275-140-aacwaaab
Z40275-140-aacwaaab
fbeyl@pvslt03 ~ $

_Originally posted by @fbeyl in https://github.com/zowe/zowe-cli/issues/974#issuecomment-798007423_

**Comment by dkelosky** [comment]
I'm unable to reproduce this @fbeyl - @zFernand0 - does this happen for you?
```
C:\>zowex --version
7.0.0-next.202102011525
```

**Comment by fbeyl** [comment]
Got it. If I start the deamon and enter the zowex command in the same terminal the answer is double. if I start them in separate terminal the reply comes once in both terminals. Is it expected for the deamon to output to stdout as well as returning the reply to zowex? Perhaps a debug setting or ...

**Comment by dkelosky** [comment]
it does for now - but thats probably a flawed approach.  

ive been using the other terminal for debugging purposes.  `pm2` is a nice tool to make this a little bit cleaner, background process runner for any platform: https://github.com/zowe/zowe-cli/pull/825#issue-491473402 

do you think a debug flag would be the best way to handle this for running in the same terminal ?

**Comment by fbeyl** [comment]
Not sure I know what a debug flag exactly means but anyway from now I will run it in separate terminal no problem.
Please proceed as seems best, fine for me.

**Comment by dkelosky** [comment]
perhaps i was misreading your comment about a "debug settings" 😄 

we could have a flag on `zowe --daemon --debug` which would cause the daemon to echo things to stdout.

i'll close this for right now - feel free to reopen or open a new issue if you have a preference on how we should do this when it's officially published in the next version on zowe.  right now, we're in "validation" stage

thanks again for trying!
