### ISSUE TITLE
Spike - Revise Versioning Scheme

### ISSUE THREAD

**Issue by JTonda** [zowe/zowe-cli#98]
Research how to version Zowe CLI based on industry standards.

Acceptance Criteria:
Proposal for versioning scheme
Which branches map to which versions
Do we require different Jenkins pipelines depending on results?
Understand a maintenance strategy
#77 needs to be well defined
- need to know what problem we're solving
- who we're solving this problem for

- [x] Write proposal for modifications to versioning scheme
   Status: Competed
   Assigned: @gejohnston 

- [x] 1st review meeting
   Status: Competed
   Assigned: @gejohnston

- [x] Incorporate feedback from 1st review
   Status: Competed
   Assigned: @gejohnston

- [x] 2nd review meeting
   Status: Competed
   Assigned: @gejohnston

- [x] Incorporate feedback from 2nd review
   Status: Completed
   Assigned: @gejohnston 

- [x] Identify tasks for a separate implementation story
   Status: Completed
   Assigned: @gejohnston

- [x] Document all results in Git issue #77
   Status: Completed
   Assigned: @gejohnston

**Comment by gejohnston** [comment]
Accidentally closed this issue. Re-opening.
