### ISSUE TITLE
zowex prompts for credentials after `zowe config secure`

### ISSUE THREAD

**Issue by dkelosky** [zowe/zowe-cli#984]
If you launch `zowex` (e.g. `start zowe --daemon`) from a directory where no `zowe.config.json` is found and have the old SCS plugin enabled then switch to a directory where `zowe.config.json` is found, you are prompted for credentials, even if you run `zowe config secure`.  

As a work around, you can run `zowex config secure` and respond to prompts.  However, this stores credentials un the credential manager as `Zowe-Plugin/...` instead of the new naming standard `Zowe/secure_config_props`.

**Comment by zFernand0** [comment]
@dkelosky, should this issue be closed now that zowe/imperative#589 is merged?

**Comment by dkelosky** [comment]
i think so 😄
