### ISSUE TITLE
Daemon mode doesn't update list of installed plugins

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/zowe-cli#986]
Steps to Reproduce:
1. Run the CLI in daemon mode and install a new plugin
2. Run `zowex plugins list` and notice the plugin is missing
3. Run `zowe plugins list` and notice the plugin is listed

Until the daemon is restarted, the `plugins list` command seems to load outdated data.

OS: Ubuntu 18.04.5 in Hyper-V VM
Zowe CLI Version: 7.0.0-next.202103152050 with zowex 0.2.0

**Comment by t1m0thyj** [comment]
It's also worth noting that rebuilding/updating a plug-in requires a restart of the daemon process for changes to take effect. Not sure whether this is a bug or a feature, since the purpose of daemon mode is to speed up Zowe commands by disabling some things that are normally reloaded automatically. Thanks to @zFernand0 for pointing this out 😛

**Comment by gejohnston** [comment]
The decision was made to document the need to restart the daemon whenever changes are made to the working environment (including the installation of a plugin). That documentation was published in the Zowe V2 release. Therefore, I am closing this issue.
