### ISSUE TITLE
When user has expired password, `zowe uss issue ssh` waits forever

### ISSUE THREAD

**Issue by plavjanik** [zowe/zowe-cli#989]
When the password is expired, issuing commands via SSH hangs.

Example:
```
zowe uss issue ssh "echo Hello"
```

**Comment by JirkaAichler** [comment]
This is a really annoying bug causing a lot of trouble. When we can expect the fix?

**Comment by plavjanik** [comment]
When this happens, it is very difficult to understand what happened because there is no error message printed and people spend at least half an hour to looking for the root cause.

**Comment by MikeBauerCA** [comment]
@plavjanik @JirkaAichler we are going to investigate this now. We'll let you know.

**Comment by MikeBauerCA** [comment]
@JirkaAichler @plavjanik this fix is on both `@zowe-v2-lts` and `@zowe-v1-lts`. Please let us know if you experience any further issues the next time the password expires.

**Comment by JirkaAichler** [comment]
Thank you for fixing it! It will save us a lot of time always trying to find out why our automation is stuck.
